### PR TITLE
Fixes Templates

### PR DESCRIPTION
**Pull request by TDcoolguy300**
Two map files were causing the issues with very little known cause, removed the affecting maps and added a Generation button to the template panel

### CODE REVIEW

**Comment by TDcoolguy300** [comment]
Also, http://puu.sh/nJkdd/c9a089979e.png

**Comment by Nebyab** [comment]
someone codecheck so this can be merged

**Comment by Pyko1** [comment]
Might had been better to just move those out of the random space generation folder until the problem is fixed.

Mapwise those should be ok

**Comment by Carbonhell** [comment]
code is ok

**Comment by Carbonhell** [comment]
It's a bugfix,merging this.

**Pull request merged**
