### PR TITLE
Remove the dumbest gamemode to actually ever exist (changelings)

### PR DESCRIPTION
**Pull request by checkraisefold**
Seriously fuck this shit gamemode, okay? Please accept and merge kthx

### CODE REVIEW

**Comment by checkraisefold** [comment]
Hold up, adding changelog so this check can fuck off

**Comment by checkraisefold** [comment]
Somebody fix this please.

**Comment by TDcoolguy300** [comment]
Imo you can't just turn off files and hope it works, best solution to this is to just remove changlings and traitor+Changling from the rotation and removing other things that could create changlings.

**Comment by JohnGinnane** [comment]
Why

**Comment by JohnGinnane** [comment]
TD is right, it'll be easier to remove them from rotation as other code maybe rely on stuff in those files

**Review by JohnGinnane — CHANGES_REQUESTED** [review]
Changelog needs to be .yml filetype. Need to rethink how to disable lings

**Comment by lcass** [comment]
no this is a terrible idea and you have just disabled the files , you are just butthurt a ling killed you.

**Comment by SpankMasterson** [comment]
They should be nerfed not removed

**Comment by yobob591** [comment]
They need to be totally redone in order to be stealth antags like they were first intended to be

**Comment by ghost** [comment]
Yeah no.

**Pull request closed without merging**
