### PR TITLE
Deadspace

### PR DESCRIPTION
**Pull request by LOLSKELETONS**
Allows the plasma cutter to dismember a targeted limb by firing at it.
Pretty much the same mechanic in all the dead space games.

### CODE REVIEW

**Comment by ghost** [comment]
Is it intended for this to only apply in low atmos environments?

**Comment by ghost** [comment]
Oh yeah, and your git has committed your bane stuff too. I have no idea how you would undo that.

**Comment by Gandalf2k15** [comment]
YES YES AND YES MAKE IT ATMOS WORTHY

**Comment by Sarcalogo** [comment]
Ah that reminds me to fix the CE and Engineering hardsuits to look less shitty. They were originally sprited to look exactly like the ones from Deadspace. it looked much more aesthetic. will see if I can do /tg/ removed because MUH copyright.

**Comment by blobbernaut** [comment]
it's because you committed your stuff to your master branch....

**Comment by LOLSKELETONS** [comment]
Closing this and reworking the code for it.

**Pull request closed without merging**
