### PR TITLE
Toggle PDA flashlight verb

### PR DESCRIPTION
**Pull request by Theoman02**
Made it so that you can now toggle the PDA's flashlight either from the menu on the right or by right clicking the PDA itself.

### CODE REVIEW

**Comment by ArcLumin** [comment]
Why not try middle clicking to turn on the flashlight? MiddleClickOn will let you simply middle click your PDA to turn on the flashlight

**Comment by Spacedong** [comment]
ehh I like opening the PDA and switching it on, just gives the sense that you're actually using it

**Comment by Theoman02** [comment]
Tried to ArcLumin, but it seems to be only for mobs, and it also makes you switch your active hand as well. Would need some rewriting in click.dm, so I'm just sticking with the simple option for now.

**Comment by myontasm** [comment]
Thank you, this is something that I've wanted for a while.

**Comment by SplergeBucket** [comment]
but i right click the PDA itself to remove my ID

**Comment by doobiedoo23** [comment]
I like QoL changes as much as anyone else, but I think having to open your PDA to toggle it is better.

-1/3

**Comment by Kokojos** [comment]
Useless to me.

**Comment by ghost** [comment]
I like it. +1

**Comment by Nebyab** [comment]
opening your PDA is IMMERSIVE

also its just a generally more appropriate way to handle it, not everything needs to be verbiaized

**Comment by SplergeBucket** [comment]
2 Headmins, and 2 GMs against it.
Safe to deny this really.

**Comment by Pyko1** [comment]
apparently denied, closing

**Pull request closed without merging**
