### PR TITLE
Post-merge map fixes/additions

### PR DESCRIPTION
**Pull request by Cafaling**
Drone shell in EVA is no longer poorly placed.

Listening post has lights and the space tile below the door is gone.

A few hostile mobs to make life difficult for explorers.

A love letter to Travis.

### CODE REVIEW

**Comment by Foosili** [comment]
I'm still not sure how I feel about drone shells being placed on map. Iffy on that, other than that, neato.

**Comment by danhibiki** [comment]
I think as long as the drone shells spawn _after_ round has started, it shouldn't be an issue.

**Comment by Cafaling** [comment]
Drone shells have always been on the Derelict, even pre-remake, and Chron solved the 'Controlling Drones before roundstart' issue already.

**Comment by Chronitonity** [comment]
Aye, you can't take control of drones until the round starts, I just made sure of it

**Comment by Cafaling** [comment]
Pls merge this. I promised Travis that I'd give him a tribute if he let my last test build pass ;-;

**Comment by Nebyab** [comment]
Yeah sure

**Comment by Cafaling** [comment]
Quick fix to keep Nex from getting murdered by the Derelict.

Seriously Nex how are you this unrobust.

Also by the request of Skeletom, I've added a T-ray and some extra metal/glass.

There's also soap in the ghetto Surgical area for neat freaks.

**Pull request merged**
