### PR TITLE
Shadowling Update

### PR DESCRIPTION
**Pull request by Chronitonity**
Brings us up to date from the latest shadowling update from TG weeks ago.

Big things from their PR.
A new spell type has been added, /self. This spell will only target the user and is made for ease of creation of new spell types made to be self-centered.
Many shadowling ability cooldowns have been reduced.
Shadowlings no longer possess Enthrall before hatching.
Shadowling clothing/items have icons
Destroy Engines is now removed after use.
The Shift Nerves button now has an icon.
Dethralling surgery's final step now requires a flashbulb, penlight, or flashlight.
Dethralling surgery now produces a shadow tumor at the target's location.
New item: shadow tumors. Have a tech origin of 4 biological. Dies in the light and heals in the dark. You get these from the surgery.

This needs to be merged before #1312 As he needs to redo his sprites and it's gonna give me merge conflicts that I DO NOT WANT TO DEAL WITH.

### CODE REVIEW

**Comment by myontasm** [comment]
https://www.youtube.com/watch?v=zAb1QBUz208

**Comment by ghost** [comment]
what exactly do the tumours do.. do they heal the user and hurt them in light or some shit or is it one-time use or what

**Comment by Chronitonity** [comment]
Once implanted they constantly heal in the dark/hurt in the light. Its basically being a shadowling without being valid or all the cool powers.

**Comment by danhibiki** [comment]
Reverse plant people

**Comment by myontasm** [comment]
The tumor is perfect for those who really want to play as the station's own maintenance goblin.

Though it should grant the user some night vision, so that people don't hurt themselves with their own flashlight.

**Comment by Nebyab** [comment]
seems fine

**Pull request merged**
