### PR TITLE
Teamspeak Button

### PR DESCRIPTION
**Pull request by TDcoolguy300**
Adds a Team speak button, a changeable config, and the base config. 

image http://puu.sh/kWemr/0be3223068.png

### CODE REVIEW

**Comment by Chronitonity** [comment]
WHERES THE CHANGELOG TD WHERES THE FUCKING CHANGELOG

**Comment by TDcoolguy300** [comment]
*SCREAM I'll do it now

**Comment by TDcoolguy300** [comment]
Fuck you too changelog

**Comment by TDcoolguy300** [comment]
For reference, the config needs to be set on the box itself, with the URL of ts3server://188.165.255.120

**Pull request merged**
