### PR TITLE
Ups the prize of Disintegrate and Plasma Fist

### PR DESCRIPTION
**Pull request by carlarc**
Is there anything to add? Disintegrate requires barely any time to hit someone with and is a instant win with a stun. Plasma Fist, while technically is only better disintegrate since no one uses the other ones, still requires the boost. I'd change the mechanics of Plasma Fist too, like only being able to gib if the target is in critical health, but I'm not familiar with Coder-Fu.

### CODE REVIEW

**Comment by trifornt-tinfornt** [comment]
Grudgecode.
Hackole went on a massive killing spree using Plasma Fist and Disintegrate, this popped up the round afterwards.

Plasma Fist doesn't need a price buff, it needs a nerf in general. Give the Plasma Fist Combo a cooldown and make it so that while hulked your punches don't stun to reduce how insanely well it combos with Mutate.

**Comment by carlarc** [comment]
Even if it is grudgecode, it's horribly overpowered, Isn't it?

**Comment by TheOneAndOnlyCreeperJoe** [comment]
I do agree that instant win spells are lame, but this is not how you nerf it.
I would personaly just give disintegrate a 2 second charge-up that cancels when either entity moves (makes flesh to stone semi-viable on its own) and I would just give Plasma Fist more combos but remove the ultimate technique.

On a sidenote Mutate seriously needs nerfing. It lasts longer than the cooldown, the lasereyes fire rapidly for 20 damage while punching only deals standard damage and knocks down.

**Comment by trifornt-tinfornt** [comment]
Yeah, laser eyes could use nerfing too.

**Comment by Crystalwarrior** [comment]
Give disintegrate wind up time, make laser eyes not bullshit or remove them and keep Plasma Fist as it is for Gucci balance 👌

**Comment by carlarc** [comment]
but im not code, pls halp

Other thing, the necromancer spell that makes you respawn is horribly overpowered. There is absolutely no way anyone will know exactly where the ensouled item is.

**Comment by TheOneAndOnlyCreeperJoe** [comment]
Not really, it gives you a direction when the wizard whisks away towards it, while the wizard is stunned for a stupid amount of time that gets longer the more you die.

But it can be cheesed with things such as papers in paper bins, cig buts and some other stuff.

Wiz deserves a proper balance overhaul that aims to cut down on some retarded and dumb abilities.

I'll have a gander at it soon.

**Comment by carlarc** [comment]
Great. Close this pr or something??

**Comment by JohnGinnane** [comment]
@carlarc is this PR going to be worked on or do you want to close it?

**Comment by carlarc** [comment]
I'm not going to work on this at all, if some coderzards tell me 1. this is dumb and 2. they're going to handle it sooner or later, then it's all fair and square.

Close it.

**Pull request closed without merging**
