### PR TITLE
Permission System Fix

### PR DESCRIPTION
**Pull request by Badmex**
Well permissions were a bit fucked. Every admin stays behind with a Rank "Removed" instead of getting deleted from the Permission DB. So this should fix that and the runtime errors.

### CODE REVIEW

**Comment by Carbonhell** [comment]
Code's ok, awaiting nalar's input

**Comment by ghost** [comment]
Added as per request of badmex.

**Comment by ghost** [comment]
Removed as per request of badmex.

**Comment by Carbonhell** [comment]
code's ok,can it be merged?

**Comment by ghost** [comment]
Has Nalar said anything about it?

**Comment by ghost** [comment]
I'd wait for Nalar to confirm it.

**Comment by Badmex** [comment]
Yeah don't merge without nalar, so just wait. Also the checks made it worse reeee so gonna take them out again will leave it with one check instead of two.

**Comment by nalarmg** [comment]
Merged and removed admins with the "Removed" rank from the database.

**Pull request merged**
