### PR TITLE
Small change to make strangling a bit more viable. Death now results in

### PR DESCRIPTION
**Pull request by ghost**
about 20 ticks, rather than about 100 before.

### CODE REVIEW

**Comment by ghost** [comment]
i support this change because making somebody wait for three minutes to strangle somebody is batshit insane

**Comment by GenericGoose** [comment]
> a small change
> +1,674 −1,674

what did you do

**Comment by KayeArray** [comment]
holy fuck what

**Comment by GeneralGoose** [comment]
SNEAKY CHANGES BAN HE

**Comment by GenericGoose** [comment]
idk

**Comment by Pyko1** [comment]
Something went obviously wrogn seeing the amount of changes, DNM until fixed, and code check after that.

**Comment by GenericGoose** [comment]
yeah it's something with the dme, i suspected its cuz of the auto set dirs thing, but not sure

**Comment by ghost** [comment]
I like this. Strangling DID suck.

Make sure it changes the values for CQC strangles too.

**Comment by ghost** [comment]
snake remember the basics of CQC

**Comment by GenericGoose** [comment]
cqc chokes are already faster
i think they give more oxyloss, in addition to regular chokes

**Comment by ghost** [comment]
@GeneralGoose cqc should go to crit in 8 second just like the metal gear games

**Comment by ghost** [comment]
You're working off of your master which could fuck your repo.
http://hippiestation.com/showthread.php?tid=2521
If you want to join our slack chat and get some help with git, let us know in the thread.

**Comment by GenericGoose** [comment]
@tabsiforu yeah also singulo should consume the whole station in literal 2 seconds and some other things should be more powerful but we like have some you know invisible faint idea of balance that manifests itself sometimes

**Comment by ghost** [comment]
@GeneralGoose i'd say make a pull but you're fresh out of hecks I see

**Comment by ghost** [comment]
yeaah something went wrong here

still though if it's ever redone, i think the most that it should be reduced by is maybe to ~55-60 ticks.
we already have a weapon that decreases the time needed to make someone turn purple and explode from lack of oxygen called a garote.

**Comment by ghost** [comment]
I can obviously tune the values to be a bit smaller, I just thought ~20ticks was a good starting point to make strangling more robust without it being ridiculous. It's still slower than the garrote, and I haven't modified the CQC variant. Realistically though, a garrote and your hand will kill someone at the exact same rate, it's just easier to maintain the hold with a garrote.

**Comment by ghost** [comment]
The dme changes were indeed because of the autodirs thing. My only changes were in code/modules/mob/mob_grab.dm for this PR.

**Comment by ghost** [comment]
righto then
well when everything's fixed and playtested a bit to fine tune then +1/3 cause current strangling is pretty super totally mediocre

**Comment by ghost** [comment]
@Dudeinyourbackyard it's not fair to turn an attack worth cold piss into hot piss. it needs to not be piss so people can use it if they're stupid enough to stand in one place trying to kill someone with their bare hands without a stun

your garrote is situational and doesn't account for those attacking with their BARE HANDS and so barely applies here

**Comment by GenericGoose** [comment]
@tabsiforu im not fresh my dude

**Comment by ghost** [comment]
Re-added a pull request that doesn't change the dme file. I'm used to using subversion or internal repository software at work. Git is a bit new to me.

**Pull request closed without merging**
