### PR TITLE
Jackboots now have sound

### PR DESCRIPTION
**Pull request by myontasm**
Adds the metrocop shuffle from Half-Life 2 to the jackboots. Plays every third step.

### CODE REVIEW

**Comment by Gandalf2k15** [comment]
NO

**Comment by calibraptor** [comment]
No thanks.

**Comment by Spacedong** [comment]
hilarious but i'd rather confine it to a gimmick item tbh

**Comment by myontasm** [comment]
It plays every third step, but I could make it a tad less frequent than that if desired.

**Comment by calibraptor** [comment]
Powergamers would just swap to sneakers in order to not make noise. Also a fairly pointless feature that we don't really have need for.

**Comment by myontasm** [comment]
I mainly made this as a neat little novelty for sec, not to give antags with great ears an upper hand or anything. If powergamers wanna switch to sandals then let them.

**Comment by ghost** [comment]
I think this feature is cool.
If this is such an issue for powergamers, why not make it toggable or something.

**Comment by TrashFiend** [comment]
i really don't see the point

**Comment by blobbernaut** [comment]
Jackboots should have a buff for this then, like reduced time on the floor when you slip, heat and cold protection or something like that. Because otherwise i'm just ditching them ASAP.

**Comment by myontasm** [comment]
Good idea, any suggestions to buffs and values?

**Comment by blobbernaut** [comment]
Maybe reduce time when slipped by 30%, and give a bit of armor to the legs? Or increase the damage dealt when kicking somebody by 1-2 points.

**Comment by trifornt-tinfornt** [comment]
Don't see the point, any other buffs to the jackboots would be dumb.
Why not give this to the jackboots in the autodrobe?

**Comment by blobbernaut** [comment]
^ that's a good idea, you could just make the jackboot in the autodrobe a child of regular jackboots and put it in there

**Comment by myontasm** [comment]
I'll let more people weigh in before I decide what to do. Personally like the sound of a jackboot buff.

**Comment by dreamcrab** [comment]
ehhhh, I'm not entirely sold. not against it entirely but ehhh

**Comment by ghost** [comment]
i just want minor jackboot protection back man

**Comment by TDcoolguy300** [comment]
Code's fine

**Comment by Sarcalogo** [comment]
No thank you.

**Comment by Lawligagger** [comment]
I hated the jackboot sounds in Nox station when they had them

**Comment by Kokojos** [comment]
A no from me, if that wasen't clear by the passive-agressive labels.

**Comment by Crystalwarrior** [comment]
Yeah let's have footstep update 2.0 isn't that an amazing idea ¿??????¿

**Comment by Pyko1** [comment]
I recall always swapping in to sneakers as sec in nox, since they sound was pretty much early warning system to greytiders breakign shit up.

**Comment by Crystalwarrior** [comment]
Unless the sound has crawl sound's range this is a big no. Even then, it needs something special to come as a result of the sound effect, since this is effectively a nerf to jackboots making them worse than normal shoes.

**Comment by doobiedoo23** [comment]
This is cool, everyone else is just a dumb bitchboy tbh

**Comment by carlarc** [comment]
its gucci

**Comment by carlarc** [comment]
just make security sneakers start on the sec locker room, they're black but red on the back

**Comment by dreamcrab** [comment]
after a second consideration no thanks

**Comment by myontasm** [comment]
Two heads against this, I'll just go ahead and close it.
I'll make it work somehow.

**Pull request closed without merging**
