### PR TITLE
Newbrig

### PR DESCRIPTION
**Pull request by calibraptor**
Changes in this PR
- The entire brig as a whole is a lot smaller now.
- The armory is now more difficult to break into without being noticed due to it being significantly smaller now, and surrounded on all sides by other rooms. I've attempted to balance this by making direct assaults easier to pull off.
- All of the brig cells and the armory are now within eyeshot of the Warden's Office.
- Barriers, Portable Flashers, Secways, and Securitrons have been moved out of the Armory and into the Equipment Room.
- Replaced the fairly useless Invasive Search room with an infirmary. The maintenance sleeper and the contents of the Arrival Shuttle first aid kit have been moved inside it.

hothooooo

teamstabs cooter

### CODE REVIEW

**Comment by ghost** [comment]
-#include "_maps\map_files\TgStation\tgstation.2.1.3.dmm" 
You unchecked the tgstation.2.1.3.dmm file?

**Comment by calibraptor** [comment]
Fuck what

**Comment by calibraptor** [comment]
Re-check'd the tgstation.2.1.3.dmm and added screenshots.

**Comment by Kierany9** [comment]
smolbrig

I like it

**Comment by Badmex** [comment]
After speaking with calib about it, it's looking like a good new sec area. The warden can finally see the prisoners. +1/3

**Comment by Kokojos** [comment]
Checklist time !
Is there...
Proper access to all doors? [ ] 
Proper C_tags for all cameras? [ ]
Proper range for cameras? [ ] 
Proper firelocks? [ ]
Proper ID on all the shutters/button? [ ]
Proper APC names? [ ]
Proper Lightning? [ ]
Good atmospherics? [ ]
Enough extinguisher? [ ]
Enough light switches? [ ]
Intercoms? [ ]
Air alarms [ ✓](I can see that)

Did you : 
Check mapping using the debug verbs? [ ]

Suggestion : Give sec a welder and a welding helmet so they can un-weld their doors.

And otherwise, this looks good, 1/3rd when my checklist will be completed.

**Comment by Kierany9** [comment]
yeah

**Comment by calibraptor** [comment]
Checklist time !
Is there...
Proper access to all doors? [✓ ]
Proper C_tags for all cameras? [✓ ]
Proper range for cameras? [✓ ]
Proper firelocks? [✓ ]
Proper ID on all the shutters/button? [✓ ]
Proper APC names? [✓ ]
Proper Lighting? [✓ ]
Good atmospherics? [✓ ]
Enough extinguisher? [✓ ]
Enough light switches? [✓ ]
Intercoms? [✓ ]
Air alarms [✓]

Did you :
Check mapping using the debug verbs? [✓ ]

Suggestion : Give sec a welder and a welding helmet so they can un-weld their doors. ✓✓✓

And otherwise, this looks good, 1/3rd when my checklist will be completed.
✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓

gimme that 1/3rd 

✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓

**Comment by calibraptor** [comment]
Updated screenshot

**Comment by Kokojos** [comment]
Y✓✓ou b✓✓✓✓etter ✓✓no✓✓t b✓✓e ly✓✓in✓✓g.

+1/3rd.

**Comment by GenericGoose** [comment]
👌👌👌👌👌👌👌👌👌👌👌👌👌👌👌👌👌👌👌👌👌👌👌👌👌👌👌👌👌👌👌👌👌👌👌👌👌👌👌👌👌👌👌👌👌👌👌👌

**Comment by ghost** [comment]
cool

1/3

**Comment by calibraptor** [comment]
I have an entire +1 now

@Nebyab @McBawbaggings 

GET IN HERE

**Comment by KayeArray** [comment]
needs more crystal windows

**Comment by SplergeBucket** [comment]
Regular prison cells are now un-break-in-able, pretty sure that's more of a minus than it is a plus.
The HoS' room should have a window in it is what I would like to say, and you could easily bring it down by one squares by making it less spacious on the bottom.
Interrogation is pretty big and I don't see the need for vending machines there.
There needs to be windows in the Security Resting Zone whatever the fuck it's called.
The Pipe Layout for the Prison Exits is awfully long when you could shorten it's end destination easily. All Good though I suppose.
It feels long and unnecessary in many regards but it's better than the current layout we've got and I'll give it a +1 if you make the cells possible for a break-in.

**Comment by calibraptor** [comment]
@SpergeBucket They can still be broken into/out of, it's just a lot more difficult to do so without being noticed. That said I'll see about getting some maint running behind the regular cells somehow.

There's vending machines in our current interrogation, and this one is just as big as our current one.

Look at the screenshot there is windows look at them LOOK AT THEM.

The disposals for the pipe layouts being lengthy is intentional <s>so I can reroute the prisoners into space</s> so the prisoners have a fun ride.

**Comment by Spacedong** [comment]
on-station permabrig please, off-station permabrig causes trouble for everyone involved, officers can't interact with the prisoners, its a hassle to get to, officers cant bring prisoners to escape shuttle/pods, and the permabrig is just so huge you can get lost in it.

**Comment by Spacedong** [comment]
interrogation is by the permabrig area and has two doors to get out of, which is kinda bad, I loved a traitor silently overpowering teh guy in interrogation then holding a hostage while aiming his gun at the door

**Comment by Spacedong** [comment]
and permabrig still has the execution room too which makes it useless since its already on-station, however having just the small permabrig we had before back on-station would be neato and correct this issue

**Comment by Spacedong** [comment]
I also see in the security maint you put a SORD and a replica katana, i'd take the SORD out since its kinda reserved for badminnery jokes

**Comment by Spacedong** [comment]
https://vgy.me/lvNK2n.png

how is this catwalk connected to the station? needs lattices

**Comment by Spacedong** [comment]
almost all the hallways by the permabrig are easy to laser down from space, just have a firing line and keep shooting and you can gun down anybody in those hallways, was this intentional?

**Comment by Spacedong** [comment]
why is the lawyer office FUCKhuge

**Comment by calibraptor** [comment]
Brig cells are now a bit more vulnerable to breakouts, screenshot updated.

Heads come +1 this I'm sick and tired of working on it.

**Comment by ghost** [comment]
I like it overall.
My only request is that in the sec equipment room you remove the top left sec vend, push up the tables a tile and move the lockers against the glass.
It triggers my autism greatly to see the vending machine in a corner like that.
After that the change, +1 considering how much of an improvement it is from current sec since you can see cells as warden.

**Comment by calibraptor** [comment]
Autism untriggered

autistdxefwtrhsd

**Comment by calibraptor** [comment]
Got a yes from 3 GMs, a yes from an HA, and a conditional yes from another HA that I've fulfilled. This is good for the mergan.

**Comment by calibraptor** [comment]
cuckless

Confirmed +1 from 2 HAs and 3 GMs. Time to go pester a coder to merge this after Travis gives it the okay.

**Comment by Carbonhell** [comment]
Not to sound like the fun police, but everytime we change a big portion of the map, all players whine and scream, i think this should be considered as a major pr to see if players like it, to avoid what happened with oldbrig/arrivals.

**Comment by Kierany9** [comment]
pls

**Comment by Sarcalogo** [comment]
Opinions of course... but you understand..

Armory can be gotten into by breaking two windows. Cannot be accessed from space (only the riot gear room can). No more room for last stands in the armory.
Sec pod is unusually difficult to access compared to the armory. 
Room below the shuttle is almost entirely useless, would be better if that space was expanded into the armory.
There isn't a toolbox in the armory.

Things I would do:

Move the sec pod to its current location. Move the bathrooms above the brig locker room, make them smaller if necessary.
Replace windows in the access to the armory with R-Walls. Put a glass airlock. Invent reinforced see through walls if being see through entirely is such a big deal.
Expand the armory 3 tiles to the north.
Remove everything to the right of the permabrig shuttle.
If possible make some of the more narrow hallways one tile wider.

**Comment by Sarcalogo** [comment]
Also brig dorms were a good idea, don't remove them.

**Comment by Sarcalogo** [comment]
There also doesn't appear to be a Warden's locker in the Warden's office. Or a Sec Vend in the armory.

**Comment by GenericGoose** [comment]
> Not to sound like the fun police, but everytime we change a big portion of the map, all players whine and scream, i think this should be considered as a major pr to see if players like it, to avoid what happened with oldbrig/arrivals.

arrivals were ugly and unnessesary
oh and they had **AIRLESS TILES**

**Comment by Spacedong** [comment]
@generalgoose remember when there was no floor under the airlocks near the arrival shuttle so you'd suffocate when you arrived late

**Comment by Spacedong** [comment]
i still think the hallways near the permabrig area are too small, and interrogation being in the permabrig "section" is just weird

**Comment by TrashFiend** [comment]
Far better than current brig, really well designed 10/10 but here's my opinion

The bathroom/shower area is kinda huge for the fact nobody uses it. I would honestly prefer putting showers above the locker room to put the pod back where it normally is. It's far as fuck away from anyone in the lobby/brig, which can be a real issue when time is tight.

Since the permabrig shuttle has doors on both sides, does that mean permabrig was also redesigned to accommodate? I could easily see some nerd accidentally opening the other side in perma and making the shuttle uninhabitable. 

This looks like a decent change for rev rounds as well. It's not utterly impossible to break in, but it still is enough of a challenge like the current brig. The only problem I could see is trying to get people who hide inside the whole execution/shuttles area without heading into space. You'd have to go through 1-2 r-walls or a door to get to them. Not difficult, but time consuming and dangerous if you go the door route.

Finally: The plant in the lobby is perfect. The station needs more plants in lobbies.

(Who thought it was a good idea to make the Warden completely and utterly unable to see the cells of the current brig?)

**Comment by GenericGoose** [comment]
https://puu.sh/qhJ4h/3658bbb33a.png
my idea for patriotic sec dorms
*tables should have hamburgers on them

**Comment by calibraptor** [comment]
"Since the permabrig shuttle has doors on both sides, does that mean permabrig was also redesigned to accommodate?"

Y-yeah, s-sure, that totally wasn't something I just did on a lark in the early stages.

If you'll excuse me I have to make a completely unrelated commit.

**Comment by Spacedong** [comment]
yeah I think the showers have no purpose either, bad hiding spot because there's no backdoor, and its just a really unused room overall

**Comment by calibraptor** [comment]
The mur- er, shower room is 100% necessary and the most important part of the brig.

**Comment by Kierany9** [comment]
>The mur- er, shower room is 100% necessary and the most important part of the brig.


For what purpose

**Comment by Kokojos** [comment]
Forthatt purpose

HELP REDSUITS
Location?
TOILETSSSS

**Comment by Lawligagger** [comment]
Getting better and better m8 keep at it

**Comment by GenericGoose** [comment]
shower is essential for [roleplay](https://www.youtube.com/watch?v=V4aOLkiXzcs)
replace it with an gym

**Comment by calibraptor** [comment]
@GeneralGoose I would if wE HAD ANY GYM EQUIPMENT AAAAA

**Comment by Spacedong** [comment]
@calibraptor when you code it

also @generalgoose is that a subtle gachimuchi meme

**Comment by calibraptor** [comment]
@Spacedong Fuck off mate you do it if you're such an authority on what makes a brig good.

**Comment by ghost** [comment]
de_stroyed

**Comment by trifornt-tinfornt** [comment]
That is one really easy to break into Armory. If there isn't a lot of sec, you don't have to even worry about multitooling or hacking any more. Just destroy a single, half-window and then take out a rack.
On the other hand, R.I.P. the idea of nuke ops bombing the armory as they'll get spotted instantly and all of sec will be on their ass.

**Comment by calibraptor** [comment]
Okay well, Nebyab made a broken poll that has vanished now, and an input thread that nobody has really posted in. Is this just in infinite limbo now?

**Comment by Lawligagger** [comment]
bring it back

**Comment by Lawligagger** [comment]
rip

**Comment by calibraptor** [comment]
NEBYAAAAAAAAAAAAB

**Comment by GenericGoose** [comment]
never forget

**Comment by Pyko1** [comment]
Looks like you have broken the disposals mail system for brig area.

**Comment by Sarcalogo** [comment]
Stil have not even fixed the sec pod issue. Sec pod is more secure than the armory. There are still no brig dorms. And two tile hallways are bad.

**Comment by Lawligagger** [comment]
pls

**Comment by calibraptor** [comment]
@Pyko1 It was intentionally removed since almost nobody used them for their intended purpose.
@Sarcalogo No idea what you mean by this. The sec pods can easily be broken into, brig dorms aren't a necessity, and two tile hallways actually make the brig very defensible during riots.

**Comment by calibraptor** [comment]
oh

Welp my patience/impatience pays off. This shit has been finished for close to a week, merge it you magnificent bastards.

**Pull request merged**
