### PR TITLE
Tank Nerf

### PR DESCRIPTION
**Pull request by AliiTea**
removed - Weeaboo, Plushie, Mime, Clown Tanks from code.

nerfed the normal Tank and Syndi Tank.

Gave the Syndi Tank space thrusters.

### CODE REVIEW

**Comment by AliiTea** [comment]
@SplergeBucket

**Comment by SplergeBucket** [comment]
No compromise, all tanks must die.

**Comment by AliiTea** [comment]
That is not how this works >:I

Tell me how I could **IMPROVE** tanks

**Comment by SplergeBucket** [comment]
By removing them.

**Comment by AliiTea** [comment]
That's not improving...

**Comment by SplergeBucket** [comment]
They're irredeemable, just like British teeth. Removing is the only real way for improvement because they're an unnecessary feature.

**Comment by AliiTea** [comment]
But they are fun and require work to get

**Comment by SplergeBucket** [comment]
Fun is Dead.
Long live Badminocracy

**Comment by AliiTea** [comment]
If badminocracy was real we would still have Weeaboo tanks

**Comment by SplergeBucket** [comment]
Not when i'm Head Honcho for Badminocracy, none but the selective recipients for Nepotism will survive unviolated and ruined.

**Comment by AliiTea** [comment]
Can you actually get serious instead of spouting ridiculous shit please.

**Comment by lcass** [comment]
I'm for them staying with a significant armour debuff , removing features doesn't help just because it is not required doesn't mean it shouldn't be there. By that logic the science department doesn't need to be there nor does the SM / EVA / Clown / Mime you get the point.

**Comment by SplergeBucket** [comment]
I was dead serious here, i'm not interested in this, I want them gone.

**Comment by Chronitonity** [comment]
Thats not nearly the same thing. Tanks have been unbalanced and pretty terrible since their addition, they're bad additions and more powerful then mechs in basically any meaningful way.

**Comment by AliiTea** [comment]
Because they are tanks...

**Comment by AliiTea** [comment]
**TANKS**

**Comment by Chronitonity** [comment]
Thats not a good reason for them to just be a straight upgrade without being noticeably harder to make. :+1: on removing them imo

**Comment by AliiTea** [comment]
3000 points in cargo to order 1 tank

**Comment by lcass** [comment]
I think this needs the other headmins and head coders opinions before the decision is made.

**Comment by Chronitonity** [comment]
volgin

**Comment by AliiTea** [comment]
@lcass if they deliver the tanks go if not they stay

**Comment by AliiTea** [comment]
@nalarmg This can be merged

Tanks aren't needed

**Comment by nalarmg** [comment]
Still needs to pass through the headmins to ensure there's some level of agreement that they should actually be removed. I've requested review (I personally don't mind either way).

**Comment by AliiTea** [comment]
Merge Conflicts.. not sure what's conflicting going to close and redo the PR

**Pull request closed without merging**
