### PR TITLE
Cloaks are worn in the Exosuit slot

### PR DESCRIPTION
**Pull request by Chronitonity**
Changes cloaks so they're used in the exosuit slot, like hardsuits, same as on TG now.

Who's going to give up their backpack for this shit really.

### CODE REVIEW

**Comment by ghost** [comment]
g-g-g-gagsa..

G GG GAG!

**Comment by danhibiki** [comment]
sure

**Comment by FuryMcFlurry** [comment]
Those capes always looked neat. cant wait to put the capes to good use!
By that I mean being a piece of shit and stealing them as the clown.

**Comment by calibraptor** [comment]
Merge this already

**Pull request merged**
