### PR TITLE
#2855: Fixes the RCD placement algorithm.

### PR DESCRIPTION
**Pull request by ghost**
#2855

**Changelog:**
- tweak: "Changed the window placement algorithm for RCDs: it should pump out full tile windows now."

**Screenshot:**

transport relay 11 2016-09-05 202616

**Note:**
- Please let me know if there's anything fishy with the fix.

### CODE REVIEW

**Comment by ArcLumin** [comment]
Clippy: I see you're installing Windows

**Comment by Pyko1** [comment]
Going full windows now? 
Oh god!

Code looks fine.

**Comment by ghost** [comment]
Yeah okay +1

**Comment by Kokojos** [comment]
Since pyko codechecked it.

**Pull request merged**
