### PR TITLE
New Zombies + MUTATIONS! (READY) #2372

### PR DESCRIPTION
**Pull request by Gandalf2k15**
**THIS IS ONLY FOR ADMINBUSSING AT THE MOMENT**

These zombies DO NOT OVER WRITE ANYTHING. They are a completely new mob, they do not use a virus to spread. That means no stress on the disease controller which means no lag. These are almost identical in how they function. I have tested these at least 100 times. They have never lagged. They shouldn't anyway. Code check please too.

The system is infection system is in several stages, takes a random amount of time for some to turn.

People are infected via bites, which has a random chance to happen when you attack someone. Once bitten there is no cure. _Yet._

Also I plan on adding mutations that you can purchase. Said currency will be based off of how many people you infect.
-DONE-
Now you have a system where you can upgrade your zombie!
All zombies start with 5 points.
You gain 3 
The abilities are:
- Evolve Health(cost: 1): Will increase the max zombie health by 10 and restore 10 (cap 300)
- Evolve Attack(cost: 1): Will increase the max and min damage by 2 (cap 60)
- Evolve Speed(cost: 1): Will increase the max(min) speed by 0.1 (cap -2)
- Self Revive(cost: 7): When purchased the zombie will auto regen but will lose all prior stats
- Force Door(cost: 3): Gives the ability to force open doors (starting 20 seconds)
- Airlock Force Time(cost: 1): Gives the ability to force open doors faster (cap 2 seconds)
- Super Form(cost: 10): Makes you invisible(2000HP), buffs stats for a certain amount of time, then it wears off.
- Upgrade Super Form(cost: 2): Increases the amount of time you are in super form. (cap 30 seconds)

Screenshot of mutations tab:
</img>
</img>

### CODE REVIEW

**Comment by ghost** [comment]
~~Infect verb should be under secrets (What permissions do you need to even have to use infect?) (It should also probably be randomly selected among living players.)~~
~~Disease itself works way too fast and the disease progression is a bit dry (Could use more span classes and blood vomiting)~~
~~Change "You dont feel right! Somethings wrong!" to "You don't feel right! Something is wrong!"~~ "You dont feel right" still needs changed.

Biosuits and hardsuits should give you immunity to infection. (I like the idea of it being incurable, but there needs to pre-emptive measures to block it. Maybe also make it on the first bite, the victim has a tiny chance to become immune.)

Speed upgrades should be rounded and probably represented in percentages (Currently as is, it looks pretty bad when it starts representing stuff in scientific notation.)
~~Infecting someone should probably be the nice blue text rather than a warning, and keep the bites as normal red.~~ The victim should get the user danger text, the zombie mob should get blue text.
~~Change "That bite felt sore as hell! Its getting worse..." to "That bite felt sore as hell! It's getting worse...." (Or do a spawn and make the bite sound like it's beginning to fester and decay.)~~

~~Superform seems way too powerful, (2000HP and 100 dmg attacks?) even if it is expensive. (The lack of sprite isn't good either)~~ Still pretty stronk, not sure how I feel about it.
~~(Code wise, it looks to me that you can upgrade in superform and then lose the changes? Even worse, be locked out of speed upgrades if you were to chug buy them all during it.)~~

~~Airlocks should probably be pried open, powered airlocks should be slow and unpowered ones should be quick.~~

Reposting my criticism here.

**Comment by Gandalf2k15** [comment]
Already amended these.

**Comment by ghost** [comment]
Oh righto

**Comment by ghost** [comment]
Updooted my criticism. Lemme know if I missed something.

**Comment by Gandalf2k15** [comment]
(Code wise, it looks to me that you can upgrade in superform and then lose the changes? Even worse, be locked out of speed upgrades if you were to chug buy them all during it.) fixed this

**Comment by Gandalf2k15** [comment]
Infect verb should be under secrets (What permissions do you need to even have to use infect?) (It should also probably be randomly selected among living players.) Perms are same as BSA, functions like BSA too.

**Comment by Gandalf2k15** [comment]
Biosuits and hardsuits should give you immunity to infection. (I like the idea of it being incurable, but there needs to pre-emptive measures to block it. Maybe also make it on the first bite, the victim has a tiny chance to become immune.) Not entirely sure how to do this.

**Comment by Gandalf2k15** [comment]
Still pretty stronk, not sure how I feel about it. Considering it only last 10 seconds and costs 10 is pretty balanced. Its supposed to make you unbeatable for that amount of time.

**Comment by Gandalf2k15** [comment]
Speed upgrades should be rounded and probably represented in percentages (Currently as is, it looks pretty bad when it starts representing stuff in scientific notation.) Forgot about this

**Comment by yobob591** [comment]
I think if the zombie can bite through a biosuit or something it doesnt make sense to make you immune. Hardsuits, yes I agree, you should need some sort of upgrade to bite through metal

**Comment by carlarc** [comment]
honestly anything with melee damage reduction over OR 15 should make you immune to normal biting from that part. if the zombies really want to infect someone they can strip then

**Comment by yobob591** [comment]
I dont know about zombies being able to strip people. Depends on what style of zombie these are, but most traditional zombies are either too dumb or dont have the dexterity needed to take off peoples clothes.

**Comment by yobob591** [comment]
Id go for the evolve strength stuff improving bite power to get through stronger materials

**Comment by carlarc** [comment]
xenos can strip

**Comment by Gandalf2k15** [comment]
Yeah, hardsuits will be an evolveable power

**Comment by Gandalf2k15** [comment]
But I'm not getting into all that armor level buyllshit

**Comment by yobob591** [comment]
xenos are suprisingly dexterous and according to canon the queen is around as smart as a normal human, but you have a point

**Comment by Gandalf2k15** [comment]
This is better than the current zombies by a mile.

**Comment by carlarc** [comment]
well we can't enforce zombie rp now can we

**Comment by yobob591** [comment]
no, but mechanic wise if the zombie is smart enough to remove clothes is the debate here. like how people who are brain damaged just get the message "x stares drools at/cluelessly at the x" or "you momentarily forget how to use x"

realism or no zombies using computers would be weird

**Comment by yobob591** [comment]
but are we just zombies on our computers????

**Comment by Gandalf2k15** [comment]
Its fine as is. I'm not gonna change the hardsuit shit. I don't even know how to do that. I'll fix the current bugs. Remember this is an adminbus command.

**Comment by yobob591** [comment]
Ah, i think it could work as a really rare event/midround antag like memeductors or ayylmaos though

**Comment by Gandalf2k15** [comment]
That may come aye.

**Comment by calibraptor** [comment]
If this'll be a rare midround thing then +1

**Comment by yobob591** [comment]
Makes sense to make it admin spawn only for now though since its just testing

**Comment by Gandalf2k15** [comment]
I'll see about making this a rare midround like ayys

**Comment by Gandalf2k15** [comment]
Aight this is an adminbus thing for now.

**Comment by yobob591** [comment]
meeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeerge

**Comment by Zadeon** [comment]
Better fix the text saying <color='blue'> in chat and stuff.

**Comment by Gandalf2k15** [comment]
aye pushin fix

**Comment by Gandalf2k15** [comment]
I managed to fuck this up somehow. I'll fix it now.

**Comment by Gandalf2k15** [comment]
this fucked up
repring

**Comment by Gandalf2k15** [comment]
Okay abandon ship, I can't fix the fuckups.

**Pull request closed without merging**
