### PR TITLE
Fixes #2396 : Supermatter shard piercing rad resist.

### LINKED ISSUE #2396: The Supermatter can stunlock you even if you have full protection from radiation damage
The stun is literally detain-mode long, as you sit there getting endlessly bombarded with radiation without any breaks until you explode. Engineers who try to fix the SM or help you - even if they have full protection too - will suffer the same fate.
http://i.imgur.com/O3B6TKR.png
Calibraptor, you suck.

how did i screw up the title that badly jesus christ

### PR DESCRIPTION
**Pull request by ghost**
Does what it says on the tin.

### CODE REVIEW

**Comment by calibraptor** [comment]
Sweet!

**Comment by Nebyab** [comment]
code check please

**Comment by Kokojos** [comment]
Code seems fine to me, leaving merge to headmins,

**Comment by blobbernaut** [comment]
not sure if this worked

**Pull request merged**
