### PR TITLE
Mech repaints, admin-spawn only 4now

### PR DESCRIPTION
**Pull request by Vievioora**
Yeah, mech repaints with different paintjobs for honker, ripley, gygax and durand with sprites from the [thread](http://hippiestation.com/showthread.php?tid=3635)

Admin-spawn only while I figure out how to get spray paint cans to do repaints.
Also my first pull and shit so bear with my fuck ups.

Changes gygax.dm, durand.dm, ripley.dm, honker.dm to allow spawning, mecha_wreckage.dm to process different sprites for repainted mechs and mecha.dmi for sprites.

### CODE REVIEW

**Comment by TDcoolguy300** [comment]
Honke, you fucked up the link naming crap, fixed it because fuck waiting for a response.

**Comment by TDcoolguy300** [comment]
Code looks fine, Travis isn't angry

**Comment by Vievioora** [comment]
I don't know who's Travis, but if he's got a problem I can fuck him up real bad

**Comment by ArcLumin** [comment]
Looks good, if you can't figure out how to make spraycans work then I'll code it once your PR goes through.

As an aside, did you test this with Goliath plating?

**Comment by Vievioora** [comment]
That's actually a good point. I'm sorta waiting for rebase with spray cans. And I'll test it with goliath plates asap, but if works with firefighter (I honestly don't know), it will work with ripleyussr

Edit: Goliath plates work fine with both ripleyussr and firefighter and does apply armor properly.

**Comment by ArcLumin** [comment]
I knew the goliath plates would work fine, I was more curious what they looked like with the goliath plating.

**Comment by JohnGinnane** [comment]
Changelog pls

**Comment by JohnGinnane** [comment]
ty)

**Comment by Scinexx** [comment]
Fuck yeah, I was waiting until someone would code these in

**Comment by Hackole** [comment]
Hey hey hey, I remember these from that fourm post - never thought they'd get put in. +1

**Comment by ghost** [comment]
Yeah okay +1

**Pull request merged**
