### PR TITLE
FULTON RECOVERY SYSTEM (traitoritem/researchitem)

### PR DESCRIPTION
**Pull request by ghost**
BIGGEST CREDITS TO IAMGOOFBALL AND FRAGG FOR PROVIDING CODE & SPRITES RESPECTIVELY

Fulton recovery device fills in the void of the rapid crate sender somewhat.
Anything not bolted down can be sent, people, welded crates, tanks, canisters, items, even containers or single items.

In order to fulton something you must have the device, and a beacon to send it to. You can engage the fulton system inhand to connect to a beacon, or hit a beacon with it inhand to sync.

Beacons are made from machine housings, requiring a manipulator to finish.
Fulton devices need 4 combat and 5 Engineering to be researched,,
and require 500 silver and 3000 metal to be created via protolathe.

Pros - Sends stuff to personalized beacons, Can send almost anything
Cons - Incredibly obvious and painfully slow to deploy at first.
When people are sent, they scream pretty loudly.

Traitors can buy the circuitboard for four TC's, and the device for six TC's

SPRITES AND THE STUFF IN ACTION! 
http://puu.sh/lCdhn/5a5009181b.png
http://puu.sh/lCcEg/2c75704be5.png <-- circuitboard requirements
http://puu.sh/lCcBA/522a6a027e.png <---- device requirements
http://puu.sh/lCgd7/aa4da4dfe7.png <-- a sheet of metal arriving to a beacon
http://puu.sh/lCglE/aceba42842.png <--- any traitor can buy the item
http://puu.sh/lCgZV/b1d9169513.png <-- device sprite
http://puu.sh/lCh1k/7be8ae15cd.png <-- beacon sprite

### CODE REVIEW

**Comment by Chronitonity** [comment]
Detail in the changelog how to use

**Comment by Spacedong** [comment]
now I can finally fulton faggots back to permabrig +1

**Comment by ghost** [comment]
http://puu.sh/lCgX6/6ac26b9d11.png
instructions in the changelog

**Comment by Weisyl** [comment]
I always wanted a retarded balloon that could immediately carry any person or item across the station an infinite number of times.

**Comment by Foosili** [comment]
As long as security cannot easily get this shit I'm for it.

**Comment by danhibiki** [comment]
I hugely opposed this for a long time before, but at this point I really don't care. Might as well.

**Pull request merged**
