### PR TITLE
Brings back the supermatter, relocates the singularity.

### PR DESCRIPTION
**Pull request by calibraptor**
What it says on the tin, engineering now closely resembles what it was pre-rebase. There are other additions and changes too, I'll list off all the ones I can remember.
- Fixed crystal glass so it actually works as intended with help from TD
- The brig now has a proper execution chamber making use of crystal glass.
- Fixed some sketchy looking wiring in the security wing, doubt I fixed the power problems considering it's on the exact opposite side of the station from engineering
- Added crystal windows to toxins on both the main station and the science outpost. Stoke the flames of your passion.
- Atmos technicians now have access to the supermatter dedicated part of engineering. Almost all of the electrical related equipment including insulated gloves has been moved to the singularity engine, where they do not have access.

KNOWN PROBLEMS:
- The supermatter shard is kind of weaksauce when it comes to power output
- The engine jettison currently does not work as I had to anchor the shard in order to keep it from getting pushed around when air is pumped into the chamber
- Could not recreate the supermatter control console from pre-rebase hippie. Couldn't get the damned thing to work. Have a table instead.

sm

singulo

execution

toxins

outpost

### CODE REVIEW

**Comment by Spacedong** [comment]
:+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1:

**Comment by ghost** [comment]
Fuck yes, please.
+1

**Comment by Gandalf2k15** [comment]
yus

**Comment by carlarc** [comment]
> tesla engine still there

make that shit cargo only now

**Comment by yobob591** [comment]
merge dis shit rite nao

**Comment by danhibiki** [comment]
Oh hell but fuck yeah

**Comment by blobbernaut** [comment]
tesla too boring and non-explosiony, 10/10 would merge

**Comment by Crystalwarrior** [comment]
Tesla is definitely broken as hell since all it takes to counter it is a freaking hardsuit, which every engineer spawns with (making it incredibly easy to murderbone with as an engie). :+1: :100:

**Comment by Voratius** [comment]
Wait what do you mean the SM is weaksauce in terms of power output?

Didn't it give off more power than an average singularity?

**Comment by ghost** [comment]
We used to have the full memeshard.
You can make more than singulo power with regular shard though.

**Comment by calibraptor** [comment]
@carlarc 
I actually like the Tesla.

**Comment by Pyko1** [comment]
Not map merged.

**Comment by carlarc** [comment]
I got instacrit by the tesla, more than a screen away, when it had zero "balls" around it.
There's also literally no benefit whatsoever to use the singulo above it.
Also it's more fun to gib by singulo than instacrit by tesla.

**Comment by calibraptor** [comment]
Love you Travis <3

**Comment by Pyko1** [comment]
seems to be properly merged now

**Comment by calibraptor** [comment]
Aight don't go merging this yet just found out I gotta repath some shit

DO NOT MERGE: Some nerd ended up removing the science outpost, which this PR makes modifications to.

**Comment by JohnGinnane** [comment]
Okay this is now out of date. You'll need to close this, update your repo and then resubmit the same branch. You shouldn't need to delete your branch or anything.

**Pull request closed without merging**
