### PR TITLE
Makes weapon tablecrafting suck less

### PR DESCRIPTION
**Pull request by calibraptor**
Changes in this PR:
- Modular receivers are no longer exclusive to RnD, and can be crafted with metal and rods.
- Unloaded shotgun shells can also be crafted without RnD. Improvised items requiring RnD was dumb anyways.
- Improvised shotguns now require duct tape to secure them instead of package wrap.
- Improvised shells now deal a max of 40 damage, as opposed to 20. Wide spread though.
- Overloaded improvised shells now deal a max of 70 damage, as opposed to 25. However it's spread is so ridiculously wide that you'll have trouble dealing serious damage at any range past point blank. If you want a more reliable, tighter spread, use actual buckshot. (Why do they deal so much damage now? You have to make black powder in order to make these, it would be easier in many cases to just hack an autolathe for buckshot.)
- Improvised tasers are now craftable. However, they hold only enough charge for one shot, take a long time to recharge, require RnD parts, and require having a /real/ taser to observe the design of in order to make them. So people will probably only make improvised tasers if they intend to distribute them or just want extra shots.
- Rifle stocks now require less wood to craft now. Seriously, it took as much wood to make a door as it did to make a stock.
- Duct tape has been added to the vendomat.

Improvised taser sprite and in-hand sprite compared to regular taser:
taser comparison

### CODE REVIEW

**Comment by Gandalf2k15** [comment]
I was actually looking forward to this. Yay!

**Comment by Gandalf2k15** [comment]
Can I see a picture of the 1shot tasers?

**Comment by calibraptor** [comment]
Yeah I'm actually working on that now

**Comment by calibraptor** [comment]
Screenshot uploaded

**Comment by Gandalf2k15** [comment]
Oh cool. I like that.

**Comment by TDcoolguy300** [comment]
Need a changelog, but the code looks fine.

**Comment by trifornt-tinfornt** [comment]
Don't see why you would ever want to make an improvised taser, given that it requires a real taser and RnD parts (unless you mean basic stock parts) and it's a straight downgrade. Stun Revolvers aren't that hard to get if you're a scientist and if you've gone through the effort of stealing a taser then it's piss-easy to just steal that same officer's I.D.

Also, given the sprite, a name like "Stun Derringer".
EDIT:
You made making an improvised shotgun way easier, too, and encourage the use of autolathes with them. What's gonna stop someone from just getting a rubber shot in that thing, which further negates the need of an Improvised Taser?

Great idea though, just could use some work.

**Comment by calibraptor** [comment]
@trifornt-tinfornt You'd have to steal either the warden's ID or the HoS's ID in order to unlock the secure case it comes in. The improvised taser does use lower tier parts, making it easy to mass produce and hand out to your fellow revolutionaries/cultists/gang members once you pass the hurdle of acquiring a security taser.

EDIT: There's nothing really stopping someone from loading standard shotgun ammunition into it. The main hindrance of the improvised shotgun is that it needs to be reloaded after every shot.

**Comment by ArcLumin** [comment]
Oh hell yeah, bring on the greytide shotguns.

**Comment by trifornt-tinfornt** [comment]
By "lower tier parts" do you mean parts that you can make out of an autolathe in the "Basic Parts" category?

**Comment by calibraptor** [comment]
@trifornt-tinfornt Nope. You need a high capacity battery and a high power micro laser. So either loot secure storage for the spare parts in there or get them from science.

**Comment by danhibiki** [comment]
I dunno how i feel about improvised tasers personally, but it is only one shot.

**Comment by ghost** [comment]
I think the improvised shotgun is going to be too dangerous. 3 shots to crit someone as opposed to 5 if the odds are in your favour for both times.
I'll voice my concern over greytide tasers again, a small taser that can fit in your pocket is to be feared.

**Comment by ArcLumin** [comment]
I wouldn't be too concerned about it being OP; I've used improvised shotguns a number of times, and they can only hold one round at a time, so you won't be firing it off very fast at all. If anything, this makes shotguns as a whole more viable.

**Comment by Kierany9** [comment]
Colours on the taser and improvised taser's inhand sprites are slightly different. Is that intentional?

Other than that, it's nice to see useless shit being made useful again.

**Comment by Kierany9** [comment]
Crafting time on almost all improvised weapons was halved, which was not noted in either the pr description or logs (please dont do this holy shit reeeeeee). I don't think that this change is necesary at all, crafting should not be uninterruptable. Most crafts only take 8 seconds anyway, the only one that really needed reducing was the blackpowder slugs(30 goddamn seconds).

Also, 2 blackpowder is extremely little and in practise a completely irrelevant ammount allowing you to make 25 slugs with a beakerfull of the stuff. 15 per slug was way too much though, perhaps make it 5 or 10.

**Comment by calibraptor** [comment]
@Kierany9 That's the recipe for paper cartridges, not improvised shells. Which I recall do pretty piss poor damage for the effort it takes to make them and get the corresponding weapon.

**Comment by calibraptor** [comment]
@McBawbaggings I honestly wouldn't be too concerned about improvised shotguns. They need to be reloaded every single shot, which is pretty tedious to do. As well as the spread on the improvised shells and overloaded shells being so ridiculously wide that you won't be dealing much damage unless you get close enough that someone could disarm you or take you down with a baton.

**Comment by calibraptor** [comment]
Alright, the improvised taser (Now stun derringer) now requires an advanced capacitor in addition to plasteel in order to produce.

**Comment by Spacedong** [comment]
you realize that a stun revolver can be made before you ever get a chance to make the one-shot taser right? what the fuck is the point, how is it improvised if it requires RESEARCH to make

**Comment by calibraptor** [comment]
Because you need to unlock the case the stun revolver comes in. The stun derringer has no such requirement and just needs the stock parts.

Also trying to please the people overly worried about how much a craftable one shot taser gun will affect the game balance.

**Comment by trifornt-tinfornt** [comment]
I still think that the Stun Derringer should only require basic science parts that you could make at the autolathe at most.
And like I said, if you're in a team-antag mode and you're stealing tasers or what not it's usually quite easy to just nab the Warden's I.D. or steal the HoP's I.D.

**Comment by Hackole** [comment]
actually calibraptor you can acid open weapon lockboxes. your stun derringer has no use right now - remove the taser requirement

**Comment by calibraptor** [comment]
I'm actually working on balancing the stun derringer to remove the taser requirement.

**Comment by trifornt-tinfornt** [comment]
No, remove the RnD requirement. There is no need to research this thing or gate it behind RnD. Even then its long recharge and one shot means you'd be better off making a ton of improvised shotguns and making rubber shots.
But it's good that you're going to attempt to balance it.

**Comment by dreamcrab** [comment]
i actually kinda agree with trifornt, if its a disaster and every greyshirt is armed to the tits with them then we can change it.. but it always confused me how the improvised shotgun and stuff required research

**Comment by calibraptor** [comment]
@Nebyab 
I've already reverted most of them except for the robot crafting ones, also crafting is interruptible as hell, I've had to start over countless times due to people pushing me away from the table.

That said once I can get around to it I'll be removing the R&D requirement.

**Comment by calibraptor** [comment]
Going on a week long trip starting sunday. I'll see if I can be arsed to continue working on this PR when I get back.

**Comment by Carbonhell** [comment]
Everything seems great but i can't really understand the point of the mini taser,i don't like the idea at all,plus you removing the rnd factor from shotguns because it made no dense to then add it to your taser thing is a logical flaw

**Comment by GenericGoose** [comment]
rip
what a rotten way to die

**Comment by calibraptor** [comment]
Can't be arsed to work on it further. Might redo it at some point.

**Pull request closed without merging**
