### PR TITLE
Makes the Hockey set properly spaceworthy and able to eat through the mask. 

### PR DESCRIPTION
**Pull request by GuyonBroadway**
In an oversight I accidentally set the min temp protect to firesuit and not spacesuit. You can now also eat through the mask, remember that a hearty breakfast is the key to any successful athlete.

Fixes: #3301

### CODE REVIEW

**Comment by GuyonBroadway** [comment]
Might need head input, one IS a bugfux but the other is a tweak. and DAMINT GANDALF I WAS JUST TYPING!!

**Comment by Gandalf2k15** [comment]
Welp, the eating part makes it balancing and therefore now needs head input.

**Comment by GuyonBroadway** [comment]
The joke was you added those tags literally as I was typing out that it might need those tags. GET OUT OF MY HEAD YOU FUKKEN SCANNER!

**Comment by Gandalf2k15** [comment]
Oh jokes on you then. I am just too fast for you.

**Comment by JohnGinnane** [comment]
Code looks good, did you test?

**Comment by GuyonBroadway** [comment]
Yep, you can wander around in space and eat things.

**Comment by JohnGinnane** [comment]
Cool

**Comment by ghost** [comment]
Sick cunt +1 yeah

**Comment by SpankMasterson** [comment]
+1

**Comment by GuyonBroadway** [comment]
So... as McBawb removed the needs head input tag is this ready to merge?

**Comment by JohnGinnane** [comment]
Yes, merging

**Pull request merged**
