### PR TITLE
Footprints Port

### PR DESCRIPTION
**Pull request by Cafaling**
Chron is bad at making puns.

Please kill him on sight.

### CODE REVIEW

**Comment by Chronitonity** [comment]
@Cafaling Give in game pictures so people can see what they look like plox

**Comment by Iamgoofball** [comment]
this is only the icon

theres no code here

**Comment by Chronitonity** [comment]
@Iamgoofball yes

**Comment by Cafaling** [comment]
I just redid the icon. chron told me to.

**Comment by Cafaling** [comment]
blood
oil

**Comment by nalarmg** [comment]
Needs a changelog.

**Comment by Cafaling** [comment]
Noice

**Pull request merged**
