### PR TITLE
Brig fix

### PR DESCRIPTION
**Pull request by AliiTea**
Fixes a bunch of oopsies made by Kilm.

{#} Fixed the brig cells so that they actually work
{#} Fixed the leftover piping & lights
{#} Added windows to lobby office
{#} Made the holding cell part of security instead of the hallway

image

### CODE REVIEW

**Comment by Chronitonity** [comment]
telling us what you fixed and changelogging it would be good

**Comment by AliiTea** [comment]
ya ya

**Comment by Carbonhell** [comment]
you sure kilm isn't already working on it?

**Comment by AliiTea** [comment]
@Chronitonity @danhibiki review and merge boi

**Pull request merged**
