### PR TITLE
MGS3 OD greene  & CQC Martial Art 

### PR DESCRIPTION
**Pull request by ghost**
new martial art, cqc. can do a three hit hombo with a stun at the end, and a slam which does brute and stuns both the user and the victim for a second.
attacks bypass armour.

https://i.gyazo.com/bf5bcd87098437f4b7c80649ca2a4499.png
onmob sprites fixed and stuff
https://i.gyazo.com/9b29baf6b2fb8de4ca4172f45bda3c0d.gif 
crude gif of me slamming some dude

### CODE REVIEW

**Comment by Chronitonity** [comment]
GIVE IT A PROPER NAME AND DESCRIPTION AHHHHHH

**Comment by danhibiki** [comment]
So whats the outfits name?

**Comment by ghost** [comment]
name = "olive drab suit"

**Comment by danhibiki** [comment]
I just want to see an actual picture of it on a person.

**Comment by danhibiki** [comment]
Sure

**Comment by doobiedoo23** [comment]
fuck yeah

**Comment by ghost** [comment]
added some more MOVES!!! and shit.

**Pull request merged**
