### PR TITLE
Supermatter Engine

### PR DESCRIPTION
**Pull request by calibraptor**
What it says on the tin, the singularity was relocated so engineering now closely resembles what it was pre-rebase. There are other additions and changes too, I'll list off all the ones I can remember.
- Fixed crystal glass so it actually works as intended with help from TD
- The brig now has a proper execution chamber making use of crystal glass.
-  Fixed some sketchy looking wiring in the security wing, doubt I fixed the power problems considering it's on the exact opposite side of the station from engineering
-  Added crystal windows to toxins on both the main station and the science outpost. Stoke the flames of your passion.
-  Atmos technicians now have access to the supermatter dedicated part of engineering. Almost all of the electrical related equipment including insulated gloves has been moved to the singularity engine, where they do not have access.

KNOWN PROBLEMS:
-  The supermatter shard is kind of weaksauce when it comes to power output
-  The engine jettison currently does not work as I had to anchor the shard in order to keep it from getting pushed around when air is pumped into the chamber
-  Could not recreate the supermatter control console from pre-rebase hippie. Couldn't get the damned thing to work. Have a table instead.

533679f8-193f-11e6-9db8-b92f4ca23817

976d338c-193f-11e6-8561-718b1396f112

5ec60f22-193f-11e6-97df-d293697c0e21

6422c58c-193f-11e6-92cb-ca5dcb17fb60

67ceb204-193f-11e6-9d9b-08b02a45d36e

### CODE REVIEW

**Comment by Gandalf2k15** [comment]
Yay
its ficed!

**Comment by Gandalf2k15** [comment]
Fized

**Comment by Pyko1** [comment]
same as https://github.com/HippieStationCode/HippieStation13/pull/2315

**Comment by ghost** [comment]
I'll remirror my +1 then

**Comment by calibraptor** [comment]
Just gonna note that if this gets merged it will also re-add the science outpost.

**Comment by Gandalf2k15** [comment]
merg pls

**Comment by trifornt-tinfornt** [comment]
Where's the real supermatter? Why is it just a shard now?

Oh well, merge.

**Comment by blobbernaut** [comment]
real supermatter was removed on the last rebase

**Comment by calibraptor** [comment]
@trifornt-tinfornt The real supermatter crystal can always be added later.

**Comment by Nebyab** [comment]
yeah alright sure whatever

you happy now?

**Comment by calibraptor** [comment]
@Nebyab yus

**Comment by calibraptor** [comment]
Got a yes from two heads, ya'll can merge this whenever. I'm headed to bed.

**Comment by calibraptor** [comment]
OH COME ON
Edit: Fixed the conflicts rather quickly now that I /know/ what to do.

**Comment by calibraptor** [comment]
Aight, all checks have passed, will be ready to merge in a sec.

**Comment by calibraptor** [comment]
Yeah I'm just gonna refork and open another PR

**Pull request closed without merging**
