### PR TITLE
Asteroid Crash Site

### PR DESCRIPTION
**Pull request by Gandalf2k15**
Adds in a new space junk item to the Z4 map.

Loot: 
1 Lazarus Injector, locker. 
1 C05r pistol, **in safe**. 
2 C05r ammos, **in safe**. 
1 RCD, **in safe**.

Its basically a cool place to stop when exploring space.
Image 1:
image

Image 2:
image

As you can see there are several kittens, its part of the LORE(Kek), the guy that once lived here came from the ruski station but crashed in his escape pod, had his cat which had babbies, he then had to start eating them to survive, however after 3 years he killed himself because of something.

### CODE REVIEW

**Comment by Spacedong** [comment]
can ya place some stuff in some of those little asteroid chunks

**Comment by Gandalf2k15** [comment]
Dem minerals spawn

**Comment by Spacedong** [comment]
also why a shotgun? we already have a shotgun on the white ship and other places in space, cmon lad

**Comment by Spacedong** [comment]
whats with the double wall in the back?

**Comment by Gandalf2k15** [comment]
yeah shotgun is abit over used ill replace it with a toy one.

**Comment by Gandalf2k15** [comment]
Also that double wall is removed, gotta update the pictures.

**Comment by Spacedong** [comment]
can you add a treasure more creative than a single shotgun?

**Comment by Gandalf2k15** [comment]
Loot: 1 Lazarus Injector, locker. 1 Nagant revolver, safe. 1 RCD, safe.

**Comment by Gandalf2k15** [comment]
Loot: 1 Lazarus Injector, locker. 1 C05r pistol, safe. 2 C05r ammos, safe. 1 RCD, safe.

**Comment by Spacedong** [comment]
can you place some enemies there

**Comment by Spacedong** [comment]
space pirates or something

**Comment by Spacedong** [comment]
maybe a booby trap

**Comment by Gandalf2k15** [comment]
I could make the cats feral

**Comment by Spacedong** [comment]
landmines perhaps

**Comment by ArcLumin** [comment]
Ｗｅ　ｎｅｅｄ　ｍｏｒｅ　ｓｈｉｔ　ｉｎ　ｓｐａｃｅ，　Ｉ’ｄ　ｌｉｋｅ　ｔｏ　ｓｅｅ　ｓｐａｃｅ　ｊｕｎｋ　ｅｖｅｒｙｗｈｅｒｅ，　ｓｏ　ｙｅａｈ，　ａｌｌ　ｆｏｒ　ｉｔ

**Comment by Gandalf2k15** [comment]
Images updated

**Comment by GenericGoose** [comment]
add floor tbh
lazarus suks benis

**Comment by ghost** [comment]
The pistol is in the safe, right?

If so cool, if not jesus christ pls stop putting guns in space everywhere.

**Comment by Gandalf2k15** [comment]
Is in safe

**Comment by Lawligagger** [comment]
looks ok

**Comment by ghost** [comment]
Shitty lore reminds me a bit about red dwarf. I like it. +1

**Comment by dreamcrab** [comment]
i will approve this but LET IT BE KNOWN THAT ALMOST ALL OTHER SPESS OBJECTS WITH GUNS WILL BE REJECTED BY ME +900009

**Comment by GenericGoose** [comment]
is there really no neat items that can be put in space? theres literally guns everywhere
there should be cool stuff people want tbh

**Comment by Kokojos** [comment]
Why not part of a NASA spacesuit, or a novaflower, or anything else.

**Comment by Carbonhell** [comment]
1)fuck guns as reward, i'm highly against guns otherwise people will go there just to collect those and fuck with the round. add something useful/funny, not a gun please
2)how did the cat have babies if there's just one adult cat,did he fuck himself

**Comment by ArcLumin** [comment]
asexual cats confirmed for the lore
they were made by scientists looking to create the ultimate life form, but it failed miserably and eventually made catbeasts/tarajans. These asexual cats were an early prototype of tarajans

BEST LORE

**Comment by ghost** [comment]
http://res.cloudinary.com/uktv/image/upload/v1385482582/lyv0htnkwjmevrsoxdxa.png

**Comment by carlarc** [comment]
make a cat render

spawns cats, 33 of hostile catbeast, 33 of feral cat, 33 of normal cate

**Comment by Rodocks** [comment]
no one in the world knows how to crack a safe even looking at the code I still don't understand it.

**Comment by ghost** [comment]
psure you just use a stethoscope and it works like a multitool on a safe

**Comment by Carbonhell** [comment]
I know how to hack a safe in less than 2 minutes
so git gud

**Comment by Pyko1** [comment]
Would be better to make these in to templates, and convert abandoned whatever in to one as well, and turn z4 in to a random space as well.

**Comment by carlarc** [comment]
Safecrackin is easy as shit

**Comment by GenericGoose** [comment]
safe cracking is ass i need to learn that
need more rewarding items that won't kill the round

**Comment by Nebyab** [comment]
k

**Pull request merged**
