### PR TITLE
6/14/16 (DO NOT MERGE;MISTAKE)

### PR DESCRIPTION
**Pull request by jediluke1999**

### CODE REVIEW

**Comment by TheOneAndOnlyCreeperJoe** [comment]
So... What's it do?
Gotta add a name and desc lad.

**Comment by danhibiki** [comment]
Just a quick glance, looks like it lowers the gateway cooldown, does a lot of code maintenance as far as its presentation (two line if-returns instead of one line), and a couple of statements to check if its frozen in a sleep loop (related to the map loader). I could be missing things, and this is something that _should_ be done by the person submitting the PR.

**Comment by TDcoolguy300** [comment]
It's primarily Gandalf's Commits from another time, his commits are just him updating from the main repo

**Comment by Gandalf2k15** [comment]
wat

**Comment by jediluke1999** [comment]
Sorry, was trying to update my own fork for testing things. My apologies. Swapped the wrong commits.

**Pull request closed without merging**
