### PR TITLE
fuck embedding

### PR DESCRIPTION
**Pull request by SplergeBucket**
boom
embed chance for sharp objects gone from 45 to 15

### CODE REVIEW

**Comment by TrashFiend** [comment]
Would this affect the Rod Gun any?

**Comment by XeonFaux** [comment]
Most likely in zero gravity, rod gun would also trigger unremovable rods with each shot. Untested, however.

**Comment by TDcoolguy300** [comment]
Rod gun projectiles are a 100% embed chance, this has no effect on it.

**Comment by TDcoolguy300** [comment]
Also, Changelog would be appreciated

**Comment by SplergeBucket** [comment]
iunno how 2 changlog, if you can message me with a for dummies guide i'll do it when i get confirmation of whether this'll be merged or not

**Comment by Pyko1** [comment]
Actually, why do rods embed when their "sharpness = 0" which is supposedly IS_BLUNT?

**Comment by SplergeBucket** [comment]
i may be confusing myself here but im pretty sure they're on the sharp list in the combat.dm or what other ever misc.dm file there is

**Comment by Pyko1** [comment]
At least ingame vars claim they are not sharp.

**Comment by McHatters** [comment]
I thought sharpness had to deal with how much bleeding it causes when someone attacks with it

**Comment by Kierany9** [comment]
I swear if this fucking nerfs hatchets I'm going to flip shit. You don't know joy until you ninja hatchet a dude in the face as botanist.

**Comment by SplergeBucket** [comment]
hatchets are next fucker

**Comment by SplergeBucket** [comment]
then i'll go for glass shards

**Comment by SplergeBucket** [comment]
and finally i'll end by removing embedding and bleeding and the health system entirely

**Comment by danhibiki** [comment]
Yes

**Comment by Nokington** [comment]
sure

**Comment by Carbonhell** [comment]
Rods are in the special list, pratically the is sharp proc checks if the item is sharp, pointy or if it's in a special list,i remember i added it in the special list instead of just making them sharp/pointy to not make them too op as thrown,but it seems like it didn't change anything

**Comment by SplergeBucket** [comment]
now i just need to figure out how to do a changelog, i'll see about that in the next two or so days iunno

**Comment by nalarmg** [comment]
Shouldn't be on a branch on the master repository. Also needs a changelog before this can be merged.

**Comment by SplergeBucket** [comment]
iunno what any of that branch doohicky is but if you're saying i need to somehow find a way to do the code that differs from the way dan and myself did then dangdoodly darn i'll be drongo'd

**Comment by SplergeBucket** [comment]
based td
this is good to go as long as travis dont give it to me raw

**Pull request merged**
