### PR TITLE
Lets Oxygen and Nitrogen (The chems) cause the gas when splashed

### PR DESCRIPTION
**Pull request by ArcLumin**
Title. Splashing oxygen or nitrogen now properly will cause the atmos to appear.

### CODE REVIEW

**Comment by Pyko1** [comment]
is that same rate as plasma?

**Comment by ArcLumin** [comment]
Half the rate, considering how easily you can splash both since you can just pour em out of the dispenser

**Comment by Pyko1** [comment]
Yeah, might be better to have it even less. Mainly worried about some dude just splashing 100u beakers of nitrogen around and making it un-breathable.

Did you do in game tests to see how bad it is if 100u nitrogen is splashed?

**Comment by ArcLumin** [comment]
Nope. This is directly forked from rebase code. I saw it and figured it'd be good to see how it goes on main server before it happening on rebase.

**Comment by Pyko1** [comment]
true, anyways code looks fine to me

**Comment by KayeArray** [comment]
I don't think nitrogen displaces air very well so it should be good.

**Comment by ghost** [comment]
Yeah okay +1

**Comment by blobbernaut** [comment]
Liquid nitro should come out really cold and make people you splash cold too

**Comment by Lawligagger** [comment]
ok

**Comment by Gandalf2k15** [comment]
Code is good. 2/4 headmins approval PASSED. Awaiting changelog before merge.

**Comment by Gandalf2k15** [comment]
All systems go! 2/4 HA approval PASSED. Code PASSED. Merging.

**Pull request merged**
