### PR TITLE
Science chem map update.

### PR DESCRIPTION
**Pull request by Weisyl**
Updates the new chemistry lab in science to be more secure and harder to break into. Also organizes the storage room in the bottom-left of the science chemistry area to make it more accessible. Additionally, some minor adjustments to the magazines of the AK-922 and AK-922 icons themselves to reflect on the casings now being dark-green.

### CODE REVIEW

**Comment by Weisyl** [comment]
Ignore the 8 other commits, it's just git being a fuckface. Look at the files-changed tab to see the actual changes.

**Comment by lcass** [comment]
Aight , mergin.

**Comment by lcass** [comment]
Did you map merge this?

**Comment by Weisyl** [comment]
@lcass Yep.

**Pull request merged**
