### PR TITLE
Gibber Fix

### PR DESCRIPTION
**Pull request by AliiTea**
Carbon told me to do it :O

### CODE REVIEW

**Comment by nalarmg** [comment]
Needs a better description on what this is doing and why.

**Comment by Carbonhell** [comment]
By default, if a mob gets gibbed it will spit out normal meat. But someone decided to put meat = null to IPCs, therefore overriding the default meat type. When the gibber tries to create the meat type, it tries to create meat(null) and fails,therefore runtimes and the proc stops working. This will make IPCs spit normal default human meat, since it'd be an huge pain in the ass to make them spit metal, which would cause snowflakey code just for a little effect to a race in my opinion useless,ay

**Comment by nalarmg** [comment]
Ah. Please keep descriptions actually descriptive in the future.

**Comment by Carbonhell** [comment]
Yeah well i told what it did in coderchat, sorry ay

**Pull request merged**
