### PR TITLE
Map Fixes(nerfs)

### PR DESCRIPTION
**Pull request by Gandalf2k15**
Removes arrivals shutters because shitlers kept on closing them blocking off access.
Replaces the maint chem dispenser with a Porta one. No more super OP nades!
Also fixes perma wall things.
Gives maint grinder
Gives xenobio an emergency toolbox

### CODE REVIEW

**Comment by ghost** [comment]
Good shit +1

**Comment by Sarcalogo** [comment]
Guess you want people to steal the chem dispenser each round don't you?

**Comment by ghost** [comment]
> Having a fully functional chem machine in maint for powergaming is a good idea lads.

Why play chemist if you can be a greyshirt with access to nearly all chems anyway.

**Comment by calibraptor** [comment]
+1

**Comment by ghost** [comment]
Oh actually, if you're making a map PR, could you make the walls near the firing room maint in sec rwalls?

**Comment by calibraptor** [comment]
dgfds

McBawbaggings is talking about this area. Make those regular walls into r-walls so people can't easily weld in.

**Comment by blobbernaut** [comment]
Fucking rip the dispenser it was so useful

**Comment by Kierany9** [comment]
>Replaces the maint chem dispenser with a Porta one. No more super OP nades!

What do you mean the clown isn't supposed to be able to make chlorine trifluoride?

In all seriousness, I know that it's not exactly the most balanced item but I have **_very_** mixed feelings about removing the chem dispenser. Just so you know, the portable dispenser is literally useless in terms of what it can make before being upgraded(yes because rnd is going to upgrade a machine in the middle of maint of course they are).

This change means more powergamers barging into chemistry, more greytides either trying to break in or asking for probably-deadly chems and so on. The dispenser in maint was also great for botanists, scientists and janitors when the chemists are being total bastards or before you have biomass/parts for mutagen/acid/cleaner. It's sort of like the few insulated gloves in vending machines and the powercells in maint/tool storage, they keep most of the shitstains out of engineering while still being out of the way enough to not have absolutely everybody use it. And about OP grenades, you need to get the parts to grenades yourself and you only get two small beakers to mix with which seriously reduces the speed at which you can pump stuff out. Unless Cargo wants to be nice or you break into chemistry(at that point you don't even need the maint dispenser), you aren't getting any more beakers, if you want multiple grenades, you'll need to conform with bottles which are 30u each. The only actual balance issue I have is how you can pump out enough sulfidzane/syptic to heal any injury in about 30 seconds, which is an issue with goofchem and not the maint dispenser since chemists don't need to use grinded plasma as a catalyst anymore.

Also, if the dispenser goes, I'll really miss the "hive of scum and villainy" atmosphere that place has.

**Comment by Gandalf2k15** [comment]
I'll fix the walls too.

**Comment by ghost** [comment]
On retrospect, I propose we also buff the starting capacity and charge and add a grinder back.

But you can still make some chems like space lube.
The old bar which has no access requirements stock chemicals that heal burn, brute and tox damage.

There's the nearby garden for some chems, and I think if we had the grinder we'd see more use out of it.
Speaking of the grinder, if we had access to one then you'd could make chems like miner's salve, mannitol.

I still think it's a bad idea to have a fully functional chemistry in maint which is just a little less efficient than chemistry and there's no plasma.
I've heard other ideas of nerfing maint chem such as removing pills, patches and accurate values from the chem master. I'd like to hear what people have to say about it though.

I want ghetto chem, but it should be uncommon recipes made with homegrown or scavenged items. The lack of a grinder is a double whammy to those two.

**Comment by dreamcrab** [comment]
also uhh, if we are fixing the map.. spacedong brought up that if you dont have a crowbar and youre in the slime area of xenobio when the fire alarm goes off, youre fucked

**Comment by Gandalf2k15** [comment]
Gives maint grinder and xenobio an emergency toolbox

**Comment by Sarcalogo** [comment]
Grinder is completely broken. Doesn't work at all.

**Comment by Kierany9** [comment]
@Gandalf2k15 YOU FUCKED UP, YOU MERGED THIS SHIT BY ACCIDENT IN THE REMOVE TESLA PR.

GOOD FUCKING JOB.

**Comment by Gandalf2k15** [comment]
Wat

**Comment by GenericGoose** [comment]
can you fiks this thing too? i think whoever changed lawyer office last time broke the disposal pipe there (security one)
i'll check again and screenshot in a sec

**Comment by GenericGoose** [comment]
selected tile has no disposal pipe
ss 2016-06-21 at 11 06 22

gg
not like anyone uses security criminal disposals anyway (because it wasnt reported)
yeah, why bother if you can just criminal all the way from RD/engineering to brig, right?

**Comment by Carbonhell** [comment]
News? @Gandalf2k15

**Comment by Gandalf2k15** [comment]
Waiting to be merged tbh

**Pull request closed without merging**
