### PR TITLE
Prototype SMG / SABER magazine size nerf

### PR DESCRIPTION
**Pull request by Weisyl**
Nerfs the SABER's / Prototype SMG's (made in RnD) magazines so that they can only hold 30 rounds of 9mm instead of 42. In Pre-rebase this was something like 21 rounds max but it was really meh in practice. Furthermore, the fire_delay of the SMG was changed to 1, as this was the value in Pre-Rebase code. Also makes the magazines with exotic ammo (such as armor-piercing, incendiary, etc) come in a lockbox. Regular ammo can still be printed E-Z P-Z. Alongside that, some of the magazines no longer require glass in their production because that made no sense at all. Finally fixes a ton of typos in the protolathe descriptions of the magazines.

### CODE REVIEW

**Comment by Chronitonity** [comment]
This thing is insane currently. :+1: From me.

**Comment by Foosili** [comment]
please please please fucking fuck :+1:

**Comment by TDcoolguy300** [comment]
Will need to merge due to the Meeseeks shit.

**Comment by Chronitonity** [comment]
Next time you remove something, put it in the title or at the very least the description. 

Meeseeks box should've been made harder to make, not straight up removed, and it shouldve been announced in the PR that it would be removed from it, not hidden in a commit.

**Pull request merged**
