### PR TITLE
Dwarves can crawl through vents

### PR DESCRIPTION
**Pull request by Chronitonity**
only works if they are naked

they take pressure damage while in the vents

This also gets rid of those two mutations no one uses/likes (Chav/Elvis)

### CODE REVIEW

**Comment by Foosili** [comment]
Can they hold objects at all while they ventcrawl?

**Comment by Chronitonity** [comment]
Nope, they gotta go in stark fucking naked

**Comment by Foosili** [comment]
Alright then I'm cool with trying this :+1:

**Comment by Nebyab** [comment]
Yeah sure, give it a trial run

**Pull request merged**
