### PR TITLE
Limit max number of dental implants

### PR DESCRIPTION
**Pull request by JohnGinnane**
This change will limit the maximum number of dental implants someone can
have active in their head to 1.

This number is arbitrary and if someone has any suggestions then please
let me know

### CODE REVIEW

**Comment by Spacedong** [comment]
how about 1 please

**Comment by JohnGinnane** [comment]
As discussed in https://github.com/HippieStationCode/HippieStation13/issues/1909 and also https://github.com/HippieStationCode/HippieStation13/pull/2004

**Comment by Kokojos** [comment]
I would also vote for one only.

**Comment by JohnGinnane** [comment]
Done

**Comment by Nokington** [comment]
:+1:  @Nebyab input pls

**Comment by Sarcalogo** [comment]
Two, not one. That way you can have smoke reactions.

**Comment by Sarcalogo** [comment]
This doesn't do much to hurt Camille or Cappy... just perfectly innocent parties who use dental implants for fun. Reduce the amount of reageants you can add to them too, make it 25 instead of 50. There goes the "immortality" implant.

**Comment by Carbonhell** [comment]
could just shoot them with calomel to negate any chemical effect,just saying

**Comment by myontasm** [comment]
Yeah :+1:

**Comment by Crystalwarrior** [comment]
~~I say reduce amount possible to 25 as well and you're golden~~

ALSO fix dentals being usable when unconscious :(

**Comment by JohnGinnane** [comment]
So two pills at 25 units each?

**Comment by Crystalwarrior** [comment]
wait nevermind I forgot pills accept 50 max chems I'm dumb.

**Comment by meteoses** [comment]
1 would be more balanced, but 2 would allow people like Kitty Kathy to still have fun with them. The limit of chems doesn't matter to the powergamers so 25 is fine.

**Comment by Pyko1** [comment]
I would limit it to 10 or 15, and make it in to actual implant teeth that you have to create, and inject the chems with.

**Comment by JohnGinnane** [comment]
I'm still very unsure what people want. Should we have a vote of some kind?

**Comment by Kokojos** [comment]
Limedood and Nokington approved so far, this should be merged.

**Comment by Nokington** [comment]
Wait for neb to see it

**Comment by Nokington** [comment]
@nebyab you nerd

**Comment by Nebyab** [comment]
One seems over the top, two might be a bit better balance-wise but I'm in the minority here.

**Comment by Crystalwarrior** [comment]
one or gtfo
Seriously though I'd hate any more than 1 dental implant due to the fact that you can make ghetto adrenal implants.

**Comment by Kokojos** [comment]
Two heads :+1: and no veto, merging

**Pull request merged**
