### PR TITLE
Adds 5 wire stacks to derelict

### PR DESCRIPTION
**Pull request by ghost**
Derelict doesn't have enough wire to repair and it's gay.

I added more wire.

That is all.

### CODE REVIEW

**Comment by Spacedong** [comment]
sure

**Comment by Badmex** [comment]
I guess so +1/3

**Comment by ghost** [comment]
Yeah okay +1

**Comment by Kokojos** [comment]
Yeah okay

**Comment by JohnGinnane** [comment]
Code looks good now

**Comment by calibraptor** [comment]
+1/3rd

**Comment by GenericGoose** [comment]
why not bring your own cable

**Comment by ghost** [comment]
Because trying to get to and fix the derelict as a crewmember isnt usually worth it.

It has drone shells though.

**Comment by GenericGoose** [comment]
why help it if its not worth it

**Comment by ghost** [comment]
What

**Comment by GenericGoose** [comment]
> trying to get to and fix the derelict as a crewmember isnt usually worth it.
> 
> Derelict doesn't have enough wire to repair and it's gay.

**Comment by ghost** [comment]
It's usually not worth, as a crewmember, grabbing a space suit and drifting around to try to find the derelict to repair it.

But if you're dead and want something to do, doing it as a drone is cool. It's a fun occasional gimmick. If admins want to use it for events it's now doable.

If ss13 worked based on what's 'usually worth doing', we'd have 5 traitor items.

**Comment by GenericGoose** [comment]
ok i got  it  now

**Pull request merged**
