### PR TITLE
Changelog for Hippie's update

### PR DESCRIPTION
**Pull request by Nokington**
Only merge if this has been merged. https://github.com/HippieStationCode/HippieStation13/pull/284

### CODE REVIEW

**Comment by ghost** [comment]
his merge is still open, he can add his own changelog.

**Comment by Nokington** [comment]
Uh no. He told me to make it. Don't lock and close this again.

**Comment by ghost** [comment]
He can easily add it to his own PR, if someone tells him how, no need for multiple pullrequests.

**Comment by Nokington** [comment]
What do you not understand, that he told me to make it. Because he is worried that he will mess something up because of all the stuff that was merged before with changelogs.

**Pull request closed without merging**
