### PR TITLE
Picket Crafting + Darkness

### PR DESCRIPTION
**Pull request by AliiTea**
Actually puts the crafting recipe for Picket Signs in the game.
Now able to click/shoot at darkness

https://github.com/HippieStationCode/HippieStation13/issues/540
https://github.com/HippieStationCode/HippieStation13/issues/531

_We no longer have to fear what lurks in the dark!_

### CODE REVIEW

**Comment by Chronitonity** [comment]
Just so everyone knows, this fixes pickets signs being uncraftable and fixes guns not being able to be fired in the dark.

**Comment by Chronitonity** [comment]
Fixes #540 and #531

**Comment by AliiTea** [comment]
Remove yo first comment & second comment

**Comment by Chronitonity** [comment]
Fuck you 4 Fingers

**Pull request merged**
