### PR TITLE
Removes Telescience, ports E.X.P.E.R.I-MENTOR from TG

### PR DESCRIPTION
**Pull request by Chronitonity**
https://tgstation13.org/wiki/E.X.P.E.R.I-MENTOR

Proper admin logging, ect. 

Telescience is not a good feature, hampers space exploration, makes it easy to fuck with people and get hard to find items easily.

### CODE REVIEW

**Comment by Megalopeos** [comment]
Literally why?

**Comment by SplergeBucket** [comment]
Literally yes.

**Comment by Nebyab** [comment]
Anything that replaces the telesci is a good thing in my books, especially if its something that works.

**Comment by ghost** [comment]
god no please no not the expirmentor no no no no
im open to telescience modification in all ways except the shitty expirimentor lol

**Comment by SplergeBucket** [comment]
rip poroy

**Pull request merged**
