### PR TITLE
Adds Bananium, Fugus to mining

### PR DESCRIPTION
**Pull request by ArcLumin**
Adds Wumborian Fugus and bananium to mining. Also veeeerrry slightly boosts chance of mining mobs spawning, to compensate for the new mob.

### CODE REVIEW

**Comment by ArcLumin** [comment]
Done a few surveys in OOC and on the slack, player interest into adding these to mining is overwhelmingly positive, so I figured I'd pop em in

**Comment by ArcLumin** [comment]
For those of whom are unaware what Fugus are, here's a breakdown

Small, weak mob normally, puffs up to be a very large mob when threatened.
When large, they can deal tons of damage, but they can only be large for a short time, and there's a cooldown afterwards
They'll try to escape while small.
They are fully coded, with multiple sprites, and verbs for if they become player controlled.
They drop an item that allows you to buff simple mobs (provided they already haven't been buffed). This makes their sprite larger, increases max and current health by 50%, adds up to 10 extra damage to the min and max, and allows them to break environmental objects.

**Comment by ghost** [comment]
I think fugu can be used on drones, cultie mobs and holoparasites.
There's a list in the fugu code banned_mobs that is empty.
Provided they get banned from use on cultie, drones and holoparasites and any other mobs along those lines then sure why not.

**Comment by ArcLumin** [comment]
I don't see any issue with drones. They can't directly attack (and their laws don't allow them to) so that's fine. The extra health is negligible since they have shit HP anyways. They can't break walls and shit since they have no harm intent. Effectively, it only makes them a bigger target.

Cult stuff is also not an issue, since they die pretty fast anyways, and it'd be far too costly to be popping them on every harvester or jugg around. 

I'm 99% sure that the buff actually gets removed when the holopara returns to its owner, and holoparas themselves have no health so it's fine. I'll have to double check if that's the case for sure though.

I'll double check the holopara one, and so long as it gets removed when the owner returns, I don't see an issue with them being affected by the fugu stuff.

**Comment by ghost** [comment]
It gives drones more HP, which I dislike.
Cult stuff is an issue very much so. You're doubling jugger damage from 30 to 60. HP from 250 to 325.
Double damage holoparasites is also retarded and shouldn't occur.
resummoning holos doesn't make new holos, it just changes their location so I don't see why it should "reset".

**Comment by ArcLumin** [comment]
It's not double damage though. The damage buff is capped at +10

**Comment by ghost** [comment]
> Max is 10
>     A.melee_damage_lower = max((A.melee_damage_lower \* 2), 10)
>     A.melee_damage_upper = max((A.melee_damage_upper \* 2), 10)
> Max

**Comment by ArcLumin** [comment]
Isn't the 10 there the max amount it'll add? It'll do upper and lower \* 2 but go no further than 10, right?

**Comment by ghost** [comment]
Okay
If a function is max(30, 10) you will get the MAXIMUM VALUE within the arguments, that being 30.

**Comment by ghost** [comment]
To add, the 10 is there in the case harm intent did like 3 damage, it wouldn't be a measly 6 but at least 10.

**Comment by ArcLumin** [comment]
Ah, I see. I was mistaken. It was the other way around.

I can see the point for blacklisting the cult mobs, then.

**Comment by ghost** [comment]
I'd wait for other headmins to chime in before making changes though since I might be in the minority.

**Comment by ArcLumin** [comment]
Added in blacklisting of Holoparas, Constructs, Drones and True Changelings

**Comment by doobiedoo23** [comment]
Yeah booooooooooooooy

**Comment by ArcLumin** [comment]
WHERE MY OKEYS

@EVERYONE

**Comment by Nebyab** [comment]
I appreciate the vague spongebob reference.

This seems neat.

**Comment by ArcLumin** [comment]
Two head okeys? So it's ready to merge?

**Comment by SplergeBucket** [comment]
ok

**Comment by ArcLumin** [comment]
Let's MEEEERRRRGE

FUSIOOON HAAAAA

**Comment by blobbernaut** [comment]
So: I don't think drones should be on the blacklist. 

For holoparas, keep in mind that the health boost does nothing for them, it'll only make them larger and give them more damage. 

For constructs, keep in mind a juggernaut will be so large it'll be really hard to even touch anything with a melee attack because you'll just click on yourself, so it's probably bad on them. It'd be nice for an artificer to have, but it's not game breaking. It should be rewarded. 

For true changelings, the same problem as the juggernaut. They'll do more damage sure, but they'll also be easier to hit and have a lot harder time hitting anything else due to their own sprite blocking whatever they're trying to click.

**Comment by ghost** [comment]
Drones, holos and culties don't even make any thematic sense though

**Comment by blobbernaut** [comment]
You can use bruise packs on a drone or a construct too. Also wizards exist. 

Speaking of which, fugu implant into your body give you bonus to max health and punch damage?

**Comment by ArcLumin** [comment]
I could implement that, although it'd likely be in a later PR

Let's get this merged first, it has all the okays and the code's good. WHERE ARE YOU MERGERS

**Comment by ghost** [comment]
Wizards have suspension of disbelief.
Bruise pack healing simple mobs is very old legacy code.

Just because current code has issues doesn't make it an excuse to dismiss making it worse. ;)

**Comment by Pyko1** [comment]
code looks fine and has enough headmin votes

**Pull request merged**
