### PR TITLE
Security starting equipment tweak.

### PR DESCRIPTION
**Pull request by calibraptor**
In response to berets now having no armor, I'm changing security's loadouts so that the HoS now spawns with his cap on by default, and security officers spawn with helmets.

### CODE REVIEW

**Comment by Sarcalogo** [comment]
Umm this definitely conflicts with 

https://github.com/HippieStationCode/HippieStation13/pull/2428

**Comment by blobbernaut** [comment]
As a compromise, this works to address the balance concerns I had and so I will agree with this PR.

**Comment by Kokojos** [comment]
Headmuns where are you.

**Comment by ghost** [comment]
Yeah, bring back goofysec please

**Comment by Nebyab** [comment]
okay

**Comment by Gandalf2k15** [comment]
Nu

**Pull request merged**
