### PR TITLE
OOC Ban

### PR DESCRIPTION
**Pull request by AliiTea**
Thanks Shadowlight

https://github.com/tgstation/-tg-station/pull/12646

### CODE REVIEW

**Comment by lcass** [comment]
yes...

**Comment by Carbonhello** [comment]
Doesn't this need a database entry and all that jazz

**Comment by lcass** [comment]
Nope that's all handled automatically by the jobban panel ,OOC appears to have been made a job in this instance and is treated as such by the code.

**Comment by Foosili** [comment]
fuckin finally YES :+1:

**Comment by danhibiki** [comment]
I still don't see the purpose of this, but I have no reason to deny it, so.

**Pull request merged**
