### PR TITLE
Revert "Ports meat pizza mobs to the game and puts some on the asteroid that the clown ship is on"

### PR DESCRIPTION
**Pull request by TheOneAndOnlyCreeperJoe**
Reverts HippieStationCode/HippieStation13#3158

Because let's face it #3160 is already a good indicator as to why it's badshit broken, and I don't expect dong to fix it.

### CODE REVIEW

**Comment by JohnGinnane** [comment]
I would probably just add a changelog saying they were removed, considering original PR had one saying they were in

**Comment by TheOneAndOnlyCreeperJoe** [comment]
changelog's here

**Comment by ghost** [comment]
@Spacedong fucking test your PRs please or I'll put a ban on your account.

**Comment by ghost** [comment]
This is priority, merging.

**Pull request merged**
