### PR TITLE
SMES now always take input charge (regardless if the load meets the input)

### PR DESCRIPTION
**Pull request by ghost**
Code is by Zaers.
PR comes from an old pizzacode pull: https://github.com/Riesen/-tg-station/pull/59
Zaers doesn't do stuff for hatestation anymore, permission to pull was granted by the general staff of hatestation (although they're under GPL from what I know, but it's nice to ask anyway.)

This makes wiring solars not a chore

### CODE REVIEW

**Comment by Carbonhell** [comment]
why was this a thing even, a+ but needs head opinion

**Comment by myontasm** [comment]
I told Jules to port it... he actually did it the absolute madman! Hahahahahaha :+1:

**Comment by Nokington** [comment]
:+1:

**Comment by ghost** [comment]
mergu pls

**Pull request merged**
