### PR TITLE
Revert "Ports dildos"

### PR DESCRIPTION
**Pull request by Iamgoofball**
Reverts HippieStationCode/HippieStation13#3093

### CODE REVIEW

**Comment by Spacedong** [comment]
LMAO

**Comment by TheOneAndOnlyCreeperJoe** [comment]
Quality shitposting right here.

**Comment by yobob591** [comment]
no its too late, bait sa dildos is going to go into effect

**Comment by JohnGinnane** [comment]
Why

**Comment by ghost** [comment]
That was quick goofball.

**Comment by SpankMasterson** [comment]
+.7 i dont like em but i support it if players do, since we are a fascist democracy and all

**Comment by Swagile** [comment]
i would like this to be removed because it does not fit the theme of ss13

:honke:

**Comment by ghost** [comment]
lmao

**Comment by lcass** [comment]
Nice shitpost? Lets not start this flame war again , only .7 on the headmin scale

**Comment by optimumtact** [comment]
goof is everywhere

**Comment by Pyko1** [comment]
+0.7 needs more head input so we can merge or rid us of this PR

**Comment by Swagile** [comment]
im already +1'd, just needs one more headmin i guess?

since spank wasn't really fucking clear with his support like adwaadwadaw

**Comment by yobob591** [comment]
why even remove this they are adminspawn only i never even see them

**Comment by MethMedic** [comment]
Tbh yea i never seem em either really

**Comment by Iamgoofball** [comment]
why have them to begin with if they aren't used

**Pull request closed without merging**
