### PR TITLE
New HoG icons

### PR DESCRIPTION
**Pull request by Carbonhell**
Replaced nexus icon with Fury's one and added missing banner/crystal icons

### CODE REVIEW

**Comment by danhibiki** [comment]
show the class cabron

**Comment by FuryMcFlurry** [comment]
but my icons aren't finished at all.

**Comment by Carbonhell** [comment]
http://imgur.com/KD4VVqD
http://imgur.com/kMxBTfT

**Comment by Carbonhell** [comment]
Actually, i'm gonna put this in the hog bugfixes PR along with fury's sprites

**Pull request closed without merging**
