### PR TITLE
Nanoui ports

### PR DESCRIPTION
**Pull request by danhibiki**
Allows admin ghosts to interact with various machinery thruout the world, allows statclick debugging of the controller, ports us up to nanoui 3.0, gives us a handful of MC improvements and ports, all courtesy of TG and listed thruout this pull

### CODE REVIEW

**Comment by Nebyab** [comment]
Will we ever get nanoui ports? Will Travis build declare everything in order? Find out next time on git-hub-z.

**Comment by danhibiki** [comment]
https://github.com/tgstation/-tg-station/pull/13195 done, moving on to https://github.com/tgstation/-tg-station/pull/13290/

**Comment by danhibiki** [comment]
Moving onto https://github.com/tgstation/-tg-station/pull/13296

**Comment by danhibiki** [comment]
Moving on to https://github.com/tgstation/-tg-station/pull/13317

**Comment by danhibiki** [comment]
Onward https://github.com/tgstation/-tg-station/pull/13336

**Comment by danhibiki** [comment]
https://github.com/tgstation/-tg-station/pull/13346

**Comment by danhibiki** [comment]
https://github.com/tgstation/-tg-station/pull/13348 https://github.com/tgstation/-tg-station/pull/13351 https://github.com/tgstation/-tg-station/pull/13386/

**Comment by TDcoolguy300** [comment]
OH FUCK
CONFLICTS

**Comment by SplergeBucket** [comment]
fuck i hate nanoui
it keeps breakin and not workin for me
i demand compensation

**Comment by Kokojos** [comment]
Nanouis are actually a way for you to process your rage. You're already compensated.

**Comment by danhibiki** [comment]
So many different pulls to reference, big ones being https://github.com/tgstation/-tg-station/commit/97ca70cd345cdad38102e40c1de35de65add7df2 and https://github.com/tgstation/-tg-station/pull/13507

**Comment by TDcoolguy300** [comment]
The conflicts is tearing me apart

**Comment by TDcoolguy300** [comment]
I've tested this live with Dan. A fucking plus

**Comment by XeonFaux** [comment]
Best. Must merge. Asap.

**Pull request merged**
