### PR TITLE
Adds Ice Picks

### PR DESCRIPTION
**Pull request by Chronitonity**
Adds Ice Picks to the game, sprites by the beautiful and talented Nienhaus.

http://puu.sh/l8XvL/79f2ae374c.png

Ice picks do 7 brute, can be found in some cold places on the station, and made in a hacked autolathe.

They also can be used to give someone brain damage during the eye surgery, which before was only possible if you used a pen.

Also lowers the amount a metal baseball bat costs. You could only make 3~ with 50 stacks of metal. A circular saw is easier (and arguably more often) to make than that, so I changed it from 30k metal to 12k.

### CODE REVIEW

**Comment by Carbonhello** [comment]
The ice pick feels terribly useless. I don't know what it could

**Comment by Carbonhello** [comment]
Be used for, i'm against it unless it actually becomes useful for anything. A screwdriver would be even better and it's common. About the baseballs yeah dure honk

**Comment by Chronitonity** [comment]
Like i said on slack

Screwdriver has less force, throw damage, and embed chance
Ive got no intrest in adding snowflakey special weapons that do special shit, its a nice sprite and took like 15 minutes to do

**Comment by Lawligagger** [comment]
Sure.

**Comment by Foosili** [comment]
I'm for it.

**Pull request merged**
