### PR TITLE
Medbay secpoint

### PR DESCRIPTION
**Pull request by TheMocheeze**
Electrifies grilles in med and engi secpoint, removes lounge replaced with secpoint, adds 2 chairs to med lobby, super cool stuff, god bless

### CODE REVIEW

**Comment by Chronitonity** [comment]
:+1:

**Comment by nalarmg** [comment]
Carpeting looks incomplete and just bad.

Please include images next time for map changes.

**Comment by SplergeBucket** [comment]
Mirroring with Nalar said.
Besides the hideous carpeting i'm fine with the rest.

**Comment by TheMocheeze** [comment]
http://i.hizliresim.com/rVyOZa.png

Here's the end product, also that carpet seems to be an accident.

**Pull request closed without merging**
