### PR TITLE
Ports /tg/'s latest gateway features and missions

### PR DESCRIPTION
**Pull request by Weisyl**
This port's /tg/'s latest gateway missions and feature changes or additions that were required for them. @Nalar or @Danhibiki must also go into game_options.txt in the server's config and set GATEWAY_DELAY to 6000, which will mean 10 minutes before the gateway can be used. They may also have to add the following line to space_levels.txt

---
# UNCOMMENT THE LINE BELOW IF AND ONLY IF YOU ARE USING AWAY MISSIONS! FAILURE TO DO SO WILL CAUSE RUNTIMES!

Away Mission;8;unlinked

### CODE REVIEW

**Comment by Chronitonity** [comment]
He won't need to touch the space_levels.txt. but yeah

**Comment by TDcoolguy300** [comment]
#1328 removed space_levels.txt

**Comment by Weisyl** [comment]
@TDcoolguy300 done

**Comment by Chronitonity** [comment]
Aye, so most of these file changes are additions we needed from TG anyway to get things working, incase you're wondering why theres 85 of them. 

Lets get this out of the way, because I doubt this is going to be a universal yes.

The gateway causing startup lag is negligible, won't be anything noticeable, it's not gonna affect game speed or performance.

"The Gateway removes players from the station/round"

The players that do their jobs do their jobs, the players that don't spend the entire round fucking about, going braindead, breaking into places, ect, in order to do something interesting. Hopefully this will alleviate that boredom that comes from playing the same rounds over and over again.

If you're worried about heads fucking off to the gateway, just implement the same rules we apparently have for the captain/hop fucking off into space, which is a talking to and potential jobban.
But most of the missions aren't fuck huge areas people are gonna get lost in, and I really don't think its a problem if a few players from a 60~ shift round go exploring and have some fun. What else is there for assistants to do anyway.

I can't really think of any other arguments that are gonna be brought up but I'll be happy to argue them, but I think the gateway is a good addition, and our players certainly do.

http://puu.sh/lD4iz/c1cb1505fb.png

This is from a community that doesn't vote on shit either, a 32-1  with 38 abstaining is a huge vote, and if you asked on the fourms or put a several round poll up I'm sure you'd get nearly the same ratio of Yes to No.

**Comment by McHatters** [comment]
If the gateway is going to be operational, are we going to move it from its current position in maint to a more accessible area?

**Comment by Chronitonity** [comment]
Already did in this PR afaik

**Comment by Weisyl** [comment]
Yeah the gateway is back in its original position and the room that was there previously was moved were the under-construction gateway had been in engineering maint

**Comment by danhibiki** [comment]
sure

**Comment by Crystalwarrior** [comment]
Fuck yeah I want this.
@DerptheStewpidGoat next up we make abandoned genetics lab an actually on-the-surface away mission with unbreathable atmosphere planet

**Comment by myontasm** [comment]
Will this include exilation? Because afaik we still have exile implants, or was that removed?

**Comment by Chronitonity** [comment]
It includes exile implants yes

**Comment by Chronitonity** [comment]
@DerptheStewpidGoat Conflicts somewhere

**Comment by Foosili** [comment]
i'm going to give this a yes but only begrudgingly because i hate the way the gateway is implemented as this time release thing instead of an RD thing

**Comment by danhibiki** [comment]
ficks merj confliktz n wi goe

**Pull request merged**
