### PR TITLE
Readds Dildos!

### PR DESCRIPTION
**Pull request by AliiTea**
After some thought I decided to readd dildos as eswords that on hit explode into more dildo eswords.

### CODE REVIEW

**Comment by blobbernaut** [comment]
i agree

**Comment by Foosili** [comment]
fuck youuuuuuu

**Comment by Foosili** [comment]
no memes in git pls

**Comment by AliiTea** [comment]
Approval from hippie

Can't stop the memetrain!

**Comment by Chronitonity** [comment]
Braindamage speak is unbearably memey that everytime i see it i just groan

**Comment by Voratius** [comment]
Hippie doesn't even play on the server, and he's not even a headmin.

**Comment by Cafaling** [comment]
:+1:
Because throwing a dildo at people and making it embed in their groin was fun.

**Comment by TDcoolguy300** [comment]
:-1: No content, just adds a bloody say text thing

**Comment by Cafaling** [comment]
Upon actually seeing what gets changed I regret my previous statement.

:-1:

You got my hopes up Nex ;-;

**Comment by Pyko1** [comment]
I could already see the clown slipping everyone and hiding horsedildos in their butts.

**Comment by Cafaling** [comment]
Pyko it doesn't actually add dildos. It just adds a random retard quote.

**Comment by Nebyab** [comment]
Why the fuck not. Its not like gibbering was ever not self-referential or memey.

**Comment by danhibiki** [comment]
Why not, gives us a little bit of our own flavor.

**Pull request merged**
