### PR TITLE
ReAdds Vox Toggling

### PR DESCRIPTION
**Pull request by AliiTea**
Pretty sure everyone wants to have this back in the game.

### CODE REVIEW

**Comment by trifornt-tinfornt** [comment]
If I ever have to tab out of SS13 while I'm dead just to be interrupted by "ASS BLAST ASS BLAST ASS BLAST ASS BLAST ASS BLAST ASS BLAST ASS BLAST" again I'm going to hurt myself.
:+1:

**Comment by Spacedong** [comment]
we need this for when the AI lad decides to spam vox_login 50 times

**Comment by ghost** [comment]
using vox should have a 1/100 chance of gibbing the user

**Comment by Kokojos** [comment]
The code seems similar to the one that was used before, I din't spot a lot of differences, so :+1: 
Could you re-add vox logs for admins, though?

**Comment by Nokington** [comment]
:+1:

**Comment by Nebyab** [comment]
why not

**Comment by Nebyab** [comment]
though vox logs would be nice, doesn't need to be this pr if you'd rather split them up nex

**Comment by AliiTea** [comment]
Hooray I will do that then @Nebyab 

I am a lazy bastard

**Pull request merged**
