### PR TITLE
Tweaked Revolution Game mode

### PR DESCRIPTION
**Pull request by Anderbergst**
As per request from this thread - http://hippiestation.com/showthread.php?tid=5543

Rev games now gives a 2 min grace period before ending.

I don't know how to test this code because I don't know how to force a rev game on a test server.

If anyone can help me test this and make sure it works, that would be awesome!

### CODE REVIEW

**Comment by Spacedong** [comment]
i dont get it

**Comment by Anderbergst** [comment]
I can change that.

**Comment by ArcLumin** [comment]
spacedong the grammer mong strikes again

**Comment by Swagile** [comment]
needs a code check

@ArcLumin 
@JohnGinnane

**Comment by trifornt-tinfornt** [comment]
Does it count "leaving the station" or is it only disconnecting?
If it counts leaving the station (and yes, going into a locker as well because trust me that would be very easy to abuse if it had so much as a 3 second timer) then I'm out.

**Comment by Anderbergst** [comment]
When the last head staff/rev die, ghost, or leave the station z level, it will give a 2 min grace period before game ends. If by that time, the last head staff/rev gets revived,  comes back to station z level or reconnects, the game will go on and if not, then the game will end. If people think 2 minutes is too long, I can shorten it to 1 minute or something lower.

Hopefully this makes rev rounds a little bit longer.

**Comment by doobiedoo23** [comment]
That's retarded

**Comment by ghost** [comment]
It should be for connection only tbh.

**Comment by trifornt-tinfornt** [comment]
Connection only. Nobody likes long rev rounds because they last for two hours long when they don't last for five minutes. And that's just a whole lot of heads camping in one area while the revs get picked off one by one.
It's boring to watch and boring to play.

**Comment by oprayx77** [comment]
yeah connection only, i'd abuse this by going rcd ce and getting the white ship and just going back and forth from station to somewhere, i'd be unkillable

**Comment by Pyko1** [comment]
You can use this to cheese things, Just hide in disposal/locker/ever moving shuttle, and pop out before 2 mins.

**Comment by Anderbergst** [comment]
Connections only can be done too. No problem.

**Comment by Anderbergst** [comment]
Now I just need someone to test this and this is ready if it works

**Comment by ghost** [comment]
Does check_completion run every tick?

**Comment by Anderbergst** [comment]
I don't know...

I'll work on this later since i gotta go somewhere.

**Comment by ghost** [comment]
Carbonhell tells me it does, which would make the code non-functional.

**Comment by Anderbergst** [comment]
Any suggestions on what I should do to make the code work?
I am new to coding so i am gonna need some help.

**Comment by Anderbergst** [comment]
Closing this since code does not function and I don't know how to make it function.

**Pull request closed without merging**
