### PR TITLE
Nanoui fixes

### PR DESCRIPTION
**Pull request by danhibiki**
should fix a lot of issues, merge conflicts but i'll solve that once i figure out where. Still under testing, if you are staff please ask for the testing server

### CODE REVIEW

**Comment by neersighted** [comment]
@danhibiki You commited node_modules. Never commit node_modules.

**Comment by danhibiki** [comment]
Just curious as to where? Unless your talking about one of my older commits on this PR

**Comment by neersighted** [comment]
Ah, didn't notice you deleted it.

**Comment by danhibiki** [comment]
ye, there was many "oops" moments for me on this

**Pull request merged**
