### PR TITLE
Added Meeseeks

### PR DESCRIPTION
**Pull request by Koriath**
Might be buggy, might not. Worst case scenario, a bunch of retarded
insane killers are loose to roam the station. That's not diferent from an Extended round.

### CODE REVIEW

**Comment by Chronitonity** [comment]
We're rebasing off the latest tg repo in a few days, it might be better to port it then, especially since it'll have all the required mutations and jazz.

That aside, im pumped and really happy this happened

**Comment by Nebyab** [comment]
I'm fucking excited. This seems fantastic in every way, and I personally can't wait until we finish rebasing so that we can port this.

**Comment by Koriath** [comment]
Yeah, you guys were missing two mutations. The happy one and the comic sans.
I added the papyru font mutation later for skeletons, but the happy was the funniest one for meeseeks.
I saw players screaming "KILL ME" and it gets worfiltered to "hug ME"

**Comment by SplergeBucket** [comment]
I want it I, I need it, need it to make me feel heated
Shake it, can't take it, must break it
Break if off yea, what'd I say bitch
Bitch

**Comment by nalarmg** [comment]
Might want to update this for the new code.

**Comment by WhiteFox08** [comment]
look at me

**Comment by Koriath** [comment]
Alright, just post here telling me when it's done.

**Comment by nalarmg** [comment]
It's been done for a while.

**Comment by Cafaling** [comment]
Merge when.

**Comment by Koriath** [comment]
I'll give it a look today then.

**Comment by Jaygriff** [comment]
If you do redo this, module-ize it if you can.

**Comment by nalarmg** [comment]
Any progress on this?

**Comment by nalarmg** [comment]
No progress/information after a week. Closing this to reduce clutter. Please reopen or make a new PR if interest in this resurfaces.

**Comment by Koriath** [comment]
Sorry, I had some other stuff to code and was waiting for some sprites (to make hamburgers with Meatseeks). I'll reopen a PR later today.

**Pull request closed without merging**
