### PR TITLE
Kudzu/Space Vine Removal

### PR DESCRIPTION
**Pull request by oprayx77**
Now, Kudzu/Space Vines are adminspawn only or the SpaceVine event. Botany can no longer make kudzu using sugar. Kudzu are pretty terrible, not really the handiest thing even for antags as they usually end up harming the antag aswell.

### CODE REVIEW

**Comment by oprayx77** [comment]
jewbans are op lad

**Comment by SpankMasterson** [comment]
i know, i am one

**Comment by GuyonBroadway** [comment]
It's RNG dependant as fuck, last few rounds I got Kudzu was by trading for them and cheesing it with another item I traded for and some holy water. It's really REALLY time consuming to get and can be countered by a fukken goat or a weed control crate from botany which gives you a fucking SCYTHE that clears out a 3x3 area of the shit with every swing.

Plus you are merging from your master, GOD DAMN IT!!

**Comment by SpankMasterson** [comment]
It's official, opray banned from github, this is -1, CONVERSATION LOCKED

**Comment by oprayx77** [comment]
yes i am a god who merges from my own master
@GuyonBroadway  
but yeah, my point is that its poo. now for people who want to make other weeds have better odds.,
aswell as wasting less time for the person

**Comment by oprayx77** [comment]
rip im banned from github forever ;(

**Comment by ArcLumin** [comment]
ding dong bannu, you got spanked

**Comment by Spacedong** [comment]
lmao you mad

**Comment by Spacedong** [comment]
theres something called a "Vine Control Crate" in cargo you know ;^)

**Comment by SpankMasterson** [comment]
# _**fuck you opray! **_

**Comment by MethMedic** [comment]
Label this grudgecode, cuz it is

**Comment by Swagile** [comment]
you realize

that botany can do something EVEN WORSE than kudzu, right?

get pest level 4 and use unstable mutagen on a tray with said pest

get spiderlings

this is just removing something that is even more RNG dependent and usually only happens through TC trades / experienced botanists

**Comment by KayeArray** [comment]
grudgecode much

**Comment by ghost** [comment]
Just use pete to destroy vines tbh. If you hit them early with pete, gg.

**Comment by GuyonBroadway** [comment]
Not to mention unless the vines are hardened a SPEAR will kill them in a single hit.

Plus as far as evil bottany shit goes, a swarm of killer tomatoes is jsut as bad if deployed correctly. Here's a hint, you can sit in a locker and spawn killer tomatoes and they appear outside of the locker.

**Comment by oprayx77** [comment]
yeah exactly, if its so aids and underpowered then lets make way for deathnettle and spiders/killer tomatoes and all that. however when the gimmick gets so far that it can blow up and whatnot, its kind of busted as fucc

**Comment by GuyonBroadway** [comment]
Exploding vines only explode after a short delay, you cut one then run.  Nah the worst is flowering vines and how they sometimes compeltly dismember you when you step on their tile, but thats a bug that needs fixing.

**Comment by oprayx77** [comment]
then it blows up, blowing the rest of them up along with every apc you ever known and love :(

**Comment by Spacedong** [comment]
Vines have tons of counters, spears, welding tools, Pete, Vine Control Crates which contain: weedkiller gas grenades that instantly kill any weed they come in contact with, scrythes, etc. This PR wants to remove them because people just can't get good. Close this.

**Comment by oprayx77** [comment]
you know dong is getting serious when he capitalizes and uses periods

everyone assumes i think its strong when i just think its poo, botanists shouldn't have to deal with something thats only useful for traitors and sometimes gets pretty busted

**Comment by Spacedong** [comment]
the only really broken feature are the retarded human fly traps

**Comment by GuyonBroadway** [comment]
Most of what makes Kudzu bad is just poor coding and bugs that need fixing. 

Improve not remove!

**Comment by oprayx77** [comment]
how about i just remove the aids fly traps that can get you through walls

**Comment by gumner** [comment]
fix it,DO NOT REMOVE MY POOR,INNOCENT SPACE VINES.

**Comment by oprayx77** [comment]
gonna just remove vine traps as they take literal admin help to fix ingame

**Comment by GuyonBroadway** [comment]
The Mantraps are bad but the flower-pods are fine. make the flower-pods decay into something else.

**Pull request closed without merging**
