### PR TITLE
RUSSIAN SHIT UPDATE

### PR DESCRIPTION
**Pull request by ghost**
now you can be a real fucking adidas-wearing russian
https://www.youtube.com/watch?v=APnPH9u8-zs
https://i.gyazo.com/03a43032341d3322f3df90230e04658a.gif
^^^ rare footage of gopniki 

mosin is refurbished and looks 10x better, can go on your back now ( how
was this missing )
new revolver reskin
cqc gloves 12 tc ( we can work out costs, i made it pretty expensive for
a reason to start off with)
IMAGES
https://i.gyazo.com/5c0cf1340c7ade33611247a42695f2c1.png
https://i.gyazo.com/55c4ce63d1ec4be8ccda7c2f55670221.png
https://i.gyazo.com/958ba91eac593e03d474d3837b7b4dfc.png

### CODE REVIEW

**Comment by TDcoolguy300** [comment]
Some will ask for an image, best if you give them one

**Comment by ghost** [comment]
mosin reskin breaks shit so im gonna hold that off for now

**Comment by Chronitonity** [comment]
:-1: On the revolver reskin, make it optional like at prehippie, I like the other one a lot.

**Comment by Chronitonity** [comment]
Apart from that its gud though codewise and shit

**Comment by ghost** [comment]
its a brand new item so mappers can put it wherever they want.

**Comment by Foosili** [comment]
I dig it :+1:

**Comment by blobbernaut** [comment]
This removes the raincoat. Why?

**Comment by ghost** [comment]
wot 
oh fuck it does

i can fix that or someone else can 
i mean its not like the raincoat was super important ;(

**Comment by TDcoolguy300** [comment]
This is what we get for PRing shit without updating to the latest version

**Comment by TDcoolguy300** [comment]
FUCK, IT REMOVED THE STICKYBAN FIX

**Comment by TDcoolguy300** [comment]
:-1: Because of the shit removed now

**Comment by ghost** [comment]
GGGGGGGGGGGGGGGGGGGG
we can revert this and ill just update and redo

**Pull request merged**
