### PR TITLE
Compressed title music by 75%

### PR DESCRIPTION
**Pull request by ghost**
whoever put in ~the artist formerly known as~ Saint Pepsi has great taste

please help me I don't know how to use Github Desktop

edit: i have no idea what the merge remote-tracking branch does

### CODE REVIEW

**Comment by GenericGoose** [comment]
rip

**Comment by ghost** [comment]
yo dawg what does that mean

**Comment by Pyko1** [comment]
Pointless really, i assume many of the players have already downloaded the title music and this would jsut causer them to redownload the compressed files.

**Comment by ghost** [comment]
alright next time everybody compress that ishid before we make pulls

**Comment by Spacedong** [comment]
close this then

**Comment by ghost** [comment]
:cry:

**Pull request closed without merging**
