### PR TITLE
Locker borgs

### PR DESCRIPTION
**Pull request by AliiTea**
Henk - borgs can now open lockers with the (toggle open) button

### CODE REVIEW

**Comment by AliiTea** [comment]
Thanks phil235 for dis btw also changeloggy comin soon

**Comment by AliiTea** [comment]
@Chronitonity Favor done
@nalarmg merge plox  :3

**Comment by SplergeBucket** [comment]
ye

**Comment by Chronitonity** [comment]
:+1: They could open normal lockers but not locked ones because of an oversight.

**Pull request merged**
