### PR TITLE
Bar shutters, medbay storage walls 

### PR DESCRIPTION
**Pull request by Chronitonity**
A remake of #1107

Changelog in a few

### CODE REVIEW

**Comment by danhibiki** [comment]
Sounds good, but if Pykos addition gets added first, you'll have to redo this again.

**Comment by TrashFiend** [comment]
add windows to library or riot

**Comment by Chronitonity** [comment]
Apparently I don't because we both map merged okay.

**Comment by danhibiki** [comment]
Yeah I noticed that too, just waiting for one more headmin

**Comment by Nebyab** [comment]
sure

**Pull request merged**
