### PR TITLE
Changeling transformation sting will not turn people into cats

### PR DESCRIPTION
**Pull request by tortellinitony**
(╯°□°)╯︵ ┻━┻

### CODE REVIEW

**Comment by yobob591** [comment]
no this is hilarious why

**Comment by MethMedic** [comment]
Reminder that dna cat stings are

**Comment by MethMedic** [comment]
Aren't valid and the admins actually think thats smart

**Comment by yobob591** [comment]
wtf no dna stung cats are valid

**Comment by MethMedic** [comment]
Nah there was a vote and they weren't found valid. Yet the feature is still in???

**Comment by yobob591** [comment]
??? thats dumb

**Comment by yobob591** [comment]
remov

**Comment by Hackole** [comment]
This doesn't require head input anyway, it was agreed upon in a past meeting.

**Comment by ghost** [comment]
17f

**Pull request merged**
