### PR TITLE
Spare Parts Vending Machines

### PR DESCRIPTION
**Pull request by ghost**
Adds a new vending machine: Spare Parts
vending
The vending machine contains the following stock:
8 console screens
25 capacitors, scanning modules, manipulators, lasers, matter bins.
15 normal cells
1 RPED (Premium)
The vending machine is located in tech board storage and requires engineering access.

I do worry about balance since I've not removed research boards. I might move them to the server room in R&D if it's seen as an issue.

Big thanks to Fury McFlurry for the sprites.

### CODE REVIEW

**Comment by Pyko1** [comment]
Much needed, nothing sucks as much as begging parts from science when they have both robo/and science shutters closed as an engineer just because you want to repair/build some machinery.

There should be one of these in the Tech storage.
Only issue I really can see is mass producing stun prods with 15 cells.
Maybe cut them down to like 6 and and 2 or 3 better ones for coin?

**Comment by Pyko1** [comment]
Even tho I would really like to see this as a pullable cart, a mobile vender. for building shit.

**Comment by JohnGinnane** [comment]
I believe stunprods require better battery cells to make

**Comment by Pyko1** [comment]
Also maybe add restock cartridges and construction boards for these, so its not game over if someone pokes it once or twice with tools?

**Comment by ghost** [comment]
I don't want this to be easily construct able to be frank.
Also, engineers can easily mass produce stunprods (infact, the limiting factor is wirecutters)

**Comment by Kierany9** [comment]
Ghetto medbay just got ten times easier to make.

**Comment by Pyko1** [comment]
yeah but if you deconstruct this with 2 clicks its all gone, since you didnt add the proper parts that make it up.

You don't need to actually make the parts makeable tho.

**Comment by FuryMcFlurry** [comment]
hey i created the pixels

**Comment by Gandalf2k15** [comment]
Code check passed, 1/4 (2) headmin approval.

**Comment by Kierany9** [comment]
>Code check passed

>yeah but if you deconstruct this with 2 clicks its all gone, since you didnt add the proper parts that make it up.

do your job properly for fucks sake

**Comment by Gandalf2k15** [comment]
I check syntax not logic, sorry.

**Comment by ghost** [comment]
This isn't the only vending machine to work like this though.

**Comment by ghost** [comment]
Actually, non-constructable vending machines don't allow to be deconned like constructable one ones. I just checked.

**Comment by Pyko1** [comment]
Yeah but it would be a lot better if it had the proper parts, even if you cant make more of em, just so its not gone for ever if someone pokes it with a crowbar if the hatch is open.

And all the other venders should also get the parts making them up, instead of using it as an excuse to make even more "broken" things.

**Comment by ghost** [comment]
I crowbarred a coffee vendor, it deconstructed.
I crowbarred a youtool and my own one. You just hit it with the crowbar and do nothing.

**Comment by Pyko1** [comment]
In that case i guess its fine, they must have added some check in to it then.

**Comment by Swagile** [comment]
For those talking about stun prods, engineering starts with 10 high capacity power cells in their vendor and they can get 10 wirecutters from tool storage vendor since they already start with toolbelts + toolbox in their engineering lockers.

This is 10/10 though, since RnD doesn't really have the time to help the station most of the time since by the time they do RnD + mining, the station is destroying itself or destroying everyone else that is attacking it.

**Comment by ghost** [comment]
AHHH GUNDALF I DON'T COUNT ON MY OWN PRS. It needs Hackole's and Loopings permissions.

**Comment by Gandalf2k15** [comment]
Oooh yeah, okie. Approval: 0/3. Needs 2. GUIS PLS

**Comment by Hackole** [comment]
+1, seems like a good idea to have this if science isnt done half the time anyway

**Comment by ArcLumin** [comment]
I like this, not to mention that autolathes already can make most of those, so there's no major balance issues. It lets engineers do what they do best; set up ghetto areas and autism forts.

**Comment by SplergeBucket** [comment]
ye +1

**Comment by Spacedong** [comment]
theres an autolathe in the fucking cargo room that makes all of this

**Comment by ghost** [comment]
Being able to access science things via autolathe is a bug and it was fixed I thought.

**Comment by Spacedong** [comment]
IT WAS NEVER A BUG ITS A FEATURE

**Comment by Spacedong** [comment]
THIS IS USELESS AAAAAAAAAAAAAAAAAAAAA

**Comment by GuyonBroadway** [comment]
Yeah didn't we have a PR where science could put a tech disk with designs on it into an autolathe and the autolathe could then make that design?

**Comment by ghost** [comment]
You used to be able to do use the search feature of autolathes to build protolathe designs:
https://github.com/HippieStationCode/HippieStation13/issues/1951

**Comment by Spacedong** [comment]
no the autolathe had a specific menu called either construction or Misc and it had the basic building parts available

**Comment by Swagile** [comment]
Autolathe has always been able to build basic parts.

The issue you are referencing is the fact that the atmoslathe, which is a child of autolathe, inherits all the items that autolathe has by default (which includes construction tab with the basic building supplies) which it shouldn't have.

**Comment by Pyko1** [comment]
But having to to break in cargoslovakia and getting shot on the face by god knows what they ordered this time is a bad feature, engies should have some access to basic parts.

**Comment by ghost** [comment]
Well shit, I just remember being able to access things when I shouldn't on the autolathe.
I mean engineering could feasibly make an autolathe to build parts now so it's not a huge issue?

**Comment by Pyko1** [comment]
Technically should fix it so that autolathes have to update from RnD server to get new shit i assume.

**Comment by ghost** [comment]
Autolathes aren't RnD based though.

**Comment by ArcLumin** [comment]
Head input reached, merging

**Pull request merged**
