### PR TITLE
Wooden barricade costs 6 planks to construct

### PR DESCRIPTION
**Pull request by ghost**
Keeping in line with the sprite being made of six planks

Edit: Whoops wrong commit
Edit: Please forgive me github is hard to understand
Edit: how the fuck do I make more than one pull request

### CODE REVIEW

**Comment by SplergeBucket** [comment]
ok

**Comment by ghost** [comment]
what the fuck even happened in here

+1/3 tho

**Comment by ghost** [comment]
@Dudeinyourbackyard i got new glasses i can't see shit please help

**Comment by ghost** [comment]
jinkies

**Comment by ghost** [comment]
gee willickers

**Comment by Kokojos** [comment]
Sure +1

**Comment by ghost** [comment]
http://hippiestation.com/showthread.php?tid=2521
If you post your details here or PM me on the forums, I can add you to the slack and we can give you git tips.

**Comment by ghost** [comment]
also is this for consistency purposes or what?
you also need a changelog

**Comment by Spacedong** [comment]
lmao sure

**Comment by ghost** [comment]
alright time to figure out how to make a changelog
@McBawbaggings i figured it out thank you and this is for consistency

edit: changelog added to #2829

**Comment by JohnGinnane** [comment]
Might make more sense to add the changelog to this PR. You can make changes to your master branch and add the file and then if you hit "sync" from GitHub client it will update this PR (hopefully)

**Comment by ArcLumin** [comment]
7 commits for a one digit change. That's almost my level bad.

**Comment by ghost** [comment]
I fucking hate Git, I'm nuking this and trying again

**Pull request closed without merging**
