### PR TITLE
No Emags for you

### PR DESCRIPTION
**Pull request by AliiTea**
Holding your emags hostage until I get my dildos back!

### CODE REVIEW

**Comment by Weisyl** [comment]
No, but erik's a fukboi I assume and edited this to yes.

**Comment by danhibiki** [comment]
fuck he's done it

**Comment by ghost** [comment]
@Memendia this misses a proper changelog explaining said issue.

**Comment by AliiTea** [comment]
@Chnkr Changelog will be in a few seconds

**Comment by lcass** [comment]
I swear
nexendia if you do this I will eat your pets
that is all

**Comment by doobiedoo23** [comment]
god fucking damn nex why

**Comment by AliiTea** [comment]
https://github.com/HippieStationCode/HippieStation13/pull/271

There is the changelog

**Comment by AliiTea** [comment]
FOR DILDOS!

**Pull request merged**
