### PR TITLE
Adds Owl Cloak to the Owl Crate

### PR DESCRIPTION
**Pull request by ArcLumin**
Adds the Owl Cloak to the Owl Crate on Z4 and the clown crash template

### CODE REVIEW

**Comment by ArcLumin** [comment]
muh prs gettin no love

**Comment by Kokojos** [comment]
ehhh why not manggggg

**Comment by doobiedoo23** [comment]
+1/3, why the friggaroo not

**Comment by Nebyab** [comment]
yeah sure

**Comment by SplergeBucket** [comment]
ok

**Comment by Pyko1** [comment]
code looks fine and approved, merging

**Pull request merged**
