### PR TITLE
Cloner room Mapping

### PR DESCRIPTION
**Pull request by AliiTea**
The cloner room is now larger and has two cloners inside.
All Credit to Zadeon :^)

{#} Had to redo the entire thing since it accidentally reverted Kilm's brig redesign. 
image

((#) Bother Zadeon if you want anything reeee (#))

### CODE REVIEW

**Comment by TrashFiend** [comment]
Not done but a more compact version with 2 cloners would be a bit nicer.

Butts
(Re-doing medbay to make it near the same as old medbay since the current one is hot garbage. Nowhere near done.)

Not having any windows in cloning is a massive boon when someone needs to get inside to clone someone. Can't break in to clone the Captain or whatever or slam on the glass to get someone's attention. People doing actual research can't see the hall as well.

Looks good, though!

**Comment by Chronitonity** [comment]
ngl oldmedbay was kinda trash

**Comment by danhibiki** [comment]
I think some windows leading out to the rest of medbay would be neat for nex's current layout, but I'm ready to accept it as it is now

**Comment by SplergeBucket** [comment]
ehh i dont mind it, prefer dragonbot's one tho

**Pull request merged**
