### PR TITLE
Wrestling Belt Backhand Chop Fix + Ebows pierce riot shields

### PR DESCRIPTION
**Pull request by Crystalwarrior**
/title
- tweak: "Wrestling Backhand Chop no longer prevents you from doing anything else to the victim"
- tweak: "Reduced stun duration on suplex for the wrestler"
- tweak: "Energy Crossbows now pierce shields"

### CODE REVIEW

**Comment by myontasm** [comment]
Did e-bow seriously pierce riot shields??

**Comment by trifornt-tinfornt** [comment]
What kind of question is that, Limed00d?
The reason it's happening is because the Riot Shield makes the ebow go from a decent stun for traitors that is fantastic in combos to a complete joke that doesn't do anything.

**Comment by Crystalwarrior** [comment]
Yeah, right now there's no reason to keep an ebow if you pick up a taser, other than infinite ammo.
Slow recharge/delay between shots is what makes this weapon a LOT more surprise attack-focused, and if you can't even dispatch shield wielders it kind of makes it completely useless against prepared-but-not-alerted sec.

**Comment by Nokington** [comment]
:+1:

**Comment by TDcoolguy300** [comment]
Codes fine

**Comment by trifornt-tinfornt** [comment]
hurry up and merge this so the wrestling belt is actually useful.

**Comment by myontasm** [comment]
yeah alright

**Pull request merged**
