### PR TITLE
5/23/16

### PR DESCRIPTION
**Pull request by jediluke1999**

### CODE REVIEW

**Comment by Kokojos** [comment]
Gonna need explanations to what the hell is that and why so many commits are in one.

**Comment by calibraptor** [comment]
???????????????

**Comment by myontasm** [comment]
The fuck

**Comment by Zadeon** [comment]
I'm scared what is this?

**Comment by TDcoolguy300** [comment]
Something something gateways from what i can see

**Comment by danhibiki** [comment]
TD is right, this is all about the gateway, changes the challenge mission, as well as backend changes to how the gateway handles bumping, some changing to the particular formatting of code. This PR should really be done better, as the title is non-descriptive and there is no information except in the actual code submitted. It also needs a changelog. Of note, this lowers the gateway activation time significantly as well.

**Comment by Gandalf2k15** [comment]
Oh, this is my PR from back then. I don't know why this is here. See https://github.com/HippieStationCode/HippieStation13/pull/2412

**Pull request closed without merging**
