### PR TITLE
Buffs and tweaks the hockey set a little.

### PR DESCRIPTION
**Pull request by GuyonBroadway**
The Hockey set, while fun has been shown to be a little under performing, so I upped the damage on the stick, gave it a reflect chance when wielded and made it so rather than being good vs bullets and weaker vs lasers the suit is now VERY good vs lasers and pretty weak vs bullets. Two good buckshot blasts will put a Hockey player at about -150 (and got help them if you get a prototype SMG with AP ammo).

I also mad it so you can fit most types of o2 internals tank in the suit slot as opposed to just emergency tanks, a minor change and unlikely to make any major difference but it's nice to have.

### CODE REVIEW

**Comment by MethMedic** [comment]
A slight chance to reflect a taser shot would be cool. Like 10-25%. Right now thats the best way to beat em.

**Comment by GuyonBroadway** [comment]
Maybe, but all you really need to do is tag em once then run over with the stun baton to put them down for good. Protiop, being on a secway makes you immune to the holopucks due to how secways, janicarts and presumably lawnmowers work with regards to thrown objects.

In any case it can be tweaked, the idea was to make chain tasing them while on the floor the less viable option.

**Comment by MethMedic** [comment]
Yea I remember the one time i used it i got fucked cuz i thought they were immune to tasers for some reason

**Comment by GuyonBroadway** [comment]
That was because creeper joe was messing about with one as a admin dummy which are unstunable.

**Comment by GuyonBroadway** [comment]
Hit close and comnent like a retard.

**Comment by trifornt-tinfornt** [comment]
Now all you got to do is add the Eyelander effect.
1 head for more damage and better reflect power until you got 4 heads where it stops making you better.

**Comment by GuyonBroadway** [comment]
I was gonna cannibalize that idea for a cargo specific tator item.

**Comment by Spacedong** [comment]
kool

**Comment by GuyonBroadway** [comment]
Also while on the subject of "options that fuck over a hockey player" slipping them up is very effective, water tiles especially as their sanic speed means they often don't notice a slip hazard until it's too late to react.

**Comment by ghost** [comment]
Throw in NOSLIP on the shoes then. It'd kinda make sense since they're used to ice rinks and shit.

**Comment by ghost** [comment]
Oh yeah currently the changes are fine +1

**Comment by GuyonBroadway** [comment]
It's tempting but I think slipping is a fair way to counter hockey players as if they are observant they can avoid slipping over. Your speed is a potent double edged sword so using it carefully is the key I think. 

Once we're in a spot where hockey players become a potent threat I'd like to see how the crew goes about fighting them, if slipping them up proves to be too easy I may well add it in but for now I've only seen slipping happen once and that was a pretty sneaky clown at that.

**Comment by calzilla1** [comment]
I say make the pucks a short stun

**Comment by GuyonBroadway** [comment]
They are, they just don't knock over, i could make them longer though.

**Comment by MethMedic** [comment]
Ehhh add noslip tbh. Currently all it takes is to lube and wait and hes ded

**Comment by GuyonBroadway** [comment]
Noslips don't block lube

**Comment by MethMedic** [comment]
By lube i meant water aaa sorry

**Comment by GuyonBroadway** [comment]
It's funny how often I get unfairly lynched as a clown for throwing a bucket of water on the floor and some dipshit goes "LUBE LUBE LUBE! CLOWN VALID KILL HE!"

**Comment by ArcLumin** [comment]
Code's good

**Comment by ghost** [comment]
Hey, why don't you make the suit block syringes like every other hardsuit in the game, seeing as this set removes all of our storage space and items except two pockets?

**Comment by GuyonBroadway** [comment]
It does block syringes....

**Comment by ghost** [comment]
Does it? Does getting hit with a syringe while wearing a hardsuit still give the normal message?

**Comment by GuyonBroadway** [comment]
Both it and the helmet have the THICKMATERIAL flag which, among other things, blocks syringes.

**Comment by JohnGinnane** [comment]
>THICCMATERIAL

**Comment by ghost** [comment]
thicc
do it +1

**Comment by MethMedic** [comment]
Has head approval

**Pull request merged**
