### PR TITLE
Moves the gateway to the abandoned satellite

### PR DESCRIPTION
**Pull request by calibraptor**
I want to see the gateway missions eventually re-added, and this is my attempt to balance things out.

The satellite now has it's own solars and generator, which have to be wired and set up before the gateway will work, since the APC and SMES start with no charge.

deport that fukken gateway

iou 1 gateway

### CODE REVIEW

**Comment by Gandalf2k15** [comment]
Yes yes yes

**Comment by Gandalf2k15** [comment]
Also remove triangulation time too

**Comment by ghost** [comment]
This is a really organic way of stopping gateway rushes. I'm fond of it.

**Comment by Sarcalogo** [comment]
Can you do something with the now empty Gateway Room? Maybe some cool room for Heads of Staff, since gateway was restricted Heads of Staff right?

**Comment by myontasm** [comment]
I really like this.

With the space we have now we could probably expand the mime and clown offices a tad more methinks.

**Comment by Kokojos** [comment]
This is a great solution to our prior problem. :+1:

**Comment by Gandalf2k15** [comment]
The gateway PR by me needs to be merged first as it will be non functional if not. See https://github.com/HippieStationCode/HippieStation13/pull/2412

**Comment by Nebyab** [comment]
This just takes a bad feature, and makes it so nobody will feasibly use it.

-1

**Comment by calibraptor** [comment]
@Nebyab It's actually fairly easy to get to it via use of the on-station teleporter. It's directly north-west of the abandoned teleporter. I also don't think the gateway is a bad feature, I just think gandalf is fucking horrible at balancing his maps.

**Comment by Nebyab** [comment]
Alright, so its a bad feature people will be able to use then.

Stellar improvement to the status quo.

**Comment by ghost** [comment]
As to counter argue further, if science is being dickwads to me when I play miner, I'd totally go gateway hunting.

**Comment by Crystalwarrior** [comment]
This is good, I suggest this is merged so gateway can have proper maps in the future.

**Comment by Gandalf2k15** [comment]
Also can someone else fix the gateway code.

**Comment by Pyko1** [comment]
Swarmers need a new spawn point on station level with this, as the gateway is their spawn point.

**Comment by Sarcalogo** [comment]
How about the teleporter.

**Pull request closed without merging**
