### PR TITLE
Gateway Rework

### PR DESCRIPTION
**Pull request by Gandalf2k15**
Massive gateway rework.
This update removes everything from the map pool APART from Caves and Moonoutpost.
Both maps have been completely reworked and balanced.
Moon outpost has the following find able loot:
M1911 w/ ammo
Taser
C05r
Decloner
Pump Shotgun(4 cap)
Automatic Security Rifle
Italian Revolver
Nagant Revolver
All loot is well hidden and protected by mobs.
Pictures:
http://i.imgur.com/OayFzvF.png
http://i.imgur.com/pfsUS24.png

Difficulty Level: 7
The lag has been sorted on this level.

Caves has the following loot:
Multiple M1911's
Automatic Security Rife
Claymore
Honk Knife
Negro Stone
Plasma Fist Scroll
Retro Lasers
HE Grenades
Mini Uzi

This map is much more of an adventure map.
The lag has been fixed by removing the shittonnes of skellys.
Fun boss fight.

Pictures:
Too many to show...
Starting Area: http://i.imgur.com/aXZnbYP.png

Second Area: http://i.imgur.com/Ladsavt.png

Third Area: http://i.imgur.com/dXedeFE.png

End Area: http://i.imgur.com/dXedeFE.png

http://i.imgur.com/462iYgE.png

### CODE REVIEW

**Comment by ghost** [comment]
+1

**Comment by Gandalf2k15** [comment]
DNM still nerfing. Fixing lag too. DONT MERGE YET

**Comment by calibraptor** [comment]
+1, granted if any of these nerfs aren't nerfy enough I'll be nerfing them even further myself.

**Comment by ghost** [comment]
+1. loot dropping mobs was terrible.

**Comment by Gandalf2k15** [comment]
Okay this is ready to merge. This will solve all dem crappy round ruining looters. Prefer that you merge this ASAP as it fixes lag and removes a lot of unbalanced loot. And disables broken maps.

**Pull request merged**
