### PR TITLE
Makes Bag of Holding range infinite

### PR DESCRIPTION
**Pull request by ArcLumin**
This is honestly memecode but what the hell this would be fun as fuck to have in

### CODE REVIEW

**Comment by SpankMasterson** [comment]
What does it do exactly? I am gay.

**Comment by ArcLumin** [comment]
Normally, dragging a bluespace satchel to any other tile dumps out the contents at range. Typically, this range is 8 tiles. This boosts that to infinite range

**Comment by JohnMcLaime** [comment]
Yes. *smugface

**Comment by Anderbergst** [comment]
:+1:

**Comment by KittyKathy** [comment]
So uh can you do this through security cameras?

**Comment by ArcLumin** [comment]
exactly

**Comment by KittyKathy** [comment]
So you can dump bombs anywhere there is a camera?
New way to meme the AI, dump bombs literally on it though it's own camera that it uses to see itself from the RD office.
This is great finally a use for this other than making a singularity on the escape shuttle.

**Comment by yobob591** [comment]
This gives bs bags a reason to exist and allows for some fucking hilarious gimmicks yes pls

**Comment by GuyonBroadway** [comment]
Oh my, bluespace active gold slime cores into medbay, bluespace all your maxcaps into the brig and on a less destructive note, pick up drones and bluespace them directly into damaged areas for quick repairs.

Bluespace teleporter beacons into the armoury and clean it the fuck out!

**Comment by ghost** [comment]
No thanks. -1

**Comment by Pyko1** [comment]
Should make bombs/grenades and such detonate on user due to bluespace interference, too op otherwise.

**Comment by GuyonBroadway** [comment]
If you try to use a bluespace wormhole projector while wearing a BoH (and i think any teleporter or wormhole) it causes you to be teleported randomly elsewhere for no reason other than someone on tg thought this would be funny.  Bags of Holding do have their downsides.

**Comment by Pyko1** [comment]
But still, camera bombing/nading with BoH from while hiding in autismfort off the station...

**Comment by GuyonBroadway** [comment]
Eh that IS true, and you could allready do that with a telepad anyway.

**Comment by ghost** [comment]
Telepad is harder and requires setup.

**Comment by Pyko1** [comment]
you can see areas real time with telepads and drop bombs directly on top of people anywhere where cameras can see?

**Comment by GuyonBroadway** [comment]
If yer robust with a telepad you can drop bombs into places you know people are and you CAN'T see. But what I meant to say was that there is little point to giving an easier to get item an easier way to do something that we already have a thing for.

**Comment by Carbonhell** [comment]
What is this shit ree
-1 use a telepad

**Comment by ArcLumin** [comment]
Like I said, this is memecode

**Comment by blobbernaut** [comment]
Boost the research reqs of BOHs way the fuck up

**Comment by ArcLumin** [comment]
sure why not, can make it viable memecode

**Comment by ArcLumin** [comment]
now requires programming 4, engineering 6, bluespace 6, and materials 7

**Comment by blobbernaut** [comment]
+1 i guess, willing to see how hard you can break the game

**Comment by ghost** [comment]
jesus what the fuck that shit's possibly hilarious but also crazy powerful even with the crazy research requirements
make it require bluespace crystals or something too iunno im gay
-1 for now

**Comment by ArcLumin** [comment]
literal hilarious memecode

**Comment by ArcLumin** [comment]
anyways, closing since two head disapprovals. rip memes

**Pull request closed without merging**
