### PR TITLE
Removes Dental Implants

### PR DESCRIPTION
**Pull request by carlarc**
Honestly I'm neutral about them, mostly because I don't get antag when there's powergaming chemists, Cappy, or Camille.
But if the decision's there, I don't care about them being removed. I haven't used them at all except for a basic burn pill implant.
This is probably wrong in every level or something, I don't know how to code at all and don't plan to.

### CODE REVIEW

**Comment by Spacedong** [comment]
y e s

**Comment by Pyko1** [comment]
Imho removing features is a bad way to fix balance issues.

Even tho the dental implants are bad in their current form, they are no way beyond redemption.
Should just be harder to make, less max chems, chance to auto trigger on falling down. Oh and limit the max amount of em.
ie, Gotta somehow make a hollow teeth that can hold the chems.

**Comment by Spacedong** [comment]
can we make it so that you can only fit 1-2 in and it takes longer than 3 clicks to put in

**Comment by Pyko1** [comment]
I'd rather not put it in research.

Maybe something like, get a teeth, drill it hollow, load with chems, seal it somehow, then implant it.
And basically you can fail the drilling part breaking the teeth so you might need more than just a 1 teeth.

Also limit the chems to something like 5 units max.

**Comment by trifornt-tinfornt** [comment]
Sad thing is you can use Dental Implants while unconscious, while already stunned, and you can even mysteriously fit PATCHES in there which basically means loading yourself up with brute + burn patches and some ephedrine/meth will let you get out of deepcrit almost immediately.
"very fair feature". Don't give Research more power, just remove them.

**Comment by Spacedong** [comment]
yeah if we nerf this it'll still be abused somehow or another, just remove it, iits a shit gameplay mechanic

**Comment by Pyko1** [comment]
If its properly fixed it cant be abused.

And deleting the code is just bad, commenting it out would be a lot better if you insist on removing it from the game. As it could be fixed/used later somehow.

**Comment by Sarcalogo** [comment]
There is no way to properly fix it. You can give yourself ghetto adrenaline sacs (actually it's a minus 6 ticks on all stuns if you do it correctly, which is better than adrenaline sacs) maybe 7 minutes into the round. You can limit the amount of reagents to a number as low as 5 and you can still abuse the anti stuns. You can lower it to just two or three implants but then people can just implant another one. After it's done. The issue with dental implants is again, anti-stuns. The only way to really fix it would be to make it impossible for any anti stuns to be implanted dentally which makes no sense from an IC perspective.

**Comment by carlarc** [comment]
Well, then either you do 'ic' and remove dentals, or just you know, remove antistuns?
if we're talking about IC perspectives, then why can't hulks get deflection from double eswords?

**Comment by meteoses** [comment]
You realize any player can use dental implants, right?

All you need are bedsheets and a screwdriver; then go to the abandoned lab to get your chems. It's not like there is a powerwall for their usage; just a knowledge wall. Antags, non antags, Sec, assistants, cats, anyone has immediate access to this feature.

Maybe you should adapt instead of trying to remove them. Plenty of others players are using them, maybe you could just learn chem instead of punishing everyone who has.

Also if you put patches in your mouth they just straight up murder you when you activate them, gives you a full overdose "You feel like you took too much".

**Comment by Sarcalogo** [comment]
>Everyone can use them
So you are essentially saying the only way to counter them is to use them yourselves. Great example of a balanced feature. You are ignoring completely that while everyone has access to them (not entirely true, some people would have to do an extra 5 minutes of work to access them) that everyone does not have access to the complimentary equipment that makes them so strong, or that there are some that simply do not have an equal amount of time to use them. 

I don't know why you bother, pretty much everyone thinks they're unbalanced and need to be removed.

**Comment by meteoses** [comment]
They are currently imbalanced. and while the 5-10 low-information-low-skill members of the playerbase  might want them removed; but they are an intended feature. This isn't like with the chemical implants from the armory where it had both a powerwall and it was a bug that allowed them to be used: this is an intended feature that has bugs.

Limit the number of implants, and/or change the build path to being able to create them.

Most admins feel the way Pyko does: don't remove a feature; alter it (notice the RTP armor as an example).

Kingcarrot, nothing will stop powergaming: before the implants I just created 20 minutes worth of stims at the start of the round, then had them running the entire rest of the round. But the thing is, even without chemicals powergaming is incredibly effective. The thing that makes powergaming so effective is that I/hackole shoot first anytime we think someone is even remotely suspicious.

**Comment by carlarc** [comment]
But the reactive teleport armor was kind of nerfed into oblivion.

**Comment by meteoses** [comment]
Probably because all you had to do was pick it up and put it on, then you became almost invincible. 25 seconds of effort for godlike power.

**Comment by carlarc** [comment]
Yah, but now not only do you need to max fucking everything at r&d [I have never seen it at the protolathe since the nerf], it also gives slowdown and is even LESS useful. Why even HAVE it? No one's going to bother with 8 downsides.

**Comment by Kierany9** [comment]
Just limit it to 1 pill max.

**Comment by Sarcalogo** [comment]
Limiting to one pill max does absolutely nothing to fix the issues present in dental implants. Namely the anti-stun and healing.

**Comment by Sarcalogo** [comment]
>They are an intended feature

From some literally who named KrystalWarrior who I haven't ever seen play on the server or submit any other PR's. He also said according to Trifornt at least, that they were unfinished when they were added and they were not supposed to act as they do now.

>Limit the number of implants

Does absolutely nothing because you can just as easily put in another implant the minute you are done.

>Most admins feel the way Pyko does: don't remove a feature; alter it

Okay. When I add in a gun that everyone gets at round start that kills everyone on the server the first time it is fired, don't ask for it to be removed. Just ask that it kills HALF the server! There it's balanced now!

**Comment by meteoses** [comment]
Kingcarrot/Sarcalogo: Dental Implants are an intended feature, hence modification rather than removal, your example is retarded with the gun. The implants are defensive for the most part, they don't kill everyone on the server.

**Comment by Sarcalogo** [comment]
The gun is an intended feature too. Don't remove it.

**Comment by meteoses** [comment]
What. Except it isn't. Using "well my made up gun is real and therefor my point stands" as a line of attack is pretty weak...

**Comment by Sarcalogo** [comment]
What you fail to understand is that anything that is added to the game that is not a bug is an intended feature. To say that something is bad to remove because it's an intended feature is to say that anything purposefully coded and added to the game should never be removed. All I'm doing is using an extreme case to illustrate this principle to you. If the gun was added to the game, under your "intended feature" axiom it would be wrong to remove. Saying that the gun should not be removed highlights the absurdity of your "if something is an intended feature it should not be removed" argument and is a classic reductio ad absurdum. If you agree that the gun should be removed then you've also agreed that there are some things that even if are intended features, need to be removed. This means of course, that this logic could also apply to the dental implants, and you are forced to defend dental implants on their own merits, not some sweeping generalization.

How could you not understand something so basic?

**Comment by meteoses** [comment]
So balance the gun in your example. You realize that right now you can fit unlimited chemicals and unlimited implants in, right? So any nerf will be gigantic, bringing it down to 1-3 implants total would be reasonable change from infinite implants. Just like a reasonable change for that gun would be that it can only kill 1 person at a time, rather than removing it.

See? Your gun had infinite power, my solution is to nerf it so it has a much more limited power; the same thing I support for the implants.

How could you not understand something so basic? :)

**Comment by Spacedong** [comment]
powergaming is disgusting and dental implants are irredeemable, lets settle it at that

**Comment by meteoses** [comment]
Not really, Spacedong, you could easily just take them from "unlimited power" to "limited power". Hardly irredeemable.

**Comment by Spacedong** [comment]
they will still be abused until they're nerfed into the ground and useless, fuck them, they can be used while stunned, KO'd, or unconscious, even glared, they're shit

**Comment by Sarcalogo** [comment]
Well you've undone yourself this time. No need to say anything more.

**Comment by meteoses** [comment]
Undone myself how so? That I support nerfs from unlimited down to a limited number?

You always just think you are right for seemingly no reason; your gun example got countered; I'd nerf that gun, and I'd nerf these implants too.

**Comment by JohnGinnane** [comment]
What if we: 
1. Limit the number of dental implants you can have in your mouth at any one time
2. Have a cool-down on them so you can't just replace/use them very quickly, so you can overdose on them (as you should if you take too much of a certain chemical)
3. Stop people from using them when they're incapacitated, as I believe you can use them while unconscious?

**Comment by AliiTea** [comment]
What if we just removed them.

**Comment by Carbonhell** [comment]
Github isn't the place to fight with other players, discuss about the feature or go away. I'm also for finding a way to balance those instead of plain removing them, so yeah, try to find a better way but if heads want this can be merged aswell

**Comment by Nokington** [comment]
:-1: No. I would rather limit how many people can put into their mouths and remove using them while in crit

**Comment by blobbernaut** [comment]
I want it to have the max dental implant limit to be 2 or 3 and heavily nerf methamphetamine and ephedrine

**Comment by Carbonhell** [comment]
If @Nebyab is also against this, PR will be closed. I suggest fixing instead of plain removing this feature.

**Comment by Nebyab** [comment]
This is heavy handed. A simple limiting of the number of implants implantable would achieve the same effect without removing something which much potential for neatness from the codebase.

**Comment by JohnGinnane** [comment]
What's a good max number of implants to have? And should having no teeth be a factor when trying to implant pills into them?

**Comment by carlarc** [comment]
shet

**Comment by Spacedong** [comment]
WHATS THE POINT OF A DENIED TAG, JUST CLOSE THE PR AAAAAAAAAAAAAAAAAAAAAAAAAA

**Pull request closed without merging**
