### PR TITLE
Tablecrafting and other tweaks

### PR DESCRIPTION
**Pull request by calibraptor**
Changes in this PR:
- Makeshift shotguns no longer require R&D in order to craft.
- Makeshift shotguns now require duct tape instead of package wrap to secure the stock.
- Stocked vendomat with 5 rolls of duct tape.
- Requirement to craft a wooden stock is no longer a ridiculous 10 planks. it now requires one.
- Improvised shells have received buffed damage, but massively increased spread to compensate for it. Both regular and overloaded shells are inferior to real buckshot in terms of damage potential.
- New ammo variant, coinshot, which comes in regular and overloaded variants. Requires 5 coins to craft a shell. A painful ghetto alternative to rubber/beanbag shells, but still inferior to the real thing.
- Removed slowdown from makeshift armor, so people will actually use it again for minor protection.

### CODE REVIEW

**Comment by ghost** [comment]
Long overdue.

**Comment by ghost** [comment]
"What are you gonna shoot out of it, DIO's money?
Coinshots more likely.
I'd be willing to see this trialled. +1

**Comment by Voratius** [comment]
hey that's pretty good, +1/3rd

**Comment by ghost** [comment]
yeah dude +1/3rd i wanna be a metal man again

**Comment by calibraptor** [comment]
Can my own +1/3 count lmao

**Comment by ghost** [comment]
No

**Comment by calibraptor** [comment]
images

**Comment by Spacedong** [comment]
what the fuck mcbawg, +1 all the goddamn way

**Comment by ArcLumin** [comment]
Hell yes. COIN SHOTS. Time to force people to see how rich I am.

**Comment by Nebyab** [comment]
ok

**Comment by Gandalf2k15** [comment]
Head input gained, code check in progress.

**Comment by Gandalf2k15** [comment]
Code has passed. Merging as all requirements met.

**Pull request merged**
