### PR TITLE
Gives admin's test dummies the admin jumpsuit

### PR DESCRIPTION
**Pull request by ArcLumin**
Why the fuck do we have an admin jumpsuit if we don't use it

### CODE REVIEW

**Comment by ghost** [comment]
Okay +1?

**Comment by TheOneAndOnlyCreeperJoe** [comment]
I'd like to point out that due to the nature of dummys, this won't do anything besides being fire-proof and not being blown up by bombs.

**Comment by SplergeBucket** [comment]
yeah i dont get the point of it but ok

**Comment by Swagile** [comment]
this is actually import because end of round shenanigans with gyrojets end up with me blowing my limbs off even in admin form

this makes my jimmies rustled and would unrustle them since protection from bombs will enable me to point blank gyrojet people with no fear of becoming a flesh puppet

**Comment by ArcLumin** [comment]
More that we have them but don't use them. Might as well

**Comment by ArcLumin** [comment]
Someone give some code review on this and it's good to merge

**Comment by gumner** [comment]
code looks good.

**Comment by ArcLumin** [comment]
Alright, merging

**Comment by Swagile** [comment]
arccc

only one head +1'd it wut are u doing ggggggg

**Comment by ghost** [comment]
splerge is looping and he was a headmin during that

**Comment by ArcLumin** [comment]
yup

**Comment by Swagile** [comment]
oh ok

**Pull request merged**
