### PR TITLE
Bye bye headslugs

### PR DESCRIPTION
**Pull request by Kokojos**
Disables headslug and lesser form, as well as their related abilities until  #2363 and #2456 are fixed

### CODE REVIEW

**Comment by calibraptor** [comment]
Yes +1

**Comment by blobbernaut** [comment]
approved

**Comment by Sarcalogo** [comment]
That's a good plan, but maybe you want to patch in a quick fix for lings so they can regenerate as a head or something?

**Comment by TheOneAndOnlyCreeperJoe** [comment]
> says it's approved
> blatantly ignores the failed travis check
> professionalism.

**Comment by ghost** [comment]
Get this workin' please. +1

**Comment by ghost** [comment]
Should probably take lings and tatorlings out of rotation until this is fixed too tbh.

**Comment by ghost** [comment]
:^)

**Comment by blobbernaut** [comment]
Creeperjoe, i am not a headmin i can't even approve things, but koko asked in coder chat for approval..... learn to shitpost nerd.......

**Comment by Kokojos** [comment]
Here's hoping I don't destroy everything.

**Pull request merged**
