### PR TITLE
Clothing Flammability and Cloak stuff

### PR DESCRIPTION
**Pull request by Cafaling**
Your attire is not as flammable as you once thought.

Changelog included!

### CODE REVIEW

**Comment by Carbonhello** [comment]
code seems fine,+1

**Comment by Cafaling** [comment]
Did I dun goof

**Comment by Cafaling** [comment]
I dun goofed :^(

**Comment by Cafaling** [comment]
Aw ye

**Comment by danhibiki** [comment]
What does this mean exactly?

**Comment by Cafaling** [comment]
Went through the clothing list and made stuff that should burn flammable and things that shouldn't burn non-flammable.

**Comment by Cafaling** [comment]
Along the way did some stupid shit and had to fix it.

**Comment by Foosili** [comment]
:+1:

**Comment by danhibiki** [comment]
Sounds good to me

**Pull request merged**
