### PR TITLE
Fixes renaming holoparasites

### PR DESCRIPTION
**Pull request by ghost**
I have no idea how they were working in the first place if that was the condition I gave it originally.

### CODE REVIEW

**Comment by Sarcalogo** [comment]
I already fixed it in my Holoparasite /tg/ port thing, but this will probably be merged first so...

**Comment by myontasm** [comment]
Metal Cumguzzler makes a comeback

**Comment by ghost** [comment]
/tg/ doesn't allow renaming holoparasites like here. I'll re-add the feature when the updates get merged.

**Comment by JohnGinnane** [comment]
If Sarcalogo works on his PR to make it compatible with our codebase you could update this one so that his names are default and your PR would allow masters to change it to something else

**Comment by Sarcalogo** [comment]
Let me be more clear. /tg/ does not support Holoparasite naming. /tg/ uses a Metal + Flower system. In my PR, the metal + flower system gives the Holoparasite a default name, but then after the name is given you have the option to name your Holoparasite. That is something I added when JohnGinnane pointed out to me that it may conflict with Holoparasite naming.

**Comment by JohnGinnane** [comment]
In that case we could go with the /tg/ port if you want to work it a little, and close this one. Up to yourself

**Comment by ghost** [comment]
If this will cause a merge conflict then yeah sure.

**Comment by ghost** [comment]
Since the holoparasite update has been removed, this is now relevant again.

**Comment by ghost** [comment]
I can compile cleanly on my end, anyone know what's up with that?

**Comment by Gandalf2k15** [comment]
code/_compile_options.dm:53:error: #error Your version of BYOND is too out-of-date to compile this project. Go to byond.com/download and update.
code/_compile_options.dm:54:error: #error You need version 510 or higher
I would update byond and redo it..

**Pull request closed without merging**
