### PR TITLE
Robbie Rotten's suit

### PR DESCRIPTION
**Pull request by Anderbergst**
We are number one!

robbie rotten

Added robbie rotten's suit to the contraband section of the ClothesMate.

It also comes with different screams.

### CODE REVIEW

**Comment by SpankMasterson** [comment]
+1 contingent on successful code review

**Comment by Swagile** [comment]
same with spank

**Comment by Anderbergst** [comment]
I tested the code on a test server. Everything works and the screams works too.

**Comment by KittyKathy** [comment]
One thing did you make sure that when you remove the clothes does it make your scream normal again or are you stuck with that scream the whole round?
Just asking because i think that happens with the xeno skin suit in the mining xeno ruins.

**Comment by Anderbergst** [comment]
when clothes are removed, you return to normal scream.

**Comment by Spacedong** [comment]
>those commit names

noice

**Comment by JohnGinnane** [comment]
> Just asking because i think that happens with the xeno skin suit in the mining xeno ruins.

Oh really?

**Comment by Spacedong** [comment]
the xeno suit doesn't give you alternate screams I thought tho

**Comment by Anderbergst** [comment]
It gave  you the xeno scream i think.

**Comment by Anderbergst** [comment]
Also the screams have some soundtrack in them from the We Are Number One video. If you guy's don't like that in the screams, I can remove it and just upload new screams without the background sounds in the scream.

**Comment by ghost** [comment]
>12 oggs

Reduce that please. A good chunk of them are six seconds long have instruments in them. They'd just be better if they were short soundbytes of vocals.
https://soundcloud.com/user-847444/we-are-number-one-vocals
Please rip them from here since those are the most clean.

**Comment by ghost** [comment]
Shit like "Now listen closely", "We are number one!", "Now watch and learn", "WHAT ARE YOU DOING?", "NO DON'T TOUCH THAT!" are all good examples of what I would want to see. SFX don't really make sense for screams and they should be quite brief and not full sentences.

**Comment by ghost** [comment]
"NOW LOOK AT THIS NET"

**Comment by ghost** [comment]
You guys should port this
https://github.com/UristMcStation/UristMcStation/pull/519

**Comment by Anderbergst** [comment]
@McBawbaggings 

I can do that.

**Comment by ghost** [comment]
Also, make these 4 in stock inside of the theatre drobe. I want to see groups of people wearing it.

**Comment by Anderbergst** [comment]
Do you want it to be a contraband too? lol

**Comment by ghost** [comment]
Yeah it being contraband is fine.

**Comment by Anderbergst** [comment]
Okay

**Comment by ghost** [comment]
https://github.com/HippieStationCode/HippieStation13/blob/602aeffd0e577493bf6b0f5913579b28a25b4a09/code/game/objects/items/weapons/vending_items.dm#L64 Update this please, the values should be a 1/3 (rounded up) for the contents of each category.

**Comment by ghost** [comment]
Also changelog is incorrect, this is the autodrobe and not the clothesmate

**Comment by Anderbergst** [comment]
Yea I can do all those.

**Comment by Anderbergst** [comment]
@McBawbaggings 

ey b0ss, is this good?

Now i just need to work on the OGGs and everything should be ready.

**Comment by ghost** [comment]
Change contraband from 3 to 4 and that should be fine codewise.

**Comment by Anderbergst** [comment]
got it

**Comment by asskek** [comment]
FUCK THIS BRING BACK TREKCHEM

**Comment by blobbernaut** [comment]
number one pr

**Comment by Anderbergst** [comment]
@McBawbaggings 

Removed all the previous screams and added 15 different screams that are only 1-3 seconds.

I also added a minor melee resistance so that our villains don't get rekt by the superheroes.

I just need a code review and this is ready to go!!!

**Comment by Anderbergst** [comment]
I tested this in a test server and it works. 

Tell me if I need to change or tweak something.

**Comment by ghost** [comment]
I'd prefer is the WE ARE NUMBER ONE line was the second to last one since it just has robbie singing. Otherwise good shit +1

**Comment by ghost** [comment]
heck yeah once this is done

**Comment by Hackole** [comment]
Dead memes are the best memes +1

**Comment by Anderbergst** [comment]
I will change the WE ARE NUMBER ONE line to the one where its only him saying it no prob.

**Comment by Anderbergst** [comment]
@McBawbaggings 

It has been done.

also ready for merging

**Comment by yobob591** [comment]
Look at this PR, that I just found, when I say go, be ready to merge

**Comment by yobob591** [comment]
GO!

**Comment by Anderbergst** [comment]
GOGOGOGO

**Comment by doobiedoo23** [comment]
THROW IT AT HIM, NOT ME!

**Comment by JohnGinnane** [comment]
Got conflicts there..

Also I see there's some work involved in adding the screams to alternate screams. I might just make this part of the base clothing's Equipped() so that people don't need to write/copy paste it. You could override it if you wish, but I believe there's a bug were the screams aren't removed

**Comment by JohnGinnane** [comment]
Code is good but conflicts

**Comment by Anderbergst** [comment]
Can you suggest what I should do to remove the conflicts?

**Comment by ghost** [comment]
Resolved it for you.

**Comment by Anderbergst** [comment]
okay thanks!

**Comment by JohnGinnane** [comment]
Codes good, merging

**Pull request merged**
