### PR TITLE
Welder fire alert fix

### LINKED ISSUE #1832: Welding logs happen when a borg is being repaired
bug
It's the guy in the top left.

### PR DESCRIPTION
**Pull request by Jaygriff**
Fixes admin log spam due to welder
fixes #1832

It will not alert admins 3 times of welders lit in areas with .01% plasma, then wait 1 minute, then alert admins again. This time can be adjusted.

### CODE REVIEW

**Comment by ghost** [comment]
:+1:

**Comment by Nokington** [comment]
:+1:

**Comment by danhibiki** [comment]
Yes

**Comment by nalarmg** [comment]
Conflicts, possibly addressed in https://github.com/HippieStationCode/HippieStation13/pull/1851?

**Comment by Jaygriff** [comment]
Does partially fix it. I will put my alert changes in the new code for even less spam.

**Pull request closed without merging**
