### PR TITLE
Fixes Pocket Knife not having a sprite while it was extended

### LINKED ISSUE #3096: the pocket knife has no in-hand sprite when not folded

### PR DESCRIPTION
**Pull request by TheOneAndOnlyCreeperJoe**
Fixes #3096

It didn't have a sprite in the mob icon folder.

### CODE REVIEW

**Comment by JohnGinnane** [comment]
Can you post pics please?

**Comment by TheOneAndOnlyCreeperJoe** [comment]
Same as the Switch knife but I'll get you one in a moment.

**Comment by TheOneAndOnlyCreeperJoe** [comment]
knife

**Comment by JohnGinnane** [comment]
Thank you! Looks good, merging as it's a bugfix

**Pull request merged**
