### PR TITLE
Immortalises fluxcapacitor1337 into the game.

### PR DESCRIPTION
**Pull request by ghost**
Flux

### CODE REVIEW

**Comment by TheOneAndOnlyCreeperJoe** [comment]
get outta here shitposter

**Comment by KayeArray** [comment]
YES

**Comment by Hackole** [comment]
it must be done

**Comment by tortellinitony** [comment]
too OP

**Comment by KayeArray** [comment]
Get spank in here

**Comment by Spacedong** [comment]
I read it as "Immobilizes fluxcapacitor1337" and I was gonna +10000 but this is good too

**Comment by KayeArray** [comment]
Make it force him to play as nitroyoshi9 kek

**Comment by Carbonhell** [comment]
code is ok
+1
merge this

**Comment by ghost** [comment]
Don’t ****ing mock me mcbawbaggins you pompous piecees of ****.   I don’t know who the * * * * you think you are but your obviously a dip * *  * who goes around acting like hes better than people buy im sure you just an ignorant **** just like everyone else you ****head. You know its pompous ignorant ****s like you who make me so mad i could ****ing murder a bitch. You think im ****ing playing games here? Hey i aint scared brother. I got a 45 with your name on it. So just come on over. Bring your gun and we’ll meet somewhere and we’ll just ****ing shoot this out cause i don’t give a **** man. I really dont. I just busted a nut in your moms face so what. You think i care if i ****ing live or die ill ****ing put a bullet in your head. This aint no joke man. Ill ****ing cut up your dead body and march around wearing your head as a hat while playing your penis like a flute to the tune of yankee doodle dandy. You wanna keep talking ****. Bring it bitch.

**Comment by Spacedong** [comment]
:joy::ok_hand:

**Comment by oprayx77** [comment]
i love flux , merge asap

**Comment by ghost** [comment]
are you guys aware that I am considering making another byond account (seriously). This **** is getting to me, I mean, my reputation as a player on this server has taken a hit. Has nothing to do with th, but, I honestly try to help when people are (srs) and when it's a lulzy thread, I join in, but now when I comment, and have any input in any thread... there are a few players calling me this and that. It's pretty nasty stuff, I have manners in real life, and I control myself online, but others... shame brahs, you cuss every other person out like he isn't a person. (inb4 u mad, puzzy, etc)

**Comment by doobiedoo23** [comment]
Have fun in your echo chamber flux

**Comment by yobob591** [comment]
fucking incredible y e s

**Comment by ArcLumin** [comment]
Is carbon still a +1 these days? If so its ready to merge

**Comment by ghost** [comment]
I don't think carbon even read the code, it'd give him a fit.

**Comment by ghost** [comment]
**this is a warning to you all**

# **if you merge this, you will force my hand**

**Comment by ArcLumin** [comment]
He'll go all back to the future on yo ass

**Comment by ArcLumin** [comment]
tbh you need to solder better if there is flux on your capacitor. YOU ONLY NEED A LITTLE FLUX

**Comment by oprayx77** [comment]
you'll force 「ＺＡ　ＨＡＮＤＯ」

**Comment by yobob591** [comment]
watch out fluccs will scrape you away

**Comment by SpankMasterson** [comment]
LOL

**Comment by ghost** [comment]
All this happened while I was asleep lmao
I only just learnt that flux had a few rounds where he screamed uncontrollably into death

**Comment by KayeArray** [comment]
fix and readd tbh

**Comment by yobob591** [comment]
it was majestic

**Comment by blobbernaut** [comment]
merge please

**Comment by blobbernaut** [comment]
+1

**Comment by blobbernaut** [comment]
oh sweet

**Comment by ghost** [comment]
sweet jesus

**Pull request merged**
