### PR TITLE
Glowcaps and Sec Barricade changes

### PR DESCRIPTION
**Pull request by Chronitonity**
Ports Glowcaps and some changes to security barricades from TG

Glowcaps are a mutation of Glowshrooms, allowing you to eat them to recharge the batteries in your inventory.

The higher potency, the longer it takes to eat due to the increased radium, but the more batteries it recharges.

They can also be used in the same way glowshrooms can, spreading across tiles on the station.

The sec barricades now block 80% of gunfire, but can also be shot over if you're adjacent to them.

Also fixes the blob win conditions and a runtime in attack logs.

### CODE REVIEW

**Comment by Foosili** [comment]
I'm adamantly against something that would let Camille recharge every single tazer and energy gun in their inventory at once. A discussion on the balance implications of the glowcaps should take place before this getsite merged.

**Comment by Chronitonity** [comment]
balancing code features around one player is bad design

You have to govto botany, mutate a glowshroom, then grow the new glowcaps and drain the radium if you don't want to deal with the after effects of it.

your better off carrying a screwdriver and a box of high capacity batteries in your backpack

**Comment by Foosili** [comment]
I agree designing around one player is a bad idea but they are a great example of top level security play.

Botany isn't required - security has glowshrooms in perma as well as everything required to grow them, it would take a trip to chemistry but that's about it.

**Comment by Chronitonity** [comment]
if someone decides to spend a decent amount of time in permabrig traveling back and forth from chemistry just to make some recharging mushrooms i think they deserve it.

perma botany is shit anyway, you get no feedback about any of the stuff your plant needs, you cant tell how much potency it has or will have, ect. its basically flying in blind for a small buff

**Comment by Foosili** [comment]
I don't consider having something that instantly reloads all cell based weaponry a small buff.

**Comment by Crystalwarrior** [comment]
Insta-recharge for weapons that doesn't require science to make sounds like a big no from me.
Recharging is a huge reason why laser guns aren't the most powerful weapon in the game.

**Comment by doobiedoo23** [comment]
:+1:

**Comment by Chronitonity** [comment]
not to sound coarse but if you glanced at the code or read the Op, it doesnt instantly charge. potency = percentage of battery recharged, with 10 potency not even being enough for a single taser shot. Shrooms need to be fully consumed for them to work, meaning if you really want to get a kick out of these you'll be injesting a ton of radium after taking several bites out of a mushroom.

**Comment by Foosili** [comment]
If that's the case then I'm not worried. Your OP didn't mention how much potency effected them, just that more potency meant more cell recharge.

**Comment by Chronitonity** [comment]
aye thats on me then, i'd update it but im on mobile

**Comment by Weisyl** [comment]
The amount of work isn't gonna matter for the players who think of others as nothing but a means to use to progress then discard like trash.

**Comment by Nebyab** [comment]
Honestly, the glowshroom thing sounds like a quirky feature which is going to be used once or never. Its easier to just steal a recharger than it is to grow high-potency glowshrooms which irradiate you when you use them to charge guns.

I'm also not sure that barricades really needed a buff, especially an 80% non adjacency block rate. Does this stack with multiple barricades? Can I use two barricades to get a guaranteed 80% miss rate? Especially as IIRC barricades are order-able from cargo, so this makes them immensely powerful items, and barricades don't really need to be buffed, at least I don't feel as though it would be necessary.

EDIT: I should make it clear I'm not against the glowshroom thing, I just think its going to fall in the dustbin of misc facts and mechanics.

**Comment by ghost** [comment]
Glowcaps are a mutation of Glowshrooms, allowing you to eat them to recharge the batteries in your inventory.'
]
https://www.youtube.com/watch?v=COdkHuogVkw

YES MGS3

**Pull request merged**
