### PR TITLE
Meteoses' hun

### PR DESCRIPTION
**Pull request by AliiTea**
It's been used enough to the point of causing brain damage.. 

So why not put it in as one of the words?

### CODE REVIEW

**Comment by TDcoolguy300** [comment]
Should of made it an append

**Comment by AliiTea** [comment]
If only I was smart enough to understand that word..

**Comment by Leon454** [comment]
+1000000000

Absolutely required feature

**Comment by TDcoolguy300** [comment]
Appending means it goes onto the end of the word, so it would go "GOERGE MELLONS IS GRIFFING ME ~hun"

**Comment by Leon454** [comment]
That would be even better

**Comment by calibraptor** [comment]
Do it

**Comment by SplergeBucket** [comment]
there are not enough brain damage quotes
start filling them up from the chat highloights

**Comment by ghost** [comment]
yes, make it an append nerd

**Comment by Nokington** [comment]
Cool

**Comment by Nebyab** [comment]
Honestly, take this as a chance to do what looping suggested and add more retard-speak. I'm alright with the PR as it stands, but this is a chance to do something wonderful.

**Comment by AliiTea** [comment]
@Nebyab once I get off my ass (in maybe an hour) I will have an entire weekend to add more retard.

**Pull request merged**
