### PR TITLE
Ports deepfriers along with features!

### PR DESCRIPTION
**Pull request by Carbonhell**
- rscadd: "Ports the deepfrier, with some neat features!."
- rscadd: "All deepfried things have a nice overlay, better than the old
  one."
- rscadd: "When you deepfry an item,if it has no reagent it'll gain 1
  nutriment, if it had more than 2 nutriment it'll have half the nutriment
  it had, any other chem gets fully transferred."
- rscadd: "You can also deepfry mobs, with an effect similar to the suit
  storage unit frying one, it causes 50 burn damage and to put someone
  inside, it takes the same time of meat spikes."
- rscadd: "All the mob's items will be deepfried aswell,but will retain
  their uses, while if deepfried alone they'll become snacks.."
  too tired to not copypaste changelog

### CODE REVIEW

**Comment by Chronitonity** [comment]
Just a note, this doesn't add it to the map as I'll do that after this gets merged so keep that in mind.

**Comment by Foosili** [comment]
Yes! :+1:

**Comment by Cafaling** [comment]
Praise the lord, deep-friers return!

**Comment by Nebyab** [comment]
Ja Sicher

**Comment by TDcoolguy300** [comment]
:td:

**Pull request merged**
