### PR TITLE
Autolathe, Protolathe and R&D Improvements

### PR DESCRIPTION
**Pull request by Theoman02**
-Autolathe can now batch build (x3, x5 and Custom(up to x12)).
-Protolathe can now batch build x3 and Custom (up to x10) on top of the existing options.
Custom just means you get an input box where you can set how many objects you want to build.

-The console can now multi-task between all its devices, except DA; this means that you can make your autolathe build e.g. 5 drills and while it's doing that, you can use the circuit imprinter and print a board and while that is going on as well, you can deconstruct. Though when you use the DA you have to wait for it to finish.
-The DA now shows the effective destruction threshold for reliability. No more maths or blind guesses!
-Protolathe and Imprinter now show what they are building in their "building screen" as well as the quantity.

Tested this with a friend; It takes into consideration when others are using the lathe(s) so no weird shit will happen. Hope this doesn't fuck shit up. As for R&D, it has been tested and seems to work perfectly.

Should be ready for deployment.
ss 2016-06-10 at 08 18 36
ss 2016-06-10 at 08 19 33

### CODE REVIEW

**Comment by TDcoolguy300** [comment]
Code looks fine.

**Comment by calibraptor** [comment]
Nice!

+1/3rd

**Comment by ghost** [comment]
cool
+1/3

**Comment by Kokojos** [comment]
Yes
+1/3th

**Comment by ghost** [comment]
A great QoL change. +1
This is protected against code injection right?

I will add this is currently accepted but I'd really prefer to know for certain that it's code injection free.

**Comment by Theoman02** [comment]
I haven't tested that to be fair, but yeah it should be protected. Input is immediately parsed as a number so no injection should be possible.

**Comment by Kierany9** [comment]
Yes please, no more printing out individual shotgun shells manually.

+0 because my opinion doesn't matter

**Comment by dreamcrab** [comment]
yea this is cool, fuck having to click shells 10 times when i just wanna blast nerds

does it still take as long to print? if so im down +5555

**Comment by Theoman02** [comment]
Nope, the build speed scales with the amount of items being built (except for stacks). Having them all build at the same speed sounds kinda too much. Beats having to click 10 times at least.

**Comment by Voratius** [comment]
Looks like a nice feature +1/3rd

**Comment by Theoman02** [comment]
Improved R&D. See initial description.

**Comment by Kokojos** [comment]
Votes are up, merging.

**Pull request merged**
