### PR TITLE
Gun Reworks, theres a lot here so grab some food

### PR DESCRIPTION
**Pull request by Chronitonity**
Adds attachable Seclights to Tasers and Eguns. Click the gun with the light to make gunlight. You can turn it on and off at will.

Allows renaming of The Detective's Revolver and Bartenders shotgun multiple times. Click the gun with a pen to rename it.

Allows you to reskin the Bartenders shotgun to have a nice different looking wood gun. You can only reskin it once, along with the detectives revolver.

Reworks Russian Roulette, it no longer requires some special fairy tale admin spawn gun to do. Any gun can be used to "play" Russian Roulette. All revolvers simulate barrel rotation so its a random chance. This means the detective can put his gun in his mouth due to bordom, or security officers can put tasers and riot shotguns in their mouths.

http://puu.sh/klADp/1ecc5f96fd.png

Allows you to put a gun to someones head and "play" Russian Roulette. This takes 4x longer than handcuffs so it certainly won't be overused. You can point any gun at their head and fire it.

http://puu.sh/klAUY/c3a730b949.png

To play Russian Roulette just aim at the mouth with a gun and use help intent.

Lastely this changes two sprites. Gets rid of our god fucking awful "deus ex traitor revolver" and replaces it with the old revolver. Comparison shot.

http://puu.sh/klBoq/5a66b7628c.png

Replaces our also god awful disabler sprite(http://puu.sh/klCNr/d75f31852e.png) with the old one (http://puu.sh/klCML/950caec9fc.png). The only player who sees a disabler in hand is the Detective Borg anyway, this just makes everything cleaner.

God have mercy on us all.

### CODE REVIEW

**Comment by SplergeBucket** [comment]
yes Dope Dope Dope yes

**Comment by Weisyl** [comment]
This is pretty ok.
Is the seclight just for E-guns and tasers? It'd be neat if it could go on things such as the riot shotgun, prototype SMG, and combat shotgun. You can also allow them to be placed on syndicate guns too but they'd likely never be used by a traitor who likely doesn't want to give away his position.
Then again though it'd probably be easy enough for me to give compatibility to more weapons.

**Comment by lcass** [comment]
It would be cool to have some sort of execution thing where neck grabbing someone and then aiming for their head with a (lethal) gun on harm intent + a period of waiting just outright kills them. Shoots a brain across the floor.

**Comment by Weisyl** [comment]
@lcass I suggested that in my executions trello card. Main difference being that the victim must be crit or incapacitated. Neck grabbing also wouldn't be needed.

**Comment by Nebyab** [comment]
yeah sure

**Pull request merged**
