### PR TITLE
Balances zombies

### PR DESCRIPTION
**Pull request by Gandalf2k15**
Balances zombies, cant upgrade speed, damage, health anymore. Base health now 150 instead of 230. No superform, can only infect when below 20 hp, 1 in 5 chance now instead of 1 in 3.

### CODE REVIEW

**Comment by Spacedong** [comment]
GOOD SHIT NOW IT CAN ACTUALLY WORK

**Comment by McHatters** [comment]
Yeah that sounds pretty good

**Comment by calibraptor** [comment]
Can only infect when your victim is below 20 HP? That's lame.

**Comment by ghost** [comment]
I've forgotten, can they smash girders and other barricades?

**Comment by Gandalf2k15** [comment]
Barricades yes
Walls no

**Comment by trifornt-tinfornt** [comment]
Then the problem of fake walls still exists with zombies, mate. Zombies need love too.

**Comment by dreamcrab** [comment]
yeeeeeeeeeee +1

i will say yes to any and all zombie updoots if they dont suck
https://www.youtube.com/watch?v=7RW7E3AmfdM

**Comment by Spacedong** [comment]
@mcbawbaggings +1 or -1?

**Comment by ghost** [comment]
I mean it's fine but they're still gonna be fucked by all other forms of barricades.

**Pull request merged**
