### PR TITLE
UPDATED: New camo boot + gorka sprites and new Auto. Laser Carbine for R&D. Lower H.E.V costs

### PR DESCRIPTION
**Pull request by Weisyl**
--UPDATED DESCRIPTION--

New Automatic Laser Carbine that can be made from R&D. Uses specialized plasma cartridges in 24-round magazines. Can also fire in bursts of 3. Hint: it needs combat level 6 research, among some other research levels.
Made the H.E.V set cost a moderate amount less of materials and required research levels. Also made the modular receiver need lower research levels and less metal to be made. Modular receiver also no longer needs silver.
New gorka on-mob icons so it looks less like ass. Also resprited the camo boots a bit to go better with the gorka uniform. Thanks to Sgt. Fragg for the new gorka uniform on-mob sprites. Additionally, also thanks to them for the entirety of the sprite work on the chest rig, defender armor, and gorka uniform.

http://puu.sh/ltbVz/fb55c6e22e.png

### CODE REVIEW

**Comment by trifornt-tinfornt** [comment]
Laser Carbine?
Yes.

**Comment by doobiedoo23** [comment]
:+1:

**Comment by calibraptor** [comment]
+1

**Comment by Lawligagger** [comment]
Not that much of a fan of the sprite for it, but yeah, I like this idea.

**Comment by calibraptor** [comment]
Now that I think about it the sprite for the laser carbine could be better, but that can always be changed afterwards.

**Comment by Chronitonity** [comment]
:-1: : on laser carbine, nuke ops are themtacially an antag type that only uses bullets, giving security a sort of knlowedge that using bullet proof armor is good to use against them. A laser carbine breaks that without bringing much to the table, it'd be better as some RD tomfoolery.

**Comment by Weisyl** [comment]
There's still a whole lot more ballistic weaponry for nuke ops since this so far is the only one. Also, the damage is outclassed by most other nuke ops weapons and the magazine size is outclassed by a few other nuke op rifles or LMGs. I could make this an RnD weapon but it'd probably be one of the hardest weapons to produce.

**Comment by Chronitonity** [comment]
Missing the point though, all nuke ops weapons are supposed to be ballistic, its thematic where NT focuses on energy weapons and the syndicate has a hard on for bullets.

Apart from that, like I said before, it's also so security knows that they're dealing with only ballistic weapons, enabling them to use ballistic counters. So yeah I'd rather it be RD or some Z level reward be implemented instead of giving nuke ops something that doesnt really fit

**Comment by calibraptor** [comment]
Sounds like a simple fix then. Throw the laser carbine somewhere out into the deep reaches of space, or as mining crate loot.

**Comment by danhibiki** [comment]
I disagree with you Chron, I don't think we should be pidgeonholing the availability of equipment from nuke ops teams solely based on the amount of ballistic weaponry we have available. It doesn't function like eguns, it functions like a normal gun with plasma rounds, and there is zero ability to create more except ordering them, which makes their usages very niche.

**Comment by trifornt-tinfornt** [comment]
Agreed with Dan Hibiki. There's no reason why Nuke Ops shouldn't have at least ONE laser-style weapon in my opinion.

**Comment by Weisyl** [comment]
Honestly I could introduce it for nuke ops again later but I can't simply revert my latest PRs now and it'd be kinda annoying to go back to stage 1 with this.

**Comment by Chronitonity** [comment]
Its not pigeonholing them, its sticking to a design thats been there since i can remember.

**Comment by lcass** [comment]
It's silly RP fluff get over it and accept your laser overlords. +1.

**Comment by Foosili** [comment]
fuck you laser bullshit remove laser remove laser fuck on with the laser

remove ityou FUICK

**Comment by danhibiki** [comment]
Currently, its only able to be made at the protolathe with diamonds and required levels or as a spawn guns from wizard. It is not orderable by nuke ops anymore.

**Comment by Foosili** [comment]
oh okay then yeah i'm fine w/ this.

**Pull request merged**
