### PR TITLE
Adds Cappy as a Daki.

### PR DESCRIPTION
**Pull request by TheOneAndOnlyCreeperJoe**
Adds Cappy as a Dakimahoweveryouspellit

Horrible memes. I was held at gunpoint.

http://i.imgur.com/oBtFw2p.png

### CODE REVIEW

**Comment by LuisReyesX** [comment]
no mag boots 0/10

**Comment by calibraptor** [comment]
+1

Memes

**Comment by Hackole** [comment]
n-no

**Comment by blobbernaut** [comment]
please add FUCK tags to this pr

**Comment by JohnGinnane** [comment]
Done

**Comment by Kierany9** [comment]
yes hackole

your powergaming is now immortalized in a weeaboo japanese anime love pillow

this is the consequence of your actions

**Comment by dreamcrab** [comment]
is the wants no trouble daki in yet

+11111

**Comment by JohnGinnane** [comment]
Code looks good.

**Comment by Kokojos** [comment]
sure why not

**Comment by ghost** [comment]
Meme PR, we have camille though so why not.

**Comment by Kierany9** [comment]
guys 2 head approvals merge now reeeeeeeee

**Pull request merged**
