### PR TITLE
Change initial wait to call shuttle from 20 minutes to 5

### PR DESCRIPTION
**Pull request by ghost**
Shit can go down on Hippie station in less than five minutes, and the arbitrary wait time pisses off community members who need to call the shuttle.

Time based on 600 = 1 minute as described on line 196 (600*5 = 5 minutes)

Considering the time required to wait for the shuttle once it's called, this commit only really affects rounds where nobody is constantly recalling the shuttle, so boring rounds are likely to end sooner because nobody wants to recall the shuttle.

### CODE REVIEW

**Comment by ghost** [comment]
image

**Comment by ghost** [comment]
@Mithrandalf Please stop commenting on my ideas unless you have something insightful to say, or I'll just ignore whatever input you have.

**Comment by Kierany9** [comment]
This means that if Nuke Ops declare war, the shuttle could reach Centcom before the nuke ops can even leave their base. If the station is on red alert, the shuttle takes 5 minutes to arrive. If you take 5 minutes, add five for the shuttle transit, twenty seconds for getting to the cockpit and authorizing an early launch and three for transit, that's a 12 and a half minute round. The nukie shuttle can't leave until 15 during a declaration.

Also, most time-related defines are actually 2 minutes fast because they're based off of world times, which count the lobby, which means that the shuttle could be called within 3 minutes. And that's not even counting if the admins delay the round if the server had crashed or something. So that's actually a ten minute round and not twelve.

And finally, five minutes is not long enough for a round to even start. All this is doing is encouraging antagonists to act immediately or risk failing their objectives due to a lack of time. While yes, long rounds can be boring, you can hardly do anything in 15 minutes, and you can't actually tell what kind of round it's going to be within those five minutes. And the last few minutes are going to be getting to the shuttle anyway. Consider this, how long does it take to confirm gangs in your average round and how long does it take for a gang to properly place a dominator and win the round? This will also negatively impact longer jobs or ones that need a lot of roundstart set up, such as engineer or virology. The shuttle being called while you're half-way through setting up is not enjoyable. Thirty minutes is perfectly fine as a minimum round length. Ten is not.



(mithrandalf has earned his right to shitpost, you haven't)

**Comment by ghost** [comment]
/pr

you can close this now

**Comment by ghost** [comment]
@Kierany9 It should also be noted that thirty minutes would be a minimum length, so what would be an average length? I don't want anybody to get bored during a round because they have nothing to do, thus the reduction in shuttle time.

The nuke ops point is situational, but reasonable, so I suppose five minutes is too short, as well as the point about world times being fast.

**Comment by ArcLumin** [comment]
to be honest, the 20 minute wait is nothing in this game, even on this station where rounds are fast paced.

If a round's slow it's because nobody is bothering to call it, or are recalling it.

**Comment by TrashFiend** [comment]
Most of the time 20 minutes is a good time. Unless some serious shit goes down with wiz/nuke ops/mass bombings most of the station will be alive and kicking. Those rounds aren't entirely common.

**Comment by ghost** [comment]
-1 for reasons stated by others.

**Comment by ghost** [comment]
Holy fuck no. -1
Fucks over declaring war.
Not only that, SS13 funnily is a role playing game.
All this does is encourage murder antags call shuttle reroll for antags which is cancerous as fuck.

**Comment by KayeArray** [comment]
Hahahahaha no rounds are already short enough on Hippie.

**Comment by GenericGoose** [comment]
shuttle time is retarded but this doesnt fix the problem

**Comment by myontasm** [comment]
This is making me wanna scream

**Comment by ghost** [comment]
wp:snow closing until you chucklefucks agree to a new meta

**Pull request closed without merging**
