### PR TITLE
Removes two invisible mobs from mining!

### PR DESCRIPTION
**Pull request by AliiTea**
Dear god Catbon..

Removes the two invisible mobs from mining that pet people and destroyed objects.
### THIS WAS DONE IN BROWSER EDITOR

who knows what it could do..

### CODE REVIEW

**Comment by Carbonhell** [comment]
they didn't attack, they would just pet and smash any obstacle in the way. also everyone loves them for some reasons,i suggest we add them into the game as a stable feature. WHO'S WITH ME

**Comment by Carbonhell** [comment]
What about all those aaaaaaaaaaaaaaaaaaaas at the end?i think they may need some kind of editing too?If not, the two spots are those so it should be theorically fine

**Comment by AliiTea** [comment]
they are supposed to be there also adding them back in with some kind of icon would be best

**Comment by Carbonhell** [comment]
They're a product of a bug. for some reasons something happened and recharge_floor/asteroid got swapped with hostile/asteroid, which is the father of all asteroid enemies(goliath, hivelord, etc). I got no idea what exactly it does therefore

**Comment by nalarmg** [comment]
Have you actually tested this to ensure it doesn't cause mapping issues and such?

**Comment by AliiTea** [comment]
@nalarmg you know me.. When do I ever test?

serious tho  I can't boot up a test server right now so I can't test

**Comment by AliiTea** [comment]
Looking at other map changes I am 99% positive that this will not NewRoundSexy

**Comment by nalarmg** [comment]
On hold until confirmation is given. Untested code should not be merged.

**Comment by AliiTea** [comment]
Alright

**Comment by danhibiki** [comment]
Whats the status on this?

**Comment by TDcoolguy300** [comment]
I've looked at this, it's basic removing accidental /mob/living/simple_animal/hostile/asteroid, which are technically non-existant mob content wise.

**Comment by TDcoolguy300** [comment]
Also, this is on the map itself, not the code.

**Comment by nalarmg** [comment]
Has this been tested yet?

**Comment by AliiTea** [comment]
Can someone test this for me?
unable to test for the next week or so

**Comment by doobiedoo23** [comment]
i love these little guys lets keep them

**Comment by Cafaling** [comment]
I'm with Doobie. Keep the magic hug monsters.

**Comment by Carbonhell** [comment]
my bug turned into a feature, fucking praise me :mememan3: :meat_on_bone:

**Comment by AliiTea** [comment]
I honestly see no harm in keeping them :/

**Comment by Chronitonity** [comment]
Can you not tell what a joke is

**Comment by AliiTea** [comment]
Well then merge it already >:I

**Comment by Chronitonity** [comment]
Test it and tell us it works first

**Comment by AliiTea** [comment]
Tested works 100% fine

**Pull request merged**
