### PR TITLE
Adds hotkeys for OOC, /me, and resisting 

### PR DESCRIPTION
**Pull request by Chronitonity**
Which are O, M, and B respectively.

You can also use CTRL+(Hotkey) to use the hotkeys while not in hotkey mode, fun!

### CODE REVIEW

**Comment by nalarmg** [comment]
I'd prefer there be options flags for different hotkey settings or something. It'd be annoying to accidentally hit M or B or O and suddenly have a popup infront of you whilst you're potentially trying to do something else. Maybe just make them ctrl + M/B/O instead, or something?

**Comment by AliiTea** [comment]
"o" has nearly gotten me banned so many times on /tg/ it's not even funny

**Comment by Chronitonity** [comment]
This is how hotkey mode works mate. If your in hotkey mode and press T you use say, its been that way forever. If you don't want the pop ups don't use hotkey mode.

**Comment by WhiteFox08** [comment]
:+1:

**Pull request merged**
