### PR TITLE
Gateway Replacement

### PR DESCRIPTION
**Pull request by Weisyl**
http://puu.sh/kKpdZ/64b465c96b.png

### CODE REVIEW

**Comment by Chronitonity** [comment]
Do not merge until the issues of swarmers needing to spawn at the gateway is fixed.

**Comment by Foosili** [comment]
Yeah this is pretty good. The sooner we get that thing off the station the better.

**Comment by danhibiki** [comment]
Would accept if it didn't fuck up swarmers

**Comment by Weisyl** [comment]
@danhibiki I added the spawn back. Looks somewhat uncanny but the way that /tg/ coded them in for spawning was in the least convenient way possible.

**Comment by Nebyab** [comment]
Yeah sure

**Comment by danhibiki** [comment]
Bit of a merge error because we ended up accepting pykos.

**Comment by Weisyl** [comment]
I'll just wait until Pyko's other mapping PR gets merged because I'm 99% sure it'll be merged first anyway.

**Pull request merged**
