### PR TITLE
Welcome to the Nanoing {DNM}

### PR DESCRIPTION
**Pull request by AliiTea**
Ports: https://github.com/tgstation/-tg-station/pull/13195

Holy fuck

### CODE REVIEW

**Comment by TDcoolguy300** [comment]
:td:

**Comment by AliiTea** [comment]
:I

**Comment by TDcoolguy300** [comment]
mv: cannot stat `tgstation.mdme.dmb': No such file or directory

mv: cannot stat `tgstation.mdme.rsc': No such file or directory

**Comment by AliiTea** [comment]
_shrug_
No clue

**Comment by TDcoolguy300** [comment]
tgstation.mdme:157:error: unable to open "code/controllers/subsystem/nanoUI.dm".

**Comment by AliiTea** [comment]
I hate this...

**Comment by TDcoolguy300** [comment]
Figured it out, you left out the new DME configuration, so alot of these new files are not active.

**Comment by AliiTea** [comment]
SHHHHHHHHHHH _totallydidn'tjustnotice_

**Comment by TDcoolguy300** [comment]
Gg

**Comment by AliiTea** [comment]
now what >_>

**Comment by TDcoolguy300** [comment]
code/modules/admin/admin_verbs.dm:142:error: /: missing comma ',' or right-paren ')'

code/modules/admin/admin_verbs.dm:118:error: list started here

code/modules/admin/admin_verbs.dm:143:error: unbalanced )

**Comment by TDcoolguy300** [comment]
Do you even try compiling this before pushing it?

**Comment by SplergeBucket** [comment]
nex smh tbh fam this pr is bROKen

**Comment by AliiTea** [comment]
yes yes it is...

**Pull request closed without merging**
