### PR TITLE
Mime statue code and icon

### PR DESCRIPTION
**Pull request by Kokojos**
THIS DOES NOT ADD IT TO THE MAP.

### CODE REVIEW

**Comment by TDcoolguy300** [comment]
ADD IT TO THE MAP YOU NERD

**Comment by Nokington** [comment]
wow too lazy to add to the map?

**Comment by Nokington** [comment]
:+1:

**Comment by Kokojos** [comment]
I knew they would be edited soon. If not done by tomorrow il add to map

**Comment by Pyko1** [comment]
I can add it to the map and make the theater backstage a bit larger while on it.

**Comment by Pyko1** [comment]
I can add em to map while I add some cameras so AI gets proper coverage on areas it should have.

**Comment by Kokojos** [comment]
Sure. Please add a .yml of me adding the statues and we're all set ;-) ;-)

**Comment by Pyko1** [comment]
Sure, just waiting for this to get added, all done with cameras already.

**Pull request merged**
