### PR TITLE
Dildos

### PR DESCRIPTION
**Pull request by AliiTea**
Re-Adds dildos.

Should we re-add dildos?
​_Yes: 11_​
​_No: 3_​
​_Fuck yeah fam smh tbh imo afaik: 6_​
​_Did not vote: 32_​

### CODE REVIEW

**Comment by ghost** [comment]
no

**Comment by Chronitonity** [comment]
do it

**Comment by trifornt-tinfornt** [comment]
No.

**Comment by Weisyl** [comment]
No.

**Comment by nalarmg** [comment]
This has been denied by two head admins, so I'm closing this.

**Comment by AliiTea** [comment]
Nooooooooooooooooo

**Comment by AliiTea** [comment]
No heads have denied it in the PR

**Comment by nalarmg** [comment]
The denial was established at a top level, and stated in coderbus at one point. The head admins can reopen this if the denial was erroneous.

**Comment by AliiTea** [comment]
Dildos can no longer be stored in butts/pockets

Let them in!

**Pull request closed without merging**
