### PR TITLE
Medical Cyborgs now have Tricordazine instead of the 4 main healing chems. Emagged mediborgs now get CLF3 instead of Facid.

### PR DESCRIPTION
**Pull request by ghost**
You now cycle through chems as well instead of the menu selection.
This is technically a nerf since tricord works slower than the other chems.
But I'd really did prefer the old healing system where it was fire and forget.

NEW THING:
This now changes emagged mediborgs to use CLF3 to make them a far more viable option for traitors and such. Ever since acid was made to tickle and we brought back sec borgs, mediborgs have been cast away in terms of usefulness.

### CODE REVIEW

**Comment by calibraptor** [comment]
Yes please +1/3rd

**Comment by Kierany9** [comment]
Why not have both?

**Comment by ghost** [comment]
Because cycling through all the better chems would be awful.
And the menu was an awful idea in the first place.

**Comment by Carbonhell** [comment]
Sidenote,DD drains nutriton if taken by nonmedics

**Comment by Badmex** [comment]
Yes +1/3

**Comment by ghost** [comment]
Intended kinda, it's either use tricord which is even weaker than current DD, has an OD limit.
I'd rather have old DD's but I think that would fuck balance to hard in the mess we call our chemistry system.

**Comment by Carbonhell** [comment]
Code is ok

**Comment by ghost** [comment]
PR has changed drastically and needs to be reconsidered.

**Comment by Spacedong** [comment]
nice

**Comment by Kokojos** [comment]
Not agreeing with the CLF3. 5 units of it sets you on fire for a long time, and the only thing that could save you is being right next to a pool

**Comment by ghost** [comment]
It's easily countered by fire extinguishers.
Hell, I'd argue the good old bottle smash and light strat is more effective than CLF3.

And considering borgs used to have polyacid before it was nerfed, mediborgs were meant to be feared when emagged.
When I was testing it, it took a good while to crit someone with the spray too.

**Comment by Kokojos** [comment]
Removed my previous post after testing. Nevermind me, this is gucci +1/3

**Comment by ArcLumin** [comment]
Just remove nutriment drain on DD

**Comment by Badmex** [comment]
Nah DD should stay that way. Also yeah seems nice that emagged Mediborgs are better now, still nobody will use them because emagged sec borgs for the win. +1/3

**Comment by dreamcrab** [comment]
+33333333

**Comment by KayeArray** [comment]
What about omnizine instead?

**Comment by ghost** [comment]
> omnizine

Surely you are jesting
That's botany only dude.

**Comment by Carbonhell** [comment]
Code ok, got approval, merging

**Pull request merged**
