### PR TITLE
Readds Esword Wall Welding

### PR DESCRIPTION
**Pull request by ArcLumin**
Part of https://github.com/HippieStationCode/HippieStation13/pull/1608

### CODE REVIEW

**Comment by doobiedoo23** [comment]
+1/3, this should be auto-merged considering it's a pre-rebase thing that was just never readded.

**Comment by Kokojos** [comment]
yes. +1

**Comment by Nebyab** [comment]
doobie you're well aware that is not how this works

yeah syre

**Comment by SplergeBucket** [comment]
ok

**Comment by Pyko1** [comment]
Code looks fine and it has been approved.

**Pull request merged**
