### PR TITLE
Revert "Changes ripley sprite to newer sprite"

### PR DESCRIPTION
**Pull request by Chronitonity**
Reverts HippieStationCode/HippieStation13#1374

It looks REALLY bad in game.

http://puu.sh/lMAY4/ff028341b1.png

http://puu.sh/lMAZX/90b4544683.png

### CODE REVIEW

**Comment by Chronitonity** [comment]
Also the fire ripley is still the same type of sprite as the old ripley, which is even weirder

**Comment by danhibiki** [comment]
I guess, seems like in general people don't like it.

**Comment by SplergeBucket** [comment]
Yeah, I don't like the new sprite.

**Comment by AliiTea** [comment]
booo

**Pull request merged**
