### PR TITLE
Black Powder Musket

### PR DESCRIPTION
**Pull request by ghost**
might put this as a z level item somewhere with a minuteman costume (mm falout4)

YOU CAN TABLECRAFT THE AMMO:
tablecraft paper cartridges with
one paper, fifteen black powder units, 2 duct tape,and a " minie ball" whilst holding a screwdriver
bullets do 25 damage (foos level damage)

the gun has alot of deviation and will miss at probably like 6 tiles

you make minieball with 2 metal sheets whilst holding a welder

dunno where i might implement it but hey

### CODE REVIEW

**Comment by Chronitonity** [comment]
Holy shit this is easier to make than the improvised shotgun and does 30 ranged damage. 

Thats considerably powerful when compared to anything else, id rather we didnt make an easy craftable gun that anyone can make.

**Comment by ghost** [comment]
this isn't.
craftable
was thinking there could be a minuteman costume with this somewhere 
maybe on a z level

**Comment by ghost** [comment]
you cannot make the gun, only the shells.

**Comment by Chronitonity** [comment]
My mistake, it sounded that way from reading the PR

**Comment by Weisyl** [comment]
30 damage is actually fairly weak for ranged weaponry and only half as strong as a shotgun slug, which does 60 damage / brute. The effort it takes to make ammo for this combined with the kinda lame damage to me means that this'll probably not be used at all. You'd at least want to make the bullet do 60 damage, equal to shotgun slugs, or a bit more than that considering the musket's single-shot capability and the effort needed to make just one new cartridge.

**Comment by ghost** [comment]
to me obscurity is ok
i mean it's a super old gun

**Comment by danhibiki** [comment]
Why not, where is it right now though, how do you acquire said gun?

**Comment by danhibiki** [comment]
Nevermind, I'm stupid and you answered this.

**Comment by Foosili** [comment]
lower the damage and sure

**Comment by Pyko1** [comment]
I have no idea why would you want the damage to be lowered as this is already weak compared to other guns.

**Comment by Nebyab** [comment]
Yeah sure

**Comment by Lawligagger** [comment]
Seems alright, I like the idea of space minute men.

**Comment by ghost** [comment]
redy 2 merge ;)

**Pull request merged**
