### PR TITLE
Adds Cappy Meal Boxes

### PR DESCRIPTION
**Pull request by ArcLumin**
Everyone's favorite food from McHackole's© is here! The Cappy Meal Box©! This Nutritious™ box comes with a toy and all the Nutrients™ you and your whole family could ever want!

WARNING: CHOKING HAZARD: CONTAINS TOY

http://puu.sh/qKW2f

### CODE REVIEW

**Comment by ArcLumin** [comment]
can't choke people with food when I'm choking on my bad code, hold up

**Comment by ArcLumin** [comment]
gonna brb while I think over the best way for a toy to spawn after you eat it

**Comment by ArcLumin** [comment]
FUCK I FORGOT "And the vision that was planted in my brain" AND MY SHIT'S STILL FAILING REE

**Comment by ArcLumin** [comment]
FUCKING FINALLY. Snowflakey as shit but I don't care; if someone else has a better way for a random toy to spawn on_Consume then tell me

**Comment by GenericGoose** [comment]
what why

**Comment by ghost** [comment]
Ayyy

+0.1

**Comment by GenericGoose** [comment]
what is cappy

**Comment by ArcLumin** [comment]
It's that guy on the dakimakura

**Comment by Spacedong** [comment]
can we stop sucking up to powergamers already? -1, fuck off, actually have a good mascot and shit, put a clown on it

**Comment by ghost** [comment]
The joke would be better if that was the case tbh.

**Comment by Spacedong** [comment]
why do we need to worship hackole again

**Comment by ArcLumin** [comment]
because clown meal boxes don't sound like "Happy meal"

**Comment by SplergeBucket** [comment]
I don't like player static references.
No thanku

**Comment by SplergeBucket** [comment]
come to think of it too
you could just call them McHippie meals
boom
situation solved

**Comment by ArcLumin** [comment]
But then it's still not a happy meal, ree

Maybe if I get another sprite for it with a clown I'll swap it.

**Comment by Badmex** [comment]
Naaaah this is not really needed

**Comment by Pyko1** [comment]
Make it Hippymeal from Burger Ling

**Comment by Pyko1** [comment]
Burger Ling - Ecological burgers made from the finest ling meat.

**Comment by GenericGoose** [comment]
oh i got it you suck some powergamers benis and its a funny meme because of that yeah thats funny haha add it into the game
its not like they are an issue and you make it worse by giving them attention smh
fursonas for donations when

**Comment by Spacedong** [comment]
its bad enough we kiss up to camille and cappy via dakis, remove those when?

**Comment by Pyko1** [comment]
Would be neat if we could make it so that that daki picture is somehow generated by player roundstart appearance. So you could make daki look like any crewmember as they looked when they entered the round.

**Comment by Spacedong** [comment]
no

**Comment by ArcLumin** [comment]
Hippy Meal from Burger Ling? Fuck that's good, I'll get a new sprite

**Comment by Spacedong** [comment]
nice

**Comment by GenericGoose** [comment]
yes and plz no more powergaymer shit

**Comment by ArcLumin** [comment]
To be honest, I only did cappy meal because;
1. Rhymed with happy meal
2. was hilarious when I came up with it
3. was originally gonna have a chance of fake adrenals and other fake powergamer items

now that that's not the case, might as well do a Hippy Meal Box from Burger Ling

**Comment by Lawligagger** [comment]
no thanks gross

**Comment by calibraptor** [comment]
I'd rather not.

**Comment by Pyko1** [comment]
I actually like this idea a lot, the name and icon just needs some polishing.

I always wanted more ways to get those wacky toys in to game beside the arcades.

**Comment by ArcLumin** [comment]
currently thinking of Hippy Meal boxes from Burger Ling or something.

I like the idea, I just threw cappy on it because rhyming + he's already in the code

Prolly gonna put a clown or horror ling or some shit on it

**Comment by ghost** [comment]
I dont get it. We've already got the cappy daki, this is just memes. Why the kneejerk?

**Comment by GenericGoose** [comment]
oh yeah remove all the powergaymer memes too its gay and not funny

**Comment by trifornt-tinfornt** [comment]
remove powergaymer memes, they're doing nothing but encouraging players to powergame harder if they want attention (JackTheLing) and as well as metagrudge. Cappy/Camille dakis are enough.
Just replace it with a Clown or something and rename it to "Hippie Meal" from "Burger Ling" as you said you would, that'd be much better.

**Comment by blobbernaut** [comment]
neat sprite tho

**Comment by ghost** [comment]
@blobbernaut literally 15 minute job

literally

I timed it

**Comment by TheOneAndOnlyCreeperJoe** [comment]
You literally copy pasted the daki's head on it. Respect my original content bro.

On a serious note, Hackole doesn't need more recognition, he's already got enough in the form of being bombed using daki's of himself. People are too neglecting of the clown, which is basically the symbol of any and all wackiness in space station 13. Plaster the clown's face on the lunchbox and people will want it.

**Comment by ArcLumin** [comment]
Wasn't my sprite, rip. Got it from Gandalf.

Gonna go ask him to make the clown one, but he's resistant to it, rip. I might just do it myself

**Comment by GenericGoose** [comment]
WTF DUDE CLOWN IS A SYMBOL OF HIPPIE ISNT IT?????????????
put clowns on every sprite in the game 
clown texture pack

**Comment by ghost** [comment]
hippie meal with a clown strikes me as the lamest thing possible tbh

**Comment by GenericGoose** [comment]
reminder that mcdonald's mascot is an clown
why can't hippie have one

**Comment by ghost** [comment]
Then go with burger ling and put a horror form ling on it?

**Comment by ArcLumin** [comment]
Closing this until I can make/get a new sprite

**Pull request closed without merging**
