### PR TITLE
Big pool update. 

### PR DESCRIPTION
**Pull request by Kokojos**
The pool no longer EMPs anything, feel free to swim with guns.
The poolcontroller has now a better UI, and allows for it to be drained/filled if wires are hacked.
The Filter now fills up by item stolen by the drain. You can empty the filter with a crowbar.
The Drain is dangerous when active, and can gib very damaged bodies.
You can now have water splashes fights.
 A lot fixed with the jumping board.

TL:DR : Pool is better now.

### CODE REVIEW

**Comment by Kokojos** [comment]
Do not merge until I get a good .dme pathing. I somehow rewrote all FILE_DIR. Waiting on Erik's response so that I can include the file in the version control.

**Comment by ghost** [comment]
Go to `build` -> `Preferences` -> untick `Automatically set FILE_DIR`

**Comment by ghost** [comment]
also.

```
code/game/machinery/poolcontroller.dm:238:error: drain: undefined type: drain
code/game/machinery/poolcontroller.dm:239:error: drain.active: undefined type: drain.active
code/game/machinery/poolcontroller.dm:245:error: drain.active: undefined type: drain.active
code/game/machinery/poolcontroller.dm:246:error: drain.timer: undefined type: drain.timer
code/game/machinery/poolcontroller.dm:248:error: drain.status: undefined type: drain.status
code/game/machinery/poolcontroller.dm:249:error: /obj/effect/whirlpool: undefined type path
code/game/machinery/poolcontroller.dm:249:error: drain.loc: undefined type: drain.loc
code/game/machinery/poolcontroller.dm:252:error: drain.status: undefined type: drain.status
code/game/machinery/poolcontroller.dm:253:error: /obj/effect/effect/waterspout: undefined type path
code/game/machinery/poolcontroller.dm:253:error: drain.loc: undefined type: drain.loc
code/game/machinery/poolcontroller.dm:238:warning: drain: variable defined but not used
```

**Comment by Kokojos** [comment]
Yeah that's because I din't set the file in the version control.

**Pull request merged**
