### PR TITLE
Update stylesheet.dm

### PR DESCRIPTION
**Pull request by AliiTea**
I'm a shithead :^)

### CODE REVIEW

**Comment by Kokojos** [comment]
WHAT'S IN THE BOXXX? WHAT'S IN THE PRRRRR?

**Comment by Nebyab** [comment]
According to nex, this is a PR to change the Command Channel Colour to... something else?

Nex, at least give us a clue as to what you're doing,

**Comment by AliiTea** [comment]
changes it from its current color to a nice dark blue/navy/I havenoidea

**Comment by AliiTea** [comment]
http://imgur.com/TmE6L53

**Comment by calibraptor** [comment]
Tbh the command radio color is pretty hard on the eyes +1

**Comment by Kokojos** [comment]
Yeah im not againts :+1:

**Comment by JohnGinnane** [comment]
Can you post a screenshot of the change in game?

**Comment by AliiTea** [comment]
Actually went and tested this and it looks almost black.

**Comment by AliiTea** [comment]
image
Changed it from the dark blue to a darker purple and it looks nice

Would have made it a lighter blue but medbay is using that color

**Comment by JohnGinnane** [comment]
Thank you!

**Comment by Kierany9** [comment]
But science uses dark purple.

**Comment by ghost** [comment]
Why purple?

Command already has that dark blue they use for the doors.

**Comment by calibraptor** [comment]
Science uses a /much/ lighter shade of purple. I don't think there will be any mistaking.

**Comment by ghost** [comment]
~~I think #4682B4 would be a nicer colour.~~
Wait nvm, too close to medical.

003F87 doesn't look too close to either medical or OOC does it?

**Comment by calibraptor** [comment]
003F87 would probably work. OOC text is bigger anyways and the command channel sees use by a whopping 6 or so people anyways so we wouldn't need to worry about having trouble differentiating between OOC and the command channel.

**Comment by AliiTea** [comment]
image

Just did a quick test with the color @McBawbaggings suggested and it's nice.

**Comment by dreamcrab** [comment]
that looks a lot like medical aaaaa whats wrong with the gold

**Comment by carlarc** [comment]
looks like medical.

**Comment by calibraptor** [comment]
@dreamcrab It can be literally unreadable on certain monitors, specifically mine. Also the medical channel color is a /lot/ lighter.

**Comment by Carbonhell** [comment]
code is (obviously) ok

**Comment by Nebyab** [comment]
Gold is fine.

No need to change.

**Comment by Kokojos** [comment]
I like this.

**Comment by Kokojos** [comment]
So far it seems 2HA are againts. Closing.

**Pull request closed without merging**
