### PR TITLE
Facepunch SS13 Ports

### PR DESCRIPTION
**Pull request by Weisyl**
Ported a bunch of things from Facepunch, which includes: ASS Operative armor, Blood Raven armor + chainsword, and gib gun.
All of these are admin-spawn exclusive except for the gib-gun, which can be spawned from summon-guns or found at the CentCom emergency shuttle dock.
Admins, there are two new selectable equipment options: ASS Operative and Blood Raven Space Marine.
Picture of this new gear: http://puu.sh/lolC1/77817aff10.png

### CODE REVIEW

**Comment by Chronitonity** [comment]
> except for the gib-gun, which can be spawned from summon-guns

Yes. Yes. Yes.

**Comment by Foosili** [comment]
hjoly SHIT

**Comment by Foosili** [comment]
ASS RISES AGAIN

**Comment by ghost** [comment]
uncle gubsy aproves

**Comment by danhibiki** [comment]
Yes

**Comment by danhibiki** [comment]
merge errors due to map changes, plz fix plz

**Pull request merged**
