### PR TITLE
Station rotation

### PR DESCRIPTION
**Pull request by TDcoolguy300**
Allows admins to rotate the entire view via calling the proc /proc/mass_edit_client_dir , where it requires a direction as a number.

### CODE REVIEW

**Comment by doobiedoo23** [comment]
F U C K

LET'S DO IT

**Comment by TDcoolguy300** [comment]
http://puu.sh/lxgHl/e451f58c01.png Forgot to link this

**Comment by Foosili** [comment]
FUCKING YES
U
C
K
I
N
G

Y
E
S

**Comment by Chronitonity** [comment]
OH MY GOD

**Comment by ghost** [comment]
fucking lmao

**Pull request merged**
