### PR TITLE
Add burpium

### PR DESCRIPTION
**Pull request by tortellinitony**
It's like fartium, but it makes you burp, a lot.

Why not?

### CODE REVIEW

**Comment by Spacedong** [comment]
lmao +1

**Comment by tortellinitony** [comment]
I'm going to try to add an overdose effect, so do not merge yet.

**Comment by KayeArray** [comment]
add the OD effect we talked about and this golden +1

**Comment by Hackole** [comment]
Why not? +1

**Comment by FuryMcFlurry** [comment]
guess i gotta update mt chemglands when this gets added, to include this chem.

**Comment by ghost** [comment]
WE GOTTA MERGE THE ***BUUUUUURP*** CODE MORTY
+1

**Comment by tortellinitony** [comment]
OK it's ready once the check passes

**Comment by tortellinitony** [comment]
you can merge it now

**Comment by ghost** [comment]
fuck sorry, I thought I posted.
I don't like the idea of an overdose gibbing someone since fartium is easy to make. Even though it's only a 3% chance per tick and you need 40u in your system.

If you give someone a burpium pill 50u, they have to survive 125 rolls of 3% chance. That is pretty likely.

**Comment by tortellinitony** [comment]
Now a 47% chance of gib after 125 rolls, instead of the previous 98% chance.

**Comment by SpankMasterson** [comment]
Yea make it like .1 or .01, shouldn't be an expected thing. besides that +1

**Comment by Swagile** [comment]
yeah it should be a meme like super nova and galaxy being like 0.04 percent or something

**Comment by tortellinitony** [comment]
.1% chance now ^^

**Comment by tortellinitony** [comment]
Too many conflicts. I will redo it without the gib, and instead something more suitable for a meme chem.

**Pull request closed without merging**
