### PR TITLE
Diner Access Fix

### PR DESCRIPTION
**Pull request by Cafaling**
Chef and Bartender have minor access to eachother's workplaces to encourage cooperation.

This door, and the one below it will now open for the barman as well as the Chef.
http://puu.sh/kPWx0/f333e72525.png

### CODE REVIEW

**Comment by Pyko1** [comment]
Umm, they already do open both for bartender and the chef.

**Comment by Cafaling** [comment]
According to Chron, they don't. He asked me to do this.

**Comment by Pyko1** [comment]
Just tested it on the server, and it did.

**Comment by Cafaling** [comment]
RIP

**Comment by Pyko1** [comment]
So yeah, By default the bartender has kitchen access, and both of those doors use it.

**Comment by Cafaling** [comment]
I'll let Chron know.

**Comment by Chronitonity** [comment]
@Pyko1 You were using Skeleton Access to test, he has more access when there are 15~ players on only, after that he doesn't have access to the bar. @Cafaling you're good to open this

**Comment by Chronitonity** [comment]
This is an old HS feature

**Pull request merged**
