### PR TITLE
Xeno Suit update

### PR DESCRIPTION
**Pull request by ArcLumin**
Screaming with a Xeno helm will now produce xeno noises, like the cosby sweater

Xeno suits and helms are now pressure proof and cold proof, like xenos. However, they're flammable, give no armor, give no heat protection, and aren't great spacesuits.

### CODE REVIEW

**Comment by blobbernaut** [comment]
Cold protection without space protection would be great if there was a single source of it on the station except space

**Comment by ghost** [comment]
you are my god if this gets through

**Comment by carlarc** [comment]
winter coat hood protects from cold, this is GOOD

in my opinion xeno suit should be spaceproof and damage resistant, i mean you killed THREE XENOS

**Comment by carlarc** [comment]
FOUR

**Comment by Spacedong** [comment]
does this apply to the fake xeno suit :^)

**Comment by ArcLumin** [comment]
Fake xeno suit? I'm pretty sure there's just a normal xeno suit

**Comment by ArcLumin** [comment]
> in my opinion xeno suit should be spaceproof and damage resistant, i mean you killed THREE XENOS

Well, I figured I'd balance it since it's basically a no slowdown spacesuit

**Comment by JohnGinnane** [comment]
I had this exact same idea, but you did it first :)

**Comment by Badmex** [comment]
Yes this is great!

**Comment by ghost** [comment]
I was gonna say no until I realised this is the xeno hide stuff.
It always bugged me it wasn't space worthy.
Now I can be naked xeno screaming at people.
+1

**Comment by Carbonhell** [comment]
just one word:
changelog

**Comment by ArcLumin** [comment]
Fuck changelogs, stealth additions all the way

**Comment by Carbonhell** [comment]
@teamstab

**Comment by dreamcrab** [comment]
cool sure why not +14758

**Comment by blobbernaut** [comment]
GOOD change we put salt and pepper on it in our household

**Pull request merged**
