### PR TITLE
Comments out the Beam Attack for Venus Human Traps

### PR DESCRIPTION
**Pull request by TheOneAndOnlyCreeperJoe**
It's broken, I'll fix it later but until then and for the sanity of the server, let's remove the beam attack.

### CODE REVIEW

**Comment by Kierany9** [comment]
holy shit don't comment out every line, use /* */ you absolute madman

**Comment by Spacedong** [comment]
>he commented out everything using // on every line

holyy fuck now thats what I call autism 97

**Comment by Spacedong** [comment]
http://i.imgur.com/lpeJbDh.png

**Comment by ArcLumin** [comment]
Says mr. invisible catman who scours every pr for a single period missing in the description.

**Comment by SpankMasterson** [comment]
I'm Jewish plus one

**Comment by GuyonBroadway** [comment]
I agree the venus Human trap is poorly coded bullshit and that walldragging thing has been the end of many a vine planting spree. It'd be nice if the now not bullshit venus human trap were a little more frequent so it's just a group of simple hostile mobs, alternatively give them a poisonous spit attack much like the alien sentinel mob.

**Comment by ghost** [comment]
I'd rather remove it for now and hope someone takes up the mantle to make it less cancer.

**Comment by GuyonBroadway** [comment]
Agreed, I'll probably give it some kind of spit that either poisons or slows down or something to make them somewhat of a threat.

**Comment by KayeArray** [comment]
maybe have it actually work like a venus fly trap and trap people who walk near it

**Comment by oprayx77** [comment]
beat me out to it, remove this faggot beam shit

**Comment by ghost** [comment]
heck yeah get it outta here

+1

**Comment by JohnGinnane** [comment]
You will probably want to set `ranged = 0`

**Comment by TheOneAndOnlyCreeperJoe** [comment]
@JohnGinnane done

**Comment by JohnGinnane** [comment]
Code looks good

**Review by JohnGinnane — APPROVED** [review]

**Comment by Swagile** [comment]
its 3/3 headmin votes on this, it can be merged

spank, mcbawg, and neko bot have all + 1'd

**Pull request merged**
