### PR TITLE
Possibly fixes #423

### LINKED ISSUE #423: SQL error causing the chat frame to jump to the bottom (SERIOUSLY)
SQL ERROR during death reporting. Error : [Unknown column 'toxloss' in 'field list']

### PR DESCRIPTION
**Pull request by Carbonhell**
I CANNOT TEST DATABASE SHIT so apply DNM tag until someone can try this
shit out. it looks easy but i may most likely be wrong,i used logic
here,i know jackshit of databases

### CODE REVIEW

**Comment by Jaygriff** [comment]
This would also need to be executed on the database itself, you can test database stuff if you setup your own database environment on your local machine using mysql, though that is a bit advanced and may not actually represent a good bug fix even if it works due to the production environments database being dissimilar.

**Comment by Carbonhell** [comment]
I asked a guy who knows how to sql and he said the code's fine. check/merge please?

**Comment by Jaygriff** [comment]
Still needs testing.

**Comment by ghost** [comment]
Looks good, merge.

**Comment by nalarmg** [comment]
@Carbonhell, a simple google search on "how to set up a mysql database" should give you plenty of resources to put you into a position to ensure the change works as intended, for future reference. hippie_schema is the database set we use on the live server, so it should be accurately representative.

**Pull request merged**
