### PR TITLE
Supermatter Engine! (If there's one more revert I swear I will eat my goddamn shoes)

### PR DESCRIPTION
**Pull request by calibraptor**
What it says on the tin, the singularity was relocated so engineering now closely resembles what it was pre-rebase. There are other additions and changes too, I'll list off all the ones I can remember.
-  Fixed crystal glass so it actually works as intended with help from TD
-  The brig now has a proper execution chamber making use of crystal glass.
-  Fixed some sketchy looking wiring in the security wing, doubt I fixed the power problems considering it's on the exact opposite side of the station from engineering
- Added crystal windows to toxins on both the main station and the science outpost. Stoke the flames of your passion.
-  Atmos technicians now have access to the supermatter dedicated part of engineering. Almost all of the electrical related equipment including insulated gloves has been moved to the singularity engine, where they do not have access.

KNOWN PROBLEMS:
-  The supermatter shard is kind of weaksauce when it comes to power output
-  The engine jettison currently does not work as I had to anchor the shard in order to keep it from getting pushed around when air is pumped into the chamber
-  Could not recreate the supermatter control console from pre-rebase hippie. Couldn't get the damned thing to work. Have a table instead.

533679f8-193f-11e6-9db8-b92f4ca23817

976d338c-193f-11e6-8561-718b1396f112

5ec60f22-193f-11e6-97df-d293697c0e21

6422c58c-193f-11e6-92cb-ca5dcb17fb60

67ceb204-193f-11e6-9d9b-08b02a45d36e

### CODE REVIEW

**Comment by TDcoolguy300** [comment]
Eat the shoes

**Comment by ghost** [comment]
Preemptive +1
Live stream the shoe eating if there is a revert please.

**Comment by calibraptor** [comment]
This is exactly the same as #2333 which already got a yes from 2 headmins. Merge this shit before TD does another revert, I beg of you.

**Comment by TDcoolguy300** [comment]
So is it good for a merge?

**Comment by Pyko1** [comment]
We really need to start getting people to do map merges tho.

**Comment by TDcoolguy300** [comment]
Yeah, that would be nice too

**Comment by calibraptor** [comment]
@TDcoolguy300 One map merge, coming right up.

**Comment by TDcoolguy300** [comment]
Was approved in the previous PR, merging

**Pull request merged**
