### PR TITLE
Shield Refactor + a bunch of other small stuff im too lazy to make separate PR's for 

### PR DESCRIPTION
**Pull request by Chronitonity**
A lot of TG ports really

Changes IsShield to hit_reaction

Adds two new reactive armors, a reactive fire armor and a stealth armor. Both will end up as traitor items as i iron them out/fragg provides decent sprites.

The fire version shoots out flames in a radius when someone attacks you, the stealth version turns you invisible and makes a "copy" of you that runs away.

Adds a cloaking belt, and as i stated above, will probably become a traitor item when i iron it out.

Wallets now store all the accesses of the ID's in them, making them even more useful.

People speaking in deadchat now have a follow link for all ghosts, just like alive people do.

Syndicate mobs cry out when they spot someone, calling their friends to them.

Clowns honk when punched.

### CODE REVIEW

**Comment by danhibiki** [comment]
Mmm, I'd like to know a bit more about the cloaking items, because toggleable invisibility use to be a really shit traitor item.

**Comment by Chronitonity** [comment]
Fire one makes you invisible for a few seconds while a mimic just runs away, basically a good escape plan.

Second one just makes you invisible for a while.

Neither are accessible in game yet so balance isn't what im worried about right now, they're just there so we can fuck around with them until i polish everything

**Comment by danhibiki** [comment]
I noticed trayshield doesn't have a defined block chance, but other shields do. Is its block chance inherited and I missed it?

**Comment by Chronitonity** [comment]
Yup, its a child of the riot shield, it inherits it

**Comment by Nebyab** [comment]
yeah sure

**Pull request merged**
