### PR TITLE
Adds anti grief measures for bombing.

### PR DESCRIPTION
**Pull request by ghost**
I was provoked into doing this.

### CODE REVIEW

**Comment by Nebyab** [comment]
ok?

**Comment by Kierany9** [comment]
yes

**Comment by Carbonhell** [comment]
remove the spacing between list and () in the first.DM file and code will be ok

**Comment by dreamcrab** [comment]
wat

**Comment by dreamcrab** [comment]
wat is

**Comment by dreamcrab** [comment]
ok i talk 2 ppl of feature

+5

**Comment by Gandalf2k15** [comment]
Code looks good, check and shit. Merging as it has head input.

**Pull request merged**
