### PR TITLE
Mulligan4wizards

### PR DESCRIPTION
**Pull request by ghost**
Addresses Issue #2848

### CODE REVIEW

**Comment by TDcoolguy300** [comment]
This needs input from the Headmins, as this was intentionally disabled originally.

**Comment by Kokojos** [comment]
I am okay with this as wizard often die early. :+1:

**Comment by danhibiki** [comment]
There is a _huge_ disdain for the mulligan system. I don't understand it, as it just keeps a round going for as long as the station can support it really.

**Comment by ghost** [comment]
It was decided at a meeting to disable mulligan on wizard.
Honestly I think the classic round is over when wizard is dead is the best way to do it.

**Comment by ghost** [comment]
Only problem with that bawb, is that staff of transformation 'kills' wizards if they lose their hands.

With mulligan, the round doesnt end and they can usually get themselves transformed back.

**Comment by ghost** [comment]
Also
https://github.com/HippieStationCode/HippieStation13/blob/0a9adaeb95bb09a8e50bec0df885bebd40f2ed80/config/initial_config/game_options.txt#L102

https://github.com/HippieStationCode/HippieStation13/blob/0a9adaeb95bb09a8e50bec0df885bebd40f2ed80/config/initial_config/game_options.txt#L127

It's a config option, new code shouldn't be added.

**Comment by ghost** [comment]
I should say I would like the round to end on wizard death.

**Comment by SplergeBucket** [comment]
i dont get the issue with mulligan
just make mulligan for wizard rounds
it's the easiest solution

**Comment by SplergeBucket** [comment]
having the whole thing end on wizard death could be cool but when you've got the issue of survivors or apprentices it can all get a bit clusterfucky and in that case i dont see why mulligan shouldnt be a thing

**Comment by danhibiki** [comment]
Its actually quite easy to do that within the current configuration, I think its just turned off. We'd need someone with box access to confirm

**Comment by Nebyab** [comment]
mulligan is bad and you should feel bad

also mulligan is a config option which needs to be changed on the box

just make apprentices and survivors not count for round ending imo. Wizman is the only one who matters.

**Comment by SplergeBucket** [comment]
> mulligan is bad
> t. doesn't play the game

**Comment by TDcoolguy300** [comment]
Due to this being a config issue, closing.

**Pull request closed without merging**
