### PR TITLE
Possibly fixes the Reagent Metabolization issue

### PR DESCRIPTION
**Pull request by TDcoolguy300**
Somehow datums are not being properly removed from the obj SubSystem. This method is no different than what i replaced, but if it works, ¯_(ツ)_/¯. Unable to reproduce the runtimes locally however.

### CODE REVIEW

**Comment by Carbonhell** [comment]
No this won't fix it man,pretty sure

**Comment by GeneralGoose** [comment]
what was the issue

**Comment by TDcoolguy300** [comment]
Then i have no idea Carbon, Reagents datums are either not being removed from the obj subsystem on deletion, or are straight up having read issues.

**Comment by Nebyab** [comment]
will it work or not, who knows?

**Comment by Carbonhell** [comment]
Why the hell didn't i close this pr?
im dumb

**Pull request closed without merging**
