### PR TITLE
Fixed some diseases being incurable

### LINKED ISSUE #2479: Some viruses can't be cured even if you take the right cure
Magnitis and the bee virus are one of them. Take the cure listed on health scanner, wait, nothing happens. Other viruses are cured like brainrot. Occurred over multiple rounds.

### PR DESCRIPTION
**Pull request by JohnGinnane**
Some diseases were missing the CURABLE status flag.

Fixes #2479

### CODE REVIEW

**Comment by Nebyab** [comment]
I think you mean

incurable

**Comment by JohnGinnane** [comment]
Words are hard.

**Comment by danhibiki** [comment]
i think you mean

fixes

**Comment by Sarcalogo** [comment]
Any relation to this?

https://github.com/HippieStationCode/HippieStation13/issues/2479

**Comment by JohnGinnane** [comment]
Yes perfect thank you! It was the Magnitis which sparked this.

Looking at your issue thought the beesease should be curable as it doesn't modify the disease_flags whose default value has the CURABLE flag: https://github.com/HippieStationCode/HippieStation13/blob/5462010e5bcc8a61ad5618ffd0f04f07eeb570b0/code/datums/diseases/beesease.dm

**Comment by Carbonhell** [comment]
Since its a bugfix it does not need head input. Is it good to merge, @johnginnane ?

**Comment by JohnGinnane** [comment]
Yes, I just figured changing the diseases to be curable might balancing. It's ready to merge

**Pull request merged**
