### PR TITLE
Last medical mapping fix I swear

### PR DESCRIPTION
**Pull request by collinxchu**
Finally got this medical fix done properly.

Same as the last two PRs.

https://github.com/HippieStationCode/HippieStation13/issues/403

### CODE REVIEW

**Comment by Kokojos** [comment]
Finnaly, a mapmerge! 

:+1: 
Merge this.

**Comment by Chronitonity** [comment]
:+1:

**Comment by collinxchu** [comment]
@Kokojos I used mapmerge on the last one, but mapmerge apparently hates my guts and doesn't like to be used more than once.

**Comment by nalarmg** [comment]
Conflicts. Please resolve.

**Comment by WhiteFox08** [comment]
Fixed in #483

**Pull request closed without merging**
