### PR TITLE
Changes ripley sprite to newer sprite

### PR DESCRIPTION
**Pull request by AliiTea**
Credit goes to spheretech & nienhaus

Mining ripley keeps old sprite while all the others use the newer fancy sprite.

New on left - Old on right
image

### CODE REVIEW

**Comment by Lawligagger** [comment]
Looks great.

**Comment by Weisyl** [comment]
This hardly fits in with the rest of the mechs or their established style. Ugh.

**Comment by Chronitonity** [comment]
Man those hands are ugly as fuck

**Comment by Crystalwarrior** [comment]
I hate the new sprite.

**Comment by SgtFragg** [comment]
digusting

**Pull request merged**
