### PR TITLE
Gib Ian Button

### PR DESCRIPTION
**Pull request by ghost**
memes

### CODE REVIEW

**Comment by Kokojos** [comment]
Why

**Comment by Spacedong** [comment]
:+1: i believe the question is: WHY NOT?

**Comment by ghost** [comment]
@Spacedong thanks fam just trying to make it in the game y'know?
@Kokojos I dislike dogs due to childhood memories. PTSD

**Comment by TrashFiend** [comment]
yes

**Comment by myontasm** [comment]
yes

**Comment by ghost** [comment]
> getting support from admins and not being told to kill myself

life complete. Also, accidentally closed this kek. that button is shittily placed

**Comment by danhibiki** [comment]
As a novelty whatever, but I'm under the impression doing a for loop that checks the world is going to run like dog shit and I don't think I can give this approval in good conscious until someone else chimes in on that. If it is an issue, I'm positive there is another way to do it and we can look into it

**Comment by TDcoolguy300** [comment]
It really isnt a good method, it would make it better if you were to use break when Ian is found

**Comment by ghost** [comment]
@TDcoolguy300 Can do, but wouldn't that do the same thing as long as there's only one Ian, or am I missing something?

**Comment by TDcoolguy300** [comment]
Simply put all it does is break the for loop so it stops looking hopefully.

**Comment by TDcoolguy300** [comment]
That being said, i am not 100% sure if that will work in the end, BYOND might just do the whole counting first then start doing the forloop

**Comment by ghost** [comment]
I'll PR it anyway

**Comment by ghost** [comment]
Done, and now monkeys can press the button so that they're even more validsalid.

**Comment by ghost** [comment]
although in hindsight that won't work unless it's emagged, wew

**Comment by Pyko1** [comment]
Gibbing Ian is all fun and games, especially if the hop gets really mad about it. But this just takes the fun away from all those assistants and clown trying to squeeze in to hop office just to pet Ian with a toolbox. Also I kinda want to make food recipes using Ian as whole just so chef can annoy hop even more than just corgi burgers.

**Comment by Carbonhell** [comment]
This PR is pmuch useless... That in world for loop is not needed,should use in mob_list or whatever it's called but even then a button that gibs a dog...what the Fuck, -1

**Comment by Nokington** [comment]
Nah :-1:

**Comment by ghost** [comment]
@Pyko1 how about an oven item that lets you roast Ian whole? 

@Carbonhell I'm not familiar with mob_list, but I'll check that out

**Comment by ghost** [comment]
I'm going to test this using locate() and mob_list, if that works I'll PR it

**Comment by ghost** [comment]
So I think I broke the map, might have to fix that later, rip

**Comment by ghost** [comment]
Fixed the map and made gibbing code use mob_list instead of a loop. Code tested.

**Comment by Nebyab** [comment]
why, what's the point

**Comment by ghost** [comment]
dank memes my friend

**Comment by Carbonhell** [comment]
-1, sorry but i just feel like the idea has no point at all.

**Comment by Pyko1** [comment]
I'd be all in for many gib buttons.
Ie.
- Gib engineers if engine is not set up 10 mins to the round
- Gib captain if hes not in his office but the disk is
- Gib cargo techs & QM if they say cargonia or any other variation of it.

But sadly, Gib Ian is not on that list.

**Comment by Carbonhell** [comment]
Funniest thing is that i think it's already possible to make a button that gibs humans...not sure tho

**Comment by nalarmg** [comment]
As far as I can tell and the answers I've recieved from the other heads, this is to be denied as a head has rejected it, and no other heads have come forward to contest it.

**Pull request closed without merging**
