### PR TITLE
Fixes never ending plasma floor fires

### PR DESCRIPTION
**Pull request by Jaygriff**
Delt with it the TG way.

img

img

### CODE REVIEW

**Comment by lcass** [comment]
I think they need to be a bit more effective , you might aswell use a fuel tank.

**Comment by Jaygriff** [comment]
Keep in mind people can make 4 of these with a single piece of plasma.

**Comment by lcass** [comment]
Yer but it should still brn for a decent amount of time , plasma is a wonderfuel.

**Comment by Jaygriff** [comment]
img
Bigger?

**Comment by WhiteFox08** [comment]
Nice work!

**Comment by nalarmg** [comment]
Code's fine.

**Comment by Jaygriff** [comment]
@Nebyab @whitefox08 @danhibiki This is ready to rolllll

**Pull request merged**
