### PR TITLE
STIMULANT VIRUS NO LONGER SUCKS

### PR DESCRIPTION
**Pull request by KayeArray**
Seriously who thought adding a painkiller chem that makes you drowsy to a STIMULANT was a good idea?! 

I added a special snowflake chemical known as 'Hyperzine' purpose built for the stimulant virus which provides a FAST speedboost and slightly faster stamina regen but nothing else.

No longer will you be put to sleep by your own viruses.

### CODE REVIEW

**Comment by Anderbergst** [comment]
i like it

**Comment by blobbernaut** [comment]
yes +1 this is the best PR ever

**Comment by Kierany9** [comment]
un-nerf ephedrine

then make it use ephedrine again

baka

**Comment by KayeArray** [comment]
i daren't touch those cursed chems

**Comment by gumner** [comment]
NO DO NOT EVER RE-ADD EPHEDRINE BURN EPHEDRINE CODE

**Comment by Kierany9** [comment]
>NO DO NOT EVER RE-ADD EPHEDRINE BURN EPHEDRINE CODE

too late

**Comment by ghost** [comment]
Considering anti stuns are gone and the main reason the change was made was to stop stacking hyperzine with anti stuns, I'd say this is good. +1

**Comment by Spacedong** [comment]
sure

**Comment by ghost** [comment]
So pretty much what stimulants used to, and are supposed to be? I miss hyperzine.

**Comment by SpankMasterson** [comment]
+1

**Comment by Swagile** [comment]
isn't aransap or whatever its called basically hyperzine?

**Comment by KayeArray** [comment]
No because it kills you

**Comment by Pyko1** [comment]
code seems fine and is approved

**Pull request merged**
