### PR TITLE
Fartmospherics

### PR DESCRIPTION
**Pull request by tortellinitony**
http://i.imgur.com/IAo8rt9.png
Added a fart gas that can be obtained in a canister, or through farting too much!

>It can be filtered by scrubbers, and it will fill up the mix tank in atmospherics.

>It is NOT flammable.

>It is so nasty that breathing it in will make you cough, and even vomit.

Farts and superfarts have a chance to propel you in space!

### CODE REVIEW

**Comment by MethMedic** [comment]
Yeeet

**Comment by KayeArray** [comment]
oh god atmos code.


we better wait for the codercucks to give this a proper look before we think about merging it

**Comment by tortellinitony** [comment]
it works and there are no errors

**Comment by dreamcrab** [comment]
super hilarious +420

**Comment by KayeArray** [comment]
uhh isn't this going to permastun people with stamina loss and vomiting?

**Comment by tortellinitony** [comment]
not with the amount that is actually obtainable without the adminspawned canister, and you'd have to stand in it for like 3 minutes

**Comment by PopNotes** [comment]
Imagine being able to buy a fart canister for like 8TC and sabotaging atmos to pump the station full of it

**Comment by dreamcrab** [comment]
i actually support a traitor atmos item full of fart gas lmfao

**Comment by KayeArray** [comment]
@PopNotes Shit meme (literally) and no one would do it because one canister isn't sufficient to 'pump the station full of it'

**Comment by Kierany9** [comment]
I don't want this to be a thing but on the other hand...

>disposals chute into a 1x1 room in space
>throw everybody into it
>launch fartium grenade inside

...it would be glorious

**Comment by yobob591** [comment]
why isnt it flammable tho

**Comment by PopNotes** [comment]
^

**Comment by KayeArray** [comment]
this should just be methane really

**Comment by tortellinitony** [comment]
you can already fart on a lighter

**Comment by tortellinitony** [comment]
I'll see if I can make it flammable, but that will take a little while to figure out

**Comment by yobob591** [comment]
gotta do it rite fam

**Comment by ghost** [comment]
Just because the code doesn't show any errors doesn't mean that it won't slow the server to a crawl. Honestly, all atmos changes should have to be voted on twice. Once to see if it's worth fucking up atmos, and once for the actual content.

**Comment by yobob591** [comment]
adding a new gas type that only spawns in small amounts from farts wont ruin the server

**Comment by KittyKathy** [comment]
One question did you actually test this on a test server and it works as intended?
Also new atmospherics job specific traitor item flamethrower powered by fart gas tank.

**Comment by JohnGinnane** [comment]
This is interesting

**Comment by tortellinitony** [comment]
@KittyKathy I have spent several hours testing it to make sure it works. Once again, it is not flammable. I could try to make it flammable, but this might create issues as plasma is the only flammable gas right now. Perhaps it could turn into plasma above a certain temperature and pressure, but I'd need help doing this.

**Comment by Pyko1** [comment]
You forgot to add farts for gas mixers, i think.

Should be shitty brown particles, not green.
Instead of using FART as gas name it should be methane, with possible chemistry integration, ie. mix 1 Carbon + 4 Hydrogen +Plasma Catalyst + Temperature = Liquid Methane that evaporates when splashed and shit.
Also monkey and especially cow farting needed. Since cows are always brought up when speaking about methane and global warming.

**Comment by gumner** [comment]
what if it made you a fat fuck if you breathed it?

**Comment by Pyko1** [comment]
Hell you could even make some atmos magic possible with methane and reverse.
CH4 + 2 O2 → CO2 + 2 H2O (ΔH = −891 k J/mol)

To make it possible to manufacture this gas from carbondioxide and water and high temperatures and some kind of atmosmagic catalyst.

**Comment by tortellinitony** [comment]
All hell will break loose if we try to merge chemistry and atmospherics.

**Comment by Pyko1** [comment]
But ultimately if this gets merged we really need people monitoring the controllers.

As this is bound to make atmos take more resources as it will have to spread every far evenly.
Which could became an issue in an event of mass farting.

**Comment by JohnGinnane** [comment]
@Pyko1 LINDA handles that already, this is basically just another gas it deals with

**Comment by gumner** [comment]
"EVERYONE,FART!! WE ARE DESTROYING THIS STATION!!!"

**Comment by JohnGinnane** [comment]
That's what I'd like to see, how much gas farting/superfarting actually produces because it's hopefully (realistically) very very small

**Comment by Pyko1** [comment]
yeah, but it will have to track one more thing, that is a lot more common than a plasma spill.
And it does start shitting itself if there are too much leaks all around.

**Comment by JohnGinnane** [comment]
Need to codecheck this but if all is well and this is approved we can merge, if server starts acting up we can revert and see if there's a better way to do it

**Comment by tortellinitony** [comment]
The only issue I had was when you fart in space, so I made it check if you're on a space tile before spawning any gas

**Comment by Pyko1** [comment]
yeah should just check how much resources atmos takes now and after merge for couple rounds.

**Comment by tortellinitony** [comment]
I can confirm that it works with gas mixers, gas filters, pipes, etc. although it registers as unknown on an analyzer like N2O does.

**Comment by JohnGinnane** [comment]
Should N2O be picked up by analyzer? Seems like it should, otherwise it's not a very good analyzer

**Comment by tortellinitony** [comment]
It says Unkown x% for trace gases.

**Comment by tortellinitony** [comment]
Handheld fart tank traitor item

**Comment by JohnGinnane** [comment]
Trace gases?

**Comment by SpankMasterson** [comment]
+1 if it works

**Comment by ghost** [comment]
N2O has always been the unknown gas.

**Comment by Pyko1** [comment]
I think its because N20 was added by someone else who did the original gasses and the whole unknown is because of sloppy job.

**Comment by Carbonhell** [comment]
Did you compile those templates?

**Comment by ghost** [comment]
i mean if it works sure thing
+1

**Comment by tortellinitony** [comment]
I compiled all of the templates, yes, and I could make N2O and Fart not unknown anymore, and I'll try that later. The equation pretty much just counts all of the oxygen, nitrogen, plasma, and CO2 and subtracts that from the total and calls it unknown.

**Comment by ArcLumin** [comment]
And Fartmospherics has nothing to do with farts as they are represented in the Encyclopedia Britannica, don't be a fucking faggot.

**Comment by ArcLumin** [comment]
Code looks good, merging

**Comment by Kierany9** [comment]
oh no

**Pull request merged**
