### PR TITLE
Removes the tesla(map wise)

### PR DESCRIPTION
**Pull request by Gandalf2k15**
Removes the tesla from the map. This will prevent not only crappy power gen op shit but will stop the lag when the tesla and singulo meet.

### CODE REVIEW

**Comment by ghost** [comment]
Kill tesla please

**Comment by calibraptor** [comment]
PR removing the tesla but not adding it to cargo.

Wow -11111111

**Comment by blobbernaut** [comment]
Crappy power gen ???

**Comment by blobbernaut** [comment]
No bad ganondalf stop this

**Comment by Gandalf2k15** [comment]
is crapgine

**Comment by blobbernaut** [comment]
No its best because if you lock it so it can't move you get a ton of balls

**Comment by dreamcrab** [comment]
add it in so you can order it from cargo, cargo tesla is best tesla

**Comment by Nebyab** [comment]
tesla is shit. Either add it to cargo or don't,either way this gets a +1

**Comment by Gandalf2k15** [comment]
two +1's.

**Comment by blobbernaut** [comment]
blease no

why is tesla shit?????

**Comment by blobbernaut** [comment]
nebyab said "the tesla is inherently better than the sing, and has no downsides is the core of the argument, it can't even get free on its own. There is no reason to use any other power source other than the tesla. That's horrific design, and as such it makes no sense for the tesla in its current form to be in the game, is the core of the argument" in coder chat 

+2 then

**Comment by Spacedong** [comment]
tesla generates so much more power than the other engines and is literally babby proof, REMOVE

**Comment by blobbernaut** [comment]
deport the tesla

**Comment by carlarc** [comment]
once, the tesla got loose. I got shocked from _more than a screen away, while the tesla was at it's weakest without a single ball, and without any way of knowing it_
**+**
**1**

**Comment by JohnGinnane** [comment]
Looks good. Did you test engineering to make sure everything still works?

**Comment by Gandalf2k15** [comment]
Yas

**Comment by JohnGinnane** [comment]
In that case merging

**Comment by Sarcalogo** [comment]
How does shit like this get merged yet me moving a pinpointer to the HOS office get denied..? Crazy!

**Pull request merged**
