### PR TITLE
Rotatium

### PR DESCRIPTION
**Pull request by TDcoolguy300**
Adds Rotatium, a chemical that causes the person who consumes it to rotate their view, causing distorted shit like the proc would do.

### CODE REVIEW

**Comment by TDcoolguy300** [comment]
Also, made with Teslium, Mindbreaker, and Spacedrugs-Neurotoxin(Not the drink)

**Comment by Chronitonity** [comment]
chaaaaangelog

**Comment by TDcoolguy300** [comment]
Changelog done

**Comment by Chronitonity** [comment]
May want to add that Calomel purges the effect from you

**Comment by TDcoolguy300** [comment]
Done

**Comment by ghost** [comment]
is the shooting and shit still bugged, this stuff crashed my byond when the rotation stuff was happening

**Comment by Crystalwarrior** [comment]
:-1: if crashes/weird shit aren't fixed yet
I'd rather have the view rotated in such a way that all sprites face the correct way

**Comment by TDcoolguy300** [comment]
Then this will never exist then Crystal, this rotate's the client in a way that Autosmoothing will not work for the effected client. This will not cause server crashes either because this is effect is entirely client based.

**Comment by Crystalwarrior** [comment]
I'm talking about client crashes which already have been reported.
I seriously don't think this weird visual effect that fucks with the client's perception and destroys his view in a way that can even cause a client crash is worth it in this case.

**Comment by Nebyab** [comment]
As long as it doesn't crash people I'm good for this even though the rotation really bothers me

**Comment by danhibiki** [comment]
We can do a test run of it, but if we have mass reports of it causing crashing, we're gonna have to back out.

**Comment by TDcoolguy300** [comment]
I'm cool with that one, this is easy to revert as long as nobody fucks with the dms too much

**Pull request merged**
