### PR TITLE
You can now stop pulling objects by control clicking

### PR DESCRIPTION
**Pull request by ghost**
An old feature we used to have which was really handy IMO.
Code was lifted from here.
https://github.com/AtlasStation/AtlasStation/blob/master/code/_onclick/click.dm#L222

### CODE REVIEW

**Comment by Carbonhell** [comment]
code is ok

**Comment by Nebyab** [comment]
i misread this and was angry

but its alright

**Comment by GenericGoose** [comment]
best thing ever

**Comment by Spacedong** [comment]
yeah finally fuck

**Comment by Spacedong** [comment]
fix the fucking title gosh can you just take an english class already

**Comment by calibraptor** [comment]
+1 this is a necessity

**Comment by Spacedong** [comment]
「Ｃｌａｒｉｆｙ」

**Comment by ghost** [comment]
Stop != cease

**Comment by Kierany9** [comment]
You made it even less clear

Good job

**Comment by Voratius** [comment]
kek

**Comment by dreamcrab** [comment]
very cool very swag i like it

**Comment by ghost** [comment]
neb and team +1'd it.

**Pull request merged**
