### PR TITLE
Buffs powerfist and removes the (tiny) charge time, also slightly lowers the price

### PR DESCRIPTION
**Pull request by Weisyl**
This buff was because many players were reporting the powerfist as being fairly underpowered compared to other weapons.

### CODE REVIEW

**Comment by Weisyl** [comment]
Why the fuck does this have conflicts I literally updated my fork right before doing this.

**Comment by Weisyl** [comment]
OK conflicts fixed.

**Comment by danhibiki** [comment]
We should watch the power fist because we're changing cost and damage at once, but other than that I'd approve it.

**Comment by SplergeBucket** [comment]
sure i guess

**Comment by Weisyl** [comment]
I was told to let a head or someone like that merge this, so uh yeah.

**Pull request merged**
