### PR TITLE
Revert "Immortalises fluxcapacitor1337 into the game."

### PR DESCRIPTION
**Pull request by SpankMasterson**
Reverts HippieStationCode/HippieStation13#3242

### CODE REVIEW

**Comment by ghost** [comment]
Wat

**Comment by yobob591** [comment]
he screams until he dies pls fix

**Comment by ArcLumin** [comment]
There was no cap to the screams or cooldown so he constantly screamed. forever.

**Comment by doobiedoo23** [comment]
That's perfect and exactly what flux deserves for being a raging fag

**Comment by KittyKathy** [comment]
This is hilarious and i saw this coming too, I did not actually thing you guys would merge that meme PR. 
I'm calling it that was the best PR of 2017.

**Pull request merged**
