### PR TITLE
Changes bartender 5tc shotgun shell to a shotgun shell box of assorted flavours

### PR DESCRIPTION
**Pull request by KayeArray**
Box contains 2 buckshot, 1 stun slug, 2 dragonsbreath and 1 bioterror dart so it's now more in line with other ammo items.

### CODE REVIEW

**Comment by KayeArray** [comment]
wait what nvm

**Comment by ghost** [comment]
remember to never commit to master

**Comment by ArcLumin** [comment]
he didn't though. He was on the banthebantzbartender branch

**Comment by ghost** [comment]
okay never mind he fucked up

but seriously if you commit to master you're fucked

**Pull request closed without merging**
