### PR TITLE
Sharkmen

### PR DESCRIPTION
**Pull request by ghost**
it's HERE lads

### CODE REVIEW

**Comment by ghost** [comment]
Come on guy, don't make the head face forwards, you make it look straight up and have no neck, the current way just looks stupid.

**Comment by Pyko1** [comment]
but that would need a whole new mask/eyewear/hat icons for them

**Comment by ghost** [comment]
Or just don't have them wear able and say they can breath in space.

**Comment by Pyko1** [comment]
also why there is changes to gitignore?

**Comment by ghost** [comment]
@Pyko1 I made an icon file that I was using for sharkmen edits, I can remove it if necessary

**Comment by doobiedoo23** [comment]
Screenshots?

**Comment by ghost** [comment]
Just cleaned up the icons a bit and changed the eyes for the side female shark sprites

http://puu.sh/nF7ZW/c89c62cb20.png = male sharks

http://puu.sh/nF828/29abcf1cd4.png = female sharks

**Comment by doobiedoo23** [comment]
holy fuck

**Comment by Kierany9** [comment]
What the fuck is this, Citadel? Keep this furry shit away from here.

**Comment by ghost** [comment]
> furry
> 
> mammals
> 
> sharks
> 
> shark != mammals

**Comment by Spacedong** [comment]
this is really kek, also better and more higher quality than noosemen, I'd play one and make a shark den in the pool 10/10

**Comment by ghost** [comment]
@spacedong thank you lad, carppeople are next

**Comment by Nokington** [comment]
What the fuck is that. This is almost worse than noosemen. They look so stupid

**Comment by ghost** [comment]
@Nokington what should I do to improve them lad

**Comment by Nokington** [comment]
What nienhaus said.

**Comment by ghost** [comment]
maybe

**Comment by ghost** [comment]
need more input from other lads pl0x

**Comment by Zadeon** [comment]
The front and back views of the head don't look so good. There is no real blending of the head to the body, it just looks like a sign is pasted on-top of their head. 

Also their snout from the sides looks like they have a very big jew nose instead of a snout.

**Comment by ghost** [comment]
Yeah, the head outline should probably be more blended at the bottom

lots of complaints about the snout on the sides, will fix that

**Comment by ghost** [comment]
Here's an example of what could be done, that I personally think looks better.
z4jy6ko

**Comment by Pyko1** [comment]
With that it cant use any eyewear/hat/mask withotu lookign really crappy, and making it not need to use em isn't really a solution either, and I doubt anyone is going to want to remodel all head equipment for 1 race.

**Comment by ghost** [comment]
@Nienhaus holy shit, could I use that icon?

Also that is a problem @Pyko1 but maybe changing the pixel_y of headgear for sharks would help? Either way, I could do some experimenting on the new icon if Nienhaus is willing to let me use it

**Comment by ghost** [comment]
All my sprites are free use unless stated otherwise. https://www.dropbox.com/s/kojjcmol6oc11ah/Shark%20Person.dmi?dl=0 Plus I have no use for it.

**Comment by Pyko1** [comment]
You are going to need some serious code magic to get all hats/masks and eyewear to work with by just moving and rotating them.

**Comment by Nebyab** [comment]
their heads make me want to die inside, but if they stop causing me to want to kill myself, then i'd be fine with it

**Comment by calibraptor** [comment]
They look pretty awful

**Comment by carlarc** [comment]
~~Make sharkmen-only stuff, look at how the highrp servers ended with that!~~

**Comment by ghost** [comment]
I've decided to use Neinhaus' icons, but I'll need to edit the shark eyes or make some special shark icons for headgear

**Comment by ghost** [comment]
How do you laddies like the scream sound, by the way? It's the first second of [this](https://www.youtube.com/watch?v=_xvmuZAqXtE)

**Comment by ghost** [comment]
This is probably going to take a lot longer than I wanted and I might as well add shark meat and shit as well. I could use the carp meat sprites.

Going to close this PR until I figure some things out.

**Pull request closed without merging**
