### PR TITLE
Plasma Rifle

### PR DESCRIPTION
**Pull request by KayeArray**
Adds a Plasma Rifle for ERT and Deathsquad Commanders (fancy blue and berets).
Also includes bad sprites made by me because I suck at drawing.
I would put more here but it's all in the changelog and code.

### CODE REVIEW

**Comment by KayeArray** [comment]
I do love conflicts, I have no idea why it's conflicting because I just updated my fork but I'll sort em out later

**Comment by ghost** [comment]
Your DMI files are out of date.

**Comment by KayeArray** [comment]
That's going to be fun to sort out

**Comment by KayeArray** [comment]
Well that's rather strange, a quick comparison of the two shows absolutely no difference so I don't see how there is a conflict, damn it git!

**Comment by KayeArray** [comment]
might be easier if I close this and try again

**Pull request closed without merging**
