### PR TITLE
Massive Chemistry Update MCU

### PR DESCRIPTION
**Pull request by lcass**
This is a complete update to chemistry , a few things need to be listed out.
1: This will not mess with trek chem , this stays as is.
2: The chemicals can be dangerous so admins may want to look out specifically in the new area.
3: This chemical update is used for the science department.

So what is added?
Lots of new machines , three which are not dangerous and 2 which can kill making the more dangerous chemicals much harder to produce. Lots of new medical chems , some which will be sought after for curing viruses and some that will reinstate the science medical links. Medical isn't as fun as it could be, because of this lots of new chemicals that are dangerous are added. This should spice up some traitor rounds , for instance the chemical emitrium causes people to shoot out emitter beams, great for destroying a crowd! An entire new department area is added , the chemical laboratory at the south of science includes all the machines in testing areas and is coated in fire locks to prevent spreading. No new jobs are added so lots of people can join in. Have fun with this.

### CODE REVIEW

**Comment by ghost** [comment]
### There are a few non-technical issues with this PR
- You need to squash your commits.
  - http://eli.thegreenplace.net/2014/02/19/squashing-github-pull-requests-into-a-single-commit
- You need to run the `mapmerge` tool
- I'm missing a proper `nanoui` or `htmlui` for all machines.

### and a few technical code related issues
- it seems that you are never removing `reagents` from `processing_objects`
- there are no spanclasses in some of the machines, could you add those?
  - ex: `user << "You add the beaker to the machine!"`
- you removed `BEGIN_PREFERENCES` from the dme.
- you removed `BEGIN_INCLUDE` from the dme.
- you are adding all instances of `datum/reagents` into `processing_objects` how about creating a special subtype to prevent more un-needed strain and memory usage?
- i'm missing `emag_act` for some machines, how about we disable safeties when emagging?

### extra brainfarts.
- the machines can't be constructed, or deconstructed, maybe a cool thing to have?
- the machines can't be upgrades,

**Comment by ghost** [comment]
Can @Nokington look at this, and yell if we have merge permission from the heads?

**Comment by Nokington** [comment]
Ill look at it later today.

**Comment by ghost** [comment]
@Nokington Cool, just don't merge it.

**Comment by Kokojos** [comment]
I need to take a final look at the map and personaly won't accept it withouth a full chem guide.

**Comment by lcass** [comment]
it seems that you are never removing reagents from processing_objects
there are no spanclasses in some of the machines, could you add those?
ex: user << "You add the beaker to the machine!"
you removed BEGIN_PREFERENCES from the dme.
you removed BEGIN_INCLUDE from the dme.
you are adding all instances of datum/reagents into processing_objects how about creating a special subtype to prevent more un-needed strain and memory usage?

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
All fixed , the machines are constructable just forgot to add it to the commit :/ emags im working on.

**Comment by ghost** [comment]
@lcass did you commit that? haven't seen it.

**Comment by lcass** [comment]
not yet , im just sorting out your commit single stuff

**Comment by Nokington** [comment]
Any updates on this?

**Comment by Iamgoofball** [comment]
you really really should of ported goonchem addiction code from tg

it's cleaner and standardized

**Comment by lcass** [comment]
GO AWAY GOOF WE DON'T WANT YOUR SHITTY CHEM HERE.

**Comment by lcass** [comment]
also we are waiting on erik. If hes not able to do it tommorow ill finish it.

**Comment by lcass** [comment]
Also , apologies for the earlier comment(which has now been removed thank god) , It's late and I thought you were just promoting your goofchem here. Didn't see you say addiction , I will happily port that as I have tested it and it works well.

**Comment by Iamgoofball** [comment]
i'd reccomend grabbing the overdose code too because you'll probably want overdose as well

**Comment by SplergeBucket** [comment]
Merge Conflicts, also we gotta test this out a bit before merging.

**Comment by lcass** [comment]
I cri

**Comment by lcass** [comment]
moved into another PR due to horrendous merge issues.

**Pull request closed without merging**
