### PR TITLE
Adds spacedong to daki, removes shit waifu

### PR DESCRIPTION
**Pull request by ghost**
~~she's like sixteen anyway~~

### CODE REVIEW

**Comment by Spacedong** [comment]
we've reached a new level of shitposting

**Comment by TDcoolguy300** [comment]
Beyond the whole "LOL MEMES" portion of this PR, the main issue is that Spacedong doesn't have a Dakisprite, meaning this turns the Daki invisible when you attempt to switch it's icon to that. This PR is ultimately more broken.

**Comment by ghost** [comment]
okay since nobody knows what spacedong looks like i'm closing this until we get a spriter

i'm making a new request to comment in that this is the case

**Comment by GenericGoose** [comment]
@tabsiforu spacedong looks like CIA, can confirm
also add the big guy and dr pavel

**Comment by Pyko1** [comment]
http://thumb9.shutterstock.com/display_pic_with_logo/3414095/334842896/stock-vector-smiling-nerd-big-teeth-334842896.jpg

**Pull request closed without merging**
