### PR TITLE
Map Fix-A-Ton

### LINKED ISSUE #2796: the sec maint doors are able to be opened by anybody once maintenance restrictions are set to off
https://vgy.me/ButDGB.png

happens to this door and the one by the office, anyone can waltz right in

### LINKED ISSUE #2797: Dumbfuck Calibraptor got rid of the Announcement System in the HoS office
And the newscaster.

### LINKED ISSUE #2815: There are no AI holopads in all of security.
Minor oversight, but it can use some in namely the armory and the main security office.

### LINKED ISSUE #2871: HoS office missing the keycard authentication device
calibraptor is a shit mapper edition

### LINKED ISSUE #2963: Extra Piping at 119,175,1
TD was showing me the server logs and there was a piping error there. Tracked it down to 119,175,1, where I found that there was double piping at this tile.

http://puu.sh/rvUPv

### LINKED ISSUE #3042: A number of areas are inaccessable by the destonation tagger
Title. Tested security and chapel, both had the package returning.

### LINKED ISSUE #3062: stunbatons still missing from sec lockers because calibraptor never used the right locker type when making the map
title

### LINKED ISSUE #3063: this area is called Security Maintenance despite not being anywhere near fucking security
https://vgy.me/V4qV3P.png

its in the goddamn public Infirmary near Arrivals, why is it sec access only

### PR DESCRIPTION
**Pull request by TheOneAndOnlyCreeperJoe**
Fixes #2871 by adding a keycard authentication device in the HoS office.
Fixes #3063 by making the area the door is on into the infirmary area and changing the access requirement to the default maintenance one.
Fixed #2963 by removing the extra piping at 119,175,1
Fixed #2815 by adding holopads to the Warden's Office, HoS office, office room, locker room, security lobby, outside the two solitary cells, perma shuttle console, infirmary, interrogation, execution and security lobby office. Purposely skipped the showers because it's the fucking showers, don't want AI ERP.
Fixed #2797 by adding the announcement system to the HoS office.
Fixed #2796 by changing the area of the maintenance doors to Security.

Map merge failed on me despite me executing the steps properly. Pictures will be up soon, trademark.

**UPDATE:**
Fixed #3062 by giving the right sec lockers instead of the normal ones and
Fixed #3042 by setting up a proper disoposal loop.

Also did the following:
-Spread out the holopads
-Added a few more newscasters and made them SECURITY newscasters instead of normal ones
-Hos has a light switch
-HoS has a Vault.
-HoS has a station intercom.

Pics in a moment.

### CODE REVIEW

**Comment by TheOneAndOnlyCreeperJoe** [comment]
pic1
pic2

**Comment by Pyko1** [comment]
Update/rebase what ever to to get your branch up to date, then.

Unedited map -> prepare -> edit -> save -> merge -> commit

Note that you only prepare once, before the first edit, and merge every time before committing with new edits to map file.

**Comment by Spacedong** [comment]
oof thanks nig

**Comment by TheOneAndOnlyCreeperJoe** [comment]
@Pyko1 Like I said earlier, the Map Merger tool cuck'd. Just like I should, I prepared the maps, made the changes, ran the map merger then put it on Github, but it just isn't doing it for me.

**Comment by Pyko1** [comment]
There is a reason tho why execution has no AI coverage, so I doubt it should have holopad either.

**Comment by TheOneAndOnlyCreeperJoe** [comment]
They can't use it trough the static though.

The amount of holopads... eck; I just wanted to make sure that the AI could yell about injustice and their lawset to Security when they did even the smallest attempt of doing their jobs. Having this many isn't going to hurt.

**Comment by Hackole** [comment]
Looks good

**Comment by Pyko1** [comment]
I see no real issues either, Only minor complaint is the holopads as the amount seems excess as AI can move rather huge area around them, so no need to have them as close to each other. Also pretty sure that interrogation pad can be used to peek in to execution.

But nothing that bad that needs to be definitely changed/fixed, but if you do happen to make changes maybe toss a light switch to HoS office as well other rooms with their own Areas that have lamps.

**Comment by Pyko1** [comment]
Would be nice if you could also see in to https://github.com/HippieStationCode/HippieStation13/issues/3062 while you are on it.

**Comment by Pyko1** [comment]
Also while on it would be super if you could add the missing mail sorters/disposal pipes around sec. https://github.com/HippieStationCode/HippieStation13/issues/3042

**Comment by TheOneAndOnlyCreeperJoe** [comment]
I'll work on both bugs, as well as spreading holopads and adding a light switch cuz why not. Though I will likely end up hitting my head on mail sorting a bunch of times as I've never done it before.

**Comment by Pyko1** [comment]
Mail sorters are pretty easy.

You will just have to make disposals loop pass through the security, instead of just having 1 pipe lead out connect to the actual disposals loop. Then you just add sorter pipes, which are kind alike manifolds that that divert mail packages with correct id to side. Also remember to pay attention on what direction the sorter sends thrash when coming from the sorter side.

Also you will need to give the correct id to the sorter.
```
0 Waste
1 Disposals
2 Cargo Bay
3 QM Office
4 Engineering
5 CE Office
6 Atmospherics
7 Security
8 HoS Office
9 Medbay
10 CMO Office
11 Chemistry
12 Research
13 RD Office
14 Robotics
15 HoP Office
16 Library
17 Chapel
18 Theatre
19 Bar
20 Kitchen
21 Hydroponics
22 Janitor
23 Genetics
```

**Comment by JohnGinnane** [comment]
I thought I asked, but is it wise/safe to merge this if it didn't use map merger?

**Comment by TheOneAndOnlyCreeperJoe** [comment]
It just means it's harder to check for changes snuck in or any stuff that should not be there like step_x and step_y. For the rest there's no technical difficulties.

Even then though don't merge yet until I fix the things mentioned above

**Comment by ArcLumin** [comment]
Yeah, I've done mapping changes without mapmerge. Works fine so long as you don't fuck up.

**Comment by TheOneAndOnlyCreeperJoe** [comment]
pic3
pic4

**Comment by Pyko1** [comment]
should be ok map wise, or at least i cant see anything that should break shit up really bad.

**Comment by ghost** [comment]
ye +1

**Pull request merged**
