### PR TITLE
Lots of new sound effects added + ambient system rework

### PR DESCRIPTION
**Pull request by Crystalwarrior**
This adds a bunch of miscellaneous sound effects.
Later on, this branch will also decrease filesize of most of the /tg/ sound effects by turning them into mono and exporting them as quality-0 OGG files.
Ambient loops have also been added to various areas like most spacewrecks and space itself.
Ambient system received a rework to update per-turf enter instead of per-area for the sake of space ambient loop.

Most of the soundeffects are pulled from Atlas. Atlas' sound effect replacements for existing sounds will be on a seperate branch for easy reverting just in case

### CODE REVIEW

**Comment by Chronitonity** [comment]
Cant tell if theres a changelog here because im on my phone. If there isnt, put one there

**Comment by AliiTea** [comment]
Won't turning them into mono ruin any atmosphere the sounds have?

**Comment by Foosili** [comment]
Can you make some kind of preview of a few of these sounds?

**Comment by danhibiki** [comment]
@Nexendia- I assume that D3D handles the stereoscopic sound, so a mono soundbite shouldn't be that big of an issue I don't think

**Comment by Crystalwarrior** [comment]
Stereo doesn't even seem to be supported by the engine, so all it does is add to the file size.

**Comment by Crystalwarrior** [comment]
Alright, this is ready for merge.

**Comment by Nebyab** [comment]
this sounds like a bunch of scary words so I'll just say okay

**Comment by Weisyl** [comment]
We should do a test server run of this before merging it.

**Comment by danhibiki** [comment]
@crystal are you sure? I'm fairly certain SS13 uses D3D for audio and I thought it used 3D sound. Using mono sound files shouldn't affect that, seeing as its all simulated codec side.

**Comment by TDcoolguy300** [comment]
BYOND does use a Simulated 3D sound system, as Dan says. Mono sounds should still work fine,

**Comment by Chronitonity** [comment]
Adds about 8.8 MB to the game, Crowbar and Wrench sounds are pretty ech imo.

**Comment by Crystalwarrior** [comment]
Will fix both in a jiffy, wrench sound is too quiet and needs a bit more impact, as well as crowbar.

**Comment by Crystalwarrior** [comment]
FINALLY MERGE-READY!
Includes sound optimizations, too. Most of the sounds have been reduced in filesize.

**Pull request merged**
