### PR TITLE
Fixes: Debrain objective;Constructs becoming deaf/blind/stuttering/druggy; Artificiers getting muted for spamming

### PR DESCRIPTION
**Pull request by Carbonhell**
Fix imported from tgstation

### CODE REVIEW

**Comment by Carbonhell** [comment]
Closes #547

**Comment by nalarmg** [comment]
This doesn't break brains being hidden in things, like lockers, recursive containers, etc?

**Comment by Carbonhell** [comment]
I tested by putting the brain into a box,and it worked. If you're on the same tile of the dropped brain it won't work,so it only works if you have the brain in your contents.Also this is the code that both tg and bay use, anyway

**Comment by Chronitonity** [comment]
@Carbonhell Wheres your changelog on either of these issues compadre

**Comment by Carbonhell** [comment]
Closes #74

**Pull request merged**
