### PR TITLE
Minor Update to Table Recipes

### PR DESCRIPTION
**Pull request by JohnGinnane**
Changed two recipes to require 5 duct tape instead of 6
1. Makeshift Armour
2. Knife gloves

### CODE REVIEW

**Comment by JohnGinnane** [comment]
As requested: https://github.com/HippieStationCode/HippieStation13/issues/2040

**Comment by Kokojos** [comment]
:+1: Totally okay with this PR

**Comment by Carbonhell** [comment]
Seems more like a bugfix than a balance issue but i am not sure, @Nebyab what's your opinion
oh yeah code is good

**Comment by JohnGinnane** [comment]
Is there a way I should have classified it as a bugfix?

**Comment by Carbonhell** [comment]
done

**Comment by JohnGinnane** [comment]
Thank you

**Comment by Nokington** [comment]
:+1:

**Comment by myontasm** [comment]
Ye looks fine

**Comment by Carbonhell** [comment]
code's ok,merging

**Pull request merged**
