### PR TITLE
Moves Grounding rods into secure storage

### PR DESCRIPTION
**Pull request by Chronitonity**
Makes it super easy to make infinite power elsewise. This way atleast requires a teensy bit of work.

http://puu.sh/m3iPa/22deefb586.png

### CODE REVIEW

**Comment by Iamgoofball** [comment]
> didn't map merge

top kek/10

**Comment by Chronitonity** [comment]
man its 3 am i aint got time for that shit

**Comment by Foosili** [comment]
im for it

**Comment by Iamgoofball** [comment]
:-1:
Here's whats gonna happen
Players set up tesla, forget grounding rods
All die from shock bounces 
Round ends from other shit
Players set up singularity instead of tesla and never again touch tesla because it takes new effort and they're too lazy

**Comment by danhibiki** [comment]
I think goof has a point, but I also think we should make this change later, once the engine has more familiarity with the player base.

**Comment by Foosili** [comment]
I think waiting on it for players to be more familiar with the engine is fine but the tesla engine can't be as EASY to use as it is now imo

**Comment by SplergeBucket** [comment]
Maybe a trial period for this after a while.
till then :-1:

**Comment by danhibiki** [comment]
Its just that its a totally new engine, and we can actually compare this to the supermatter. The supermatter saw extremely limited use, and a lot of that was not knowing how to properly operate it. With the rods already being in place, this will stand as a foothold for people to start learning it, rather than becoming immediately turned off

**Pull request closed without merging**
