### PR TITLE
Makes RCD matter amount more accurate

### PR DESCRIPTION
**Pull request by ArcLumin**
When matter cartridges were buffed from 40 matter to 50, they forgot to change the max amount it can hold from 160 to 200, meaning 40 units are wasted on the 4th cartridge. This fixes that. 

See also https://github.com/HippieStationCode/HippieStation13/issues/2780

### CODE REVIEW

**Comment by ghost** [comment]
Prices of RCD things have went way down.
To be honest, RCD should have a lower max ammo that's divisible by 50. Say like 100?
https://github.com/HippieStationCode/HippieStation13/pull/2633

**Comment by ArcLumin** [comment]
Well, the way I see it;
100 would be a serious nerf to RCDs, as CMCs are large items that don't fit in boxes, you have a very limited amount of space for them. Before, you could fit 4, now it's 3 and a partial. Lowering it to 2 is huge. RCDs, currently, are pretty nerfed in our meta; they can't deconstruct rwalls where diamond drills and sonic jackhammers can, sonic jackhammers can instantly break down walls faster than you can say "what", etc. And now we have inflatable walls which makes its wall making abilities far less useful. Right now, it's fairly underused. A buff as slight as this is fine

**Comment by ghost** [comment]
I've only ever seen sonic jackhammers and drills from finding them in mining rather than RnD but yeah I understand what you mean.

But still,
Floors have went from 2 to 1.
Decon floors have went from 33 to 5.

Walls have went from 16 to 3.
Decon walls have went from 26 to 5.

Airlocks have went from 16 to 10.
Decon airlocks have went from 32 to 20.

Grills have went from 4 to 2.
Decon grilles have went from 4 to 2.

Windows have went from 8 to 2.
Decon windows have went from 16 to 2.

RCDs are waaaaay cheaper to use.

**Comment by ArcLumin** [comment]
I also included mech drills in that. STILL, this is a pretty minor thing. I don't see too much issue with doing a slight buff rather than a nerf because buffs > nerfs around here, shit's a slippery slope. Right now, RCDs are still underused, this should help rectify that, at least in a small degree

**Comment by GenericGoose** [comment]
only diamond mech drill can drill rwalls
and that requires diamonds
RCDs are pretty low level for research

**Comment by KayeArray** [comment]
Maybe nerf the normal RCDs and give the CE one of the combat RCDs used by the ERT.

**Comment by Pyko1** [comment]
The sheer fact that rcd can take down a door makes it really strong, and the ridiculous ammo capacity makes you just carry spare RCD's instead of matter cartridges.

I would rather see it hold 50 and make the matter cartridges smaller.

Also please no start of the round combat RCD's, that will just mean holes everywhere in cap office/armory/brig/AI core. There should be at least minimal effort to take down rwalls.

**Comment by KayeArray** [comment]
Ah I didn't realise they could break rwalls.

**Comment by ArcLumin** [comment]
@GeneralGoose the mining ripley has a 25% chance of spawning with a diamond drill, and 80% of the time the miners just fuck around on the station with it instead of mining

Would everyone be fine if I reduced the size of CMC's and lowered RCD amount to 100?

**Comment by ghost** [comment]
Yeah that'd be fine IMO.

**Comment by Spacedong** [comment]
why did you close my issue on this it was a minor issue but still an issue

**Comment by ghost** [comment]
Because it's not an issue? It doesn't like consume the ammo, it just rejects it which is intended in the code.

**Comment by Spacedong** [comment]
its bad game design, therefore an issue

**Comment by ghost** [comment]
The issue tracker is for bugs.

**Comment by Spacedong** [comment]
>bugs
>there are more than 3 balancing issues up

get fucked

**Comment by SplergeBucket** [comment]
issue tracker should be able to be used for balancing as well
i've done it
as long as it isnt some bullshit recode this entire gamemode shit

**Comment by SplergeBucket** [comment]
also im fine with going along what mcbaw/arc have come to

**Comment by Gandalf2k15** [comment]
Just saying the RCD carts will only fill the RCD up and leave whats left inside the cart. So if you have a cart with 40U in and you have an rcd with 92/100u it will take 8 and leave the cart with 32. This aint a problem

**Comment by Kokojos** [comment]
Changelog please and this is good to go.

**Pull request merged**
