### PR TITLE
Buffs Firefighter

### PR DESCRIPTION
**Pull request by ArcLumin**
It's supposed to be better, not an inferior version of the ripley

### CODE REVIEW

**Comment by ghost** [comment]
> no changelog

lack of dignity but okay +1

**Comment by ArcLumin** [comment]
In the middle of making it, hold your ass

**Comment by doobiedoo23** [comment]
sure why the FUCK not +1/3

**Comment by Kokojos** [comment]
fire fire fire higher higher higher +1

**Comment by ArcLumin** [comment]
I see

So we good?

**Comment by ghost** [comment]
n o i c e
+1/3

**Comment by ArcLumin** [comment]
Wait, am I retarded? Is damage absorbtion not armor, but actually the percentage of damage you take when hit?

**Comment by ArcLumin** [comment]
Accidentally mistook damage absorption as armor. It has been fixed

Seriously though, who the fuck codes a damage mitigation type as a multiplier of the damage you take rather than a divisor like 90% of the other code we got?

THANKS /TG/

**Comment by ArcLumin** [comment]
Good to merge?

**Comment by Nebyab** [comment]
sure

**Pull request merged**
