### PR TITLE
Wild West improvements, new AKS-740U, new ALC sprites

### PR DESCRIPTION
**Pull request by Weisyl**
Added the new AKS-740U carbine. It is similar to the AK-922, but fires the lower caliber 5.45x39mm round.
New sprites for the Automatic Laser Carbine. Credits to Dr. / Sgt. Fragg for the sprites.
Polished up the Wild West away mission to give it some more detail. Also added a C05-R, Luger, Automag, Mac-10, and AKS-740U to the map. Additionally, fixed the invincible windows.

### CODE REVIEW

**Comment by Foosili** [comment]
Again, pictures for these items? What kind of damage does the AK-740U do?

**Comment by TDcoolguy300** [comment]
Where the hell is the FUCK label

**Comment by Weisyl** [comment]
AKS-740U Does 20 damage per shot and is only available on the Wild West away mission for now.
Pictures:
AKS-740U and New Auto. Laser Carbine: http://puu.sh/lHv4R/7413f3150c.png

Polished Wild West: 
Bar: http://puu.sh/lHvuA/28f50ac60e.png
Mining Dock: http://puu.sh/lHvsc/54ec79ae33.png
Main Town - Overview (Relatively unchanged apart from the non-invincible windows, some new weapons, and the bar): http://puu.sh/lHvqJ/ddda204840.png    http://puu.sh/lHvrq/de71c982e1.jpg

**Comment by Foosili** [comment]
Yeah I'm fine with this then :+1:

**Comment by danhibiki** [comment]
I guess my only suggestion would be to make that bar sign a unique one, but its an incredibly nitpicky thing to hold back the whole PR for, so I'm totally cool with it. Having something unique, or just taking one of the signs away from the stations choices (worst option) would work.

**Pull request merged**
