### PR TITLE
Undos ghetto chem nerf

### PR DESCRIPTION
**Pull request by ghost**
It got merged by mistake in gandalf's PR.

### CODE REVIEW

**Comment by trifornt-tinfornt** [comment]
Fuckin' Gandalf.
:+1: ghetto chem nerf was dumb

**Comment by ghost** [comment]
I still stand by ghetto chem nerf being required, but it shouldn't have been merged.

**Comment by trifornt-tinfornt** [comment]
Yeah, but I think the chem dispenser had far too few options, and you could make almost nothing with it. It then became a catbeast's personal lube dispenser rather than a legitimate device you could use to make ridiculous chems.
It should get reverted, or at least get more options in there (like potassium) because otherwise it serves no purpose other than valids getting their lube to annoy people.

**Comment by ghost** [comment]
I personally think there should be a grinder in maint garden so you can homebrew chems and use the chem dispenser to supplement it.

**Comment by Spacedong** [comment]
no, keep it as a portable chem dispenser with barely any chems, just enough to make some ointment or bicaridine, doesn't the ghetto lab already have a grinder anyway

**Comment by KayeArray** [comment]
#makeghettochemgreatagain

**Comment by Spacedong** [comment]
this is fucking stupid and babby mode, you can get all the chems you need from plants grown in garden maint or the public garden, or fuck, just break into chemistry, get good

**Comment by ghost** [comment]
I still stand by that ghetto chem shouldn't have a full power chem machine.
But this is still required because the nerf was merged WITHOUT headmin approval. In an unrelated PR.

**Comment by Nebyab** [comment]
why is this not merged

fix your font github jeez

**Comment by JohnGinnane** [comment]
@McBawbaggings I'm looking at the file for https://raw.githubusercontent.com/HippieStationCode/HippieStation13/5462010e5bcc8a61ad5618ffd0f04f07eeb570b0/_maps/map_files/TgStation/tgstation.2.1.3.dmm and I see it already has that? Can you tell me which PR was merged that included the change?

**Comment by ghost** [comment]
https://raw.githubusercontent.com/HippieStationCode/HippieStation13/master/_maps/map_files/TgStation/tgstation.2.1.3.dmm
Check line aqA

**Comment by JohnGinnane** [comment]
Ah, I must've been looking at the wrong file. Merging as it's a **fix for unintentional map change**

**Comment by ArcLumin** [comment]
I've been throwing around the idea of taking out a few key chems from the dispenser, but putting in a grinder. Removing: iron, carbon, silicon, silver, sugar, water, and welding fuel, as all of those can be aquired via use of grinders in at least minor amounts. Possibly stable plasma too.

**Pull request merged**
