### PR TITLE
Adds Big Papa's clothing and pimp stick to autodrobe

### PR DESCRIPTION
**Pull request by McHatters**
Big Papa's zoot suit, zoot hat, and pimp stick are now available from the autodrobe! The pimp stick has the same stats as the cane, with a slightly higher force of 7 to account for its diamond tip.
2nd try, hope this one can be pulled without any sort of problem this time.

### CODE REVIEW

**Comment by McHatters** [comment]
have some pics by the way
image 
image
image
image

**Comment by Chronitonity** [comment]
Pretty good looking :+1:

**Comment by danhibiki** [comment]
Sure

**Comment by McHatters** [comment]
anyone know how to add a changelog update?

**Comment by Lawligagger** [comment]
Looks nice

**Comment by McHatters** [comment]
oh fuck man I was gonna add the changelog thingy to this but oh well

**Comment by danhibiki** [comment]
i wait for no man

**Comment by McHatters** [comment]
I'm gonna make a new PR solely for announcing Big Papa to the masses

**Pull request merged**
