### PR TITLE
Fixes Medical being too difficult to break into.

### PR DESCRIPTION
**Pull request by collinxchu**
Fixes https://github.com/HippieStationCode/HippieStation13/issues/403

Several locations in medical now are more easy to bust into. Most
notably;

http://puu.sh/joQxs.png The front desk
http://puu.sh/joQzb.png Maintenence
http://puu.sh/joQEp.png Medical storage and the morgue
http://puu.sh/joQFw.png And a minor change to virology.

Removed those rwalls on the outer break room (really, what are you
protecting with those?)

http://puu.sh/joRpk.png As a bonus, more public meds near medical to deter people wanting to break in to begin with.

### CODE REVIEW

**Comment by Chronitonity** [comment]
:+1:

**Comment by Nokington** [comment]
DNM because it is a feature and doesn't need fixing.

**Comment by collinxchu** [comment]
Game balance is important - slapping 'feature' on everything that exists in the game as a reason to not merge it will lead to an unbalanced game. It's still an issue at the end of the day.

**Comment by Chronitonity** [comment]
Yeah, feature would imply its adding or changing a function to the game, you're better off tagging it 'balance' or something like that.

**Comment by WhiteFox08** [comment]
We should also check with the community and get their opinion before meging this.

**Comment by Nokington** [comment]
The community is the reason it was put in.

**Comment by Chronitonity** [comment]
Do you mean because they broke in every round or what

**Comment by Nokington** [comment]
These http://www.hippie-station-13.com/forums/viewtopic.php?f=4&t=1578&p=8301 http://www.hippie-station-13.com/forums/viewtopic.php?f=19&t=1985 and the complaining/ahelps about people breaking in etc.

**Comment by Chronitonity** [comment]
Just skimming those posts neither of them mention putting R-walls all around medbay to make it a fortress. One addresses electric windows, which is a much better alternative to reinforcing walls around medbay, and the other puts sleepers in the lobby, which this PR doesn't even address so why bring it up

**Comment by WhiteFox08** [comment]
Did we do a poll or something

**Comment by collinxchu** [comment]
This PR simply changes the interior of medical so that it isn't a fortress and has clear break-in points that take a decent amount of time to get into.

The old medical bay took ten seconds or less if you had a decent weapon. This is balance, not 'feature' or some massive thing to consult the players about.

**Comment by Jaygriff** [comment]
Medical storage needs to stay RWalls or solid walls at least. People break into medbay just to get to that area. Leaving it reinforced will deter any of that.

**Comment by Chronitonity** [comment]
The parts open to the public are all R-walls

**Comment by collinxchu** [comment]
@JustinBNewton Please read the PR description - I address this in a way that i believe balances the ability to be able to get in as an antag or in an emergency without it being trivial to get in.

**Comment by SplergeBucket** [comment]
I prefer this compromise, reinforced walls aren't required, people still break in albeit taking longer and most of the time i've seen people breaking in it's for medical supplies.

**Comment by collinxchu** [comment]
Ignore those commits - I'm a fuckin moron when it comes to github apparently.

**Comment by Kokojos** [comment]
I would like to import this, it's for now a good middleground between too much and not enought for our playerbase.

**Comment by Chronitonity** [comment]
So its been five days and everyone except Nokington is supporting this, whats the status

**Comment by Nokington** [comment]
Its not getting merged, it just hasn't been closed yet.

**Comment by Jaygriff** [comment]
waiting on LCASS for any more map updates afak.

**Comment by Chronitonity** [comment]
What a great attitude to have when everyone disagrees with you

**Comment by Jaygriff** [comment]
@Chronitonity Any map updates that happen before LCass chem or other map update gets merged will just get undone when the merge goes through. Considering the chem update adds a LARGE portion of the map and the coders have discussed the medbay issue, its not getting merged at this time.

**Comment by Chronitonity** [comment]
In that case it wouldn't be closed like Nokington said, it would be put on hold m8.

**Comment by Jaygriff** [comment]
@Chronitonity Either way it will need to be remade once the pr for lcass goes through. So yes it will need to be closed.

**Comment by collinxchu** [comment]
@JustinBNewton How long is Lcass chem going to take? I'd rather not have a billion mapping issues put on hold for one feature.

**Comment by collinxchu** [comment]
Closing until Lcass chem comes in later

https://github.com/HippieStationCode/HippieStation13/pull/385#issuecomment-129996520

**Pull request closed without merging**
