### PR TITLE
Adds coder sprites ("Improves" Morph dead sprite)

### PR DESCRIPTION
**Pull request by ghost**
Fixes https://github.com/HippieStationCode/HippieStation13/issues/3122
image
Don't hold your applause.

### CODE REVIEW

**Comment by Spacedong** [comment]
better sprite than it was before

**Comment by ArcLumin** [comment]
Isn't this BASICALLY a bugfix to deal with a white pixel?

**Comment by SplergeBucket** [comment]
looks ok
dunno what happened to my vaginal monster creature tho

**Comment by SplergeBucket** [comment]
merge it

**Comment by Hackole** [comment]
Why not? +1

**Comment by ghost** [comment]
I'll fix this tomorrow lmao

**Pull request merged**
