### PR TITLE
Combat First Aid

### PR DESCRIPTION
**Pull request by ghost**
Replaces internals boxes with something a bit beefier.

Standard kits contain:
- 1 breath mask
- 1 Emergency oxygen tank
- 1 medipen
- 1 patch containing 5u of tricord
- 1 blood bag containing 300u of saline glucose solution, and 100u of inaprovaline

The engineering kit contains the same as the standard kit but with and engineering emergency oxygen tank.

The security kit contains:
- 1 Sec gas mask
- 1 Emergency oxygen tank
- 1 medipen
- 1 one patch containing 10u of tricord
- 1 hypospray containing 80u of iron and 20u of salbutamol, injected in one use
- 1 blood bag containing 300u of saline glucose solution and 100u of inaprovaline

The combat kit contains:
- 1 breath mask
- 1 double oxygen tank
- 1 medipen
- 1 patch containing 20u of tricord
- 1 hypospray containing 150u of iron and 50u of salbutamol, injected in one use

All kits contain a paper with instructions for fluff.

The standard kit gets a band-aid for minor injuries, like being slipped b the clown. That's really all 5u of tricord can heal. 

The bags of saline glucose and inaprovaline are there for when medbay is being stingy about its' blood packs, as they almost always are.

The hyposprays are for sec and nuke ops to keep a critical patient alive long enough to receive treatment. All the hypos do is heal oxyloss and increase the patient's blood generation rate by a small amount.

None of the kits contain enough meds to heal a player from crit to anywhere near full, unless they fell into crit from something ridiculous like pure oxy loss. The kits aren't powerful enough to stop someone from actively killing you. What they're designed for is to keep you from dying after the action is finished, the bad guys are dead, and the crew is dragging the casualties to medbay. While you're lying in crit in medbay lobby, someone can pull out your CEFAK and keep you alive with it.

### CODE REVIEW

**Comment by trifornt-tinfornt** [comment]
I fail to see the point.
For the standard box, the patch of 5u Tricord might be a little bit nice but that bloodbag sounds absolutely insane. Inaprovaline is extremely good at healing you while you're in crit, and Saline will keep you from dying of bloodloss. All you'd have to do is steal an IV injector from medical, put your bag on it, and then start injecting in your free life insurance if you aren't killed by whatever antag/space wind/dumb thing crits you.
Security one is way worse. Hyposprays given to sec at start would be horrifying if they're refillable, and your code never suggests that they aren't. That, and they get more Tricordrazine, and that will absolutely only be used when they're in a combat situation which would be unfathomably annoying in revs.
Combat one has no excuse. 20 tricord for nuke ops is terrifying given that they can flee with jetpacks and have some of the best weaponry in the game. That, and they get a hypospray for free. Enjoy the initropidril, Captain.

**Comment by ArcLumin** [comment]
The way I see it;
1. No hyposprays. If you're gonna do some basic healing, have it in a medipen form, so it can't be refilled.
2. No bloodpacks. If you want, make a 10u iron, 10u vitamin pill, maybe with a small bit of nutriment. Bloodpacks REQUIRE the use of an iv drip (or a super annoying syringe), and there's limited amounts.
3. That's way too much iron. even 50 iron will get you loads of blood back, without anything else. Ideally, it should have just tiny amounts, as it's an emergency supply.

**Comment by ArcLumin** [comment]
A normal hypospray, only injecting 5u instantly, with no message given, is already fatal in the right hands. Think of that times 40. Even 15u is enough to permanently fuck someone up and give a guaranteed kill, even WITH treatment.

**Comment by ArcLumin** [comment]
Also, saline glucose also heals brute and burn damage. Quite a lot, in fact. Somebody taking all that saline glucose could easily just heal through, far better than even that 20u tricord.

**Comment by trifornt-tinfornt** [comment]
in other words unbalanced as fuck pr

**Comment by ghost** [comment]
I don't like this.
Medical doctors are meant to save people in crit, not everyone. There are plenty of ghetto heals people can carry around if they want to be ghetto med doctors.
As it stands, everyone has epi pens and gauze is very easy to make and that's enough to stop most from dying.
Sec officers can just carry donuts which are pretty common if they want health. They don't need an experimental technology from NT to heal people.

**Comment by ghost** [comment]
I wrote this at 3am. I'm still not sure I know why.

**Pull request closed without merging**
