### PR TITLE
Rad storm fix ROUND NaN, FIGHT

### PR DESCRIPTION
**Pull request by Jaygriff**
used spawn(60) as a suggestion from nok

per #252

### CODE REVIEW

**Comment by Nokington** [comment]
Will merge as long as @Chnkr doesn't say something is bad 3 hours after I merge it

**Comment by ghost** [comment]
bad

**Comment by SplergeBucket** [comment]
Lowering the sound level of the blowout?
psssshhhhfhfhttt no

**Comment by Nokington** [comment]
Its ear deafening loud

**Comment by Nokington** [comment]
@Chnkr Make your fix already aaaaaaaaaa
Also fix the ear deafening

**Comment by Jaygriff** [comment]
even at 20 volume its still pretty loud

**Comment by WhiteFox08** [comment]
Reduce it by 15 db's

**Comment by Nokington** [comment]
@Chnkr Tell me why its bad or ill probably just merge it, this isn't something that is gonna sit around for a month like the antag problem.

**Comment by nalarmg** [comment]
Code is fine to be merged. "This is bad" is worthless without a reason

**Pull request merged**
