### PR TITLE
Makes the cursed owl hardsuit protect from syringes

### PR DESCRIPTION
**Pull request by varyy**
It's a hardsuit, kind of weird it doesnt protect you from syringes.

### CODE REVIEW

**Comment by ghost** [comment]
Yeah okay +1

**Comment by GenericGoose** [comment]
shouldn't all hardsuits just have this property and inherit it?

**Comment by varyy** [comment]
yeah but the cursed owl suit didnt inherit because it had seperate flags

**Comment by ArcLumin** [comment]
No blockhair flag?

**Comment by varyy** [comment]
its got blockhair from the syndi hardsuit helm.

**Comment by Kokojos** [comment]
sure +1/rd why not.

**Comment by Carbonhell** [comment]
blockhair is for the helmet, unless you have hairs on your chest :^)
code ok

**Comment by Badmex** [comment]
Eh sure I guess. Nobody ever goes out to get that suit but w/e. +1/3

**Comment by ArcLumin** [comment]
I actually use the owl suit, so I'm happy with this

**Comment by calibraptor** [comment]
Sure why not +1

**Pull request merged**
