### PR TITLE
Ports Dakis over, allows you to make basic machine parts in the autolathe

### PR DESCRIPTION
**Pull request by Chronitonity**
Dakis are those stupid body pillow things, and before you ask why we're adding them, I'll tell you why.

They're fucking stupid and they have no reason not to be in here.

http://puu.sh/kJmFG/8013143273.png
Theres a lot of versions of them, even a narsie one. They function as 3 slot backpacks, and you can hug or punch them if you really need to show your love/anger.

Captain spawns with 1, maint spawners have em, and so does the contraband spawner

Other part of this PR is allowing Cargo to make the BASIC machine parts like capacitors, which makes sense seeing how they're in every machine on the station already. If you want upgraded machine parts you still need to go to science.

### CODE REVIEW

**Comment by Weisyl** [comment]
Thanks chron you gave me cancer.

**Comment by ghost** [comment]
there's nothing that can stop us from moving forward towards the pit

**Comment by Pyko1** [comment]
But we can try to fill the pit with dakimakuras.

**Comment by Spacedong** [comment]
im going to kill myself if this is merged no joke

**Comment by Chronitonity** [comment]
Even more of a reason to merge it

**Comment by Jaygriff** [comment]
Ill merge this tonight as long as anyone that has one is valid.

**Comment by Foosili** [comment]
Oh my god.

**Comment by Foosili** [comment]
To be fair we already have school girl uniforms and cat ears, we might as well go full anime embarrassment. I'm sure nexendia will be happy :^)

**Comment by Chronitonity** [comment]
All ready, changelog is there along with inhands

**Comment by TDcoolguy300** [comment]
:td: also known as :scream:

**Comment by nalarmg** [comment]
Waiting for further headmin input.

**Comment by Cafaling** [comment]
We Animu station now?

**Comment by Pyko1** [comment]
uguu~

**Comment by Cafaling** [comment]
Absolutely disgusting.

**Comment by danhibiki** [comment]
Dear god no

**Comment by Chronitonity** [comment]
fight me on this hibiki, we can already stick things in our asses and wear cat ears and tails, having weird punching bags isnt a stretch anymore

**Comment by Carbonhello** [comment]
I'm ok with this only because there's camille daki so i can hug it to death

**Comment by Cafaling** [comment]
I can do gimmicks with this so :+1:

**Comment by danhibiki** [comment]
It even looks weird as an icon, like wavering and poorly tapered toilet paper thats been drawn on

**Comment by Chronitonity** [comment]
http://puu.sh/kKaIU/3abcf2a4bf.png

now with Camille

**Comment by ghost** [comment]
https://i.gyazo.com/b62150ca9c64bd33bdd4a3b1a7435d5b.png

https://i.gyazo.com/75457e9fe6d7eade57d4f2600d7ad363.png
NOW WITH CLOWN AND SKELETON

**Comment by danhibiki** [comment]
The icons need more work, maybe a gradient near the edges to make them "pop" more.

**Pull request merged**
