### PR TITLE
Revert "New Admin Ticket System"

### PR DESCRIPTION
**Pull request by Gandalf2k15**
Reverts HippieStationCode/HippieStation13#2533
I FUCKING HATE IT MYSELF. I CANT FIX IT EITHER. OKAY THANKS FOR THE TRIAL BYE NOW.

### CODE REVIEW

**Comment by calibraptor** [comment]
merge merge Merge Merge MERGE MERGE

**Comment by ghost** [comment]
IT HASN'T EVEN SATISFIED TRAVIS YET JFC

**Comment by Gandalf2k15** [comment]
Who thought this would be a good idea.... I'm looking at you nebyab

**Comment by Gandalf2k15** [comment]
MERGEEE

**Comment by Nebyab** [comment]
> nebyab

Wasn't my idea mate, and its the one the meeting had. If I recall correctly you spent all of last night endorsing it as well. So... yeah.

**Comment by Gandalf2k15** [comment]
Yeah It was everyone who voted for its fault to be honest. I never knew it was gonna be sooo clunky. I'm making my own from scrach. Purely text based.

**Pull request merged**
