### PR TITLE
Beacon Microphone Fix Balances #1343

### PR DESCRIPTION
**Pull request by Zadeon**
This is just a balances but fixes the microphones on tracking beacons so that they work. 
I was looking for issues I could maybe fix and saw this one so here it is.

### CODE REVIEW

**Comment by TDcoolguy300** [comment]
As above, balances #1343

**Comment by Nebyab** [comment]
yeah sure

**Comment by Carbonhell** [comment]
To be fair,this is a sloppy fix. Tracking beacons shouldn't even be radio childs at all, making them work like radios sounds just...weird, no clue.It'd be good if someone reworked them to be their own item, but code's fine anyway i guess.

**Comment by Carbonhell** [comment]
So yeah,i'd prefer if you actually made it its own item instead of being a radio child. But if you want this to be merged, say so, code's fine

**Comment by Nokington** [comment]
:+1:

**Pull request merged**
