### PR TITLE
Revert "blastco armory is now completely burglarproof (TM)"

### PR DESCRIPTION
**Pull request by ArcLumin**
Reverts HippieStationCode/HippieStation13#3324

DONGCODE STRIKES AGAIN HE SAID HE TESTED IT, HE LIED TO CODE REVIEWERS AAAA

### CODE REVIEW

**Comment by Anderbergst** [comment]
this needs to be merged fast or future syndiecates cant buy blastcos anymore.

**Comment by ArcLumin** [comment]
Gonna quick merge as this is an important fix, and there's no code to review as it's a revert

**Comment by blobbernaut** [comment]
Rip, free blastco inc

**Comment by Pyko1** [comment]
was just a typo tho so should prolly fix it even if code freeze.

**Comment by blobbernaut** [comment]
for(var/obj/machinery/blastco_antibuurglar in world)

**Comment by blobbernaut** [comment]
you fucking fuck

**Comment by blobbernaut** [comment]
@Spacedong

**Comment by blobbernaut** [comment]
fix it RRRRREEEEEEEEEEEEEEEEEEE

**Pull request merged**
