### PR TITLE
Improves Reviver Implants

### PR DESCRIPTION
**Pull request by ArcLumin**
Title. Reviver implants are trash, waste of TC. This at least makes them somewhat viable

### CODE REVIEW

**Comment by SplergeBucket** [comment]
what changes did you make
thanko

**Comment by danhibiki** [comment]
Makes the cooldown lower by a factor of 5 it looks.

**Comment by ArcLumin** [comment]
Cooldown between heals decreased by a factor of 5, heal amount boosted by 50%, chance boosted mildly.

Before, reviver implants couldn't even stabilize your crit, you'd still slowly die. This helps that.

**Comment by ArcLumin** [comment]
Reviver implant will now make you conscious so long as you have reviver charges.
Healing is now if you're < 1

**Comment by ArcLumin** [comment]
Lemme know if the anti-stun is too much

**Comment by Hackole** [comment]
+1/3, I'd like to see reviver implants have an actual use

**Comment by ArcLumin** [comment]
Reminder that you only have space in your chest for ONE implant or organ, so there needs to be something that makes it more viable than the other organs/implants you can get. With shit like anti-stun and hivelord remains outclassing reviver immensely, there's basically not reason to get it

**Comment by doobiedoo23** [comment]
+1/3

**Comment by Kokojos** [comment]
yes +1

**Comment by Nebyab** [comment]
yeah sure

**Pull request merged**
