### PR TITLE
Readds Botany Buffs

### PR DESCRIPTION
**Pull request by ArcLumin**
From before the revert. Thanks Dan. Changes are here; https://github.com/HippieStationCode/HippieStation13/pull/1617

### CODE REVIEW

**Comment by KayeArray** [comment]
travis angry travis kil

**Comment by ArcLumin** [comment]
travis too salty for me, even though I updated a number of those, rip.

**Comment by ghost** [comment]
Yeah okay +1 if you feel like fighting git.

**Comment by ArcLumin** [comment]
I'll fite you travis, come at me

**Comment by doobiedoo23** [comment]
+1/3

**Comment by Kokojos** [comment]
Please fix travis.

**Comment by ghost** [comment]
> Travis
> Merge conflicts

It's not travis that is unhappy, it's git.

**Comment by Spacedong** [comment]
rip

**Comment by ArcLumin** [comment]
I'll do fresh DL's of the files tomorrow AGAIN and try to see why github is so pissed off

**Comment by Nebyab** [comment]
yeah sure

**Comment by ArcLumin** [comment]
gonna fight git tonight, THROWDOWN

**Comment by SplergeBucket** [comment]
ok?????

**Comment by Pyko1** [comment]
conflicts, please fix em

**Comment by ArcLumin** [comment]
I need to find the time and figure out why github is pissed. I'll redownload everything and get to it later

**Comment by Lawligagger** [comment]
conflicts

**Comment by ArcLumin** [comment]
99% of my coding is on a machine without DM, so I can't easily edit .dmi's on it. I'll have to figure out why it's pissed when I'm on a different one

**Comment by ArcLumin** [comment]
Nothing I do removes the conflicts, rip

Might as well start from scratch.

**Pull request closed without merging**
