### PR TITLE
Changes Syndie Firing Pin to a Safety Firing Pin

### PR DESCRIPTION
**Pull request by ArcLumin**
Because apparently seeing a syndicate firing pin on a bartender shotgun is too triggering for some people.

### CODE REVIEW

**Comment by ghost** [comment]
How hard is it to make the bartender shotgun and bartender contender just use a generic firing pin?

**Comment by ArcLumin** [comment]
It's not. But the idea is I don't want nuke ops to grab the contender from space or the bartender and then use it to break into blastco.

**Comment by KittyKathy** [comment]
Yeah but if Spacedongs PR to make blastco bomb cores blow up on proximity detection even if you managed to break in you would blow yourself up and the loot up when you walk past one.
Should just do what McBawbaggings said and someone check and merge Spacedongs PR already.

**Comment by SpankMasterson** [comment]
sure i guess +1

**Comment by Hackole** [comment]
Technically my fault, I had forgotten to put a generic pin in the bartender's shit when I added the syndicate pin. +1/3

**Comment by ghost** [comment]
yeah go ahead and whatever +1 but with the generic firing pin

**Comment by Pyko1** [comment]
+1 spank and +1 dude with completely other pin to be changed...

**Comment by ArcLumin** [comment]
Merging as a description change doesn't have code to review

**Pull request merged**
