### PR TITLE
LubeOverlay

### PR DESCRIPTION
**Pull request by AliiTea**
Makes lube use the water overlay.

Credit to PKPenguin321
https://github.com/tgstation/-tg-station/pull/12769

### CODE REVIEW

**Comment by TDcoolguy300** [comment]
:+1: The only one worth merging

**Comment by AliiTea** [comment]
@TDcoolguy300 add the tgport label.. I would but I don't have Collaborator

**Comment by AliiTea** [comment]
@nalarmg @Nebyab @Chronitonity 
Yo look at this

**Comment by Chronitonity** [comment]
Code is fine, its accepted on trello

**Comment by PKPenguin321** [comment]
neat

**Pull request merged**
