### PR TITLE
Say logs now transfer over to ghosts

### PR DESCRIPTION
**Pull request by TheOneAndOnlyCreeperJoe**
On swagile's request, haven't tested in-game yet but I think it'll work?

### CODE REVIEW

**Comment by ghost** [comment]
If guy A dies, ghost talks then revives, will a changeling who later absorbs guy A be able to access those ghost say logs?

**Comment by TheOneAndOnlyCreeperJoe** [comment]
It only copies the say logs, it doesn't modify the old ones on the body in any way.

**Comment by Swagile** [comment]
yes thank you :)))

**Comment by ghost** [comment]
Guy A > Dead Guy A > Revived Guy A.

So Dead Guy A doesn't pass say logs onto Revived Guy A?

**Comment by ghost** [comment]
Wait I'm retarded, I see why this wouldn't affect lings.
+1.

**Comment by Hackole** [comment]
Good QoL feature. +1

**Comment by TheOneAndOnlyCreeperJoe** [comment]
needs a code review, 2 heads said yes

**Comment by JohnGinnane** [comment]
Can you test it pls

**Comment by TheOneAndOnlyCreeperJoe** [comment]
It works and is mergeable

**Comment by TheOneAndOnlyCreeperJoe** [comment]
Should be merged @McBawbaggings or anyone currently online

**Pull request merged**
