### PR TITLE
Re-enables the gateway (ubermeat urgent)

### PR DESCRIPTION
**Pull request by Gandalf2k15**
Its not the gateway causing the lag anymore. The caves map was causing
major problems, removes this.
Also this is an extremely important PR as the server will not restart correctly without maps in the config. Merge ASAP.

### CODE REVIEW

**Comment by JohnGinnane** [comment]
Will merge as soon as Travis finishes.

**Comment by JohnGinnane** [comment]
Travis is happy, so merging

**Comment by blobbernaut** [comment]
thank

**Comment by Lawligagger** [comment]
why you do

**Comment by Gandalf2k15** [comment]
I had originally though it was this, but it was not. Apparently another fix broke the server. Separate from the gateway.

**Pull request merged**
