### PR TITLE
Removes contender from bartender

### PR DESCRIPTION
**Pull request by SplergeBucket**
THIS WILL KILL THE SHOTGUN GIVEN TO THE BARKEEP WHICH FOR SOME REASON WAS CONSIDERED A GOOD IDEA ON TOP OF HIS ORIGINAL SHOTGUN, ALSO IT HAD A SYNDICATE FIRING PIN

also apparently i fucked up standard procedure, thanks ot the helps of tdflexguy300 i have now learned standard procedure

references #3231

### CODE REVIEW

**Comment by Anderbergst** [comment]
lol

**Comment by gumner** [comment]
BUT HOW WILL I SHOOT FURRIES WITHOUT MY SHOTGUN?!!

**Comment by SplergeBucket** [comment]
you already have one you BR fuck
this is just a second snowflake shotgun with syndicate descriptions

**Comment by SplergeBucket** [comment]
also this gun is weak as hell for a syndicate selection piece
ideally @ArcLumin lowers the TC price to something like 7

**Comment by KittyKathy** [comment]
Why are you removing it? All i can get from the PR is that he had two guns and this one had a syndicate pin which was probably a coding mistake as only the syndicate version should have a syndicate pin.

Also this gun is not a shotgun because it can shoot any ammo as in it can shoot the same ammo the detective .38 shoots for instant stuns. Or it can shoot .357s for 60 damage per shot.

And this gun is not weak as hell for a syndicate gun it can shoot sniper ammo without the delay the sniper has and it can shoot the grenade ammo or taser slugs.

I would consider it the best gun to use just for the variety of strategies that you can use with it. 
Like using thermals and the sniper penetrator ammo that goes through walls to kill the captain without him even seeing it coming all without even buying the expensive sniper and having to lug it around or use it as your main gun.

**Comment by Pyko1** [comment]
code seems fine

**Comment by Pyko1** [comment]
Hardly removal of content, unless i missed the note that it includes removal of backpack_contents

**Comment by Kierany9** [comment]
# DID SOMEBODY SAY POWERCREEP?

**Comment by SplergeBucket** [comment]
fair enuff kitty
i dont believe the barkeep should have this as a weapon tho'
especially not with a syndicate firing pin inside it

**Comment by SplergeBucket** [comment]
also changelogs are gay as hell  shieeet

**Comment by JohnGinnane** [comment]
This definitely needs a changelog

**Comment by SplergeBucket** [comment]
i aint gunna figure out how to do em unless i get a yes or no on it

**Comment by KittyKathy** [comment]
Yeah it does seem too strong even more than the detective revolver to be available pretty much round start if a bartender joins at round start. Maybe add it to a mining loot crate or something so it is not syndicate exclusive though.

Does the syndicate firing pin even do anything special other than being unable to shoot it on the syndicate base? Or is it just a reason for people to valid hunt you for having a "syndicate gun"?

**Comment by SplergeBucket** [comment]
according to the PR it spawns in space i believe at Z4
the syndicate firing pin does nothing but confuse players and get the barkepe killed
its dumb as hellggh

**Comment by KittyKathy** [comment]
Oh yeah Looping is 100% right merge now or fix the pin thing then merge now.
To fix the pin thing you need to add
`pin = /obj/item/device/firing_pin/generic`
after line https://github.com/HippieStationCode/HippieStation13/blob/master/code/modules/projectiles/guns/projectile/shotgun.dm#L541
be sure to keep the indent to match line 541 and there should be a blank line after the line you added to keep the other code separate and it makes it more readable.

I'm not actually 100% sure if the code change i told you would work but it should.

the reason it has a syndicate pin is because this is a child of type revolver which does have a syndicate pin and so it just inherited it because it was never overridden.

**Comment by ghost** [comment]
Yeah as soon as I noticed he had the syndie firing pin.
Make it fukken generic or remove it from bartender.

**Comment by GenericGoose** [comment]
so basically its fucking broken and unfinished lol this is a good reason to delete it
why the fuck does it shoot any ammo lol
thats not how guns work?

**Comment by ghost** [comment]
Yeah sure +1

**Comment by blobbernaut** [comment]
It's a space techno gun that's why fuck you!

**Comment by ArcLumin** [comment]
Bartender's normal shotgun has a syndie area firing pin. This is a child of it.

All the syndie area pin does is prevent it's use in the nuke ops base. The reason it has it is so they can't use sniper ammo to break open blastco if they steal it from the barkeep or space.

Also @GeneralGoose It's not broken or unfinished. It shoots any ammo because, if you read the description, it's a bluespace barrel that automatically conforms to the shot type. It's based on the real like Contender, which can do the same, albeit by swapping barrels. Go look it up.

**Comment by ArcLumin** [comment]
Also I made the traitor version have a completely different skin, so it should be obvious taking a look at it that it's not the syndie version

**Comment by trifornt-tinfornt** [comment]
To be fair while it is capable of shooting .357 ammo, the Bartender's shotgun can shoot shotgun slugs which also deal 60 damage per shot, but his shotgun can load two shots instead of only one.
The difference is the Contender can do the same and this time doesn't have the restrictions of the Shotgun, effectively giving the Bartender another powerful gun that he doesn't need and will get robbed at roundstart by powergamers.
remov

**Comment by ghost** [comment]
Then make the bartenders guns have normal firing pins.

**Comment by MethMedic** [comment]
Syndicate firing pin is literally a firing pin that makes it so nukies don't shoot each other in the main base. Why does it matter?

**Comment by yobob591** [comment]
Exactly, also everything that people have said about the gun being op are either impossible for bartender to get without killing syndies or are basically things the shotgun or det revolver can also do but worse

**Comment by yobob591** [comment]
I've never used it but I'm fairly sure it can't load magazines so it's still one shot no matter what ammo you have before you need to reload

**Comment by MethMedic** [comment]
Its one shot yea

**Comment by ArcLumin** [comment]
I don't see the point in removing the contender. Latejoin bartenders ussually won't be able to get their shotgun because it's been stolen. This gun is a single round backup pistol for crowd control. It's worse than the shotgun or the det revolver for a non-antag barkeep as it needs to be reloaded every shot. If you want me to change the firing pin, I totally can. But removing it from the barkeep's arsenal is a bad idea. Plus, if there's more than one barkeep, they definitely can't all have the shotgun. Barkeep spawning with armor means the shotgun fits perfectly on the backslot of the armor, meaning it is just as portable.

**Comment by yobob591** [comment]
I agree this is kinda a knee jerk reaction to someone getting valided for having a barman contender

**Comment by ArcLumin** [comment]
Which is retarded because the barkeep one has an entirely different skin

**Comment by MethMedic** [comment]
The contender is good for using ammo types that finding a gun for is really hard

**Comment by ArcLumin** [comment]
Surprised people are complaining that the contender has a syndie firing pin when the fuckin bartender shotgun does too and has had it for a long time

**Comment by yobob591** [comment]
Nobody noticed til now

**Comment by ArcLumin** [comment]
I mean, I noticed it. I just didn't see it as an issue

**Comment by JohnGinnane** [comment]
Is it even an issue?

**Comment by ArcLumin** [comment]
Not really. Just some people who don't know better might jump to conclusions. I made a PR for renaming it; https://github.com/HippieStationCode/HippieStation13/pull/3340

**Comment by Kierany9** [comment]
>giving the Bartender another powerful gun that he doesn't need and will get robbed at roundstart by powergamers.
>remov

basically this

>Latejoin chemists usually won't be able to get their syringe gun because it's been stolen
>Latejoin engineers usually won't be able to get their hardsuit because it's been stolen.
>Latejoin wardens usually won't be able to get their armoury because it's been stolen

**Comment by GuyonBroadway** [comment]
The contender has weapons 6 which allows R&D to bypass the need for combat shotguns/spending TC as a tator for a power fist. 

Might make R&D stupid easy as a result.

**Comment by ArcLumin** [comment]
Or you know, just fuck off to space and grab one there. Or grab one of the shittons of powerfists on mining since you have access (they have a good chance to spawn in abandoned crates) or just get cargo to order it, it's just as easy as getting the gun from the bartender.

**Comment by Spacedong** [comment]
yeah sure honestly or just fucking put it to weapons level 4 so rd cant profit as much from it

**Comment by SplergeBucket** [comment]
i didnt put up this pr only because i saw a cunt get valided because of this
i put it up because giving the barkeep two guns is dumb and i dont see the reason to arm him up
if his gun gets stolen because he joined 30 minutes late then too bad???

**Comment by SplergeBucket** [comment]
MUH GUN HUGBOX
BARKEEPS GOTTA BE ARMED 25/34 to fight off shitcunts
IF I DONT GOT MY GUN THIS GAME AINT RIGHT

**Comment by SplergeBucket** [comment]
i mean lets be real here
you're all retards for endorsing the barkeep having two guns
you dont see me going GEE BILL HOW COME UR MUM LETS U HAVE TWO ENERGY GUNS
THeN SCREaMIN about hoW THAT SHIT AINT FAIR I WANT TWO GUnS 2!!!11

**Comment by SplergeBucket** [comment]
i will destroy arc "contending for bartending" lumin

**Comment by Pyko1** [comment]
+1 heads, i believe

**Comment by SplergeBucket** [comment]
yeah i've only got spewbags on me side maybe??

**Comment by ArcLumin** [comment]
Might be a good idea to close this, since you made a branch on our hippiestation account and not your own fork. Good idea to close and delete that and then remake on your own fork if you still want it done

**Comment by SplergeBucket** [comment]
HELL YEAH BITCH

**Pull request closed without merging**
