### PR TITLE
Stun Update 2.0

### PR DESCRIPTION
**Pull request by Crystalwarrior**
Alright, so last time this got in a little WAY too fast without any semblance of discussion and, naturally, the server was in shambles.
Let's try this again, but this time we need to discuss all the balance changes applied in this PR, perform extensive testing and figure out if I missed any stuns that give you too much "crawl space".

//**DISCLAIMER**//
Most affected are stuns that either cannot be followed up with a reliable cuff or are long enough on their own to warrant control given back to the victim so they're not fucked for an extremely long time (some 20-22 second stuns, for example). Some of "environmental" stuns were also affected.
//**DISCLAIMER END**//

Keep in mind that due to the tick nature of Weaken/Stun procs, the "first tick" will have a slightly random effect on stun duration - basically depends on how early into the tick the proc was called.

Example: Stun(2) might last from 2 to 4 seconds due to 1 tick taking 2 seconds and the ticks aren't initialized in the Stun() proc itself.

**STUNS THAT WEREN'T TOUCHED/YOU CANNOT CRAWL FROM/CAN ONLY CRAWL FROM ON LAST TICK:**
- Lichdom spell stun for wizard
- Being absorbed by changelings (after being stabbed with a proboscics)
- Stun trap in Hand of God
- Most shadowling abilities
- Defib/emagged Defib stuns
- Flashbangs and Flashes (can crawl only on last tick)
- Stunbatons and peppersprays
- CQC gloves and Krav Maga, as well as Plasma Fist's knockdown punch
- Xeno Hunter Pounce
- Fire resist (rolling on ground to put yourself out)
- Xenomorph tackles
- Plant people having their vacuoles boiled from floramut
- Being exhausted from low stamina
- Changelings being stunned from when they lose their horror form due to damage
- Venus Plant human trap
- Untying the noose over your neck when hanged
- Detective revolver
- Neurotoxin spit on xenos
- Ebow
- Most reagents were untouched (other than flash powder, stun duration was set to be the same as flashes)
- Butt smacking you in the face
- Wizard's magic missile
- All pool-induced stuns
- Tabling
- Slam Dunking someone in holo-hoop (4 stun, 5 weaken)
- Electropack zap (4 stun, 5 weaken)
- Walking on shards/dice/etc. w/o shoes (3 ticks stun, 5 ticks weaken)
- Strained Muscles stun for changelings
- Airlock charge disarm fail stun
- Reagent explosion
- Spraycan spray
- Tray's 10% stun chance
- Wallslam stun
- Tazers (4 stun, 5 weaken)
- Hallucination hunter pounce

**STUNS FROM WHICH YOU CAN CRAWL:**
- Wizard's repulse spell (can crawl on last 2 ticks of stun)
- Hand of God smiting (stun lasts half as long as weaken - can crawl for 5/6 ticks)
- Earthquake Hand of God trap (3 ticks stun, 5 ticks weaken)
- Emagged Orion Trail stun (1 tick stun, 3 ticks weaken)
- Headbutting airlocks while retarded (4 ticks stun, 5 ticks weaken)
- Most slips (Clown PDA, Banana Peel, lube, etc.) have a period of crawling after enough stun ticks
- Bostaff knockdown move (3 stun, 4 weaken)
- Sleeping Carp back kick (2 stun, 4 weaken)
- Slime zap (half of their weaken)
- Hulk Smash on people (2 stun, 4 weaken)
- Radiation-induced weaken (5 stun, 10 weaken)
- Singulo Shield zap (5 stun, 10 weaken)
- Mulebot knock-over (8 weaken, 5 stun)
- Appendicitis pain (5 stun, 10 weaken)
- Lighting Strike for shadowlings (6 stun, 8 weaken)
- Door crush (2 stun, 5 weaken)

### CODE REVIEW

**Comment by Crystalwarrior** [comment]
pls.

**Comment by doobiedoo23** [comment]
You shouldn't be able to crawl on the last tick of a stunbaton stun

**Comment by Crystalwarrior** [comment]
Fair point, lemme tweak that

**Comment by doobiedoo23** [comment]
I also don't like the taser changes at all, but you should probably wait for more input

**Comment by Crystalwarrior** [comment]
The main idea for the taser changes is to make tasers slightly less viable as a last resort weapon.
Still, if you can follow up with a melee stun or you can land two shots in a quick succession they won't even have a chance to crawl away.

**Comment by myontasm** [comment]
Yeah not a fan of the taser change.

**Comment by Nokington** [comment]
:-1: for taser change :+1: for the rest

**Comment by Crystalwarrior** [comment]
Updated stun guns to stun you for 4 ticks and weaken you for 5 (no lying down bonus bullshit)

**Comment by carlarc** [comment]
You could still crawl to the AI that way, it's kind of defenseless

**Comment by Crystalwarrior** [comment]
Hmm. Perhaps force the AI turrets to keep tazing the downed target?
Or, maybe make them check for STUNNED variable on the victim and shoot them instead of checking for lying.

**Comment by carlarc** [comment]
tase them only once after hit so they cant crawl

**Comment by Crystalwarrior** [comment]
Fixed a bigger issue with AI turrets, thanks for bringing it up @carlarc

**Comment by JohnGinnane** [comment]
Code looks good

**Comment by Crystalwarrior** [comment]
I think this is merge-ready now, tested slips and most of the "conventional" stuns.

**Comment by Spacedong** [comment]
no

**Comment by Sarcalogo** [comment]
Here's an even better idea. Why don't you just fuck off forever you fucking retard? Stop trying to change something that has been the norm for a literal decade because WAHHH I DIED RESTART. Get fucking good. Your last update ruined the game for everyone and so will this. Just fuck off. Go away. Your dental implant shit ruined the game. You'll ruin the game with this. You belong on /tg/ with your shitty ideas.

**Comment by Spacedong** [comment]
wew lad that's copypasta tier

**Comment by blobbernaut** [comment]
Sarcalogo literally nobody but you thinks that, quit shitposting

**Comment by Sarcalogo** [comment]
Hackole pretty much agrees with me...

**Comment by blobbernaut** [comment]
hahahah holy shit

"Hackole agrees with me" And in your previous line you were saying how dental implants ruined the game.

**Comment by McHatters** [comment]
The big stuns that people might abuse aren't that affected, such as taser stuns. I do like that you can crawl away from door crushes now so you won't get stunlocked when the kitchen shutters come down.

**Comment by Sarcalogo** [comment]
Hackole hated the same stupid ass update we had earlier just as much as I did and won't welcome the idea of more stun changes.

**Comment by McHatters** [comment]
It probably won't affect the gameplay as much as you think, aside from fixing some stuff that had the possibility to stunlock unfairly.

**Comment by blobbernaut** [comment]
You are just TRYING to be an insufferable ass, Sacalogo.

Crystal, from that PR earlier: "Yeah the problem with that pull request is that it wasn't even ready for server use.
It's mostly my fault as I didn't add a DO NOT MERGE tag"

**Comment by Sarcalogo** [comment]
I am being honest and this change is garbage and I can guarantee you others will feel the same way. If I don't voice my opinion here, then when it gets merged they'll say, "Well where were you?" Here I am.

**Comment by McHatters** [comment]
Fair enough. I personally don't think this won't make much of a difference.
The biggest effect this change will probably have on the server is that
slips will be a bit nerfed, as people can crawl back across the slippery
tile and away from danger if someone or something is waiting on the other
side of the tile.

**Comment by TDcoolguy300** [comment]
Lets do a proper test run on the bloody server first, if everybody hates it when it's live PROPERLY, it can be reverted.

**Comment by doobiedoo23** [comment]
EDIT: I FUCKED UP IGNORE THIS COMMENT 
Sarcalago is actually right, despite his aggressive approach. You constantly try to rebalance shit that doesn't need fixing, your code is generally broken on arrival, and you always make issues about your own code instead of actually fixing it.

After thinking on this for a while I'm gonna give a -1.

**Comment by Kierany9** [comment]
I *kind of* like this but I feel it's a one-step-forward-two-steps-back sort of deal especially since you fucked up so hard the first time. Crawling while resting was the original intention of your first PR but it then spiralled into a game-changing balance update. But what is the exact purpose of this? Like, **how does it make the game better?** The only place I found it to be an improvement was with pushdowns in hand-to-hand fights, enviromental stuns(rad stun, singulo shield stun, etc) and to escape crush stunlocks. In all other places it just seems like a get-out-of-cuffs-free card that's unnecesarily frustrating for the other person. It doesn't even make sense, if you're on the floor and crawling you'd be better off using that energy to get off the bloody floor.

I get that you want to decentralize the meta from being so stun-centric, but hatestation did it first and did it better.

**Comment by Carbonhell** [comment]
No need to be rude cunts, it's not like we're fucking paying crystal to code for us, if you don't like a feature try to be mature and express your opinion on it instead of directly attacking the coder.

**Comment by Crystalwarrior** [comment]
@Kierany9 In actuality most of the stun-crawls were reverted to mostly their original form. Escaping cuffs when stunned is not really as easily done as it was when the update was live on server in its' broken state.
The update also lets you try to crawl away from hostile mobs weakens, and escaping from airlock stunlock is still really fucking hard as you have to pray the timing is on your side.

**Comment by Crystalwarrior** [comment]
Being able to crawl is also a huge contribution to disarms/other melee-based stuns since you can finally at least try to dodge the incoming onslaught of attacks - think "combat rolls" :^)

**Comment by Nebyab** [comment]
I have concerns about how far reaching this is, and to echo what kierny9 or whatever pretty much echoed my concerns. I fear that this simply touches too many things, and has the potential to be really fucky. Like the detective's revolver, and a bunch of antagonist abilities which I have concerns about how this change my negatively impact their viability.

Though in general stuns are great, which is where I differ from Kierany9.

**Comment by blobbernaut** [comment]
uh nebyab

it says "STUNS THAT WEREN'T TOUCHED/YOU CANNOT CRAWL FROM/CAN ONLY CRAWL FROM ON LAST TICK:Detective revolver"

**Comment by Crystalwarrior** [comment]
I specifically made sure things like detective's revolver work like they worked before, like blobber said.
Heck the general idea is if the weaken is not supposed to be a stun induced by security it will let the victim crawl around AFTER some time has passed.

**Comment by meteoses** [comment]
The taser change is terrible. I completely agree with everything that Kingofcarrots/Scalago said in his first post, your last update literally ruined the server, can you just stop trying to put this in?

The only thing this update does is nerf antags via nerfing some of their most viable crowd-control options.

**Comment by Crystalwarrior** [comment]
I'm not sure if you're blind or what but taser is almost completely unaffected.

**Comment by Carbonhell** [comment]
Opinions against the code are OK, attacking the coder is not OK,please guys

**Comment by Crystalwarrior** [comment]
Just to clarify, once more:
**ELECTRODE STUNS ARE ALMOST COMPLETELY UNAFFECTED.**
4 ticks stun means that you have from 6 to 8 seconds of complete immobility for the victim, so basically approximately 7 seconds before they can crawl. That's more than enough to run up to them and follow up with a stronger stun like a stun baton or a flash/telebaton. Not to mention putting on cuffs takes about 3 seconds.
It will not ruin the functionality of tazers, so please stop telling me to quit the game because of it.

**Comment by meteoses** [comment]
I mean okay, I won't attack, as you say; but it's not code that magically spawns from thin air. I don't think this will improve the server, I'm not even sure how it possibly could improve it (unless you just hate antags/dying), and I've never played on a server that didn't have the current (pre-crawl) system. This stun system has worked on servers for over half a decade.

Crystal, I just don't know why you are choosing to nerf antags in this way, aren't antags already gimped enough?

**Comment by Crystalwarrior** [comment]
Actually I'm of the opinion that some antags (like traitors) have some major balancing issues, especially the uplink costs. Some things are way too pricey for how niche they are. Some things are straight up useless against competent security (_cough_ebows blocked by riot shields_cough_)
Not to mention most of the affected stuns are either those that cannot be followed up with a reliable cuff or are long enough on their own to warrant control given back to the victim so they're not fucked for 20 or more seconds.

**Comment by oprayx73** [comment]
add this in to make meteoses/general memers leave, then revert the code.

**Comment by Crystalwarrior** [comment]
oprayx are you literally braindead

**Comment by oprayx73** [comment]
oprayx73 commented just now

add this in to make meteoses/general memers leave, then revert the code.

**Comment by meteoses** [comment]
I'd like to see someone revert the ebow so that it has 5 shots that recharge over time like it did before.

**Comment by Nebyab** [comment]
So perhaps I was off-base on the Detectives revolver. I still don't think this is a needed change, and this refactor is massive with no real evidence that we need these changes made to the game, when these systems have worked fine for ages. How will this make the game better? I don't think it will. Though the shutters one might be nice.

@meteoses Its being pushed internally, we may see it return someday.

**Comment by Gandalf2k15** [comment]
I think this stun balance thing is needed. It sounds like it would help greatly when the chef crushes you using shutters.  The taser thing is cool too. Also why are people so aggressive toward people just trying to improve the game..

**Comment by calibraptor** [comment]
I'd support trying this out

**Comment by doobiedoo23** [comment]
Still feeling a strong -1 here

**Comment by Nokington** [comment]
Kinda against this actually now that I have looked over it more

**Comment by Crystalwarrior** [comment]
Can you elaborate?

**Comment by myontasm** [comment]
I agree, after a small disxussion I've changed my mind about this. A lot of these changes would honestly not change a lot for the better. It's a :-1: from me.

**Comment by Crystalwarrior** [comment]
Aye, fine by me. It's a majority veto, then

**Pull request closed without merging**
