### PR TITLE
Ninja Rework - Take 2

### PR DESCRIPTION
**Pull request by ghost**
I royally fucked up the last PR, so I'm setting up a new one.

Ninja should now be fixed. Everything has been moved into the events module, code has been compressed into 10 files from 25, and I tested with multiple ninjas and no runtimes.

### CODE REVIEW

**Comment by ghost** [comment]
Fuck it, unchecking isn't working. I'll just delete the old files since they aren't needed anymore.

**Comment by gumner** [comment]
travis fucking dies.jpg

**Comment by ghost** [comment]
Guys I killed travis. Send help.

**Comment by ghost** [comment]
I swear to god, if I deleted that last PR over a changelog.

**Comment by ghost** [comment]
I don't know what the issue is here. I tested this shit, it had no issues.

**Comment by ghost** [comment]
Whatever this issue is, I'll fix it in the morning.

**Comment by KayeArray** [comment]
hero.jpg

**Comment by SpankMasterson** [comment]
+1 contingent on code working

**Comment by ghost** [comment]
Success. Code can be merged, now that travis isn't pitching a fit over my changelog.

**Comment by ghost** [comment]
@ArcLumin

I'm not actually sure if this can be merged as a bug fix it not, seeing as this change is pretty yuuge, but it's ready, and I'll probably have to work on it again later when the rebate drops.

**Comment by ArcLumin** [comment]
The codefreeze does not affect PR's already made prior to the codefreeze label, so this can be merged

**Comment by RemieRichards** [comment]
Not even going to credit me?

A little rude.
Small PRs sure, but fixing the spaghetti of Ninja? you're just gonna take credit for that?

**Comment by ghost** [comment]
If quarian commando merged your code under his name then that's an issue. Can you please redirect me to the PRs where you claim this code is your own? @RemieRichards

**Comment by RemieRichards** [comment]
https://github.com/tgstation/tgstation/pull/8261
https://github.com/tgstation/tgstation/pull/8737

I only bring it up because in the past most people I know from here (Chron, Blobbernaut) etc. have been good with noting credit and noting what is and isn't a port.

**Comment by ghost** [comment]
I'm leaving in a bit, but I'll read over this and speak to quarian if I do believe he's failed to credit you.
While all code here is open source, not crediting people is still pretty rude and unwarranted.

**Comment by ghost** [comment]
Thanks for bringing this up by the way.

**Comment by KayeArray** [comment]
oh snap

**Comment by ghost** [comment]
@RemieRichards 

Not sure if anyone is still reading this, but I didn't steal anyone's code you little shit. I never even said that I added anything. I explicitly said that all I did was move the already existing code to its proper location and cut down on the number of files. I said I was going to rework it in the first PR, then saw that just moving shit around fixed the problem, so I dropped the entire idea of reworking and never mentioned it again. This PR didn't add any content, it was a bug fix.

**Comment by RemieRichards** [comment]
If it came from a rebase or something, that's fine, but there's no easy way to find that (besides looking through all of your rebase PRs hint: not happening) so when I see my code and my comments spontaneously appear in a PR + some of hippie's history for stealing shit wordlessly, yes of course I'm going to assume.

**Comment by j-mie** [comment]
This repo isn't even used anymore, everyone calm down.

**Pull request merged**
