### PR TITLE
Krokodil and spookium do not change the species of catbeasts

### LINKED ISSUE #3336: [FUCK] SPOOKIUM BYPASSES CATBANS
FUCK OFF CODERS WHY'D YOU MERGE THIS

### PR DESCRIPTION
**Pull request by tortellinitony**
Fixes #3336

### CODE REVIEW

**Comment by TheOneAndOnlyCreeperJoe** [comment]
Just a FYI this does not work on catbanned people.

**Comment by tortellinitony** [comment]
Then, what does?

**Comment by TheOneAndOnlyCreeperJoe** [comment]
It won't work because catban constantly re-applies the catban if the species were to be changed. In short, it is irreversible (as it should be). Only way to revert being a cat is trough the shitmins.

**Comment by tortellinitony** [comment]
Well this still works for normal cats.

**Comment by ArcLumin** [comment]
This is the only way for dudes who got turned into cats by like, ling dna stings to turn back, so no thank you

**Comment by yobob591** [comment]
nah no reason for this

**Comment by Spacedong** [comment]
just make it for catbans jesus christ

**Comment by ghost** [comment]
Aren't cat DNA stings disabled?

**Comment by yobob591** [comment]
no

**Comment by SpankMasterson** [comment]
+1

**Comment by SplergeBucket** [comment]
-1 dis hedmin nikkas
this is a way for cats turned by spells or shiet to be regular nukkas agauin
doesnt work on catbanned cunts

**Comment by ghost** [comment]
No point. Only reason to keep people cats is if they're catbanned, and catbanned players have a check that turns them back into cats if they secret monkey trick themselves into something else.

**Comment by ghost** [comment]
yeah nah, there's no need.
-1

**Comment by Pyko1** [comment]
has 2 head -1 so more or less denied unless Hippie/Nalar

**Pull request closed without merging**
