### PR TITLE
Re-added megascreaming

### PR DESCRIPTION
**Pull request by Weisyl**
Re-added megascreaming. Uses new sounds instead of just being the
regular scream sound spammed half a dozen times. Currently uses 2 sounds
and is only available for males.
Sounds:
https://www.dropbox.com/s/dgzjaeuvm7f1ahb/scream_male_mega1.ogg?dl=0
https://www.dropbox.com/s/jhbophd1sfkqg8x/scream_male_mega2.ogg?dl=0

If this passes...wew lad.

### CODE REVIEW

**Comment by Crystalwarrior** [comment]
edit: nevermind, the extra range is already +10

**Comment by Weisyl** [comment]
I have no idea how to do that crystal and long-range megascreaming sounds TOO spammy.

**Comment by danhibiki** [comment]
Sure

**Comment by Nebyab** [comment]
sounds good

**Comment by Lawligagger** [comment]
I kinda didn't really like megascreaming

**Comment by danhibiki** [comment]
Awhoops

**Pull request merged**
