### PR TITLE
Updates all Admin names ontop of the Changelog

### PR DESCRIPTION
**Pull request by TheOneAndOnlyCreeperJoe**
Didn't touch the mentor names (aside from taking out the names of those that became admins), I'll do that another time.

### CODE REVIEW

**Comment by JohnGinnane** [comment]
tfw not on coding team :(

**Comment by JohnGinnane** [comment]
I wonder is it possible to open up the files that contain this information and read it from there?

**Comment by dreamcrab** [comment]
zyzarda isnt a GM, or even on the team anymore. and im on there 3 times. head, GM and admin.i may have missed something like missing people

**Comment by Spacedong** [comment]
why is nexendia on the mentor list and the admin list, make up yer mind

**Comment by dreamcrab** [comment]
headmins are 
myself, mcbawbaggins and nebyab

gms are 
dudeinyourbackyard, bartelz, looping, brawzki, calibraptor, 

admins are 
danhibiki, drunkenflyingdemoman, lordkruor, carbonhell, zadeon, yobob, snake2512, kokojo, chaznoodles, lawoggamer, hutchen, speakercity, gandalf2k15, mchatters, nexendia, spacedong, solidfury7, wallaceshark, 

coders are
pyko, johnfg, whitefox08, scooterkid, tdcoolguy300

**Comment by TheOneAndOnlyCreeperJoe** [comment]
updooted

**Comment by Nebyab** [comment]
okay

**Comment by TDcoolguy300** [comment]
But Whitefox and Scoots are not here anymore

**Comment by TheOneAndOnlyCreeperJoe** [comment]
Gah conflicting information

**Comment by dreamcrab** [comment]
i just took it out of the permissions panel okay!!!!

**Comment by Gandalf2k15** [comment]
no

**Pull request merged**
