### PR TITLE
Revert "Dismemberment (Based on RemieRichards' efforts)"

### PR DESCRIPTION
**Pull request by TDcoolguy300**
Reverts HippieStationCode/HippieStation13#2190

This is a last resort as we need to fix this shit ASAP

### CODE REVIEW

**Comment by TheOneAndOnlyCreeperJoe** [comment]
Yes. Now. Now. Now.

**Comment by Crystalwarrior** [comment]
Hol up I'm fixingi t

**Comment by Crystalwarrior** [comment]
What EXACTLY is broken though!???

**Comment by PKPenguin321** [comment]
Haha what happened

**Pull request closed without merging**
