### PR TITLE
Pool performance update + bloodpool feature.

### PR DESCRIPTION
**Pull request by Kokojos**
Minor tweak to how the pool works, code wise, I've been told it'd be more efficient to use directly linked var instead of for() when possible.

This makes the pool able to be destroyed properly by explosions/other things that would kill floors.

(EDIT) This will also allow people to get in or out of the pool even when it's drained.

Also, this allows the pool to be filled to the brim with blood. Putting blood into the pool only changes it's color, and if too much is put in, it stops cleaning itself. The only way to reset that is to drain it and fill it again.

poolblood

(Next PR I make will be bug fixes, I swear.)

### CODE REVIEW

**Comment by Spacedong** [comment]
is that blood in the water because to me it looks just like orange juice blood

**Comment by Kokojos** [comment]
It's water and blood at the same time.

**Comment by Spacedong** [comment]
yeah buddy blood in water doesn't look like orange soda

**Comment by Spacedong** [comment]
looks more like a red mist pal, fix et

**Comment by ghost** [comment]
:+1::eyes::+1::eyes::+1::eyes::+1::eyes::+1::eyes: good shit gooԁ sHit:+1: thats :heavy_check_mark: some good:+1::+1:shit right:+1::+1:there:+1::+1::+1: right:heavy_check_mark:there :heavy_check_mark::heavy_check_mark:if i do ƽaү so my self :100: i say so :100: thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ:100: :+1::+1: :+1:НO0ОଠOOOOOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ:+1: :+1::+1: :+1: :100: :+1: :eyes: :eyes: :eyes: :+1::+1:Good shit

**Comment by Nokington** [comment]
:+1:

**Comment by Nebyab** [comment]
why not

**Pull request merged**
