### PR TITLE
Fixes welding pipes

### PR DESCRIPTION
**Pull request by Tomeno**
Fixes issue #329
WELDING FUEL CAN'T WELD STEEL PIPES

### CODE REVIEW

**Comment by Chronitonity** [comment]
Putting the issue number in the comments links it and says its mentioned over there too. Use your title for describing the issue you melon with ears 

#329

**Comment by nalarmg** [comment]
Code is fine to be merged.

Needs a changelog, however.

**Comment by Chronitonity** [comment]
@Nokington Should be gud 2 go

**Comment by nalarmg** [comment]
Looks good.

**Pull request merged**
