### PR TITLE
makes vodka usable for cleaning cyka blyat ))))))))))))))))))))))))))))))))))))))))))))

### PR DESCRIPTION
**Pull request by zenek123321**
i have noticed i am unable to clean anything with vodka , so i decided to fix it

### CODE REVIEW

**Comment by ArcLumin** [comment]
You can clean letters off of paper with vodka.

**Comment by zenek123321** [comment]
yes , but i want to be able to clean the blood of greytiders from captains office with expensive alcohol

**Comment by ghost** [comment]
Doesn't this only work with mops though?

**Comment by ArcLumin** [comment]
Yup

**Comment by JohnGinnane** [comment]
Code looks good, even if a tad snowflakey (was a little snowflakey to begin with)

**Comment by ArcLumin** [comment]
Basic, simple, but a fun little easter egg, I don't see any reason not to add this

**Comment by Swagile** [comment]
some of the neatest features are simple, like the fact that you can drag and drop storage items onto another storage item to quick transfer. greatest thing ever since sliced bread.

**Comment by JohnGinnane** [comment]
I think I'll port this onto rebase this weekend, but maybe change it so it's much easier for us to change any liquid to clean stuff if that's okay

**Comment by zenek123321** [comment]
tbh most of it was done using copy paste , i have no idea of how to do it.Well , i have an idea but i don't know enough of whatever language byond is using to do it

**Comment by zenek123321** [comment]
actually , ill try

**Comment by JohnGinnane** [comment]
Well what I had in mind was adding a flag to reagent datum (https://github.com/HippieStationCode/HippieStation13/blob/56a3fdddeb58b6e0dedb20514f4cc43bee628c58/code/modules/reagents/Chemistry-Reagents.dm#L16) called "can_clean = False" and then just change the water, holy water, and vodka definitions so can_clean = True instead, then in the clean() proc loop through reagents and check if can_clean is true

**Comment by JohnGinnane** [comment]
This means if we decide to add new reagents that are capable of cleaning (e.g. bleach anyone?) then it's easier to set this flag than go back over code where it's checked if it can clean manually (as it is at the moment)

**Comment by ArcLumin** [comment]
We have bleach lad. and it cleans up colorful reagent

**Comment by JohnGinnane** [comment]
Neat, but if you put it in a bucket does it clean blood and stuff?

**Comment by ArcLumin** [comment]
I thought about making it do that by giving it the clean decal ability, but I took it out since it'd make space cleaner worthless. I can make it do that though.

**Comment by ghost** [comment]
Does it make the floors wet?

**Comment by zenek123321** [comment]
it should , but i don't know

**Comment by zenek123321** [comment]
you won't need to port it i think
https://github.com/tgstation/tgstation/blob/master/code/game/objects/items/weapons/mop.dm

**Comment by JohnGinnane** [comment]
Neat!

**Comment by zenek123321** [comment]
But i am not sure if it works , i haven't tested it.Actually , i wrote that, so i don't think any of that works , test merge pls.

**Comment by JohnGinnane** [comment]
Can't you compile and test? Also need head input before merging

**Comment by zenek123321** [comment]
will do that

**Comment by zenek123321** [comment]
yep , it works

**Comment by JohnGinnane** [comment]
Excellent, just need head input

**Comment by dreamcrab** [comment]
sure, seems funny and neat +Сука Блят

**Comment by Swagile** [comment]
dreamcrab is teamstab and he is headmin currently hence thats +1 to headmin support for those not in the know

**Comment by ghost** [comment]
))) сука +1

**Comment by JohnGinnane** [comment]
:(

**Comment by JohnGinnane** [comment]
Two heads approval, merging

**Pull request merged**
