### PR TITLE
Telvis Jumpsuit

### PR DESCRIPTION
**Pull request by McHatters**
Adds Telvis' jumpsuit to the Clothesmate. Big Papa's right-hand man, Telvis gets the job done

### CODE REVIEW

**Comment by McHatters** [comment]
Some images for ya bubs, thank Fragg for letting me build off the base sprite

http://i.imgur.com/e732VJp.png
http://i.imgur.com/v0ATJgk.png
http://i.imgur.com/vt8ASOo.png

**Comment by SplergeBucket** [comment]
yes

**Comment by Nebyab** [comment]
seems fine and dandy

**Comment by Lawligagger** [comment]
Looks good to me.

**Comment by doobiedoo23** [comment]
don't fuck with telvis
he's got a comb in his hair and a CHIP ON HIS SHOULDER
:+1:

**Pull request merged**
