### PR TITLE
Update laser pointer description

### PR DESCRIPTION
**Pull request by ghost**
You can't shine it in both eyes at once and you would be fucking stupid to try

### CODE REVIEW

**Comment by Spacedong** [comment]
why

**Comment by ghost** [comment]
Saves a byte and saves bandwidth ;)

**Comment by ghost** [comment]
Yeah okay +1

**Comment by Kierany9** [comment]
But humans have two eyes.

**Comment by ghost** [comment]
Lasers have a single focal point, you can't shine the light into both eyes without refracting it into 2 beams.

**Comment by Kierany9** [comment]
I know, but you could shine it in either of your eyes, hence the plural in the description.

**Comment by GenericGoose** [comment]
it blinds you completely tho
which it shouldn't if you blind only 1 eye
so either leave it as is or change the text and make both eyes targetable separately and code blindness for each eye ;^)

**Comment by SplergeBucket** [comment]
This update is cutting edge and for the first time in my Australian life I will be able to load up SS13 easier due to the dreaded space taken up by an update slowly being chipped away smash the communist state, remove gook blood.

**Comment by ghost** [comment]
@SplergeBucket sorry that this comment will max out your data caps ;;)))))

**Comment by ghost** [comment]
To refute that kierany.
You could have two dogs and say the statement "I'm going to walk my dog."
Doesn't matter which dog you walk, provided you walk one and only one.

**Comment by Kokojos** [comment]
Why the fuck not who cares AAAA

**Comment by Kierany9** [comment]
A better example would be "Don't kick my dogs". You could say "Don't kick my dog" if you had two dogs, but only if there's one dog that is kickable for whatever reason.

**Comment by GenericGoose** [comment]
stop animal abuse

**Pull request merged**
