### PR TITLE
Adds clocks

### PR DESCRIPTION
**Pull request by tortellinitony**
Clocks tell the time

### CODE REVIEW

**Comment by Hackole** [comment]
> clocks tell time

woah +1/3

**Comment by Spacedong** [comment]
# BUT IT SAYS IT RIGHT IN THE STATUS BAR

**Comment by KayeArray** [comment]
I like it

**Comment by tortellinitony** [comment]
yea it's really nice and adds tot he atmosphere

**Comment by MethMedic** [comment]
Yea +1

**Comment by Spacedong** [comment]
>no sprites

put em in your original post

**Comment by Spacedong** [comment]
>clock sprite doesn't change based on the time

mediocre

**Comment by Spacedong** [comment]
9ef176f0e577e263c9c7f18c2005228655b150b87fe79ddb48354bf7d9d477a1

**Comment by FuryMcFlurry** [comment]
show pixels in OP

**Comment by ghost** [comment]
Sprites are kinda eh but I like the concept.
+1

**Comment by Gandalf2k15** [comment]
Needs a changelog too.

**Comment by SpankMasterson** [comment]
maybe too OP, but +1

**Comment by tortellinitony** [comment]
Changelog

**Comment by ghost** [comment]
could be cool
+1

**Pull request merged**
