### PR TITLE
Vehicle Rework(Para Port)

### PR DESCRIPTION
**Pull request by Gandalf2k15**
Reworks vehicles based off of paradise station. Enables modular creation of vehicles, adds some more vehicles too.
Current Vehicles:
Pussy Wagon (huh)

Ambulance:
http://i.imgur.com/KPiRuta.gifv

ATV:
http://i.imgur.com/2xGqdOu.gifv

Motorcycle:
http://i.imgur.com/2FrQqKC.gifv

Snowmobile:
http://i.imgur.com/OACDXby.gifv

Car?:
http://i.imgur.com/AmZMyAd.gifv

Speedbikes:
http://i.imgur.com/eQXRNRV.gifv

I'm going to add the adminbus.. Someday...

### CODE REVIEW

**Comment by Spacedong** [comment]
:+1:

**Comment by GenericGoose** [comment]
ｈｅｋ　ｙｅａｈ

**Comment by Spacedong** [comment]
>no adminbus

wow

**Comment by dreamcrab** [comment]
is this somehow gonna fuck with tds pod update? if not im about it +9999

**Comment by GenericGoose** [comment]
doesn't look like it possibly can, since both are modular, with completely new files 
we'll see

**Comment by ghost** [comment]
Can nothing be done about over the buckle button showing an oversized car and bike?

**Comment by Gandalf2k15** [comment]
Not really, as it takes the icon direct.

**Comment by Voratius** [comment]
more ve-hack-els, looks like they'd be used for adminbus, so thats pretty cool, +1

**Comment by ghost** [comment]
Car and speedbike look a bit weird, can't say I'm fond of them.
Does the ATV have an overlay issue? When it turns right it looks like it's driving forwards too.
Motorcycle has a light on the front, I feel as if it should have luminosity associated with it.

**Comment by ghost** [comment]
Everything else is fine though.

**Comment by Nebyab** [comment]
what mcbaw said

**Comment by Gandalf2k15** [comment]
ill do this another time

**Pull request closed without merging**
