### PR TITLE
Replaces bartender buckshot with shell box

### PR DESCRIPTION
**Pull request by KayeArray**
Because 5tc for a single buckshot is stupid, buffs tendy a little.

### CODE REVIEW

**Comment by danhibiki** [comment]
Yeah this is definitely worth it, that or lowering the cost for a buckshot to 1. Even that seems fairly expensive though.

**Comment by KayeArray** [comment]
Not to mention that's his job exclusive item.

**Comment by danhibiki** [comment]
Well, in general, I think having the traitor bought item be something QM can pump out fairly early in the round is sort of lame, its the best of what we got to buff this instead of keeping it at what it is now

**Comment by KayeArray** [comment]
Ye that's why I added a few syndicate exclusive shells to make it actually viable.

**Comment by danhibiki** [comment]
Oh, this actually gives you several different types of slugs. Very nice. I'd say maybe make the distribution of the shells random to add some uniqueness to the loadout you'd get, but at the same time it would probably just be more frustratingfor hte player if they rolled all of one or none of one.

**Comment by Pyko1** [comment]
I think 5 TC for 6 shots is still ridiculous price.
Especially when the gun they are meant for is bulky and limited in magazine size.

**Comment by KayeArray** [comment]
Eh I'll wait for headmin input and see if they want a buff or not.

**Comment by Pyko1** [comment]
Ie.
.357 revolver ammo is 2 TC for 7
9mm g17 ammo is 1 TC for 14
10mm pistol ammo is 1 TC for 8

**Comment by danhibiki** [comment]
Arguably, shotguns are vastly different in usage compared to pistols, especially the double barrel. You have two shots, you have to make them count, and when they hit they fuck whatever is on the other side up. Maybe it could be more shots, but not many more, because your talking about several bodies with just 5 shells.

**Comment by ghost** [comment]
@Pyko1 Incendiary is strong specifically because of rolling.

Smart pyromaniac waits for the roll, then kills them during it.

**Comment by Pyko1** [comment]
That's why you bump to them and set em on fire as well. Or grab an extinguisher.

Or both, if you are smart.

**Comment by ghost** [comment]
Mein freund. Smart pyro carries a bottle of water. If you are ignited, splash it on yourself to be instantly cured.

And extinguishers suck, hit them while they're trying to use it.

**Comment by Pyko1** [comment]
Actually bioterror was the already loaded shotgun dart, so i guess its a bit more viable at least.

**Comment by Pyko1** [comment]
Anyways code seems fine.

**Comment by ghost** [comment]
My gut feeling is this is going to be too good but I'm down for trialing this. +1

**Comment by GenericGoose** [comment]
@Pyko1 you should note that shotgun can be sawned off, which every sane person does, to fit anywhere, like pistols and also it's way less suspicious, than traitor guns

**Comment by ghost** [comment]
Getting it sawn off is exactly as easy as getting it virtually-unlimited ammo.

**Comment by KayeArray** [comment]
Wew lad I take a small break and this thing explodes with comments.

**Comment by ghost** [comment]
Forgive me for asking but bartender still has his armor that can take his shotgun right?

**Comment by KayeArray** [comment]
I believe so

**Comment by ghost** [comment]
Then sawing it off isn't really required.

**Comment by Kierany9** [comment]
Alcohol shotgun darts that act like beanbags but also get the target so drunk that they can't walk.

Make it happen.

**Comment by KayeArray** [comment]
Sounds like a meme, maybe something for another pr

**Comment by ghost** [comment]
@Kierany9 Gargle Buckshot

Lemon juice + grinded gold.

**Comment by KayeArray** [comment]
Or salt shot or something

**Comment by ArcLumin** [comment]
To be honest, bartender needs more buffs. I'd love to see shit like meteorshot shells and pulse shells, easily craftable by RND, in it at that price.

**Comment by ghost** [comment]
10-TC sampler pack. Bandolier with a selection of !fun! shells. Bartendie item.

Make it happen, choders.

**Comment by blobbernaut** [comment]
yes please, pulse shells arent even op compared to .357

**Comment by ArcLumin** [comment]
Meteorshot and pulse shots are useful as fuck for utility too. For 5 TC, not op at all

Meteorshot can knockback doors (prolly a bug, I should make an issue) and pulse shells can break rwalls. You'd only get a small amount, so you'd need to make em count

**Comment by blobbernaut** [comment]
not a bug i think its a bug it doesnt knock back more things

**Comment by ghost** [comment]
Shitcurity should have the right to dump bartender's shotgun down the disposal if they see him with it

**Comment by ArcLumin** [comment]
Security has the right to get shot in the fucking face by the barkeep if they touch his fucking gun

RIGHT TO BEAR ARMS, MURICA STATION

**Comment by GenericGoose** [comment]
you can have your shotgun but you get spaced with it
~Security

**Comment by Lawligagger** [comment]
I'm for it hombre

**Comment by SplergeBucket** [comment]
ye ok

**Pull request merged**
