### PR TITLE
Brig rejig

### PR DESCRIPTION
**Pull request by Kilmannan**
Made Armoury, Riot Gear Room and Locker Room in Brig slightly bigger,
better appointed and more appropriate to the high levels of traffic they
receive now. Also changed weapon cabinets for secure lockers with base
security access required. Antags can still antag, but a bit harder for
greytiders to asshole it up.

Also gave shared access to barriers, because if you're crashing out the Riot Squad, it makes sense to let them tow the barriers along with them if need be.

image

image

### CODE REVIEW

**Comment by trifornt-tinfornt** [comment]
There's no reason for armory to take up that much space and force officers all the way back. There's a lot of empty space in this new armory any way, and a lot of unnecessary changes that really were fine the way they used to be. Riot Squad is almost never used (unfortunately) save for Camille and in the rare situation where there's a riot, AND Security is competent.
Also I swear to God if this is another case where the firelocks/blast doors overlap the main airlocks making it so you can't close them (isolation, invasive search area, bleh) then I'm going to scream.

I'm sorry but this is really dumb.

**Comment by Kilmannan** [comment]
First of all, ending a comment with 'this is really dumb' is a really dumb way to end anything,

This has been talked about in coder chat with several people having valid input, and one thing that was agreed on was that there is an obsession with having tight, small spaces where it makes no sense to have those spaces.

It looks big on a picture, but once you're in there, it's not that big at all, and what it does allow, is freedom of movement and it avoids the usual cluster of people not being able to get past one another because of intent, or pushing each other out the way when trying to get items from vendors / lockers, etc.

Do a few more tiles really ruin things for you so much? When the overall aim is to create a more fluid and enjoyable player experience without getting pissed off at people pushing you / blocking you?

I've sat and observed for numerous rounds, and I've played Sec for more rounds that I care to remember, and it's always the same, it's always a big jam in there. 

In terms of the Riot Gear, I've seen them deployed frequently, and it's down to the players to ask for / get it out. I'd really like to see a proper, full on Riot team descend into the station in some form of order, dragging the barriers with them. They now have the equipment to try that. Hopefully someone will go for it.

Hippie tends to be there's either no sec on, or there's a shitton, and with the current setup, there isn't enough gear lockers for all of them, hence the increase in size there, as I've again sat and observed as people have been unable to get any kit from a locker and have been forced to go to a Sec office to get their stuff.

As for firelock overlaps, etc, I've checked everything and I'm fairly happy it's all in order. A second set of eyes can't do any harm, but it's only a game, and if for a few rounds there's a door overlapping, is it really the end of the world? It's unprofessional, I get that, but I'm trying my best here.

Scream all you want. It's space, no-one will hear you.

**Comment by danhibiki** [comment]
I want to push for better security enforcement in the future, which means they will have to be fitted out to be able to handle larger amounts of security officers, which currently the layout can't do. Large spaces are good for the brig because of bumping into other officers being a huge problem and pretty common

**Comment by trifornt-tinfornt** [comment]
If you insist that this is fine and the airlocks aren't broken, then I'd still say that the overall massive area is still relatively dumb (especially given it's all running off of a single APC that gets drained in minutes if engineers don't set up the engine) and the main sec lockers being pushed all the way back would be a hard change but I'd give it a whirl.

**Comment by Kilmannan** [comment]
I'm not insisting anything is fine. I'm asking that people try it though, feedback, and we can tweak / change to a better solution.

I don't get this 'hard change' though. Why would it be a hard change having to go a few tiles right to get your gear?

Not being funny, I genuinely don't get why that'd be a hard change. A hard change to me would be being told I need to run halfway across the station to get my gear. Genuinely looking for your input on this one.

**Comment by TrashFiend** [comment]
The riot gear area having windows but not the general loadout area is a bit sketch

**Comment by trifornt-tinfornt** [comment]
Yeah, how did I not notice that earlier? What's the point of having super secure riot gear if any random dude can just bust down the window?
That and I still think it'd be more convenient if the riot gear stayed next to the general loadout area.

**Comment by Lawligagger** [comment]
I'd say remove the windows leading to riot from the south and I don't really know why the HOS has a window looking at gear.

**Comment by SplergeBucket** [comment]
i can fuck with it
fix the erros tho

**Comment by SplergeBucket** [comment]
erros r fixt

**Comment by danhibiki** [comment]
I'm willing to try it

**Comment by Pyko1** [comment]
Being the person who made the armory we had.

I have few issues.
First is the odd corner with window next to sec vender that should make the vender visible outside the armory.
Second is the breakable glasses to the riot gear room. 
And the third is I don't really recall any case of seeing all the 4 armors we had ever used since they have slow down.

Also sec had an airlock for a reason when the engineers/miners start breaking in to armory from space.

**Comment by TrashFiend** [comment]
Actually yeah, this armory seems far easier to break into. No need to make explosions or spend 5 years taking apart an r-wall, one window and either an emag on the barrier doors or a toolbox on the windoors looks to be enough to get in and grab guns.

**Comment by Kilmannan** [comment]
I've not updated the image, but those issues have all been fixed. Will see if I can find the image as on phone.

**Comment by Kilmannan** [comment]
https://slack-files.com/files-tmb/T085X750F-F0HGJ3M7G-cea6fd9589/pasted_image_at_2015_12_30_04_37_pm_360.png

**Comment by Kilmannan** [comment]
That's what I want Pyko, feedback, of which you've given plenty and its appreciated. I hadn't even noticed the issue with access to ablative.

As for comment on pulling lockers out with guns, that's what happens right now as neither cabinet is secured in place.

Will work on the comments made when I get back from work tonight.

**Comment by Pyko1** [comment]
Also 2 cameras right next to each other. 
capture

**Comment by danhibiki** [comment]
Theres a lot of little minor things we could tweak on this, so I'm gonna merge koko's pool update until you and pyko can sit down and get a good feel for what needs to be done.

**Comment by Kilmannan** [comment]
Righty:

Being the person who made the armory we had.

**\- Good design, just needed to be made bigger and have more floor space to move around on. Lots of people complaining about various things, I decided to dip my hand in and try to learn mapping to fix it, so please don't be offended. Things should always evolve and change.**

First is the odd corner with window next to sec vender that makes the vender visible outside the armory.
Second is the breakable glasses to the riot gear room. 

**\- Fixed previously**

And the third is I don't really recall any case of seeing all the 4 armors we had ever used since they have slow down.

**\- I've seen them deployed, and I regularly deploy them myself as Warden / HoS, or request them as a Sec officer. Slow-down or not, they're good bits of kit, and with the increase in Sec officers, it makes sense to have a decent amount of resources. I envisage a time when you'll have a full 8 man team of Riot officers descending on the greytiders, or charging in to battle against Nuke Ops whilst towing barriers and setting up makeshift defensive positions.**

Also sec had an airlock for a reason when the engineers/miners start breaking in to armory from space.

**\- Do you mean Firelock? Fixed. If you're talking about the shutter doors, there are Sec airlocks behind each one.**

Edit: Also what is with the clusterfuck of items in armory where you have to pull closets around to reach ablative and stuff? Also gun closets seem to be back in to a spot where beepsky's cant auto arrest people with no access picking them up.

**\- Fixed. Moved items around, put lockers closer to beepsky.**

Also the armory is a lot easier to break in since the desk that starts open is no longer protected by a access locked door, but instead of window to space and sec office.

**\- Fixed with a closed shutter**

Also shared access to barriers means there is easy way in with emag/hacking. Which is exactly why the old room used to start bolted.

**\- Same doors have been used, should work the same. I've stuck a shutter over it though as well.**

Except for the fact that its a lot easier just to drag a locker and steal all the guns with minimal effort.
The extra armors/lockers could had easily accomplished by just extending the current rooms meant for them without compromising security.

**\- You could always drag the gun cabinets about, it was common practice. Breach, grab a laser locker, run like fuck back to space. That's now been part mitigated by securing the lockers. As for extending the rooms, have you seen how people cry about large spaces as it is?? Ideally, yes, but I've had enough complaints about the increase in size of the armoury as it is, so a layout rejig was required to make better use of the space.**

I think overall, it is an improvement on a good system that just needed to be updated with the number we're getting now playing Sec throughout a round.

See the latest screenshot on the first post and please do comment.

**Comment by Pyko1** [comment]
I meant the external airlock that led to space, that was next to the pod.
It was kinda useful when people were dismantling walls from space, but they had not yet made a hole.

**Comment by Kilmannan** [comment]
Rgr, will look at fitting one back in.

**Comment by Pyko1** [comment]
capture
Also are you sure that the vender wont be seen on the corner tile from the sec office?
Also there seems to be some stray pipe under the vender if im seeing correctly.

**Comment by Kilmannan** [comment]
Vendor cannot be seen from the corner. Neither through the glass, or even with the window removed and you right in the corner, you can't see or identify any objects in the vendor tile - it's gone now though. All part of the cut and paste shuffle, hadn't really noticed that it does sweet fuck all where it is now!!

No, that's the air pipe that runs up and the vent is under a locker.

**Comment by Kilmannan** [comment]
What about that with the escape shuttle? Often requested to let Sec get their prisoners off. Lots of other potential (mis)uses, but a fun addition I think. No? Waiting area where they can buckle the buggers in until it's time to go too.

**Pull request merged**
