### PR TITLE
Duct tape is back baby!

### PR DESCRIPTION
**Pull request by Crystalwarrior**
+changes: 
-  - rscadd: "DUCT TAPE IS BACK BABY! You can tape people's mouths if you aim at head. Here's all the things you can craft, too:"
-  - rscadd: "Makeshift armor: Tablecrafting, put 1 sheet of metal, 1 hazardvest and 6 duct tape on the table."
-  - rscadd: "Trayshield: Apply duct tape on a tray."
-  - rscadd: "Shank: Apply duct tape on a glass shard."
-  - rscadd: "Retractable spear: Tablecrafting, put 1 telebaton, 1 shank and 5 cable coil on the table."
-  - rscadd: "Knife gloves: Tablecrafting, put boxing gloves, 2 kitchen knives and 6 duct tape on the table."
-  - tweak: "Now if you're dragged across glass shards they can embed in you. Also, if you're laying down, uniform will protect you instead of shoes."

yes i literally copy pasted changelog it's 1 AM alright

### CODE REVIEW

**Comment by FuryMcFlurry** [comment]
I love you vidam

**Comment by AliiTea** [comment]
Vadim*

**Comment by Chronitonity** [comment]
15 force is a lot for the retractable spear, literally as much as a functioning pocket knife

**Comment by Lawligagger** [comment]
The pocket knife does 15 brute last time I checked

**Comment by danhibiki** [comment]
:+1:

**Comment by Crystalwarrior** [comment]
Retractable spear is rather expensive to make so I feel that it sort of balances out.
You also permamently lose a stun weapon so it's a risky tradeoff.

**Comment by Chronitonity** [comment]
Fair nuff

**Pull request merged**
