### PR TITLE
Re-adds sharks and plushies and fixes borg floaters.

### LINKED ISSUE #1789: Ghosts can move cyborgs by clicking and dragging them while adjacent
You get a message that you begin to float and after a short delay you move the borg one tile.

### PR DESCRIPTION
**Pull request by Kokojos**
Fixes #1789

Re-adds sharks and living plushies again

### CODE REVIEW

**Comment by ghost** [comment]
icon_dead = "living_dead"

kek

:+1:

**Comment by Nokington** [comment]
sure

**Comment by danhibiki** [comment]
Yes

**Comment by Nebyab** [comment]
yeah

**Comment by TDcoolguy300** [comment]
The Kawii sharks are undying

**Comment by Carbonhell** [comment]
how exactly does this fix borg floaters sorry,i don't see any code related to ghosts or borg

**Comment by Carbonhell** [comment]
Also it'd be nice if you could make syndie plushies spawn this living plushie instead of normal carps but that's just my idea

**Comment by Kokojos** [comment]
@TDcoolguy300 I call ..() on death, this makes them still die but also do what's specified, no?
@Carbonhell The check for observers on the file code/game/objects/structures/pool.dm

**Comment by danhibiki** [comment]
..() is to call any parent information. For instance, if the sharks path is mob/animal/carp/shark, and you call ..() on any proc that is shared by the carp, then it will call all child definition for the proc. This is useful to avoid copypasting things that are already defined in a parent but you want to make slight alterations to it

**Comment by TDcoolguy300** [comment]
I know about that Koko, i meant in a sprite sense they never truly die

**Comment by Kokojos** [comment]
They continue to sparkle until love stops.

**Comment by ghost** [comment]
I'm glad you remembered that @TDcoolguy300

**Comment by nalarmg** [comment]
The fix ideally should've been in a seperate PR as it's unrelated and there's always the potential that the feature could be rejected whereas the bug fix is desired, causing unnecessary slowdown in the merging/approval processes.

Maintainers/coders, safe to merge?

**Comment by TDcoolguy300** [comment]
Code looks fine.

**Pull request merged**
