### PR TITLE
New Mac-10, CO5-R, PO57A Luger, and .44 Automag

### PR DESCRIPTION
**Pull request by Weisyl**
Added 4 new guns! These guns are the Mac-10 SMG chambered in 9mm, C05-R
(Mauser C96) chambered in .45 ACP, P057A Luger (PO-8 Luger) chambered in
.357, and .44 Automag chambered in .44 AMP. Credits to Nienhaus for the
majority of the sprites.
All guns except for the automag are currently summon-guns exclusive. A
single automag spawns on the bar counter with the nuke ops leader. It
has a 7-round magazine and does a very formidable amount of damage. Also
has some armor-piercing traits which makes it dangerous even to users of
a bulletproof vest. The ammo that comes with the automag is the only
ammo that nuke ops can ever get for it, so it is advised that you
conserve your ammo.

### CODE REVIEW

**Comment by Weisyl** [comment]
Also, here's what they all look like.
http://puu.sh/lndeb/c6faf0e6f2.png

**Comment by Nebyab** [comment]
Yeah syre

**Comment by Lawligagger** [comment]
Not that much a fan of some of the sprites on these

**Comment by Weisyl** [comment]
@lawligagger which ones specifically? Luger is the one on the far left, automag is the middle-left, C05-R is the middle-right, and Mac-10 is on the far right.

**Comment by danhibiki** [comment]
I'd do it, lets hear out hippie on the rest of this though.

**Comment by Lawligagger** [comment]
The shading on some mesh with the floor textures

**Comment by ghost** [comment]
The Mac-10 sprite is pretty old which is why it doesn't look any good.

**Pull request merged**
