### PR TITLE
Tesla {DNM}

### PR DESCRIPTION
**Pull request by AliiTea**
Ports: https://github.com/tgstation/-tg-station/pull/13258

All credit goes to Goofbal, Carn, Ausops.

### CODE REVIEW

**Comment by Weisyl** [comment]
Nice .dme there.

**Comment by Chronitonity** [comment]
Imagine waiting for this to be finished first

**Comment by AliiTea** [comment]
reeeeee
WHY does that shit always start on

**Comment by ninjacha** [comment]
Just a reminder: Goof didn't code this.

**Comment by Iamgoofball** [comment]
Aw, you being a little crybaby because you got called out on scamming people? Go back home to mommy.

Ignore the ninjacha douchenozzle.

**Comment by Lawligagger** [comment]
Sure

**Comment by Nebyab** [comment]
Ninjacha, if you want to continue your campaign against goof, please do it somewhere outside of this PR, lord knows we're dysfunctional enough as it is.

I have problems with the spritework, it just doesn't fit thematically.
I'm also not sure what this will add? Are we literally just adding it to the code? If we're going to implement this, we should actually have it on the map in game a la the old implementation of the SM, else this is just going to be something that'll never see the light of day.

**Comment by Chronitonity** [comment]
Im pretty sure it'd be added in to the map.

The sprites look fine imo, great even. We don't even have this real thematic thing going like they do anywhere else. We've got a mishmash of everything

**Comment by AliiTea** [comment]
I didn't have time to put the stuff on the map.. 

When I can I will add it to map.

**Comment by Foosili** [comment]
i for one welcome our new tesla overlords

**Comment by FuryMcFlurry** [comment]
Gateway with Tesla coils when?

**Comment by AliiTea** [comment]
idunno

**Comment by AliiTea** [comment]
Haven't been any new updates to the /tg/ PR

Going to add it to the map and consider it mergable??

**Comment by Iamgoofball** [comment]
Stil working on it,  I've been pressed for time and haven't been able to work on it.

**Comment by AliiTea** [comment]
This will be worked on in the next 1-30 days

**Comment by danhibiki** [comment]
AS chron has said in our coder chat, this pull request is closed and merged on TG, and is ready for a potential port when you are ready nex

**Comment by AliiTea** [comment]
Working on it

**Pull request closed without merging**
