### PR TITLE
Buffs Plasma Shots

### PR DESCRIPTION
**Pull request by ArcLumin**
Buffs plasma shots from plasma cutters so they don't hit like wet paper. Increases range and damage. Now you won't have to deal with 5 damage shots, which made no sense when shooting with what's supposed to be plasma.

### CODE REVIEW

**Comment by KayeArray** [comment]
I support this since plasma cutter is a joke

**Comment by ghost** [comment]
```
if(environment)
        var/pressure = environment.return_pressure()
        if(pressure < 30)
            name = "full strength plasma blast"
            damage *= 3
```

WHAT COULD POSSIBLY GO FUCKING WRONG?

I really think 90 damage plasma blasts in no air is pretty fucking nasty, even for a mech.
45 damage for a handgun in no air is still pretty horrible too.

ALSO NO FUCKING CHANGELOG.

**Comment by ArcLumin** [comment]
It's not done lad. But yeah, I forgot to tone that down

**Comment by KayeArray** [comment]
Wow fuck I missed that part, yeah pls no

**Comment by ArcLumin** [comment]
Reduces damage multiplier to 2 in low pressure, and reduces mech plasma cutter to 25.

**Comment by ghost** [comment]
This is a pretty huge buff but I agree that plasma cutters are fucking garbage despite them being cool as fuck weapons.

Yeah okay +1

**Comment by ArcLumin** [comment]
Also removed the plasma add thing

**Comment by ArcLumin** [comment]
Don't forget that plasma cutters use actual plasma ore/sheets as ammo

**Comment by ghost** [comment]
Isn't that a good thing? It's pretty easy to have lots of ammo as a miner.

**Comment by ArcLumin** [comment]
Yeah, just something to keep in mind, they're not infinite shots. Also, they have a pretty sizable delay between shots

**Comment by Spacedong** [comment]
b095d0e
@ArcLumin
ArcLumin commented a day ago

Don't forget that plasma cutters use actual plasma ore/sheets as ammo


# since when

**Comment by ArcLumin** [comment]
It has the  can_charge = 0 flag, meaning you can't charge it by normal means. Adding a plasma ore adds 500 charge, adding a plasma sheet adds 1000 charge. You can examine it to see the percent charge.

**Comment by blobbernaut** [comment]
Let them cut limbs off

**Comment by Gandalf2k15** [comment]
Code check passed. 1/4 headmin approval. HEADMINS PLS.

**Comment by doobiedoo23** [comment]
+1

**Comment by ArcLumin** [comment]
Merge when

**Comment by SplergeBucket** [comment]
+1
tbh i'd prefer them being limb cutters which do mediocre damage

**Pull request merged**
