### PR TITLE
Fixing duct taping mouths & spell book possession

### PR DESCRIPTION
**Pull request by lcass**
Makes it so you have to stand next to the person in order to ducttape their mouths. Requested by Pyko

### CODE REVIEW

**Comment by lcass** [comment]
Spell book commit added

**Comment by lcass** [comment]
Fixed cards being stuck in pockets.

**Comment by lcass** [comment]
Fixed engineering cyborg rods.

**Comment by ghost** [comment]
I'd personally prefer one pullrequest, per fix.

**Comment by lcass** [comment]
Fairly new to github , sorry about that.

**Comment by ghost** [comment]
no problem, looks good :+1: going to merge later today.

**Comment by lcass** [comment]
Awesome.

**Comment by ghost** [comment]
You added the defib code into this PR, setting it to DNM @lcass

**Comment by lcass** [comment]
Ugh yer I know , ill fix it again. Hold off , trying to sort out branches

**Comment by lcass** [comment]
Sorted , you can merge it again

**Pull request closed without merging**
