### PR TITLE
Combat Knives, pocket knives, 

### PR DESCRIPTION
**Pull request by Crystalwarrior**
Updated all guns to properly face to the right for consistency and sanity
Added pocket knives and combat knives. Combat knives cost 3 TC and have very good throwforce. Nuke Ops start with combat knives.
Made combat knives and seclites attachable to many things, including assault rifles and bulldog shotgun
Fixed species teeth not working correctly
Added coolio anims to cqc
Cleaned up brass knuckles a bit

### CODE REVIEW

**Comment by danhibiki** [comment]
shore

**Comment by Foosili** [comment]
Nice :+1:

**Comment by TDcoolguy300** [comment]
MERGE CONFLICTS ENSUED

**Comment by danhibiki** [comment]
wat

**Comment by TDcoolguy300** [comment]
Waiting for shit to happen to the cane shotgun PR, this indeed did modify shotgun.dm

**Pull request merged**
