### PR TITLE
Unhides the face behind the cluwne mask

### PR DESCRIPTION
**Pull request by TDcoolguy300**
They deserve to be seen for their horror

### CODE REVIEW

**Comment by trifornt-tinfornt** [comment]
Wait, what does this actually do?

**Comment by TDcoolguy300** [comment]
It doesnt hide the cluwne's face, AKA it prevents the UNKNOWN bullshit with their mask

**Comment by trifornt-tinfornt** [comment]
Ah.
I already suggested this, but Cluwnes in general should just be treated like how they are on Goon, in other words, makes their name "cluwne" which can't be disguised at all.
I think that'd do better here too.

**Comment by TDcoolguy300** [comment]
That requires a bunch of snowflake coding mate, i aint doing that

**Comment by trifornt-tinfornt** [comment]
Regardless, is gud PR.

**Comment by Lawligagger** [comment]
gud

**Comment by myontasm** [comment]
Yeah hiding the face with a clown mask doesn't make sense when the parent doesn't hide it.

**Comment by TheOneAndOnlyCreeperJoe** [comment]
the parent does hide it.

Seems nice to me.

**Comment by TDcoolguy300** [comment]
As creeperjoe said, the normal and sexy clown masks do hide the face, this one shouldnt however.

**Comment by Nokington** [comment]
:+1:

**Comment by Crystalwarrior** [comment]
anyone codechecked this????????

:^)

**Pull request merged**
