### PR TITLE
Tweaks

### PR DESCRIPTION
**Pull request by Kilmannan**
Improved some wiring in Brig along with some APC rejiggling.
Fixed flasher issues in Brig.
Fixed the Mime / Clown area as per:
https://github.com/HippieStationCode/HippieStation13/issues/1578

### CODE REVIEW

**Comment by danhibiki** [comment]
Sure

**Comment by Lawligagger** [comment]
Cool

**Comment by SplergeBucket** [comment]
hey
hey
fix dis pls:
#1593
ty

**Comment by ghost** [comment]
holy fuck, squash your commits.

**Comment by Kilmannan** [comment]
As if I know how to do that. I barely get GIt working at the best of time.

**Pull request merged**
