### PR TITLE
Autoimplanter

### PR DESCRIPTION
**Pull request by XeonFaux**
Ported https://github.com/tgstation/-tg-station/pull/14879

Sets the station status to red when the nuke ops declare war.

### CODE REVIEW

**Comment by XeonFaux** [comment]
Updated PR to fix heads of staff revolution bug.

**Comment by danhibiki** [comment]
:+1:

**Comment by Nokington** [comment]
:+1:

**Comment by XeonFaux** [comment]
Updated to log plasma, being lit by welder.

**Comment by Nebyab** [comment]
sure

**Pull request merged**
