### PR TITLE
Doubles the amount of blood that bloodpacks have+Adds 2 new places to maint

### PR DESCRIPTION
**Pull request by Chronitonity**
200u of blood only gives ~20% of your blood back from what it seems, this is the easiest way for me to make blood transfusions less annoying on the server, besides just doubling blood packs that we start with.

Also changes the map because I fucked up and am 2 lazy.
http://puu.sh/lyNhT/650ef0a4f3.png

http://puu.sh/lyNjB/eaf769e6dc.png

### CODE REVIEW

**Comment by ghost** [comment]
ya

**Comment by Crystalwarrior** [comment]
why not triple it?

**Comment by Chronitonity** [comment]
thats a lot of blood, if we really need more we can triple it, or just add more blood packs.

**Comment by danhibiki** [comment]
sure

**Comment by Foosili** [comment]
Oke doke

**Pull request merged**
