### PR TITLE
Sanitizes ID card inputs

### PR DESCRIPTION
**Pull request by ArcLumin**
I think this is how you sanitize? There's a few ways I've seen it done, so we'll see how travis likes this first.

Fixes https://github.com/HippieStationCode/HippieStation13/issues/3075

### CODE REVIEW

**Comment by ArcLumin** [comment]
Tested, properly sanitizes. Wew

**Comment by JohnGinnane** [comment]
image

**Comment by JohnGinnane** [comment]
Eh, can you put on "Fixes #whateverthenumberisforissue" so it auto closes the issue?

**Comment by ArcLumin** [comment]
I did already. Refresh lad

**Comment by JohnGinnane** [comment]
Cool, I wonder if we should have changelog to let players know?

**Comment by ArcLumin** [comment]
The less they know about hrefs possibly existing, the better yeah?

**Comment by JohnGinnane** [comment]
Good point

**Comment by JohnGinnane** [comment]
Merging so

**Comment by JohnGinnane** [comment]
Note to self: Wait for Travis to give the signal

**Pull request merged**
