### PR TITLE
Tesla Engine

### PR DESCRIPTION
**Pull request by Chronitonity**
i knew this was gonna happen.
- rscadd: "Ports Goofballs Tesla Engine as something else to do as an engineer."
- rscadd: "For the tesla engine, you need to wrench down all the tesla coils outside in the engine area."
- rscadd: "Then in the middle, move the singularity engine generator out of the way and wrench the tesla generator in the middle."
- rscadd: "Turn the containment shields on, and for more saftey, wrench down the grounding rods. These will hopefully prevent lightning from shocking you."
- rscadd: "Turn the PA on. It'll generate a huge ball of lightning. The longer the PA on, the more energy goes into the lightning ball, creating more smaller lightning balls that generate more power!"
- rscadd: "Be warned though, the more minature lightning balls, the more dangerous the engine is, especiall when freed."
- rscadd: "Be sure to stay safe and wear an engineering hardsuit and gloves in the event that you get near a ball of lightning."
- rscadd: "This doesn't remove the singularity, it just means you can pick between which engines to set up, or go set another engine up somewhere else now!"

Huge thanks to Gooftroop obviously.

http://puu.sh/m387E/8c0c28d26e.png

### CODE REVIEW

**Comment by Chronitonity** [comment]
Also heres the engine room 
http://puu.sh/m38OI/4261b62a87.png

**Comment by Lawligagger** [comment]
+1

**Comment by Nebyab** [comment]
As much as I hate new things, this isn't bad. I really do think its neat, but I do have some issues with the mapping of the singulo/energy ball pen. Its looks a bit fugly, and could do with a bit of love. Other than that, it seems great and chrons resolved all my spelling and grammar issues I've found thus far.

**Comment by Foosili** [comment]
GOOD SHIT

**Comment by Iamgoofball** [comment]
> DIDNT MAP MERGE

TOP KEK/10

**Pull request merged**
