### PR TITLE
Adds Mothmen wings

### PR DESCRIPTION
**Pull request by TDcoolguy300**
http://puu.sh/nKu7F/c6d785a476.png I am lazy to get the full image set right now.

### CODE REVIEW

**Comment by Zadeon** [comment]
Push this now mothpeople.

**Comment by Spacedong** [comment]
:+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1:

**Comment by Leon454** [comment]
+1 for more special snowflake options for MUH IMMULSIONS

**Comment by calibraptor** [comment]
Merge dis

**Comment by FuryMcFlurry** [comment]
here is a preview of how it is intended to look

**Comment by ghost** [comment]
> more mothman snowflake bullshit

kill urself my man

:+1: anyway

**Comment by Nebyab** [comment]
ok

**Comment by Carbonhell** [comment]
Code's ok

**Comment by Lawligagger** [comment]
yes

**Pull request merged**
