### PR TITLE
Fix for Multiple Messages when Farting on Somebody

### PR DESCRIPTION
**Pull request by Zadeon**
This just fixes both messages of you farting and you farting on somebody displaying when you do fart on somebody. Now it'll only show you farted on somebody. 

Also cleans up some old code being used.

### CODE REVIEW

**Comment by Carbonhell** [comment]
codewise it's ok,not sure how many people consider this as a bug through

**Comment by Zadeon** [comment]
I guess just label this as a feature then?

**Comment by Nebyab** [comment]
i mean sure alright

**Comment by ghost** [comment]
good shit tbh. Also maybe the damage dealt should be changed so that it's not static in case the ass-damage is ever changed

**Comment by Nokington** [comment]
:+1:

**Pull request merged**
