### PR TITLE
MEESEEKS MUST RETURN!

### PR DESCRIPTION
**Pull request by XeonFaux**
Add's meeseeks boxes as a possibility in maintenance loot, and in contraband locker.
Changed meeseeks box to self destruct upon recalling the meeseek.

### CODE REVIEW

**Comment by Lawligagger** [comment]
Definitely

**Comment by GunHog** [comment]
You Hippies know what fun is!

**Comment by AliiTea** [comment]
Bad Idea 2.0

**Comment by Higitus1** [comment]
good idea 3.0

**Comment by yobob591** [comment]
nigga this shit over a year and a half old on an old repo why u be commenting

**Comment by Higitus1** [comment]
I completely forgot I did this, but its still a good idea

**Pull request merged**
