### PR TITLE
Noose Decap Fix

### PR DESCRIPTION
**Pull request by Gandalf2k15**
People will now drop from nooses when decapped.
Only unbuckles if people are noosed.
Fixes https://github.com/HippieStationCode/HippieStation13/issues/2594
Demo: https://dl.dropboxusercontent.com/u/109295987/ShareX/2016/07/2016-07-10_00-50-28.mp4

### CODE REVIEW

**Comment by Spacedong** [comment]
wait so if I chop a guy's head off and he's buckled to a chair he'll fall over? what

**Comment by Nebyab** [comment]
ok sure

**Comment by Spacedong** [comment]
this can get merged its a bug fix

**Comment by JohnGinnane** [comment]
Looks good. Merging

**Pull request merged**
