### PR TITLE
Janicart Storage increase

### PR DESCRIPTION
**Pull request by AliiTea**
Increases the amount of water the janicart can hold from 100 -> 400

### CODE REVIEW

**Comment by Spacedong** [comment]
dude why do you just keep spitting out meme PRs that nobody asked for, like literally what PURPOSE

to what end

**Comment by AliiTea** [comment]
Makes Janitors life easier by not having to run to a water tank every time they clean a large area.

**Comment by Spacedong** [comment]
also you spelled "Increased" wrong in your changelog, its currently "Oncreased"

**Comment by trifornt-tinfornt** [comment]
Why not increase the amount of space cleaner that they have in their backpack tank instead of the janicart - the latter of which is just going to incite more people to beat up the janitor that is wetting the floors?

**Comment by Kokojos** [comment]
I think having water clean up is an essencial and proven annoyance of SS13 that needs to stay. The cart gets stolen all the time anyway,

**Comment by Spacedong** [comment]
theres another cart in chapel maintenance

**Comment by Pyko1** [comment]
to be honest all teh containers need an overhaul how much hey can hold

**Comment by Pyko1** [comment]
basically make bucket hold 700 instead of 70 abd nak it not fit in chem machine. Make chem storages hold 10k instead if 1k

**Comment by Pyko1** [comment]
and balance otehr shit around that

**Comment by AliiTea** [comment]
Could some heads look at this?

Not adding anything else to this PR so what you see is what I am doing.

**Comment by Nokington** [comment]
:+1:

**Comment by Lawligagger** [comment]
Sure

**Pull request merged**
