### PR TITLE
Changes the mob sprite for the Golden AK992

### PR DESCRIPTION
**Pull request by TheOneAndOnlyCreeperJoe**
Makes it look less like an aborted child and more like a genuine gun. Need I sayeth more?
The floor icon or the icon on the UI remains unchanged.

Will likely cause a decrease in Syndicate Operative suicide rates of around 3.45% and decreasing depression by another 6.9%.
goldenakresprite - presentation

### CODE REVIEW

**Comment by ghost** [comment]
This PR pinged me in slack because it said "aborted" lmao.
+1

**Comment by Kokojos** [comment]
IT CALLS TO YOU

**Comment by Spacedong** [comment]
no it looks fine

**Comment by Hackole** [comment]
These look pretty good, I like 'em. +1

**Comment by TheOneAndOnlyCreeperJoe** [comment]
has 2 head approvals merge pl0x

**Comment by Pyko1** [comment]
Approved, merging

**Pull request merged**
