### PR TITLE
World's smallest layering bugfix

### PR DESCRIPTION
**Pull request by ghost**
Fixes https://github.com/HippieStationCode/HippieStation13/issues/2623

It's one line of code.

### CODE REVIEW

**Comment by ghost** [comment]
This PR was an exercise in patience.

It's like trying to thread a needle with dicks for fingers.

**Comment by Carbonhell** [comment]
I don't think this is the proper fix, you sure it is?

**Comment by ghost** [comment]
Well I mean I tested it and it works.

What makes you think it isn't?

**Comment by Pyko1** [comment]
Pretty much all the machinery is 3.0, I think it would be better to move the tanks above it.

**Comment by ghost** [comment]
Pretty much everything in general is 3.0

I figure moving the dispenser down makes more sense than moving the tanks up, since dispensers dont tend to move much during the round at all.

**Comment by carlarc** [comment]
yes please

**Comment by Gandalf2k15** [comment]
Code looks good. I'll ask this one question, did you test it?

**Comment by Gandalf2k15** [comment]
Holding off as per request.

**Comment by Carbonhell** [comment]
Issue is not caused by the layer probably,because the bug appears to happen only with one tank dispenser,the one in atmospherics control room. Check if that dispenser's fixed with the layer edit.

**Comment by ghost** [comment]
That's the one I tested.

I can tell you without a shadow of doubt that this will fix the issue, only question is whether you think this is the best way to go about it.

**Comment by Carbonhell** [comment]
Mah, i don't get why this bug applies to a single tank dispenser. I still don't think this is a code issue,but rather a mapping issue,but if you claim it fixes it, then merging

**Pull request merged**
