### PR TITLE
Option to view changelog on login

### PR DESCRIPTION
**Pull request by nalarmg**
Adds the ability to view the changelog on login. Has a preference to disable.

### CODE REVIEW

**Comment by Kokojos** [comment]
Isin't it important that every player see gameplay changes? It's a one hit annoyance at worst.

**Comment by Kokojos** [comment]
Rephrased : It pops up already, at least for me, each time there's at least one change.

**Comment by WhiteFox08** [comment]
Eh I'm not to sure about this. People could miss out on critical info.

**Comment by Chronitonity** [comment]
:-1:

**Comment by ghost** [comment]
You ALWAYS see the changelog when it's changed, the md5 hash of the html file is saved in the savefile which shows the changelog if it changes

**Comment by nalarmg** [comment]
This is less of a good idea now than it was at 3 AM. RIP.

**Pull request closed without merging**
