### PR TITLE
Medbay sec checkpoint mk2

### PR DESCRIPTION
**Pull request by TheMocheeze**
100% less accidental carpet this time

http://i.hizliresim.com/rVyOZa.png

### CODE REVIEW

**Comment by Chronitonity** [comment]
:+1:

**Comment by Chronitonity** [comment]
@nalarmg @SplergeBucket This version has the fixed carpet and jazz you two didn't like

**Comment by TheMocheeze** [comment]
Also this adds the chemlab and toxins revamp as seen here http://i.hizliresim.com/B0GNLv.png

**Comment by Kokojos** [comment]
Not mapmerged correctly.

---

Sec area need better window placement on the left side, also lacks a light switch. Otherwise it seems good.

## 

No firelocks on smaller chemlab and toxins.

Way too much freezer/heater, pretty sure all those pipes are unlabeled.

Canister and pipes could be more effeciently placed, currently it forms 2 clusterfucks and a long corridor.

Also the WHOLE toxin lab and some area of the  is missing lights, test your fucking things.
Atmos placement kinda abysmal.

Plus sincerely the whole new chemlab + new toxin test area look like shit. :-1:

**Comment by Kokojos** [comment]
And also I bet the camera Ctags are not set correctly.
There's 2 cameras next to eachother in the new chemlab.

Lacking cameras in the main toxin lab. Il reiterate again, but :-1:

**Comment by TheMocheeze** [comment]
http://i.hizliresim.com/B0GgAG.png cameras, lights, igniter, pumps work, once-over'd.

**Comment by SplergeBucket** [comment]
I'm for the Med changes you've made being merged.

**Comment by WhiteFox08** [comment]
Check with @Pyko1 before merging.

**Comment by TheMocheeze** [comment]
Bump, you slow fux

**Pull request merged**
