### PR TITLE
Allow removal of special snowflakes.

### PR DESCRIPTION
**Pull request by ghost**
CATBANNING, stolen from @Memendia.

catban

### CODE REVIEW

**Comment by Kokojos** [comment]
Yesss

**Comment by AliiTea** [comment]
Ayyy lmao you gave me credit... but go give Scooter credit.. he made it in the first place.

**Comment by AliiTea** [comment]
Also where is your changelog!?

**Comment by ghost** [comment]
@Memendia admin stuff needs no changelog imho

**Comment by AliiTea** [comment]
@HoaxIT :I let the peasants know what's coming

**Comment by ghost** [comment]
@Memendia there we go.

**Comment by AliiTea** [comment]
@HoaxIT not fully green gtfo

**Comment by ghost** [comment]
@Memendia 100% GREEN.

**Comment by AliiTea** [comment]
@HoaxIT   OH REALLY

We can’t automatically merge this pull request.
Use the command line to resolve conflicts before continuing.

**Comment by ghost** [comment]
@Memendia IT WAS GREEN WHEN I POSTED THIS.

**Comment by AliiTea** [comment]
WELL
IT'S NOT ANYMORE

**Comment by AliiTea** [comment]
Fix it Fix it Fix it Fix it

**Comment by ghost** [comment]
@Memendia MEME'D IT

**Comment by AliiTea** [comment]
@HoaxIT not green get fukkd

**Comment by ghost** [comment]
@Memendia GREEN

**Comment by Kokojos** [comment]
Merging this shit.

**Comment by AliiTea** [comment]
@HoaxIT totally forgot about this thing :'D

**Pull request merged**
