### PR TITLE
Fixes pinning on forced movement and icon when un-pinned

### PR DESCRIPTION
**Pull request by Tomeno**
Fixes issue #302 and another bug I found out about while fixing this - your offset when pinned doesn't go back when you get unpinned.

### CODE REVIEW

**Comment by Tomeno** [comment]
The second commit's diff is a little messed up in Github because I didn't update the branch before editing stuff so it lists all the other things as a change even though they're not changed from the current version on here...

**Comment by Kokojos** [comment]
:+1:

**Comment by Nokington** [comment]
Please update your branch so we don't have to revert this if one of those other things get reverted.

**Comment by Tomeno** [comment]
I have updated my fork, but it still shows up like this for some reason :( Can't do anything about it

**Comment by Nokington** [comment]
aaaaaaaaaaaaaaaaaaaa
fine
i'm blaming you for all my problems now

**Pull request merged**
