### PR TITLE
Fixes heal related things not removing bullets correctly

### LINKED ISSUE #650: Bullet Surgery don't work, t. Surgeon General
Reply PM from-Killing Torcher/(Killing Torcher): alright so
Reply PM from-Killing Torcher/(Killing Torcher): I was braindead for a while, I got back and the botanist shot me in the head, quite a few times. A guy saved me and defibed me. He cryo'd me and when I was fixed, I went and gave myself synaptizine, anti-toxins and imidazoline from chemistry. I noticed I was still bleeding from my head. I tried to fix it with gauze, it didn't work. So I concluded it was the bullets. I went to surgery and gave myself bullet surgery on my head, but it didn't work. That's basically it. So I kept bleeding. Eventually another antag came with a gun and killed me.

tl;dr did the surgery for digging for bullets; it listed that he didn't have anything in his head, bleeding didn't stop as a result of the invisible bullets lodged in his skull and he died

### LINKED ISSUE #665: Staffs of healing/admins still don't fix bullets ahhhh
they set the list of entries to be null without actually removing the entries, and the bleeding is based only on the number of entries, not what's in them. So basically, it's even worse than before, because the person cannot have the ghost bullets removed via surgery.

### PR DESCRIPTION
**Pull request by Carbonhell**
DNM yet,need to see if this shitchangelog works

Fixes #665 and Fixes #650

### CODE REVIEW

**Comment by Carbonhell** [comment]
fixes #665

**Comment by Carbonhell** [comment]
also fixes #650

**Comment by Chronitonity** [comment]
Put what commits you fix in the title, if this gets merged it should autoclose those.

**Comment by Carbonhell** [comment]
I tried that once and it didn't work...?I'll try to,next time

**Pull request merged**
