### PR TITLE
Re-adds the prototype station, and KEEPS the old comms sattelite. 

### PR DESCRIPTION
**Pull request by Kokojos**
Exactly my old pr, but this keeps the satellite and moves around stuff in z-3 so people don't just have to drift in straight lines to reach them.

### CODE REVIEW

**Comment by Kokojos** [comment]
Old comments here : https://github.com/HippieStationCode/HippieStation13/pull/2359
Basicly a +1 from Nebyab.

**Comment by dreamcrab** [comment]
yes i like

**Comment by ghost** [comment]
Please someone check this.

**Comment by Kokojos** [comment]
Since there's no actual code besides the book - and I checked them, il merge this myself.

**Comment by calibraptor** [comment]
Yay more space stuff

**Pull request merged**
