### PR TITLE
RUSSIAN SHIT UPDATE v2 egh

### PR DESCRIPTION
**Pull request by ghost**
ow you can be a real fucking adidas-wearing russian
https://www.youtube.com/watch?v=APnPH9u8-zs
https://i.gyazo.com/03a43032341d3322f3df90230e04658a.gif
^^^ rare footage of gopniki

mosin is refurbished and looks 10x better, can go on your back now ( how
was this missing )
new revolver reskin
cqc gloves 12 tc ( we can work out costs, i made it pretty expensive for
a reason to start off with)
IMAGES
https://i.gyazo.com/5c0cf1340c7ade33611247a42695f2c1.png
https://i.gyazo.com/55c4ce63d1ec4be8ccda7c2f55670221.png
https://i.gyazo.com/958ba91eac593e03d474d3837b7b4dfc.png
literally the same thingg

### CODE REVIEW

**Comment by ghost** [comment]
someone should merge this ;)

**Comment by danhibiki** [comment]
Eh, sure.

**Comment by Weisyl** [comment]
I don't like your new mosin actually. It actually looks like a sawn-off or obrez version of the mosin, rather than the full-sized rifle.

**Comment by ghost** [comment]
i actually didnt show both sprites i think

**Pull request merged**
