### PR TITLE
Adds Temmie

### PR DESCRIPTION
**Pull request by Weisyl**
Added Temmie. Temmie can also be summoned by badmins through the temmierune subtype of the golemrune, via the create object panel.
http://puu.sh/lA8Wc/18588c12a9.png

### CODE REVIEW

**Comment by TDcoolguy300** [comment]
:+1: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Comment by Lawligagger** [comment]
why

**Comment by Weisyl** [comment]
Hey why not?

**Comment by ghost** [comment]
useless funny mob that will never be used
add it

**Comment by danhibiki** [comment]
Counterpoint: Its just bloat then.And we have a lot as is.

**Comment by Weisyl** [comment]
I've seen no real resistance to us adding other pointless mobs. As is, we have a whole bunch of mobs that are practically never seen.

**Comment by ghost** [comment]
anoyying dog is literally tem
and was accepted and its a good feature so lets add this

**Comment by calibraptor** [comment]
hOI!

**Comment by Nebyab** [comment]
yeah syre

**Comment by Crystalwarrior** [comment]
I'd rather have Tem actually do more stuff rather than just say "hOI!!" on repeat.
Can you do something more along the lines of buttbot where Temmie mocks you or mimmicks you or does other random bullshit? That'd be much more substantial hue

**Comment by Weisyl** [comment]
@Crystalwarrior They don't really do that from what I know.

**Comment by Weisyl** [comment]
Closing this to make room for my hugh jass PR coming up soon so that it isn't thrown in with this.

**Pull request closed without merging**
