### PR TITLE
Ports TG prs from Adds del() log to world log(12184) to Prepare Maps bat for entire _maps directory(12287)

### PR DESCRIPTION
**Pull request by Carbonhell**
First wave, page 89 to 87,still a lot to do

--CHANGES CONFIG FILE

--The only feature is the addition of alien praetorians, the rest is all bugfixes/refractor
thanks tg obviously

### CODE REVIEW

**Comment by Pyko1** [comment]
And then, errywing was broken!

But then again its been a while since server was broken, lets have cuckbonehell take the blame this time. :+1:

**Comment by Carbonhell** [comment]
As commit says, pyko pointed out it's pretty useless for us so i reverted it

**Comment by TrashFiend** [comment]
This does change some actual stuff:

This buffs the alien queen from 250 health to 400. Probably a good thing tbh, queens are a bit weak. 

This also seems to remove the giant alien queen thing, which was literally just an alien queen with the same sprite but larger. No real loss.

Mobs that aren't advanced tool users won't be able to use hand labelers anymore, but monkey and drone are both covered so it shouldn't matter.

You can't use telekinesis to take cups from water coolers anymore. How else are you going to impress your co-workers around the water cooler?

**Comment by Nebyab** [comment]
I'm alright with everything but the "You can't use telekinesis to take cups from water coolers anymore. How else are you going to impress your co-workers around the water cooler?" bit. Fix that

**Comment by Carbonhell** [comment]
done

**Comment by Nokington** [comment]
:+1:

**Comment by Carbonhell** [comment]
Why is this still opened after 5 days...?

**Pull request merged**
