### PR TITLE
Adds in colored reagents + Bleach

### PR DESCRIPTION
**Pull request by ArcLumin**
Come back to spess after being busy as fuck, get banned for 4 days within 24 hours of being back for giving the crew grenades for free. Best. Time to code, at least.

:cl:
rscadd: Added Bleach. Bleach is made with Space Cleaner, Sodium and Chlorine. Removes colored reagents, but harmful if ingested.
rscadd: Adds colored reagents. These are made using colorful reagent and the color of crayon powder you want to turn the reagent. This means you don't have to hope for a random color each time you use it!
/:cl:

Still trying to get used to git, so let's hope this PR works right this time. Read in a guide that adding that above will autolog it to the changelog, but we'll see.

Currently, colorful reagent can't be removed by anything, making everyone covered in permanent color changes for the whole round. Bleach will remove those color changes. Colored reagents are to force it to be a specific color rather than a random one. Was testing an "invisibility reagent" using mime crayon powder, but was far too OP. Perhaps I'll retool it as an invisibility potion that can only be ingested that turns you invisible for a short time. But for now, this is good enough.

### CODE REVIEW

**Comment by ArcLumin** [comment]
Indentation errors, great. Fixing

**Comment by LuisReyesX** [comment]
seems good to me

**Comment by TDcoolguy300** [comment]
Code is indeed fine.

**Comment by LuisReyesX** [comment]
wow im a master coder

**Comment by ghost** [comment]
This is pretty dope tbh, +1.

**Comment by dreamcrab** [comment]
neato +666

**Comment by Voratius** [comment]
bleach nade? hell yeah +1/3rd

**Comment by Kokojos** [comment]
Votes match.
Merging

**Pull request merged**
