### PR TITLE
Added new reflective mirror

### PR DESCRIPTION
**Pull request by JohnGinnane**
This is a new structure that reflects lasers and beams (including emitters). Use a wrench to anchor/unanchor the mirror. Use a crowbar to change the direction.

Can be built with 2 sheets of plasteel; Craft the base, then add 1 sheet of silver, and 1 sheet of reinforced glass and screwdriver to finish.

Quick videos showing it:

Assembly: https://gfycat.com/HiddenScholarlyChrysalis
Movement: https://gfycat.com/HoarseMetallicInexpectatumpleco
Disassembly: https://gfycat.com/GraveBrilliantCarpenterant
Fun: https://gfycat.com/FreeBiodegradableFoxhound
Emitters 1: https://gfycat.com/LawfulNaturalCopperhead
Emitters 2: https://gfycat.com/SpanishHardEastrussiancoursinghounds

Also note that this still acts like a regular mirror, so you can change your appearance.

### CODE REVIEW

**Comment by ArcLumin** [comment]
Silver + plasteel + rglass to make, do it

**Comment by JohnGinnane** [comment]
Reinforced glass? Why

**Comment by ArcLumin** [comment]
plasteel frame, silver for reflective, rglass for scratch and tarnish resistant coating. It's to mirror actual mirror making processes

**Comment by JohnGinnane** [comment]
Alright, and what about numbers on those? What about ordering from cargo? And what if some department started with them?

**Comment by TDcoolguy300** [comment]
The Entertainment department(See clown and mime) get mirrors so they can apply their makeup and ensure they look good for entertaining(Blood optional)

**Comment by ArcLumin** [comment]
two sheets of plasteel, one sheet of silver, one sheet of rglass. Some in engie storage, cargo orderable

**Comment by ArcLumin** [comment]
also let them reflect light for anti sling

**Comment by JohnGinnane** [comment]
How would they even be created? Using plasteel crafting menu?

**Comment by JohnGinnane** [comment]
>reflect light for anti sling

Okay gonna need to checkout how that works..

**Comment by TDcoolguy300** [comment]
Plasteel crafting menu to create the frame, apply silver, then apply Rglass

**Comment by ArcLumin** [comment]
yeah, frame, silver, glass

**Comment by JohnGinnane** [comment]
Emitters currently do not work: https://gfycat.com/OrganicFavoriteChupacabra

**Comment by Spacedong** [comment]
awesome

**Comment by JohnGinnane** [comment]
This is WIP, added a way to create this. Still some issues I want to fix (missing icon for broken mirror)

**Comment by ArcLumin** [comment]
Code's good, might want to update changelog on how to make them

**Comment by JohnGinnane** [comment]
Okay, it's updated, but I'm gonna try and work on legacy projectiles (for emitter) and see what I can do there.

**Comment by JohnGinnane** [comment]
Still WIP, added some new functionality but almost ready to go

**Comment by Hackole** [comment]
This is cool as fuck, +1 assuming you get it done

**Comment by JohnGinnane** [comment]
Okay, emitters work with mirrors and I've updated the icons a little. Gonna do some testing and update soon

**Comment by ArcLumin** [comment]
If only it could reflect light. But that'd be hard in our current light system so hey. Unless we had like, a light beam (that wasn't a laser)

**Comment by JohnGinnane** [comment]
I can look at that soon, how exactly is light processed?

**Comment by ArcLumin** [comment]
Light basically is like, "this tile has 5 so the next tile has 4 light" and so on

**Comment by JohnGinnane** [comment]
Okay, updated it lots, just noticing runtimes, gonna look at those and then see what we can do about slings

**Comment by JohnGinnane** [comment]
Okay, looks like I was mistaken, no runtimes!

**Comment by JohnGinnane** [comment]
@ArcLumin which abilities do you want potentially reflected?

**Comment by ArcLumin** [comment]
Just lights, so I could make a mirror maze of light

**Comment by JohnGinnane** [comment]
Might look at in another PR. For now this is ready, unless we want mirrors to be set up in the station by default?

**Comment by ArcLumin** [comment]
Neat, but not necessary.

**Comment by Swagile** [comment]
honestly more gimmick items like this is great

and i can finally make a full hallway mirror emitter trap where it keeps reflecting until it hits a grey shit

**Comment by Swagile** [comment]
btw that was a gm + 1, i didn't specify correctly

so its 1/3 right now

**Comment by SpankMasterson** [comment]
neat, +1

**Comment by ArcLumin** [comment]
Code's good, merging before spank gets the chance to. MERGE SNIPE BOYS

**Pull request merged**
