### PR TITLE
Supermatter Crystal Port

### PR DESCRIPTION
**Pull request by calibraptor**
- This is the real deal, the big supermatter crystal is back and capable 
  of producing OVER ONE MILLION WATTS of power! (The singularity by comparison produces two millon. Sky's the limit with the tesla.)
- Added more shutter buttons for the sake of convenience.
- Added some wire leading from the SMES room into the maint west of it connecting to the main grid. This'll ensure that if the SM detonates while there's a singulo up, the station won't be entirely without power.

real deal

### CODE REVIEW

**Comment by blobbernaut** [comment]
one MILLION watts...http://www.goodfinancialcents.com/wp-content/uploads/2011/12/dr.-evil-million-dollar-term-policy-300x241.jpg

**Comment by ghost** [comment]
Let it all burn
+1

**Comment by dreamcrab** [comment]
can you make it so people cant click on the SM at all? dragging the SM with a radsuit is mega-cheese and lame

**Comment by calibraptor** [comment]
@dreamcrab The supermatter is now anchored, but still launchable with the mass driver. If it collides with anything when it's launched it will explode in roughly 10 seconds after the collision. So if it loops around and hits the station it will float some distance back into space before going kaboom.

**Comment by TDcoolguy300** [comment]
Code looks fine to me

**Comment by Nebyab** [comment]
can you also remove the tesla at a later date?

But this pr alone is wonderful

**Comment by calibraptor** [comment]
That looks like an okay from two heads. This is ready to merge. Three if you count me fulfilling dreamcrab's request.

**Comment by TDcoolguy300** [comment]
Don't fuck me over, code reading ability

**Comment by ghost** [comment]
aw fuk, you forgot to change the name on the changelog

**Pull request merged**
