### PR TITLE
Brig and Arrivals fixes

### PR DESCRIPTION
**Pull request by Kilmannan**
As noted here:
https://github.com/HippieStationCode/HippieStation13/issues/1571

And re-did my brig fixes which seem to have been reverted somehow.

### CODE REVIEW

**Comment by Kilmannan** [comment]
What is all this merge remote shit? How do I stop that from coming  up?

**Comment by nalarmg** [comment]
Conflicts needs to be fixed.

**Comment by Kilmannan** [comment]
What?? There was no conflicts when I first PRd it

**Comment by nalarmg** [comment]
Possibly from other map changes that may have ended up merged. Not sure otherwise.

**Comment by AliiTea** [comment]
Pull the newer map and just throw your fixes on top and the conflicts will be fixed

**Comment by nalarmg** [comment]
Still conflicted. Unable to merge.

**Comment by Nokington** [comment]
This is kinda dead now. Still conflicts.

**Comment by nalarmg** [comment]
Over a week with no changes or feedback with visible intention on updating. Closing this for now. Please feel free to re-open it if this regains interest.

**Pull request closed without merging**
