### PR TITLE
Fixes Bartender having syndie pins

### PR DESCRIPTION
**Pull request by ghost**
ONE LINE MY DUDE

### CODE REVIEW

**Comment by KayeArray** [comment]
inb4 dongcode

**Comment by ghost** [comment]
This fix is better than the other PR. It doesn't matter if newcops can grab the non-syndie contender and blast their way into the blast-co armory now that the anti-theft devices are fixed.

**Comment by ArcLumin** [comment]
I mean, very much the same as the other pr, but I don't care whats merged

**Comment by KittyKathy** [comment]
This would also make improvised shotguns and cane shotguns also have a generic pin now.

**Comment by ghost** [comment]
From what the other PR said, the only difference with syndie pins is that they won't fire on certain z-levels. If you see a cane with a firing pin in it, there isn't really a non-syndie cane shotgun to confuse it with.

**Comment by KittyKathy** [comment]
Yeah not right now but maybe there will be in the future also syndicate guns should have syndicate pins.

**Comment by SpankMasterson** [comment]
Can we be sure this won't break the game? I do not trust the coder.

**Comment by ArcLumin** [comment]
Can confirm that this will not break the game. This is not dongcode

**Comment by ArcLumin** [comment]
You know what, seeing that this was an oversight, might as well merge it as a bugfix. Merging

**Pull request merged**
