### PR TITLE
Fixes butts runtiming

### PR DESCRIPTION
**Pull request by ghost**
proc name: handle blood (/mob/living/carbon/human/handle_blood)
  source file: blood.dm,117
runtime error: Cannot read null.contents
proc name: handle blood (/mob/living/carbon/human/handle_blood)
  source file: blood.dm,117
runtime error: Cannot read null.contents
proc name: handle blood (/mob/living/carbon/human/handle_blood)
  source file: blood.dm,117
runtime error: Cannot read null.contents
proc name: handle blood (/mob/living/carbon/human/handle_blood)
  source file: blood.dm,117
runtime error: Cannot read null.contents
proc name: handle blood (/mob/living/carbon/human/handle_blood)
  source file: blood.dm,117
runtime error: Cannot read null.contents
proc name: handle blood (/mob/living/carbon/human/handle_blood)
  source file: blood.dm,117
runtime error: Cannot read null.contents
proc name: handle blood (/mob/living/carbon/human/handle_blood)
  source file: blood.dm,117
runtime error: Cannot read null.contents
proc name: handle blood (/mob/living/carbon/human/handle_blood)
  source file: blood.dm,117
runtime error: Cannot read null.contents
proc name: handle blood (/mob/living/carbon/human/handle_blood)
  source file: blood.dm,117
runtime error: Cannot read null.contents
proc name: handle blood (/mob/living/carbon/human/handle_blood)
  source file: blood.dm,117
runtime error: Cannot read null.contents
proc name: handle blood (/mob/living/carbon/human/handle_blood)
  source file: blood.dm,117
runtime error: Cannot read null.contents
proc name: handle blood (/mob/living/carbon/human/handle_blood)
  source file: blood.dm,117
runtime error: Cannot read null.contents
proc name: handle blood (/mob/living/carbon/human/handle_blood)
  source file: blood.dm,117
runtime error: Cannot read null.contents
proc name: handle blood (/mob/living/carbon/human/handle_blood)
  source file: blood.dm,117
runtime error: Cannot read null.contents
proc name: handle blood (/mob/living/carbon/human/handle_blood)
  source file: blood.dm,117
runtime error: Cannot read null.contents
proc name: handle blood (/mob/living/carbon/human/handle_blood)
  source file: blood.dm,117
runtime error: Cannot read null.contents
proc name: handle blood (/mob/living/carbon/human/handle_blood)
  source file: blood.dm,117
runtime error: Cannot read null.contents
proc name: handle blood (/mob/living/carbon/human/handle_blood)
  source file: blood.dm,117
runtime error: Cannot read null.contents
proc name: handle blood (/mob/living/carbon/human/handle_blood)
  source file: blood.dm,117
runtime error: Cannot read null.contents
proc name: handle blood (/mob/living/carbon/human/handle_blood)
  source file: blood.dm,117
runtime error: Cannot read null.contents
proc name: handle blood (/mob/living/carbon/human/handle_blood)
  source file: blood.dm,117
runtime error: Cannot read null.contents
proc name: handle blood (/mob/living/carbon/human/handle_blood)
  source file: blood.dm,117
runtime error: Cannot read null.contents
proc name: handle blood (/mob/living/carbon/human/handle_blood)
  source file: blood.dm,117
runtime error: Cannot read null.contents
proc name: handle blood (/mob/living/carbon/human/handle_blood)
  source file: blood.dm,117
runtime error: Cannot read null.contents
proc name: handle blood (/mob/living/carbon/human/handle_blood)
  source file: blood.dm,117
runtime error: Cannot read null.contents
proc name: handle blood (/mob/living/carbon/human/handle_blood)
  source file: blood.dm,117
runtime error: Cannot read null.contents
proc name: handle blood (/mob/living/carbon/human/handle_blood)
  source file: blood.dm,117
runtime error: Cannot read null.contents
proc name: handle blood (/mob/living/carbon/human/handle_blood)
  source file: blood.dm,117
runtime error: Cannot read null.contents
proc name: handle blood (/mob/living/carbon/human/handle_blood)
  source file: blood.dm,117
runtime error: Cannot read null.contents
proc name: handle blood (/mob/living/carbon/human/handle_blood)
  source file: blood.dm,117
runtime error: Cannot read null.contents
proc name: handle blood (/mob/living/carbon/human/handle_blood)
  source file: blood.dm,117
runtime error: Cannot read null.contents
proc name: handle blood (/mob/living/carbon/human/handle_blood)
  source file: blood.dm,117
runtime error: Cannot read null.contents
proc name: handle blood (/mob/living/carbon/human/handle_blood)
  source file: blood.dm,117
runtime error: Cannot read null.contents
proc name: handle blood (/mob/living/carbon/human/handle_blood)
  source file: blood.dm,117
runtime error: Cannot read null.contents
proc name: handle blood (/mob/living/carbon/human/handle_blood)
  source file: blood.dm,117
runtime error: Cannot read null.contents
proc name: handle blood (/mob/living/carbon/human/handle_blood)
  source file: blood.dm,117
runtime error: Cannot read null.contents
proc name: handle blood (/mob/living/carbon/human/handle_blood)
  source file: blood.dm,117
runtime error: Cannot read null.contents
proc name: handle blood (/mob/living/carbon/human/handle_blood)
  source file: blood.dm,117
runtime error: Cannot read null.contents
proc name: handle blood (/mob/living/carbon/human/handle_blood)
  source file: blood.dm,117
runtime error: Cannot read null.contents
proc name: handle blood (/mob/living/carbon/human/handle_blood)
  source file: blood.dm,117
runtime error: Cannot read null.contents
proc name: handle blood (/mob/living/carbon/human/handle_blood)
  source file: blood.dm,117
runtime error: Cannot read null.contents
proc name: handle blood (/mob/living/carbon/human/handle_blood)
  source file: blood.dm,117
runtime error: Cannot read null.contents
proc name: handle blood (/mob/living/carbon/human/handle_blood)
  source file: blood.dm,117
runtime error: Cannot read null.contents
proc name: handle blood (/mob/living/carbon/human/handle_blood)
  source file: blood.dm,117
runtime error: Cannot read null.contents
proc name: handle blood (/mob/living/carbon/human/handle_blood)
  source file: blood.dm,117
runtime error: Cannot read null.contents
proc name: handle blood (/mob/living/carbon/human/handle_blood)
  source file: blood.dm,117
runtime error: Cannot read null.contents
proc name: handle blood (/mob/living/carbon/human/handle_blood)
  source file: blood.dm,117
runtime error: Cannot read null.contents
proc name: handle blood (/mob/living/carbon/human/handle_blood)
  source file: blood.dm,117
runtime error: Cannot read null.contents
proc name: handle blood (/mob/living/carbon/human/handle_blood)
  source file: blood.dm,117
runtime error: Cannot read null.contents
proc name: handle blood (/mob/living/carbon/human/handle_blood)
  source file: blood.dm,117
runtime error: Cannot read null.contents
proc name: handle blood (/mob/living/carbon/human/handle_blood)
  source file: blood.dm,117
runtime error: Cannot read null.contents
proc name: handle blood (/mob/living/carbon/human/handle_blood)
  source file: blood.dm,117
runtime error: Cannot read null.contents
proc name: handle blood (/mob/living/carbon/human/handle_blood)
  source file: blood.dm,117
runtime error: Cannot read null.contents
proc name: handle blood (/mob/living/carbon/human/handle_blood)
  source file: blood.dm,117
runtime error: Cannot read null.contents
proc name: handle blood (/mob/living/carbon/human/handle_blood)
  source file: blood.dm,117
runtime error: Cannot read null.contents
proc name: handle blood (/mob/living/carbon/human/handle_blood)
  source file: blood.dm,117
runtime error: Cannot read null.contents
proc name: handle blood (/mob/living/carbon/human/handle_blood)
  source file: blood.dm,117
runtime error: Cannot read null.contents
proc name: handle blood (/mob/living/carbon/human/handle_blood)
  source file: blood.dm,117
runtime error: Cannot read null.contents
proc name: handle blood (/mob/living/carbon/human/handle_blood)
  source file: blood.dm,117
runtime error: Cannot read null.contents
proc name: handle blood (/mob/living/carbon/human/handle_blood)
  source file: blood.dm,117
runtime error: Cannot read null.contents
proc name: handle blood (/mob/living/carbon/human/handle_blood)
  source file: blood.dm,117
runtime error: Cannot read null.contents
proc name: handle blood (/mob/living/carbon/human/handle_blood)
  source file: blood.dm,117
runtime error: Cannot read null.contents
proc name: handle blood (/mob/living/carbon/human/handle_blood)
  source file: blood.dm,117
runtime error: Cannot read null.contents
proc name: handle blood (/mob/living/carbon/human/handle_blood)
  source file: blood.dm,117
runtime error: Cannot read null.contents
proc name: handle blood (/mob/living/carbon/human/handle_blood)
  source file: blood.dm,117
runtime error: Cannot read null.contents
proc name: handle blood (/mob/living/carbon/human/handle_blood)
  source file: blood.dm,117
runtime error: Cannot read null.contents
proc name: handle blood (/mob/living/carbon/human/handle_blood)
  source file: blood.dm,117
runtime error: Cannot read null.contents
proc name: handle blood (/mob/living/carbon/human/handle_blood)
  source file: blood.dm,117
runtime error: Cannot read null.contents
proc name: handle blood (/mob/living/carbon/human/handle_blood)
  source file: blood.dm,117
runtime error: Cannot read null.contents
proc name: handle blood (/mob/living/carbon/human/handle_blood)
  source file: blood.dm,117
runtime error: Cannot read null.contents
proc name: handle blood (/mob/living/carbon/human/handle_blood)
  source file: blood.dm,117
runtime error: Cannot read null.contents
proc name: handle blood (/mob/living/carbon/human/handle_blood)
  source file: blood.dm,117
runtime error: Cannot read null.contents
proc name: handle blood (/mob/living/carbon/human/handle_blood)
  source file: blood.dm,117
runtime error: Cannot read null.contents
proc name: handle blood (/mob/living/carbon/human/handle_blood)
  source file: blood.dm,117
runtime error: Cannot read null.contents
proc name: handle blood (/mob/living/carbon/human/handle_blood)
  source file: blood.dm,117
runtime error: Cannot read null.contents
proc name: handle blood (/mob/living/carbon/human/handle_blood)
  source file: blood.dm,117
runtime error: Cannot read null.contents
proc name: handle blood (/mob/living/carbon/human/handle_blood)
  source file: blood.dm,117
runtime error: Cannot read null.contents
proc name: handle blood (/mob/living/carbon/human/handle_blood)
  source file: blood.dm,117
runtime error: Cannot read null.contents
proc name: handle blood (/mob/living/carbon/human/handle_blood)
  source file: blood.dm,117
runtime error: Cannot read null.contents
proc name: handle blood (/mob/living/carbon/human/handle_blood)
  source file: blood.dm,117

etc.

### CODE REVIEW

**Comment by carlarc** [comment]
what a butt

**Comment by carlarc** [comment]
you don't have to be a butt about it

**Comment by carlarc** [comment]
butt you know what it's fine

**Comment by Kokojos** [comment]
butt why?

**Comment by carlarc** [comment]
just pass me some of that peanut butt-er

**Comment by TDcoolguy300** [comment]
Butt fix, merging

**Comment by calibraptor** [comment]
Only on Hippie Station

**Pull request merged**
