### PR TITLE
Buffs the RD Hardsuit

### PR DESCRIPTION
**Pull request by AliiTea**
For science!!

Helmet
melee = 10, bullet = 5, laser = 10, energy = 5, bomb = 100, bio = 100, rad = 60 OLD
melee = 15, bullet = 5, laser = 10, energy = 5, bomb = 100, bio = 100, rad = 70 NEW

Hardsuit
melee = 10, bullet = 5, laser = 10, energy = 5, bomb = 100, bio = 100, rad = 60 OLD
melee = 20, bullet = 5, laser = 10, energy = 5, bomb = 100, bio = 100, rad = 70 NEW

### CODE REVIEW

**Comment by danhibiki** [comment]
> 100 bomb

fuuuuuuuck no

**Comment by FuryMcFlurry** [comment]
LITTERALY UNBOMBABLE

**Comment by Chronitonity** [comment]
its always had 100 bomb. its a bomb suit.

**Comment by danhibiki** [comment]
Why not

**Comment by GunHog** [comment]
Still weak compared to the HEV suit and stuffs. The /tg/ version is balanced for a very armor stingy codebase which lacks the ability for Science to produce armor at all. There is no need for it to be weak here as well.

**Comment by Nebyab** [comment]
why not?

**Comment by GunHog** [comment]
Woop woop butts

**Pull request merged**
