### PR TITLE
Makes Revenants immune to the Singulo/Narnar

### LINKED ISSUE #2984: Revenants are still affected by the singulo, even when in ghost mode
Nothing like thinking you'll be fine and then getting deleted by the singulo

### PR DESCRIPTION
**Pull request by TheOneAndOnlyCreeperJoe**
Fixes #2984 

Done entirely from my phone.

EDIT: Not immune when revealed

### CODE REVIEW

**Comment by Pyko1** [comment]
Technically narsie should affect it tho, as it transforms ghosts as well.

**Comment by ghost** [comment]
Headmins have conflicting opinions.
They should be destroyed by singulo/narsie if they are manifested imo.

**Comment by TheOneAndOnlyCreeperJoe** [comment]
I'll do that when I'm home.

**Comment by Scinexx** [comment]
Yeah, being manifested seems like a good idea as it is interacting physically with the world

**Comment by ArcLumin** [comment]
Glad I'm not the only one who phonecodes

**Comment by Spacedong** [comment]
yeah what mcbawg said

**Comment by TheOneAndOnlyCreeperJoe** [comment]
Alright, he's now vulnerable when he's revealed.

**Comment by ghost** [comment]
Yeah okay +1

**Comment by SplergeBucket** [comment]
sounds good to me
i'd honestly like it if nar-sie destroyed them at any form but idk how difficult that is to code

**Comment by TheOneAndOnlyCreeperJoe** [comment]
should be merged since 2 heads.

**Comment by ArcLumin** [comment]
On it. I can't keep track of what's heads and what's not.

**Pull request merged**
