### PR TITLE
Adds new room to outpost with toxins stuff in it (A lot of fixes also)

### PR DESCRIPTION
**Pull request by calibraptor**
- Heating loop that makes use of heat exchange piping running through the mixing chamber to make plasma superhot without having to mix it with oxygen.
- Additional o2 and plasma canisters.
- Portable air pump and scrubber added.
- Disposals!
- AI can actually see what's going on now.
- No more autolathe.
- Xenobio has shield generators now
- Gave the armory it's shields back because why the fuck not

que

If there's anything I forgot to mention just check the commits

### CODE REVIEW

**Comment by ghost** [comment]
I think a part where you're modified the offset or something uses pixel_step which breaks the game.

**Comment by calibraptor** [comment]
I did modify the offset of the signs I added in, following the example of the other signs that were already there. Not entirely sure where I went wrong but I think I could redo it from scratch if I really needed to. I was able to test it without much issue however.

**Comment by ghost** [comment]
When testing out, you didn't teleport from tile to tile did ya?

**Comment by ghost** [comment]
Also, changelog please.

**Comment by Carbonhell** [comment]
Travis claims you used step_x or y somewhere

**Comment by calibraptor** [comment]
Wrestled around with figuring out how to push new commits, in my confusion actually did so correctly whilst having no idea what I'm doing.

**Comment by ghost** [comment]
The heating loop is a little concerning?
I know you can make max caps without it but it might make it too easy.
The extra canisters and the portable scrubber and vent is good though

**Comment by calibraptor** [comment]
Old Hippie map had a H/E pipe heating loop in it's toxin lab, I imagine some people have been wanting something similar to that for a while now.

Max caps can already easily be made using heaters and coolers without even touching the mixing chamber. Using the heating loop is also resource intensive, as you've got to burn through a lot of plasma and oxygen to get the temperature to a high enough point for a max cap bomb. Especially with a 3x3 burn chamber.

**Comment by ghost** [comment]
> Max caps can already easily be made using heaters and coolers without even touching the mixing chamber.

TIL
If it makes no gameplay difference besides having a big theoretical boom then yeah sure.

**Comment by Zadeon** [comment]
The firedoor is above the airlock leading to the canister storage.

**Comment by calibraptor** [comment]
Fixed and updated screenshot

**Comment by Gandalf2k15** [comment]
This looks great, if you wouldnt mind could ye add a mining satchel kek I forgot

**Comment by Gandalf2k15** [comment]
Also, remember to Copy/paste the windows from say the RD's office to ensure the shutters get put in, they are important. Other than that it looks good. Oh and check that your atmos scrubber and vent are ON

**Comment by calibraptor** [comment]
@Gandalf2k15 Done

**Comment by Gandalf2k15** [comment]
Noice!!

**Comment by calibraptor** [comment]
Removed autolathe and updated screenshot.

**Comment by dreamcrab** [comment]
sure, yeah. everything in here functions?

**Comment by calibraptor** [comment]
@dreamcrab 

Tested it thoroughly so it should be good to go.

**Comment by calibraptor** [comment]
Unless I'm mistaken that's a yes from two headmins. Somebody wanna merge this?

**Comment by Spacedong** [comment]
yeah you can get like 10/20/40's with pure superhot plasma and pure superchilled oxygen really easy now, doesn't matter that much since theres a bomb cap but hey neat

**Comment by Nebyab** [comment]
okay

**Comment by calibraptor** [comment]
Somebody merge this yo.

**Comment by calibraptor** [comment]
Discovered new stuff to fix, also adding disposals. Don't merge yet.

**Comment by calibraptor** [comment]
Aight, ready to merge now.

**Comment by calibraptor** [comment]
Okay definitely ready to merge now. I'm done fixing things. I promise.

**Pull request merged**
