### PR TITLE
Fixes the Ventcrawling Ghosts runtime

### PR DESCRIPTION
**Pull request by ArcLumin**
This should prevent ghosts from spamming runtimes when they alt-click.

Fixes https://github.com/HippieStationCode/HippieStation13/issues/3273

### CODE REVIEW

**Comment by TDcoolguy300** [comment]
The ..() is now one indent too low

**Comment by ArcLumin** [comment]
reeee

**Comment by ArcLumin** [comment]
I'm the indentation master

**Comment by Spacedong** [comment]
this is a fix and should be priority since it causes runtimes right? can we get a merge on it?

**Comment by SpankMasterson** [comment]
+1 don't want to merge without permission from other HA

**Comment by ghost** [comment]
yeah get it merged since its a bugfix +1

**Comment by JohnGinnane** [comment]
Merging

**Pull request merged**
