### PR TITLE
Adds z level rewards

### PR DESCRIPTION
**Pull request by ghost**
https://i.gyazo.com/791939b15f76345925296472ed827b41.png
3 shot capacity triplebarrel shotgun to the white-ship

https://i.gyazo.com/2173a06cd742cfbea070261479383220.png
5 shot capacitty, lever action shotgun that requires pumping between each shot. weight-class 3, can fit in your bag. added to DJ russian listening post area.

https://i.gyazo.com/8d2c024abeb2f63885dfde88f555f869.png
Single-shot capacity breech loading musket added to the clown area, since the clowns are dumb enough to use this shit item in these times. Shells are made from paper, 10 unit black powder, a minieball made from 2 metal sheets, and holding a screwdriver.(tablecraft)

https://i.gyazo.com/9eb115028902246d52e4611fef3b6ac8.png
Power armour hardsuit with toggleable helmet and light. Fairly robust, riot-armour protection with good laser protection aswell, Very weak to EMP attacks. (shocks user if hit by emp and permanently slows the hardsuit down)

### CODE REVIEW

**Comment by ghost** [comment]
haven't added these even though they have been in the code forever

**Comment by oprayx73** [comment]
Sure

**Comment by danhibiki** [comment]
No more telesci, why not.

**Comment by Nebyab** [comment]
I'll have you know its called ruskie DJ station

Otherwise this seems tolerable

**Pull request merged**
