### PR TITLE
Minor Syndicate Base makeover

### PR DESCRIPTION
**Pull request by Weisyl**
The spawn-room is a bit bigger but also looks cooler, and there are also
new spots to look outside. Included are some very pretty snow sprites to
replace the old ones. Nienhaus made said snow sprites for Arctic
Station. Additionally, new ambience loop which plays for the syndicate
base areas.

### CODE REVIEW

**Comment by Weisyl** [comment]
Note that the reason why Z1 is now showing as 7k deletions / additions is simply because I had to commit that to fix merge conflicts - which isn't from me because I (DEFINITELY) had map-merged everything I worked on in this PR.

**Comment by Weisyl** [comment]
Oh right almost forgot here's a pic: http://puu.sh/kOiHa/84bfaa8f50.png

**Comment by Foosili** [comment]
Very nice, Derp. I like it. :+1:

**Comment by danhibiki** [comment]
This is good

**Comment by Pyko1** [comment]
What was actualyl changed on the Z1 since this reverted all the mapchanges done in few days.

**Pull request merged**
