### PR TITLE
TG Ports

### PR DESCRIPTION
**Pull request by Crystalwarrior**
-  - tgs: "Weapons and projectiles that are armour piercing now have an increased chance to bypass riot shields (Thanks to KorPhaeron for this one!)"
-  - tgs: "Sped up recursive_hear_check (Thanks to tkdrg for this one!)"

### CODE REVIEW

**Comment by nalarmg** [comment]
Description is not useful or informative.

**Comment by Lawligagger** [comment]
Fix the description

**Comment by danhibiki** [comment]
descriptorino buddy

**Comment by Crystalwarrior** [comment]
Updated description

**Comment by Nebyab** [comment]
How much of an increase are we looking at here? I can't really figure my way out around the code for this, so some specifics would be nice so I can micromanage more effectively.

**Comment by danhibiki** [comment]
Interested in this, but as I've discussed shortly with @Chronitonity, we need to lower guardian's crystal shot's armor penetration. Right now, its at 100, with the second highest one being a baseball at 20. The shots themselves do 5 damage.

**Comment by Chronitonity** [comment]
Doesn't have much to do with this PR seeing how this will nerf Guardians a bit anyway.

**Comment by nalarmg** [comment]
Heads prompted for feedback. Sorry for the wait!

**Pull request merged**
