### PR TITLE
A.U.S.S.I.E Lawset

### PR DESCRIPTION
**Pull request by AliiTea**
Adds the AUSSIE lawset from this thread:

http://hippiestation.com/viewtopic.php?f=4&t=1094

### CODE REVIEW

**Comment by trifornt-tinfornt** [comment]
As long as it has the mustached-cowboy mustaches then I'm in.

**Comment by Nebyab** [comment]
This really just seems like ASIMOV: Clusterfuck and Memes edition
and not at all in a good way

**Comment by Chronitonity** [comment]
:-1: Its gonna be an administrative nightmare to make players understand what these do and what an AI has to do while synced to these laws. 

Also its literally a super meme

**Comment by TDcoolguy300** [comment]
I just came back from my Fallout 4 Splerge, and jesus this is going to be a nightmare for admins. So a :-1: from me

**Comment by Crystalwarrior** [comment]
:-1: :-1: :-1: 
Who the fuck is going to understand what "dog" means without context?

**Comment by danhibiki** [comment]
No

**Comment by Lawligagger** [comment]
Nah

**Pull request closed without merging**
