### PR TITLE
Fixes medical being an autism fort.

### PR DESCRIPTION
**Pull request by collinxchu**
https://github.com/HippieStationCode/HippieStation13/issues/403

Same fixes as before, really.

### CODE REVIEW

**Comment by ghost** [comment]
Dont define `file_dir`

**Comment by collinxchu** [comment]
SHIT. I fucked it.

**Comment by Chronitonity** [comment]
Ahhhhhhhhhhhhhhhhhhhhh

**Comment by collinxchu** [comment]
It's all okay now, we can all forget that I'm fucking shit at github and move on with our lives.

**Comment by Kokojos** [comment]
#remember2015
#thebigfailofcollinxchu

Otherwise yeah I like this.

**Comment by WhiteFox08** [comment]
:+1:

**Comment by collinxchu** [comment]
Is fix merge pls <3

**Comment by Chronitonity** [comment]
@SplergeBucket

**Comment by Kokojos** [comment]
Showing  2 changed files  with 7,163 additions and 7,161 deletions.

HOLY SHIT YOU DIN'T RUN MAPMERGERRRRRRRRRRRRRRRR

**Comment by Jaygriff** [comment]
Needs map merge , read in dir/tools/mapmerge and resyncbwith master then redo changes with mapmerge.

**Comment by ghost** [comment]
@JustinBNewton he knows.

**Comment by Jaygriff** [comment]
@chnkr just making sure.

**Comment by collinxchu** [comment]
Man I ran mapmerge what is this shit. Will fix again since apparently it's criminal if I don't make every single mistake imaginable

**Pull request closed without merging**
