### PR TITLE
People in neckgrab will only fall over if in crit/unconscious/dead

### PR DESCRIPTION
**Pull request by Crystalwarrior**
Suggested feature on Trello, makes meatshields much more practical.

### CODE REVIEW

**Comment by Lawligagger** [comment]
Sure.

**Comment by Nebyab** [comment]
sounds good

**Comment by Chronitonity** [comment]
Needs changelog

**Comment by danhibiki** [comment]
Add changelog, then accepted

**Comment by Chronitonity** [comment]
If this gets merged I'll just do his changelog for him

**Comment by Chronitonity** [comment]
#1162

**Comment by Pyko1** [comment]
Maybe make the overal speed a bit higher, and if the meatshield is stunned/critted then it slows you down more.

**Comment by Chronitonity** [comment]
Speed is fine how it is, you're moving a body, and that would slow you down considerably in most situations.

**Comment by Chronitonity** [comment]
Gonna merge this as its accepted and theres a changelog up for it already

**Pull request merged**
