### PR TITLE
Gateway - BUGFIX

### PR DESCRIPTION
**Pull request by Gandalf2k15**
# **THIS ONLY FIXES THE GATEWAY MAP LOADER, NO MAPS WILL SPAWN, E.G. IT WILL STAY NONFUNCTIONAL.**

### CODE REVIEW

**Comment by trifornt-tinfornt** [comment]
No.
It's either a laggy, bug-ridden mess or something that has no balance.
It also made rounds way too easy as an antag as tons of crew would simply enter the Gateway immediately causing there to be no crew members left, resulting in the antags steamrolling the entire crew - especially during gamemodes like Nuke Ops.
Unless, of course, they gave the crew free eshields and .357s and SMGs.

**Comment by Gandalf2k15** [comment]
Duly noted! All of the above is fixed my man! Of course Mr Fun Hitler would be against something that could be remotely fun!

**Comment by calibraptor** [comment]
+1 with the condition that the gateway delay be increased to 15 minutes.

**Comment by carlarc** [comment]
that just means people are gonna come in a little more prepared

**Comment by calibraptor** [comment]
@carlarc People who enter the gateway /should/ be prepared. I actually intend to rebalance some of the maps so overpowered loot is more difficult to come across.

**Comment by Gandalf2k15** [comment]
I can't change start times its a server configuration

**Comment by Badmex** [comment]
Delay time should really be increased.

**Comment by myontasm** [comment]
Can you make it so it only has a random chance to activate that round instead of evrry round? That'd be great imo

**Comment by Nebyab** [comment]
I never liked the gateway. Its antithetical to the way rounds are supposed to play out, and its hard to incentivize people without good loot, which if they get breaks the roundflow.

**Comment by Gandalf2k15** [comment]
Tbh most people are bored of the same shit over an over. This was already in why is it being debated. People are pissed it's gone atm.

**Comment by Sarcalogo** [comment]
>Most people

Citation needed.

**Comment by dreamcrab** [comment]
yeah, I don't really like the gateway. especially with the loot and levels that were in it. I don't even like the research station because it takes more people out of the main action of the round.

**Comment by TheOneAndOnlyCreeperJoe** [comment]
Revamp the thing to be less bland and be more balanced. Less focus on combat (still a big focus on it though) and more on puzzles, interesting dynamics etc.

Custom Sprites would be very much appreciated too. Everything feels and looks bland, little to no variety. We should at least give it some more flavor.

**Comment by Gandalf2k15** [comment]
Again, this was already added. Its standard procedure to readd things that were mistakenly removed.

**Comment by blobbernaut** [comment]
> Citation needed.

me and as headmin, server host, and president of the united states of america, i say merge this

**Comment by Kokojos** [comment]
So far 2 headmins have indicated they don't like this, and Il add a GM no to this. Sorry, but while the gateway always seems fun, withouth major changes, it's not viable for the station.

Il wait for Mcbabaggins' opinion

**Comment by ghost** [comment]
If we're gonna have gateways, we need the following:
1. A good selection of maps. We saw people bringing back xenos erry round before.
2. Have the gateway not round start on and even then, to be semi functional.

Unless those two things can come into play, there's no point.

**Comment by Gandalf2k15** [comment]
Might I refer you to this forum post: http://hippiestation.com/showthread.php?tid=3993
This is wanted by essentially the entire server. I don't know what you mean by point 2. However we have a good selection of maps, also calibraptor will be working on them. IF you want the gateway to start later please bug admiral hippie to change the start time in the game options config file on the server. I refer you to this for the map selection pool: http://hippiestation.com/showthread.php?tid=4013

**Comment by calibraptor** [comment]
I propose we move the gateway to a new z-level honestly.

**Comment by Gandalf2k15** [comment]
https://github.com/HippieStationCode/HippieStation13/pull/2444#issuecomment-222309641

**Comment by Nebyab** [comment]
No. I have no idea why exactly you specifically asked for me to weigh in on this gandalf, since it has good odds of dashing your hopes. 

The gateway is just a bad idea, and has literally never worked out well.

**Comment by Gandalf2k15** [comment]
Alright. the select few people hate the gateway, said people have power. No use in trying anymore. Just check the polls and you will see what I mean. Closing.

**Comment by Gandalf2k15** [comment]
Okay, gonna reopen this and only have the code. No maps will spawn, see config.

**Comment by Gandalf2k15** [comment]
# **THIS ONLY FIXES THE GATEWAY MAP LOADER, NO MAPS WILL SPAWN, E.G. IT WILL STAY NONFUNCTIONAL.**

**Comment by Crystalwarrior** [comment]
Merge this shit

**Comment by TDcoolguy300** [comment]
Code looks fine, maps do not matter because they wont be loaded in

**Comment by ghost** [comment]
I think the gateway being a spess thing is cool. My only complaint about the current missions being bad is now gone. Therefore, +1.

**Comment by Gandalf2k15** [comment]
Can we merge this? I need to delete the current fork.

**Comment by Sarcalogo** [comment]
The triumvirate has spoken.

**Comment by ghost** [comment]
To be fair, teamstab and nebyab disagree with me. I'm out ruled.

**Comment by Gandalf2k15** [comment]
Its a bugfix n0 headmin input needed.

**Comment by nalarmg** [comment]
Two head admins against, one for. There do seem to be people still against them, too.

It's worth noting that whilst it's a "bugfix", maps are changed in some way still - even if they won't be loaded. This means that if we do enable in the future, those changes will be present.

Could a head admin please confirm they'd like this merged?

**Comment by Gandalf2k15** [comment]
Nalar, the maps will never be used again.

**Comment by nalarmg** [comment]
They'll still be be available _incase we do decide we want to re-enable the gateway again in the future_, which is entirely a possibility. Given that, I'd like verification to be given from the head admins.

**Comment by Gandalf2k15** [comment]
Even then, the maps are only fixed as well. Removed several broken aspects. This is at its core a bugfix.

**Comment by nalarmg** [comment]
"Removed several broken aspects" is not very clear, and could mean almost anything. Could you clarify as to what precisely was fixed - it's not obvious at first glance. Your description states you only fixed the map loader, which loads the maps into memory so that they're available. Is this not the case?

**Comment by Gandalf2k15** [comment]
The current maps are not to the standard required. I edited them according to player wants. And they will likely be redone. Most maps have simply had mobs removed to reduce lag, less loot. Maps are irrelevant.

**Comment by nalarmg** [comment]
Maps are not irrelevant, as they're in the codebase and are available to the code for use via the use of the config - which could be set at any time should the head admins decide to in the future (granted this is done via myself/Hippie for security reasons, but that does not change the possibility of the occurance). Unless you've a mechanism in place to prevent this?

**Comment by Gandalf2k15** [comment]
The maps that are changed in this PR only IMPROVES them. They used to lag, and even crash the server as they had zombies and alien eggs in. This removes that from ALL gateway maps. That can be classed as a bugfix. Loot has been balanced too. Meaning the amount of work needed is reduced by a large amount.

**Comment by nalarmg** [comment]
Unfortunately, if there are balance changes, those balance changes should be reviewed by the head admins and approved first.

This still does not change my previous statements and therefore my stance remains unchanged. I'd like definite confirmation before this is merged as a "bugfix", as there's more than just simple bugfixes to this PR.

**Comment by Gandalf2k15** [comment]
Fine, I'll remove the map changes.

**Comment by Gandalf2k15** [comment]
Well sadly I have deleted the fork. Therefore the branch no longer exists. I can't edit this at all now. Unless you can @nalar.

**Comment by TDcoolguy300** [comment]
Only you can edit your fork Gandalf, we have no control over forks of the code.

**Comment by Gandalf2k15** [comment]
Okay I'll change the map loader in a PR I'm about to push. I guess this can be removed.

**Comment by Carbonhell** [comment]
psst
how about giving permanent aesthetical rewards instead of in round loot,like achievements or an aesthetic item to spawn with
or just make the mission fun so people do it for fun and not for the loot

**Comment by TDcoolguy300** [comment]
We'd need to implement and then manage a aesthetic save, but is doable

**Pull request closed without merging**
