### PR TITLE
Flares, etc.light color + light colors transfer to mob

### PR DESCRIPTION
**Pull request by Crystalwarrior**
Flares now have l_color, as well as lanterns and golden slimes.
Picked up flashlights will now properly transfer their light color to mob.

### CODE REVIEW

**Comment by SplergeBucket** [comment]
fuck you russia

**Comment by ghost** [comment]
yes more lag!!!1

**Comment by PJB3005** [comment]
...This is wrong on SO many levels.

**Comment by PJB3005** [comment]
If you want non shit coloured lights (This implementation is pure garbage, only using dropped() means artifacts and bugs out of the ASS)

Get baylights, no, it doesn't lag anymore.

**Pull request merged**
