### PR TITLE
Ports newcrit system and crit-crawling!

### PR DESCRIPTION
**Pull request by Carbonhell**
Ports newcrit system from old hippie(Where you'd still be able to mutter
words out), plus the crawling while crit system from atlas.IF YOU'RE
PORTING RODGUNS CHECK THIS PR, there's a thing you must add in mob.dm
line 792, add a || pinned_to !

### CODE REVIEW

**Comment by Chronitonity** [comment]
This is what hippie is about right here lads, this is arguably the most important thing ever

**Comment by Carbonhell** [comment]
special thanks to @Nexendia- who gave me the idea to use atlas to look for code to easily port shit,i love you

**Comment by Carbonhell** [comment]
actually it was @DerptheStewpidGoat i failed

**Comment by Carbonhell** [comment]
you know what fuck it THANKS EVERYONE i love you all

**Comment by Nebyab** [comment]
yeah sure

**Pull request merged**
