### PR TITLE
Cane Shotgun + Gear, Antag equipment for Clowns + Mimes

### PR DESCRIPTION
**Pull request by TDcoolguy300**
- rscadd: "Adds the Cane shotgun, a single barrel shotgun with no context clues and is silenced, examining it wont even prove that it's a gun. Can be purchased by clowns and mimes."
- rscadd: "The cane shotgun can also be disguised to the Pimp cane and whatever cane is added next."
- rscadd: "Also included 6 Assassination darts to use with the cane"

### CODE REVIEW

**Comment by Chronitonity** [comment]
:+1: Gimmicky and dangerous

**Comment by FuryMcFlurry** [comment]
oh shit more job-tator weapons.

I got a question regarding the damage output.
6 neurotoxin
and 6 lexorin.
how much damage would this do actually? will it apply more units if the person gets shot pointblank with it?

**Comment by danhibiki** [comment]
If its the same as pre-rebase, then roughly 15 units of lexorin should bring someone into crit. And if I'm not mistaken, we ported a recent lexorin buff from TG

**Comment by FuryMcFlurry** [comment]
Alright, Also neurotoxin and neurotoxin2 are two different things
And neurotoxin is the drink a bartender can make while neurotoxin2 is the poison chemists can create.
Just pointing that out.

so not sure which one you used

**Comment by Crystalwarrior** [comment]
why won't anyone rename the neurotoxins so it's not as confusing holy fuck

**Comment by danhibiki** [comment]
i for one blame @Iamgoofball

**Comment by TDcoolguy300** [comment]
I chose the drink on purpose, it's meant to knock them out.

**Comment by danhibiki** [comment]
Also I support this

**Comment by Foosili** [comment]
Sure okay

**Comment by TDcoolguy300** [comment]
Going to close this one as it's FUCKED with merge conflicts, will open a new one soon

**Comment by danhibiki** [comment]
all my dreams :*(

**Comment by TDcoolguy300** [comment]
It's coming back in like 5 minutes

**Comment by danhibiki** [comment]
rip i will miss you shotgun cane, you will never exist again

**Comment by TDcoolguy300** [comment]
IT'S HAVING A TANTRUM, LET ME GIVE IT A LOLIPOP, IT WILL BE BACK ON STAGE IN 5

**Comment by TDcoolguy300** [comment]
Shotgun.dm is giving me trouble

**Comment by danhibiki** [comment]
i remember when we use to jest about the cane shotgun, and talk about the fun antics we would get into. :100: it was real :100:

but you know how it do :cry:

**Comment by TDcoolguy300** [comment]
DOIN SHIT

**Comment by TDcoolguy300** [comment]
Made a horrible mistake, accidentially deleted shotgun.dm from master in my shit

**Comment by TDcoolguy300** [comment]
@danhibiki I think it's fixed

**Comment by TDcoolguy300** [comment]
I hate my life

**Comment by TDcoolguy300** [comment]
Welcome, to the shitfest that is merge conflicts

**Comment by danhibiki** [comment]
is this real

**Comment by TDcoolguy300** [comment]
Yes

**Comment by ghost** [comment]
teef

**Comment by TDcoolguy300** [comment]
Shits fixed nerds

**Pull request merged**
