### PR TITLE
Adds Raincoats

### PR DESCRIPTION
**Pull request by Chronitonity**
Antag Item which costs 1 TC, under pointless badassery, ported from VG.

http://puu.sh/kjYlZ/342f85ba72.png

It's Hip to be Square!

### CODE REVIEW

**Comment by SplergeBucket** [comment]
+1

**Comment by WhiteFox08** [comment]
:+1:

**Comment by lcass** [comment]
yis

**Comment by Weisyl** [comment]
I see absolutely no point in this. It's useless, screams I AM AN ANTAG, and doesn't even look good

**Comment by Pyko1** [comment]
At least make the raincoat protect from any chems sprayed,

**Comment by Chronitonity** [comment]
No thanks, it'd make it much better than a 1tc item than it is, maybe in the future but for now, its just a gimmick item.

**Comment by nalarmg** [comment]
Seems like most are fine with this, merging.

**Pull request merged**
