### PR TITLE
Big shadowling update

### PR DESCRIPTION
**Pull request by Carbonhell**
DO NOT MERGE, code is ready but i still need to make a detailed
changelog. I PRed it just incase. DO NOT MERGE

### CODE REVIEW

**Comment by Carbonhell** [comment]
-Ports a lot of shadowling fixes and features from tg:
-Adds a create shadowling button for admins in "Create antagonist" verb.
-Now you can only thrall five people before being forced to hatch.
-Cooldown removed from hivemind commune.
-Drain Thralls spell replaced with Drain Life spell, now it works on anyone and not just thralls.
-Spatial Relocation replaced with Black Recuperation, now you can revive thralls or empower them to make them stronger.
-Empowered thralls become shadowpersons, which have the same features of shadowlings, halved.
-All ascendant abilities are now instant except Glacial blast,which has a countdown of 10 seconds now.
-Adds a new ability to ascendant shadowlings to talk to the entire world.
-Replaces shadowlings' names from Shadowling(number) to custom names.
-Adds a way to deconvert thralls, through surgery:aim head, scalpel, hemostat, retractor, saw, empty hand.Cyborgifying also works.
-Adds action buttons for the spells.
-Shadowling chitin is now spaceworthy.
-Adds a new spell, destroy engines. You can sacrifice one thrall to raise the shuttle arrival time by 15 minutes, only available to hatched shadowlings.
-Gives thralls lesser versions of shadowling's spell, Lesser glare,Lesser shadow walk and Thrall vision, and gives them a funny description on examining them.
-Fixes "Veil" not disabling lights properly, now it can also break glowshrooms.
-Removes the ability to enthrall braindead/catatonic/mindless people.
-Fixes a lot of grammar errors and span classes.
-Now hatched shadowling abilities can only be used by shadowlings, to prevent issues.
-Fixes not being able to toggle shadowling preference through special role preference verb.
-Fixes a rare issue where shadowling end text would sometimes not display.

Copied from my changelog,there were so many changes,ask me if i forgot anything.
All is fixed, merge when possible/if possible!

**Comment by Carbonhell** [comment]
PR is completed unless you have some important feedbacks. Please OK it or tell me what to fix, thanks!

**Comment by Carbonhell** [comment]
If anyone could tell me why this shit is conflicting i'd be glad,it seems to not be the changelog

**Comment by WhiteFox08** [comment]
This needs to be redone, dnm until further notice.

**Comment by Carbonhell** [comment]
PR completed.Merge when possible

**Comment by Carbonhell** [comment]
ACTUALLY WAIT lemme speak with whitefox first to be sure everything is ogre

**Comment by Carbonhell** [comment]
Good to merge for me. Waiting for whitecuck input

**Comment by Carbonhell** [comment]
All fix'd

**Pull request merged**
