### PR TITLE
Standardises Space and Hardsuit slowdown from 2 to 1

### PR DESCRIPTION
**Pull request by Chronitonity**
Ports Fox McClouds standardization of Space and hardsuit movement speed
No one wears these things indoors because a slowdown of 2 is near crippling, they always just run with them in their hands and equip them as soon as they need them/are getting disarmed.

Fits with our fast paced gamestyle anyway.

### CODE REVIEW

**Comment by danhibiki** [comment]
Just to be clear, this makes them one stage slower than normal, instead of 2 stages? So having a hardsuit/exosuit still slows you down, just not as much?

**Comment by Weisyl** [comment]
@danhibiki yep

**Comment by danhibiki** [comment]
Sure

**Comment by Weisyl** [comment]
Thank GOD.

**Pull request merged**
