### PR TITLE
Cosby sweater makes you scream Cosby lines. Cosby sweater now available in clothes mate.

### PR DESCRIPTION
**Pull request by ghost**
Updates the refill vending machine object for clothesmate.
Cosby sweater is only vended with a coin.
Hitting someone with a Cosby sweater no longer screams Cosby lines.

### CODE REVIEW

**Comment by Carbonhell** [comment]
Pretty snowflakey,would've preferred if you did it tdcoolguy's way. Wasn't John working on this? I can make it properly easily

**Comment by Carbonhell** [comment]
So yea do not merge,i can make it better but i will need 2-3 days,your choice

**Comment by ghost** [comment]
Yeah that's fine, I was told to do it this way even if I thought it was snowflakey.
If you can do it better then it's good fam.

**Comment by JohnGinnane** [comment]
_quickly scrambles to computer_

**Pull request closed without merging**
