### PR TITLE
CQC Gloves Disguise

### PR DESCRIPTION
**Pull request by GenericGoose**
Allows you to disguise CQC gloves as any other gloves (not including colored), so they aren't useless to jobs that have their own gloves or for sneaky fun (works same way chameleon thermals do, btw someone should probably re-write that proc to make it universal, which may be the nekst thing i'll do). Only changes name and sprite.

Upd: now this PR also fikses [missing sec bomb suit icon](https://github.com/HippieStationCode/HippieStation13/issues/2530), changes is_type_in_list back to what it was before 'optimization' that broke it, so it [fikses ](https://github.com/HippieStationCode/HippieStation13/issues/2501)reagent grinder [not being able to process any food](https://github.com/HippieStationCode/HippieStation13/issues/2535) and replaces Pete's attack message for some reason it bothered me. Oh yeah and I added disguising feature to pickpocket gloves too as @Kierany9 suggested

### CODE REVIEW

**Comment by TDcoolguy300** [comment]
Code should work just fine, also congrats, your build was #5000 on Travis.

**Comment by GenericGoose** [comment]
Nice, thank you
Btw yeah I tested it and it does work.

**Comment by Kierany9** [comment]
Might also want to add this to the pickpocket gloves, it's up to you.

**Comment by dreamcrab** [comment]
remember the basics of CQC +3 subsistence

**Comment by GenericGoose** [comment]
gud idea @Kierany9

**Comment by GenericGoose** [comment]
oh well why cant i make multiple pull requests thats p autistic tbh
i guess it also fikses security bomb suit sprite
i mean i can make another fork but thats retarded too git plz 
sorry i kinda wanna die or something

**Comment by Kierany9** [comment]
To make multiple PRs you need to change the branch you're working on.

**Comment by GenericGoose** [comment]
how
i only have 1 branch

**Comment by Kierany9** [comment]
By making a new branch

**Comment by GenericGoose** [comment]
i can't allow that i don't have infinite space and git works slow as frick 
just plz accept or deny this it's been up for like forever then i'll fiks more things

**Comment by ghost** [comment]
Good shit +1

**Comment by Gandalf2k15** [comment]
+69

**Comment by Gandalf2k15** [comment]
Please merge.

**Comment by JohnGinnane** [comment]
@GeneralGoose have you looked at http://wiki.hippiestation.com/index.php?title=Setting_up_git ?

It should detail how to create branches. This means you can create a branch for each different feature/fix that you're doing and you won't have to lump everything into one PR.

**Note that I'm going to merge Gandalf's missing icon fix as it's a bugfix and we're currently in codefreeze, which delays this PR because it includes a new feature (disguising CQC gloves)**

**Comment by JohnGinnane** [comment]
You can remove the change you made to replace the missing icon as it will conflict when the other PR is merged

**Comment by blobbernaut** [comment]
You really shouldn't do so many different things in one PR

**Comment by GenericGoose** [comment]
i know sorry but i couldn't allow to have multiple branches

**Comment by JohnGinnane** [comment]
Are you getting an error when trying to create a branch?

**Comment by GenericGoose** [comment]
no i just have no space and it confuses me and my pc is slow enough already
i am sorry
they should've made it possible to PR without making branches tbh (its actually possible but involves some fuckin around which i didnt get)

**Comment by JohnGinnane** [comment]
The way git works is that by having other branches it doesn't create copies of the entire time. Instead it will just record the difference between the "master" copy and the changes you made, so it's very very minimal on space.

**Comment by JohnGinnane** [comment]
Also keep in mind you don't need to branch if you're only working on the one thing, but in this case you'd need to have a branch for each fix and feature as they each have to be reviewed and approved

**Comment by GenericGoose** [comment]
@JohnGinnane wait, branches don't take up space? I'll try it then. Thanks.

**Comment by blobbernaut** [comment]
Don't need to actually since the fix is already in another PR

**Comment by JohnGinnane** [comment]
Yeah this should become the CQC glove feature. You can remove fixes.

And no, additional branches don't take up much space. The more you work on a branch yeah, but we're talking less than a single megabytes at most typically.

**Comment by GenericGoose** [comment]
@blobbernaut yes i know its in other PR
I meant I'll try doing it since now, if they really don't take space
thanks and sorry again

**Comment by Carbonhell** [comment]
PR has conflicts and is inactive since 15 days,closing

**Pull request closed without merging**
