### PR TITLE
Removes some stuff in the armory

### PR DESCRIPTION
**Pull request by Chronitonity**
Removes the 3 boxes of 40 SHOTGUN SHELLS that were in the ammo locker. Extremely overpowered, not fun. You can load shotguns directly from them.

Removes the 15 STACK of plasma on the generator, all the other plasma bars on the station would barely even add up to that much plasma, the armory sure doesn't need it. Replaces it with 1 bar of plasma.

No changelog because none of this was supposed to be on the map

### CODE REVIEW

**Comment by Foosili** [comment]
finally :+1:

**Comment by Pyko1** [comment]
Might as well remove the generator all together as 1 bar of plasma lasts less than a minute.
Engineering has 30 plasma just to jumpstart the singulo emiters.

Make it at least 5 or so.

**Comment by lcass** [comment]
I think moving the shotgun shells to a more secure area would be a better idea , for instance having a special area of the armoury that requires the hos to unlock but I digress.

**Comment by danhibiki** [comment]
15 was too much, but maybe 1 is too little. Either remove the generator or bump the plasma stack to 5.

**Comment by Chronitonity** [comment]
Me and pyko agreed 3 is fine so thats what ill go with. As for the shells they are way to powerful and have no place on the station

**Comment by TDcoolguy300** [comment]
:+1:

**Comment by nalarmg** [comment]
Conflicts. Needs further head input.

**Comment by Chronitonity** [comment]
eughhhhhhhhh fuck hold on

**Pull request closed without merging**
