### PR TITLE
Guidebook Fix?

### PR DESCRIPTION
**Pull request by AliiTea**
This might fix guidebooks being broken..

Fixes: https://github.com/HippieStationCode/HippieStation13/issues/2022
_maybe_

### CODE REVIEW

**Comment by Carbonhell** [comment]
No. Those values get changed to the config values,those one you edited are the default values so they don't affect that bug, to fix the bg just go check where hippie-station.com is used and change it with pur new host hippiestation.com

**Comment by TDcoolguy300** [comment]
As carbon said, these are primarily default values and are overwritten once the configurations have loaded

**Comment by Carbonhell** [comment]
Just close your PR and make a new one when you fix your code

**Comment by AliiTea** [comment]
Aye aye

**Pull request closed without merging**
