### PR TITLE
Cluwnes now always have Epilepsy

### PR DESCRIPTION
**Pull request by TheOneAndOnlyCreeperJoe**
They need to be more miserable :^)

### CODE REVIEW

**Comment by blobbernaut** [comment]
really not neccessary

**Comment by Lawligagger** [comment]
yes

**Comment by myontasm** [comment]
Yes

**Comment by TDcoolguy300** [comment]
Codes fine

**Comment by myontasm** [comment]
Blobbernaut hates fun

**Comment by TheOneAndOnlyCreeperJoe** [comment]
This isn't in progress lad.

**Comment by Pyko1** [comment]
its a label used for waffle sorting, better that than backlog

**Comment by trifornt-tinfornt** [comment]
This is already merged, but this literally has had no effect on cluwnes in gameplay. Is that a bug, or is it just not noticeable?

**Comment by TheOneAndOnlyCreeperJoe** [comment]
Epilepsy has a very low chance of triggering, so you must just be lucky

EDIT: Server hasn't been updated yet.

**Pull request merged**
