### PR TITLE
Adds two new templates to randomly generate

### PR DESCRIPTION
**Pull request by TDcoolguy300**
[Fire thing](http://puu.sh/mELMq/41fdf3adbf.png?raw)

[Botanyship](http://puu.sh/mELPz/0d0da27612.png?raw)

### CODE REVIEW

**Comment by Nokington** [comment]
:+1:

**Comment by danhibiki** [comment]
Trying to use my love for botany against me? :+1:

**Comment by TDcoolguy300** [comment]
I credited Fury in the changelog as he made these, not me.

**Comment by Kokojos** [comment]
:+1:

**Comment by TDcoolguy300** [comment]
Looks like two Headmins approved, waitin on that MERGE

**Pull request merged**
