### PR TITLE
moth screaming

### PR DESCRIPTION
**Pull request by ghost**
Damn megroes

### CODE REVIEW

**Comment by danhibiki** [comment]
Given your history with moth people, I predict this will get denied once I review the sound

**Comment by danhibiki** [comment]
Its actually not that bad.

**Comment by ghost** [comment]
true, it is a fitting sound for second class insect scum

**Comment by Spacedong** [comment]
this hurts my fucking ears however i currently got my volume a little high so idk its a little loud tbh famtoid

**Comment by ghost** [comment]
@spacepenis it didn't hurt my ears, you must have really loud headphones

**Comment by FuryMcFlurry** [comment]
Nevermind, I dunno it sounds wacky but it fits sorta. I did create my own sound but whatever this seems good.

**Comment by ghost** [comment]
Since no one seems to be against this, is this getting merged?

**Comment by Spacedong** [comment]
you need headmin approval for features dumbdumb

**Comment by ghost** [comment]
let me approve my fist in your ass

no homo

**Comment by Nebyab** [comment]
yeah syre

**Comment by Nokington** [comment]
sure whatever

**Pull request merged**
