### PR TITLE
Brig Update

### PR DESCRIPTION
**Pull request by Kilmannan**
Brig public area re-design to provide more cell space, more general
accessibility and control by Sec staff. Redesign of Sec muster area into
briefing style display.

Detective and Lawyer offices also redesigned to accommodate Holding Cell
directly north of Detective Office. This is for the temporary holding of
prisoners should Cells be full, or simply not warrant brigging them
properly. They can be fed in via disposal.

### CODE REVIEW

**Comment by doobiedoo23** [comment]
Add pictures please

**Comment by Kilmannan** [comment]
Yep. Will do. This is my first time map editing, so still trying to get my head around Git, map merge, and all the nuances of Dream M(bre)aker.

Also, please do note, this is my first time - I expect there to be issues with this but I've tested it numerous times and am relatively happy with it. If this goes through, there will be another PR shortly with some cosmetic fixes I've just noticed and any other points raised.

Ta!

image

image

**Comment by Nebyab** [comment]
This seems fairly solid

**Comment by ghost** [comment]
My only gripe is that the cells dont have blast doors/windows
and that the security office is made of normal walls, the one with the two buttons and mounted flasher.
and why is there 3 seats in the sec office???? i'd assume theres just one that the warden would roll in

**Comment by AliiTea** [comment]
Wow this is really nice.

Goodjob @Kilmannan

**Comment by Chronitonity** [comment]
Remind me or someone else to teach you how to changelog @Kilmannan 

Apart from that minor gripe, great work here.

**Comment by Kilmannan** [comment]
Sorry folks, never spotted pipe issue.

@oprayx73 - that's not the wardens office. That's the public counter for dealing with the public / monitoring cells. Warden office is still there. Creates a firewall between everyday brig shit and more high level issues that can be dealt with behind secure doors.

I was also told to put some vulnerabilities in, hence why the B.O has normal walls.

**Pull request merged**
