### PR TITLE
Admin logs for heads that have been dismembered.

### PR DESCRIPTION
**Pull request by Gandalf2k15**
Fixes https://github.com/HippieStationCode/HippieStation13/issues/2455

INSTRUCTIONS
Step 1:
Find head
Step 2:
View Vars
Step 3:
Search "body"
image
Step 4: 
Click on the blue text
image

Done!

### CODE REVIEW

**Comment by calibraptor** [comment]
Nice.

+1

**Comment by JohnGinnane** [comment]
Code looks good!

**Comment by dreamcrab** [comment]
good stuff boys +32

**Comment by Kokojos** [comment]
yes +1

**Comment by Nebyab** [comment]
okay

**Comment by TDcoolguy300** [comment]
Two head approval, merging

**Pull request merged**
