### PR TITLE
Beret Armor Value Removal

### PR DESCRIPTION
**Pull request by McHatters**
What it says on the tin. All security berets have had their armor values stripped, so now there actually is a difference between the beret and helmet!

### CODE REVIEW

**Comment by Nebyab** [comment]
its happened

finally all my complaining has come to fruition

**Comment by Kierany9** [comment]
>/obj/item/clothing/head/beret/sec/navyhos
>armor = list(melee = 80, bullet = 60, laser = 50, energy = 10, bomb = 25, bio = 10, rad = 0)

>melee = 80
>bullet = 60

Rest in peace you goddamn hat

**Comment by Sarcalogo** [comment]
HoS looks stupid with a helmet on. Sprite an HoS helmet or something. Make it look like something out of Jin-Roh.

**Comment by Nebyab** [comment]
that's literally the point

you pick looking good or having head armour

**Comment by calibraptor** [comment]
+1

**Comment by blobbernaut** [comment]
@Kierany9 That's not even the fucking HOS's hat

**Comment by blobbernaut** [comment]
this is: 
armor = list(melee = 60, bullet = 30, laser = 50, energy = 10, bomb = 25, bio = 0, rad = 0)

**Comment by blobbernaut** [comment]
and you didn't even change 	desc = "A robust beret for the Head of Security, for looking stylish while not sacrificing protection."

0/10 PR DNM

**Comment by McHatters** [comment]
> and you didn't even change desc

glaring oversight, has been fixed.

**Comment by blobbernaut** [comment]
thanks. 2/10 PR now

**Comment by dreamcrab** [comment]
this suxxx, looking fly is cool and good

**Comment by blobbernaut** [comment]
Seriously though. You're actually changing the HOS to start with ZERO ARMOR ON HIS HEAD. That is BAD.

**Comment by calibraptor** [comment]
Give the HoS a NT swat helmet then

**Comment by blobbernaut** [comment]
That would be a strict buff to them starting out, if you're okay with that. melee = 80, bullet = 60, compared to melee = 60, bullet = 30

**Comment by trifornt-tinfornt** [comment]
HoS armor should just be brought down to its current /tg/ armor stats.

**Comment by blobbernaut** [comment]
why? it's already been nerfed to be the same as a vest.

**Comment by trifornt-tinfornt** [comment]
Because muhfullbody vest is kind of obnoxious. Also the beret still has an asinine melee resist.

**Comment by blobbernaut** [comment]
60. That's 10 more than a helmet. That's asinine to you?

**Comment by trifornt-tinfornt** [comment]
/obj/item/clothing/head/beret/sec/navyhos
    name = "head of security's beret"
    desc = "A special beret with the Head of Security's insignia emblazoned on it. A symbol of excellence, a badge of courage, a mark of distinction."
    icon_state = "hosberet"
-  armor = list(melee = 80, bullet = 60, laser = 50, energy = 10, bomb = 25, bio = 10, rad = 0)
  strip_delay = 60

I don't think that says 60.

**Comment by TDcoolguy300** [comment]
60 deciseconds, or also known as 6 seconds.

**Comment by carlarc** [comment]
whoa this pr is even more retarded than WIN STING and crawl update

**Comment by ghost** [comment]
do it :100:

**Comment by Voratius** [comment]
yeah sure +1/3rd

**Comment by ghost** [comment]
Okay +1

**Comment by blobbernaut** [comment]
Trifornt THAT'S NOT THE FUCKING BERET HE WEARS

**Comment by blobbernaut** [comment]
That's a different item entirely which DOESNT EVEN SPAWN ON THE STATION AAAAA

**Comment by Gandalf2k15** [comment]
Why would you remove the HOS beret armor
thats retarded

**Comment by trifornt-tinfornt** [comment]
BLOBBERNAUT IT'S YOUR FAULT THAT I'M STUPID AAAAA

**Comment by Gandalf2k15** [comment]
Infact no... This is REALLY... REALLLLLLLLLLLLY RETARDED. Why would you EVER remove the good looking HoS berret so that he has to go around wearing a fucking HELMET or crappy hitler hat. Are you being serious? That is the worst fuckin idea I've ever heard of. Thats even worse than my R&D idea. Fuckin jesus. He already looks retarded enough. God damn.

**Comment by ghost** [comment]
look cool or look like a dumb retard and live for 2 deciseconds longer
choices, man

**Comment by doobiedoo23** [comment]
I don't wear a beret as a rule when I play sec because I'm not a huge fuckboy

**Comment by Nebyab** [comment]
yes my dream has come true

**Comment by TDcoolguy300** [comment]
Fairly sure the HoS still starts with the dermal patch in his locker, so really this is just a beret nerf

**Comment by blobbernaut** [comment]
dudinyourbackyard .... Looking cool or living longer? Why should that be an intentionally designed choice? That's fucking dumb as hell what the fuck

and no, TD, the HOS does not have the dermal patch at all anymore.

**Comment by Carbonhell** [comment]
I am With nebyab for this one,piss off play-to-win fuccbois

**Comment by Spacedong** [comment]
this change is dumb -1

**Comment by TheOneAndOnlyCreeperJoe** [comment]
fuck berets; nerf them so that only Frenchmen will ever wear them.
+1

**Comment by Spacedong** [comment]
I don't understand why the fuck we're nerfing regular security berets

**Comment by blobbernaut** [comment]
piss off play-to-win fuccbois? Are you an autism? The hat isn't even OP, the only things it had going for it are: The HOS starts with it, and it has 10 melee armor more than the default helmet. 

i

**Comment by Spacedong** [comment]
what the fuck is this PR even, I'm pretty sure 90% of the people that are commenting don't understand what is actually going on

**Comment by calibraptor** [comment]
Two headmins have +1'd this in addition to three GMs who have 1/3rd a headmin vote.

Merge this shit.

**Comment by JohnGinnane** [comment]
Okay dokey, merging

**Pull request merged**
