### PR TITLE
Adds Mothmen!

### PR DESCRIPTION
**Pull request by TDcoolguy300**
-  - rscadd: "Adds mothmen as a playable race"
-  - rscadd: "Mothmen can choose from a current selection of wings at this time"
-  - rscadd: "Big thanks to Fury for the Sprites"

Image
Image
Image
Image

### CODE REVIEW

**Comment by danhibiki** [comment]
do they have any speech impediments like lizards?

**Comment by TDcoolguy300** [comment]
Not at the moment

**Comment by TDcoolguy300** [comment]
Adding a DNM until it's ready to go fully

**Comment by TDcoolguy300** [comment]
This is good to go

**Comment by FuryMcFlurry** [comment]
Aww yeah.

**Comment by Carbonhello** [comment]
This PR adds a config,you may need to speak with an headmin to add it properly

**Comment by TDcoolguy300** [comment]
Carbon it's not a normal config file, this does not get thrown into initial config, only the config/names

**Comment by calibraptor** [comment]
This looks pretty cool.

**Comment by Carbonhello** [comment]
Nvm TD is right

**Comment by danhibiki** [comment]
Looks good t me

**Comment by nalarmg** [comment]
Neb approves

**Pull request merged**
