### PR TITLE
shit

### PR DESCRIPTION
**Pull request by tortellinitony**
merge it now
http://i.imgur.com/eqiNbVZ.png

### CODE REVIEW

**Comment by 2Dollarbill** [comment]
no.

**Comment by gumner** [comment]
yes.

**Comment by ghost** [comment]
no

**Comment by Swagile** [comment]
yes

**Comment by MethMedic** [comment]
Yes

**Comment by TDcoolguy300** [comment]
No

**Comment by Cnavin3002** [comment]
Yes

**Comment by chesse20** [comment]
yes ok

**Comment by TDcoolguy300** [comment]
No

**Comment by calzilla1** [comment]
DEEP LORE

**Comment by TDcoolguy300** [comment]
In the past we've denied shit and piss PRs before, this doesn't change today.

**Comment by PopNotes** [comment]
reopen reeeeeee

**Comment by ghost** [comment]
No.

**Comment by MethMedic** [comment]
Wew closed before it was even denied by heads gg

**Pull request closed without merging**
