### PR TITLE
Fixes non-contraband posters not spawning on map

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Nokington** [comment]
Merge conflicts.

**Comment by TDcoolguy300** [comment]
Likely just a mapping merge issue

**Comment by danhibiki** [comment]
Fix the map conflicts

**Comment by ghost** [comment]
Will work on conflicts in a minute, reopening afterwards.

**Comment by ghost** [comment]
and I fucked up the maps again rip

**Comment by ghost** [comment]
should be working now

**Comment by TDcoolguy300** [comment]
I assume you tested this in game with both the legit and contraband posters, alongside placing both types by themselves?

**Comment by ghost** [comment]
Yep.

**Pull request merged**
