### PR TITLE
Buffs Penned Nerf Darts

### PR DESCRIPTION
**Pull request by ArcLumin**
Adding a pen to a nerf dart now boosts the damage of the dart from 5 to 11

### CODE REVIEW

**Comment by ghost** [comment]
Heh no, I don't want this to become an actual cost effective strat to buy foam force and load pens.

**Comment by blobbernaut** [comment]
it does 11 damage a shot, why not, that's not that much

**Comment by ArcLumin** [comment]
You need to also add in the pen after every shot, as it doesn't keep the pen inside of it

**Comment by JohnMcLaime** [comment]
Dont be dumb, it would take a lot of preparation time to get proper ammount of ammunition upgraded and it would still require a lot of hits to kill someone. Better buy ebow or emag and steal stunguns.
Fucking lol. You would rather have a shitty 1 hit kill combat but not this?
Come on.

**Comment by ArcLumin** [comment]
And it doesn't boost the damage very high at all. Good luck even getting 10 pens you need to get a crit with this, screwdrivering 10 foam darts, addings 10 pens to it, adding all 10 foamdarts back in, and then making all shots hit. If you fuck up you gotta prep em again

**Comment by MethMedic** [comment]
Would be good as a finishing weapon

**Comment by ArcLumin** [comment]
"you just got killed by a nerf dart nigga"

**Comment by asskek** [comment]
I like this, allows for cool Owl gimmicks

**Comment by ghost** [comment]
haha yes
go ahead
+1

**Comment by KittyKathy** [comment]
Hmm where can you get a ton of pens....
Also it would be cool if you could insert a sleepy pen into the foam dart for a improvised syringe gun which is reusable if you miss.
Can you get the pen back from the foam dart i am not sure you can.  Sucks if you accidentally used your energy pen to make one. Why can't this fire activated energy pens!

**Comment by ArcLumin** [comment]
it can. However it just drops the activated pen in front of the target. Any pen inside the dart drops after the shot, not affecting the shot's damage directly.

**Comment by asskek** [comment]
dude holy shit!! imagine firing activated energy pens like a makeshift laser rifle. 
kitty's idea is genius

**Comment by LuisReyesX** [comment]
You can already put sleepy pens inside normal foam darts and it gives them the effect, so this is actually a good balanced change

**Comment by KittyKathy** [comment]
Why does it delete the foam dart it uses and drops the pen. Would be a waste to use riot darts because it does not do stamina damage and it deletes it when used.
Also why is it dropping the pen in front of them instead of making it hit them it would be useless right now to use any pen other than a ordinary one.
I tried in a test server unless it is RNG dependent this is not a ranged sleepy pen gun disappointing.

**Comment by JohnMcLaime** [comment]
Make pens embed?

**Comment by ArcLumin** [comment]
Yeah just use an ordinary pen. Would be neat. But I'd need to heavily change the current code to make it so that pens do an attack by when in the nerf dart. This is just a small damage tweak

**Comment by Pyko1** [comment]
Should really make it drop penned nerf darts, with a chance of embed.
And adjust the damage accordingly.

**Comment by ArcLumin** [comment]
Need to alter how this code is done considerably, but I'll take a look at it. Might have to make it a tad snowflakey. Foamdarts already are a bit snowflakey so it might snowball. But yeah, prolly something like adding the force of the pen to the damage of the projectile and then giving it additional properties based on the path of the pen (i.e. high damage for edagger, giving the sleepy pen effect for the sleepy pen)

**Comment by SpankMasterson** [comment]
+1 mcbaw experiences loss of opinion????

**Comment by ArcLumin** [comment]
Code review needed then it's good to merge.

**Comment by Pyko1** [comment]
Code seems fine, even tho it might be better using set damage instead of adding on to other, as someone might just do herp derp buff without knowing the whole deal.

**Pull request merged**
