### PR TITLE
Removes Syndrone from lootspawner in the armory

### PR DESCRIPTION
**Pull request by Chronitonity**
We really cannot have an antag spawner there sorry

### CODE REVIEW

**Comment by Pyko1** [comment]
still was only about 1 out of 1850 chance for it to spawn.

**Comment by Chronitonity** [comment]
Still shouldnt have a chance at all, theres no reason an admin only antag should have a chance to spawn in the armory with 20tc and laws to kill everyone. No thanks.

**Comment by Pyko1** [comment]
Technically same as spess ninjas and other random antags spawning, just a lot less deadly and rarer.
not that I really have against it being removed, just don't see the issue with it extremely low propability.

**Comment by ghost** [comment]
they have only 10tc btw you've got a higher chance of worse stuff happening tbh and if thye really dont want it, just throw it in the garbage in a box er somethin

**Comment by oprayx73** [comment]
you've got a higher chance of worse stuff happening tbh and if thye really dont want it, just throw it in the garbage in a box er somethin

**Comment by Spacedong** [comment]
aga dont merge this

**Comment by Foosili** [comment]
Yes please. Remove this. :+1:

**Comment by TDcoolguy300** [comment]
:+1:

**Pull request merged**
