### PR TITLE
Chem balancing

### PR DESCRIPTION
**Pull request by lcass**
Balances some issues with chems , sorts out some issues with explosions and makes pyrosium usable. Also buffs a large number of the recipes so that they aren't tripe to make.

### CODE REVIEW

**Comment by Chronitonity** [comment]
@lcass does this fix robotics having access to the science lab

**Comment by lcass** [comment]
It does not, that is being handled by jay.

**Comment by Jaygriff** [comment]
my update also includes door permission fixes.

**Comment by Chronitonity** [comment]
@SplergeBucket hello

**Comment by Jaygriff** [comment]
This is ready to roll.

**Comment by JohnGinnane** [comment]
@Chnkr why is pooling bad?

**Pull request merged**
