### PR TITLE
Fixes dakis.

### PR DESCRIPTION
**Pull request by ghost**
Fixes dakis going invisible after changing their icon.
Fixes being able to change the icon of the daki if you didn't give it a name.
Fixes adding an empty space if you don't give a custom name.
Adds backpack icons to dakis and adds inhand sprites for the Cappy daki, credit goes to GandalfGreyhame for the sprites.
Increases name limit from 10 to 26 as to keep consistent with the defined name limit length.

### CODE REVIEW

**Comment by ghost** [comment]
~~I'd be inclined to argue that adding downscaled sprites (for the most part) for backpacks to make them not invisible is more a bugfix than a feature.~~

Disregard that, does technically change things.

**Comment by Badmex** [comment]
Yes finally

**Comment by ghost** [comment]
yes

yes.

**Comment by SplergeBucket** [comment]
dude i scratched my back and i think i've pulled off a chunk of my flesh because i'm bleeding all over the place wippie gee gawoozwooz this is a pickle of a situation is what i'd say if i wasnt currently bleeding out from the endless pit of flesh unleashed by that plug flesh bit removed now woe is i because woe is me is for hipsters in my last words i say this is a bugfix so yes

**Comment by Lawligagger** [comment]
yes

**Comment by myontasm** [comment]
boy wouldnt it be absolutely hilarious if some degenerate with an anime avatar came and said yes

**Comment by ghost** [comment]
Supposedly I don't have the authority to review code but what you've wrote seems okay to me.

**Pull request merged**
