### PR TITLE
(UPDATED) New recreation room in arrivals

### PR DESCRIPTION
**Pull request by Weisyl**
Added a new recreation room to replace the rarely-used holodeck. Has a nice table for chatting with your fellow grey tide committee and a few arcade machines if you're looking to robust time. Also comes stocked with 2 easels and plenty of canvas for anyone feeling a bit artsy.

### CODE REVIEW

**Comment by Weisyl** [comment]
Oh yeah here's a picture: http://puu.sh/lqEW2/e4b458db21.png

**Comment by danhibiki** [comment]
I've been vocal about this already, but I don't think we should remove the holodeck.

**Comment by calibraptor** [comment]
Why remove the holodeck when you could just make more additions to it?

**Comment by Weisyl** [comment]
What additions would you suggest exactly?

**Comment by Pyko1** [comment]
I personally would hate to see holodeck go.

If anything I would rather see the space adjacent to arrivals hallway used to "proper rooms", and maintenance thinggys moved deeper in to maintenance.

**Comment by ghost** [comment]
:-1:

**Comment by Carbonhell** [comment]
I love the holodeck, death to unbelievers,holodeck is love,holodeck is life

**Comment by Carbonhell** [comment]
Err,you removed access lock from maint bartender vendor. You should report that aswell, and the issue related to it was being discussed so i am not sure how allowed that is.

**Comment by Weisyl** [comment]
@carbonhell That didn't actually remove the access lock.

**Comment by Carbonhell** [comment]
wut,what's this then, +"ane" = (/obj/machinery/vending/boozeomat{req_access_txt = "0"},

**Comment by Nebyab** [comment]
Holodeck4life, but seriously, I'm not certain of the endgoal of this. We've replaced a neat feature that has some fun antag interactions with another room. If we needed some kind of recreation room, there's almost certainly somewhere we can shove it without killing the holodeck.

**Comment by Weisyl** [comment]
Okay forget this for now I'm gonna be fixing everything and overhauling arrivals.

**Comment by Weisyl** [comment]
Here's what we have now:
Arrivals: http://puu.sh/lrN6C/626b9fdccd.png
Bar: http://puu.sh/lrNsm/ac6e15deeb.png

**Comment by danhibiki** [comment]
That actually looks really cool

**Comment by ghost** [comment]
looks gordo

**Comment by Nebyab** [comment]
This looks neat

**Pull request merged**
