### PR TITLE
Gang Update

### PR DESCRIPTION
**Pull request by ghost**
https://i.gyazo.com/949bec7c4e16b604676e2d6cf4ec9cd8.png
https://i.gyazo.com/faf190199bd437b431ab85a7b07f3742.png
The Rigatoni GANG! 

Their special items consist of ;
Brass Knuckles [10 Points] Makes your punches do 10 brute & SOME STAMINA DAMAGE, after a few good hits your enemy can be KNOCKED OUT!! You CAN DISARM AND GRAB WITH THEM EQUIPPED ( Keziah Bould has knocked Valeria Simmons out with a haymaker! )
Italian Revolver [25 Points] A .38 revolver, that does heavy stamina damage like the detective's.
Revolver Ammo [10 Points] A six-shot speedloader for the revolver.
Tommy Gun Ammo [35 Points] A 40 Round drum (reduced from 50) made for the tommygun.
Tommy Gun [55 points] .45 Caliber, does a 3 round burst ( reduced from 4) with some deviation.

The CLANDESTINE GANG's items consist of;
Suppressor[5 Points] suppressors for their gun
Glock 17[25 Points]  Accepts suppressor, higher cap mag than normal pistol
Glock mag[10 points] 14 capacity 9mm magazine
Uzi [60 points] Accepts 32 round stick mag and suppressors
Uzi Mag [40 points] 32 round 9mm magazine.

### CODE REVIEW

**Comment by Chronitonity** [comment]
Brass Knuckles seem like a debuff, Tommy gun costs way too much, like, 105 points for both is terrible dude.

**Comment by McHatters** [comment]
Good shit +1

**Comment by Crystalwarrior** [comment]
Brass Knuckles are objectively worse than Knifegloves that can be created easily.
Tommy Gun seems way too expensive, 30 influence just for ammo is bad.

**Comment by ghost** [comment]
30 is as much as uzi

**Comment by danhibiki** [comment]
So this is a subset of gangs that can spawn in, just themed? Sure.

**Comment by ghost** [comment]
fixed, gave credits to fragg
& randybucket

**Comment by Chronitonity** [comment]
Post pictures of all sprites in game prefferably in the pr

**Comment by oprayx73** [comment]
they ARE did you look at the thing

**Comment by oprayx73** [comment]
https://i.gyazo.com/83d2a25dd51d591474cc4a4674213b8d.png
https://i.gyazo.com/828972394c14447c06fd47435b8f1371.png

**Comment by ghost** [comment]
this is finished

**Comment by Foosili** [comment]
YEAH ALRIGHT sure neat neat sure neat

**Pull request merged**
