### PR TITLE
Adds wooden teeth

### PR DESCRIPTION
**Pull request by Chronitonity**
Botanists can make 5 wooden teeth with 1 wooden plank now.

### CODE REVIEW

**Comment by danhibiki** [comment]
:+1: some good shit right here :+1: :+1: :+1: :+1:

**Comment by danhibiki** [comment]
:100: :100: :100: :ok_hand: sum guuuuud shit boi better approve this yes sir :ok_hand:

**Comment by ghost** [comment]
teef

**Comment by Foosili** [comment]
Teef

**Comment by danhibiki** [comment]
i take that as endorsement

**Pull request merged**
