### PR TITLE
Makes Smuggler's Satchels size 2 instead of 3

### PR DESCRIPTION
**Pull request by ArcLumin**
Title. Now they can fit in your ass, actually giving people a reason to get them. Become the true ass smuggler you always dreamed of, TODAY!

### CODE REVIEW

**Comment by ghost** [comment]
For comedic effect alone I support this.
+1

**Comment by ArcLumin** [comment]
Whelp. Accedentally put the branch on the main thing. I'll delete it as soon as this gets approved or denied.

**Comment by TrashFiend** [comment]
I support this fully

**Comment by Kierany9** [comment]
Yes

**Comment by Pyko1** [comment]
Also you can put them in your pockets if they are size 2 i believe, which isnt really a bad thing as these are under used.

**Comment by Pyko1** [comment]
Also I demand embed chance of 1 on satchel so you can superfart bomb satchel on someones face and have it embed :3

**Comment by ArcLumin** [comment]
Demand? I must cave to your demands then

**Comment by doobiedoo23** [comment]
+1/3

**Comment by SplergeBucket** [comment]
+1

**Pull request merged**
