### PR TITLE
Adds the power fist for traitors

### PR DESCRIPTION
**Pull request by Weisyl**
The powerfist is available to any traitor for 14 TC. When wielded in hand, the user can smash any target across a room with moderate damage and some stamina damage. Needs to charge automatically in-between punches, but the time needed to charge is negligible. Does NOT go in your gloves slot, instead, it must be held in hand like any generic melee weapon. Uses placeholder sprites for the moment, but they're okay for now,

### CODE REVIEW

**Comment by danhibiki** [comment]
I think its definitely worth a spin

**Comment by Chronitonity** [comment]
You should probably change all the descriptions referring to it being two handed now

**Comment by Nebyab** [comment]
Yeah sure

**Comment by Weisyl** [comment]
Mergable now since 2 heads said yes?

**Comment by TDcoolguy300** [comment]
Yes, two headmins have approved this :+1:

**Pull request merged**
