### PR TITLE
Adds a new AI display based off of Tim Buckley.

### PR DESCRIPTION
**Pull request by ghost**
image
image

### CODE REVIEW

**Comment by myontasm** [comment]
LOL

**Comment by doobiedoo23** [comment]
GREATEST

**Comment by yobob591** [comment]
l-loss

**Comment by ghost** [comment]
It's now semi animated with a heart beat rhythm.

**Comment by ghost** [comment]
(Unlike buckley's child.)

**Comment by Spacedong** [comment]
dude im fucking done this is it

**Comment by MethMedic** [comment]
JESUS FUCK WE ARE REACHING LEVELS OF MEMES THAT NO HUMAN HAS EVER SEEN BEFORE. Also a loss of breath from laughter. You should add a display option on the message screens that says "L-LOL"

**Comment by SpankMasterson** [comment]
no -1

**Comment by ghost** [comment]
oh my god

**Comment by MethMedic** [comment]
Spank why

**Comment by calzilla1** [comment]
I'm at a lord of words

**Comment by calzilla1** [comment]
LOST* FUCKING PHONE YOU JUST RUINED MY PUN AAAAA

**Comment by yobob591** [comment]
1 headmin -1 if the other +1s then its up to the gms

get here faggots

**Comment by ghost** [comment]
+1

**Comment by Swagile** [comment]
harmless meme PR

+ 1

**Comment by JohnGinnane** [comment]
Code looks good

**Review by JohnGinnane — APPROVED** [review]

**Comment by Kierany9** [comment]
>(Unlike buckley's child.)

holy fuck

**Comment by Pyko1** [comment]
needs more gm input or nalar/hippie

**Comment by Swagile** [comment]
needs 2 more GM +1's as i gave my approval

**Comment by SpankMasterson** [comment]
I actually +1'd this I just want mcbaw to experience the loss of his PR

**Comment by ArcLumin** [comment]
Yee merging

**Comment by ghost** [comment]
LMFAO THIS GOT MERGED?

**Comment by JohnMcLaime** [comment]
What is the kicker? I cant into memes, i mean what is this?

**Pull request merged**
