### PR TITLE
Changes Slime People

### PR DESCRIPTION
**Pull request by Chronitonity**
Slime People now generate Slime Jelly while fed, up to 200 units

Slime people can "split" and create a new body at 200u of slime jelly. This new body can be controlled only by the original slime person, and they can switch between the new body and the old one provided they aren't dead. The new body doesn't create any equipment, just a naked slime man.

It takes about 10~ minutes after getting a slime person and staying well fed to generate up to 200 slime jelly so this is hardly going to be abuseable. Not to mention that if a slimedude keeps trying to do this he'll get fat and useless. 

It's easier to just get an autocloner and copy your DNA in research than to do this. Hopefully it makes xenobio a ~bit~ more interesting.

### CODE REVIEW

**Comment by danhibiki** [comment]
It'd be interesting to test, but having a spare body might be totally OP and we might need to consider removing it later.

Still up to test it though

**Comment by Carbonhell** [comment]
Wait so you can make clones of yourself and store them for later use?can you even switch while dead?this looks fuckingly cool yet a bit OP

**Comment by Chronitonity** [comment]
Nah if you die while in one you stay dead

**Comment by Carbonhell** [comment]
Seems balanced enough and pretty cool. I'd be up for testing, but perhaps it should've been put in a different PR so if it causes problems it could be easily reverted imo, +1

**Comment by danhibiki** [comment]
Yeah actually, I agree with carbonhell. Lets split this update, one for the plant people removal, and one for the slime race change.

**Comment by Chronitonity** [comment]
Will be done tomorrow then

**Comment by Chronitonity** [comment]
Podpeople removed from this PR, i'll revisit them some other time

**Comment by danhibiki** [comment]
Just waiting on one other head input

**Comment by blobbernaut** [comment]
A slime person hivemind? That's pretty cool. How long does it take to switch?

**Comment by Chronitonity** [comment]
Just about instant. Its less of a hivemind and more backup bodies though.

**Comment by ghost** [comment]
Seems awfully familiar. https://github.com/tgstation/-tg-station/pull/12476

**Comment by Spess-Rando** [comment]
Yeesh, it's almost as if some code was copied directly without credit.

**Comment by Carbonhell** [comment]
I though we already discussed this issue on your coderchat irc,didn't we?Chronitonity handles the porting of fixes/features from tg to hippie, and he forgot to add the "TGstation port" to his PRs, we already discussed the issue on your irc and said sorry heh. Sorry again, i guess

**Comment by AliiTea** [comment]
This is a random comment :^)

**Comment by Carbonhell** [comment]
stfu you cuck

**Comment by Incoming5643** [comment]
It would be nice, if nothing else, to wait until they're merged on TG before ported here. When they're live on your server first people are libel to say we ported you instead of the other way around. Which just kinda stings a bit.

**Comment by Carbonhell** [comment]
That's supposed to be fixed shortly when we'll add TGstation port tags. The tag itself should be enough,i suppose?

**Pull request merged**
