### PR TITLE
Ports TG's Chemistry Balance and Additions

### PR DESCRIPTION
**Pull request by Chronitonity**
As always give me a minute for the changelog

Rebalances some lesser used healing chems so that they're more effective and worthwhile to make
Toxins have been rebalanced, making some of them more efficient and some of them less efficient 

Two new poisons 

Heparin: It's made from Formaldehyde, Sodium, Chlorine, and Lithium. Makes the victim bleed uncontrollably.
Teslium: It's made from Plasma, Silver, and Black Powder and then heated to 400K. Periodicly shocks in the victim and changes their examine text, and makes them take more damage from incoming shocks.

Full list of Medical Changes from TG's PR

Medicine descriptions have been made more descriptive.
Synaptizine now has a 30% chance to cause toxin damage (down from 60%).
Rezadone now instantly heals all clone damage.
Rezadone's negative effects are now an overdose effect that kicks in at 30u.
Oxandralone now heals 4 burn damage if burns are severe (up from 2).
Morphine now makes victims drowsy at 12 cycles, with the old sleeping effect kicking in at 24 cycles.
Miner's Salve now stuns and weakens for 4 ticks when ingested/injected rather than applied via touch (up from 2).
Miner's Salve now gives a message when used properly hinting at its use as a painkiller.
Pentetic Acid no longer has a small chance to cause bruising.
Oculine now heals eye damage before 15 cycles and gives messages upon blindness and nearsightedness being removed.
Atropine now heals all damage types by 2 each tick if the patient is in critical condition and completely halts losebreath.
Diphenhydramine now has a 10% chance to cause drowsiness (down from 50%).
Diphenhydramine now removes 3 units of Histamine per tick (up from 1.5).
Epinephrine's healing effects now function when the patient is in critical condition at all.

Amatoxin now deals 2.5 toxin damage (up from 1).
Lexorin is now much more effective due to its inferiority to similar chemicals that cost less to make.
New toxin: Heparin. Made from Formaldehyde, Sodium, Chlorine, and Lithium. This functions as an aggressive anticoagulant, inducing uncontrollable bleeding that even bandages won't stop. Bleeding in this manner has a unique examine text.
New toxin: Teslium. Made from Plasma, Silver, and Black Powder, heated to 400K. Teslium modifies human examine text ("They are emitting a gentle blue glow!") and periodically induces shocks of varying strength. The shocks themselves happen often but unpredictably, and bypass clothing protection because it's inside the bloodstream.

Additionally makes blood packs be able to be renamed with a pen, and changes them to OPENCONTAINER instead of INJECTONLY, meaning that you can pour a beaker into a blood pack. Note that this doesn't allow blood packs to function as beakers, and you can't pour things out of them to use them as ghetto beakers.

### CODE REVIEW

**Comment by ghost** [comment]
is black powder a little touch stronger??

**Comment by Chronitonity** [comment]
Nope, not touching explosion sizes for anything right now

**Comment by Chronitonity** [comment]
Changelog added, this is ready to merge pending head input.

**Comment by ghost** [comment]
yea this is good quality
just someone fix black powder ;(

**Comment by danhibiki** [comment]
Looks good.

**Comment by danhibiki** [comment]
Only comment I have

> Rezadone now instantly heals all clone damage.
> Rezadone's negative effects are now an overdose effect that kicks in at 30u.

when would you overdose on rezadone?

**Comment by Chronitonity** [comment]
Probably never, but it never hurts to have it do something

**Pull request merged**
