### PR TITLE
Vampires now appear on the check antagonist verb

### PR DESCRIPTION
**Pull request by ghost**
Works pretty much the same as traitor check antagonist BUT tells you if the vampire is in bat form. (Can be removed if required)

### CODE REVIEW

**Comment by myontasm** [comment]
I vill check your valids, bleh!

**Comment by TheOneAndOnlyCreeperJoe** [comment]
Vlad's not a vampire though :^)

+1

**Comment by ghost** [comment]
> Impaling

**Comment by Nebyab** [comment]
alright, someone code check this. Fine otherwise

**Comment by dreamcrab** [comment]
yesssum

**Comment by Kokojos** [comment]
Code's good

**Pull request merged**
