### PR TITLE
Space Update v1

### PR DESCRIPTION
**Pull request by oprayx77**
http://puu.sh/t6o0I/b0b1ffd8c0.jpg
Derelict science now has the proper supplies to get started, with all circuits and some acid spawning there.

http://puu.sh/t6nKm/56778e1db1.png
Clown crash site now has a plasma cutter instead
of a pickaxe to make it subtly more rewarding.

http://puu.sh/t6nEA/33a5a7555b.png
Asteroid area in derelict zlevel was barren and barely useful because no one would crack the safe. Now it's got a alien pistol that requires you to remove the firing pin to use.

http://puu.sh/t6nqv/42157e5fae.png

Mining abandoned area got its suspicious toolbox back aswell as a chest carrier, so you cant complain there was a scary suit there. Dunno why anyone removed it, it's a nice gift that the miners can go out of there way to get for scientists.

i plan to make shifts in items often to make the playerbase atleast check in space every once in a while instead of expecting the sameold sameold all the time

### CODE REVIEW

**Comment by ArcLumin** [comment]
I like it. We need more space shifting

**Comment by ArcLumin** [comment]
Also, wouldn't mind if the derelict was easier to fix up. Like premade solars for powering. This gets us that much closer

**Comment by Swagile** [comment]
its nice too because 3 drone shells spawn on derelict

i was so rustled when i couldn't even fucking start RnD so i could make more drones to fix up derelict as a pass time during changeling rounds

my GM +1 if this all works

**Comment by Pyko1** [comment]
Instead of manually map editing the items, might be better to make spawners for em.
So you could automate the item changing with big list to pick from.

Also a spawner can contain only 1 item, and you can then change the spawner, instead of map to swap items around.

**Comment by lcass** [comment]
the spawners idea is a good one , have 15 or so locations where cool syndie items can spawn with 5 or so locations that are chosen.

**Comment by Pyko1** [comment]
Would do it with spawn chance isntead.

ie. all 15 spots have same spawner but the spawner has built in 2/3 chance to be empty, so in average it gives loot to 5 spots.
Or instead of being empty just make it put not as desirable items.

Basically make it be like supercharged maintloot or contraband spawner.

**Comment by ArcLumin** [comment]
Would be a good idea to add lesser used tator items. Like camera bugs and shit.

**Comment by ghost** [comment]
Derelict science is eh but okay I guess.
Clown shuttle already has honker shoes and banimum (solidification recipes shouldn't exist imo). Plasma cutters are easy to get and this makes little difference.
Cracking the safe is easy if you have a stethoscope, there's a guide on it.
I don't understand the non syndie toolbox item addition. What does it entail?

**Comment by oprayx77** [comment]
No, i put a syndicate toolbox back where it used to spawn on the map. 
@McBawbaggings 
http://puu.sh/t6nqv/42157e5fae.png

I also put a chest carrier cause its a neat way to carry a gun or whatnot

**Comment by oprayx77** [comment]
right now i am extra lazy but i will probably go ahead and see about using maint loot spawners system for space rewards

**Comment by ghost** [comment]
I was asking what a chest carrier does because I can't find it in the code.

**Comment by Swagile** [comment]
its what you use to hold guns

its a reskin of ballistic armor i believe because it protects from bullets more than anything

it also holds guns; its what you use to hold the mosin from space

**Comment by oprayx77** [comment]
no chest carrier literally has 0 protection it just carries ammo or a gun

armor = list(melee = 10, bullet = 5, laser = 5, energy = 0, bomb = 0, bio = 0, rad = 0) 
big deal

**Comment by SpankMasterson** [comment]
+1

**Comment by oprayx77** [comment]
@ArcLumin  changelog added

**Comment by oprayx77** [comment]
@McBawbaggings take a look and give VOTE dad

**Comment by Hackole** [comment]
yeah this looks fine, +1

**Comment by oprayx77** [comment]
reeeeeeeeeeeee merge

**Pull request merged**
