### PR TITLE
ERT Rebalance

### PR DESCRIPTION
**Pull request by calibraptor**
Purpose of this PR:

Red Alert ERT shouldn't be tearing up the station en masse with pulses, thus I'm changing their loadout so there's an actual tangible difference between Red Alert ERT and Deathsquad.

Changes in this PR:
- Red Alert Commanders retain their non-rechargable pulse pistol, being the only ERT unit equipped with pulse weaponry.
- Red Alert Security now start with a laser rifle and laser pistol in their bag.
- Red Alert Medics now start with a laser pistol, and no longer spawn with a medbeam gun. A single medbeam gun has been placed in the ERT armory. This is to solve the issue of them blowing everything up when the beams are crossed.
- Red Alert Engineers now start with a laser pistol
- Removed the space graffiti on Z2 while I was at it*

wee wee wee all the way home

### CODE REVIEW

**Comment by Gandalf2k15** [comment]
> files changed 0

**Comment by Spacedong** [comment]
>

**Comment by calibraptor** [comment]
I forgot to commit before making the PR, fixed it now you nerds.

**Comment by Gandalf2k15** [comment]
mother fucker did you not map merge

**Comment by calibraptor** [comment]
I did actually, that's odd.

**Comment by Spacedong** [comment]
that commit name is NOT kosher, gonna have to give this the Organization Dedicated to Kosherness seal of disapproval :-1: :8ball:

**Comment by calibraptor** [comment]
There, it's properly mapmerged. Now get off my butt.

**Comment by Gandalf2k15** [comment]
I am no longer on your butt. THANKS.

**Comment by dreamcrab** [comment]
yeah looks good to me +5

**Comment by ghost** [comment]
Yeah okay +1

**Comment by calibraptor** [comment]
<3

**Comment by Gandalf2k15** [comment]
Head input gained, final checks in progress.

**Comment by Gandalf2k15** [comment]
Code is good, merging.

**Pull request merged**
