### PR TITLE
Alters Phazon creation to be actually viable (Updated)

### PR DESCRIPTION
**Pull request by ArcLumin**
REVISED
Altered the scanning modules to use phasics, and the caps to be quadratic, meaning it needs both diamonds and silver.
Removes anomaly core requirement
Since there's no telesci, only place to get non-artificial crystals is mining, and you'll need mining anyways for the diamonds.
Phazons were nerfed a while back too, so they're pretty squishy compared to most mechs

### CODE REVIEW

**Comment by ghost** [comment]
No this is bad. Anomaly cores were added for a reason.

You can make a phazon from on-station materials and some RnD at roundstart, robotics had like 5 of them at the end of every round.

**Comment by Carbonhell** [comment]
wut
to make a phazon you need to COMPLETELY maximize research(materials level 6, EM level 6, everything else to level 5 excluding illegal), along with a very good amount of plasma sheets. I've seen phazons once in a month, and it needs a good 30 mins to make one, i don't think an anomaly core is needed but my main point is that we shouldn't use RNG as a barrier for fun things

**Comment by ghost** [comment]
Which can be done with shit the station starts with.

All it takes is an Overlop and 30 minutes and they can mass-produce them.

Surely carbon you remember when this was added and why.

**Comment by Carbonhell** [comment]
Honestly i don't, I don't think i was around when this got added but we could surely find a better barrier than something decided by byond rng?no clue

**Comment by GenericGoose** [comment]
Tru, anomaly requirement doesn't stop powergaymers, you're only making it easier
Also I have a route of getting enough research without ever interacting with a single person on the station and without mining (it's outdated, now it's even easier tbh)
tbh idk 
is it even worth it? you can mass produce other mechs
it will just be easier for powergaymers and whoever gets high research
good in essence
but then anomaly cores are useless?

**Comment by ArcLumin** [comment]
Well, here's my reasoning;
1. Relying on something to be completely dependent on both a large time investment and a random event which might not happen in the round is pretty fucked up
2. You still need to get the bluespace crystals from mining
3. It's limited to only those with a high enough knowledge of the game and its systems to do rnd to mats 7 and bluespace 6, among others
4. It's about the same tier, and arguably worse, than some of the other mechs. It has some mediocre defenses, huge powerdrain on it's phasing (200 power per action compared to the 3 normal power drain), can't interact with things while phasing, standard attack only deals 15 damage (mind you, you can change the type, but when a ripley can clamp you for double that in brute/oxy mixed damage, you're kinda shortlived). The phasing isn't even super great; any mech with a drill can gain similar access by drilling down doors or walls. It's slow, huge powerdrain, and not particularly great at combat, but it's fun. Sure metagamers can make them, but with more of a time investment than the other mechs without much of a payout, as the other mechs are far better in combat and can reach the same levels of access.

**Comment by ghost** [comment]
Bluespace crystals are RnD, not mining.

And you doubt the crew's ability to make them. I assure you, the core limitation was a direct response to how often they were produced. Sci could make a combat mech 100% independently. That is scary regardless of how good the mechs actually are.

**Comment by ArcLumin** [comment]
You can make them via rnd provided you get diamonds from mining, if I recall, and they can be found scattered amongst the asteroid.

And I don't doubt the crew's ability to make them. I'm just saying they're not particularly great compared to other mechs. Currently, sci can make honkmechs almost entirely independently as well, and within 10 minutes or so of roundstart, which ARE combat mechs, and with little to no research done.

**Comment by ghost** [comment]
If you can confirm 100% that it requires diamonds to make, then that's less of a problem in my books. Even honk mechs require clown or botany co-operation.

And casting my mind back, one factor may have been that we had telesci at the time, so they could take crystals from the teleporter.

**Comment by ArcLumin** [comment]
Yes, telesci back then had full on bluespace crystals, which could be taken. With telesci gone, there's only a few artificial bs crystals on the station by deconing the teleporters, and those won't work with this. 

Additionally, when the telesci nerfs hit, it seems normal bluespace crystals were removed from RnD ENTIRELY, leaving only artificial bs crystals in RnD, which can't be used for phazons and STILL require diamond. Can 100% confirm, they use 1500 diamond. Currently, only place to get true bluespace crystals is mining

Also, by taking the whiteship to Z4 (RD can get to the whiteship in under 2 minutes of roundstart every time by using the abandoned teleporter) You can easily get to the clown asteroid and take its 92 bananium for tons of honk mechs. As well as 3 sets of clown gear and clown access to use the honk mechs. Additionally, you can make 25(or was it 28?) sheets of bananium from the clown's honk cooler, another 2 from deconing the clown's door, and another 5 from deconing the clown's statue, all accessable by simply taking down a non-reinforced window. There's also another set of clown gear near sec, if you don't feel like breaking the locker open with lasers or drills or acid or anything of that nature.
It only takes about 20 or so bananium for a honk mech, and less if you upgrade the exosuit fabs

Additionally, 29 of the bananium from the clown asteroid is pure ore, meaning it can be multiplied to make even more bananium by properly upgrading the ore smelter before smelting

**Comment by GenericGoose** [comment]
honk > phazon
tbh remove anomaly core requirement and all these gayass fake bluespace crystals. what's even the point of them? they're just a pain in the ass

**Comment by GenericGoose** [comment]
I think it's a good change, though anomaly cores don't have other uses, do they?

**Comment by ghost** [comment]
They can be deconstructed for research but that's all I think.

**Comment by Carbonhell** [comment]
they can be attached to assemblies and put in grenades to have anomaly grenades,lads

**Comment by ghost** [comment]
I think this is fine.
We don't have the same issues as /tg/ has over RnD powergaming.
+1

**Comment by Spacedong** [comment]
I saw a guy use one to take out an entire deathsquad. Phasing through walls is pretty OP. Gygax is really all you need if you're robust anyway. Ehh? also @mcbawbaggings surely you're being sarcastic right?

**Comment by Nebyab** [comment]
nah

**Comment by ArcLumin** [comment]
@Nebyab why not?

**Comment by SplergeBucket** [comment]
Quick Phazons are a devastating cancer.
Unless it's going to be made into a glass cannon esque mech then nah.

**Comment by ghost** [comment]
1 against 2.

**Comment by ArcLumin** [comment]
@SplergeBucket As I posted above, they are glass cannons compared to other mechs, and they're not quick at all; you'll find it easier to make a gygax or a durand than a phazon due to the lack of bluespace crystals on the station, and needing mining for them, and them being far rarer on the mining asteroid than ores.

Meanwhile, honk mechs are a far faster, far easier combat mech to make that requires no mining and you can have one up and running in less than 5 minutes of the roundstart, solo, if you're good at it. It also has a powerful AoE knockdown that trumps the phazon's phasing massively.

**Comment by GenericGoose** [comment]
who needs phasing anyway if ripley can drill airlocks

**Comment by GenericGoose** [comment]
@also bullshit crystals aren't that hard to find on the asteroid with mining equipment
~3 minutes from roundstart to crystal being in the RD

**Comment by Carbonhell** [comment]
> absence of bluespace crystals on station
> Just decon a teleport console

**Comment by ArcLumin** [comment]
As I said above, those are artificial crystals, which shouldn't work in the phazon creation. The only way to get real crystals is mining.

**Comment by ArcLumin** [comment]
> tfw you can't add more code because it's closed

Altered the scanning modules to use phasics, and the caps to be quadratic, meaning it needs both diamonds and silver.

**Comment by ArcLumin** [comment]
Also altered it so it FOR SURE won't accept artificials.

**Comment by ArcLumin** [comment]
@McBawbaggings, reopen this

**Comment by GenericGoose** [comment]
plz remove aritficial crystals they are snowflakey
whats even the point
p sure its easy to get BS to lvl6 without crystals

**Comment by ArcLumin** [comment]
@Nebyab, @Carbonhell, @SplergeBucket, new opinion?

**Comment by Carbonhell** [comment]
For me it's okay, but i'm not an head so why ping me? :mememan2:
Code's ok through BUT SLAP A DAMN CHANGELOG ON IT

**Comment by SplergeBucket** [comment]
finna fine we do a trial

**Comment by ArcLumin** [comment]
@Carbonhell Because you're the only one who codechecks

**Comment by Carbonhell** [comment]
changelog mate and it can go

**Comment by GenericGoose** [comment]
can it go now?

**Comment by ArcLumin** [comment]
I think it can be merged now?

**Comment by ArcLumin** [comment]
We good to go on this lads?

**Comment by ghost** [comment]
Nebyab still objects I would imagine. 
I'll ask him about it.

**Comment by ghost** [comment]
This is good to go on the headmin front.
However the changelog lacks a .yml extension.

**Comment by ArcLumin** [comment]
10/10 phonecode top tier

**Comment by ArcLumin** [comment]
Fixed

**Comment by Gandalf2k15** [comment]
Everything checks out. Merging.

**Pull request merged**
