### PR TITLE
Addresses Issue #2841

### PR DESCRIPTION
**Pull request by ghost**
Addresses Issue #2841

### CODE REVIEW

**Comment by ArcLumin** [comment]
I wonder how exactly this would work with very small bombs? If it's deleting the container rather than doing the explosion (emptying before exploding), wouldn't that cause small bombs (i.e. PDA explosions) cause say, the backpack they're in to be entirely deleted, or even worse, delete the mob that's holding them?

**Comment by ghost** [comment]
With smaller bombs, if they're big enough to harm anything, they're big enough to destroy the container they're in, realistically speaking. But, as noted, I've made it drop all items from the container before destroying it. This has the added effect of stuff inside the container being able to be pushed around, a la shrapnel when the explosion goes off.

And it checks if the container is of type /obj/weapon/storage. It would never destroy the player.

**Comment by ArcLumin** [comment]
Yeah, saw that /obj/weapon/storage after I posted that.

I dunno off the top of my head, is package wrapping part of /obj/weapon/storage?

**Comment by ghost** [comment]
The boxes it produces are, yeah.

**Comment by ArcLumin** [comment]
They're not /obj/item/smallDelivery and /obj/structure/bigDelivery?

**Comment by ghost** [comment]
/obj/item/weapon/storage/box

**Comment by ghost** [comment]
You were right about the delivery objects being the issue. Changed to address those instead.

**Comment by TDcoolguy300** [comment]
Code is good, fixes a known issue. Merging.

**Pull request merged**
