### PR TITLE
Updates the admin list

### PR DESCRIPTION
**Pull request by Nokington**

### CODE REVIEW

**Comment by Pyko1** [comment]
Uh oh, still not in a Coding/Spriting/Mapping Team, time to leak hippie code!

**Comment by AliiTea** [comment]
@Nokington pretty sure Nien left and I don't really code anymore

**Comment by Nokington** [comment]
hey fuck you guy

**Comment by AliiTea** [comment]
:'D

**Comment by Pyko1** [comment]
But I already leaked our code :s

**Pull request merged**
