### PR TITLE
Increases the amount of spacedrugs in ambrosia vulgaris and ambrosia …

### PR DESCRIPTION
**Pull request by danhibiki**
Increases the amount of spacedrugs in ambrosia vulgaris and ambrosia deus so they have an effect when in rollies.
Added poisoned apples as a mutation to apple trees, as well as changed their descriptive text and seed packet description to have a slight difference between normal apples (merely a question mark)

### CODE REVIEW

**Comment by Carbonhell** [comment]
Code looks fine

**Comment by Spacedong** [comment]
wait wait a minute hold up, increase the amount of omniziine in deus

**Comment by doobiedoo23** [comment]
S E S H H O L L O W A T E R B O Y S 

:+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1:

**Comment by danhibiki** [comment]
I wanted to make deus less of a catch all, it still is better than ambrosia, and you'll still get a lot of healing, its just now its not exclusively a medicinal plant; its a drug.

**Comment by ghost** [comment]
water boys on deck water boys in this shit

**Comment by SplergeBucket** [comment]
yup

**Comment by Nebyab** [comment]
sure

**Pull request merged**
