### PR TITLE
Increase wooden barricade cost (redo)

### PR DESCRIPTION
**Pull request by ghost**
Reduces the clutter and merges changelog into one commit see #2825

### CODE REVIEW

**Comment by Pyko1** [comment]
code ok i guess

**Comment by Kokojos** [comment]
yes sure +1

**Comment by ArcLumin** [comment]
What's even the point outside of "muh immersion"

**Comment by ghost** [comment]
Yeah okay +1.
QoL changes are always appreciated even if they're a bit pedantic.

**Comment by ghost** [comment]
yee

**Comment by GenericGoose** [comment]
how many PRs are related to this? at least 3?

**Pull request merged**
