### PR TITLE
Re-adds vox toggling

### PR DESCRIPTION
**Pull request by danhibiki**
No longer will AIs be able to spam you without your consent

### CODE REVIEW

**Comment by Nokington** [comment]
:+1:

**Comment by TDcoolguy300** [comment]
There's no "Before Rebase Content" label, so i just threw it as a Pre-rebase issue

**Comment by AliiTea** [comment]
Fuck yes :+1:

**Comment by Nebyab** [comment]
siure

**Comment by TDcoolguy300** [comment]
Two headmins, merging

**Pull request merged**
