### PR TITLE
Fixes that cancerous Ai special_role bug

### PR DESCRIPTION
**Pull request by Carbonhell**
get fucked bugs

### CODE REVIEW

**Comment by ghost** [comment]
BLYAAAAAAAAAAAAAT

**Comment by blobbernaut** [comment]
What did this bug do

**Comment by KayeArray** [comment]
I'm assuming this fixes traitor AIs from being assigned special roles such as cultist

**Comment by ArcLumin** [comment]
Code's fine. Merging bugfix

**Pull request merged**
