### PR TITLE
defibrillator funny business

### PR DESCRIPTION
**Pull request by lcass**
gives defibs huge ability when emagged , if used for a full cycle on a dead body they will gib it. If a full defib occurs on a living person they will receive substantial damage and a stun

### CODE REVIEW

**Comment by lcass** [comment]
Hold off on this for a little bit , a few kinks i've found.

**Comment by Kokojos** [comment]
I am not sure about the gib part. Seems abusable with a full charge and a medbay lobby.
Adding DNM until your kinks are fixed.

**Comment by ghost** [comment]
Gibbing feels like an no-go to me, since it's waaaaay to easy to just go around and gib death bodies.

**Comment by lcass** [comment]
If I removed the gib feature would that be alright? Just deal huge damage to livings after a full charge?

**Comment by lcass** [comment]
I did have an idea , make it so that emagged ones can deal the full damage as already present in my code , but also allow for medical personel (specifically medical personel ) to be able to buy a second version of it for 16 telecrystals that has the gibbing implemented. Thoughts?

**Comment by collinxchu** [comment]
Again, adding items that can easily be spammed to gib bodies seems a bit ech to me. There's a reason why C4 doesn't gib bodies anymore. Maybe make them husked to unknown at most, but honestly an emagged defib being able to be used as a weapon is good enough IMO.

**Comment by lcass** [comment]
aight

**Comment by SplergeBucket** [comment]
@lcass 
You gunna do anything with this?
Otherwise i'm gunna shut down the PR.

**Comment by lcass** [comment]
nop , decidedly OP

**Pull request closed without merging**
