### PR TITLE
#2871: Adds RC & KAD & NC to the Head of Security office.

### PR DESCRIPTION
**Pull request by ghost**
#2871

**Changelog:**
- rscadd: "There is now a Key Authentication Device (KAD) in the Head of Security office." 
- rscadd: "There is also a Request Console (RC) in the Head of Security office." 

**Screenshot:**
science town 2 2016-09-05 163908

**Note:**
- Please let me know if there's any issues in regards to anything.

### CODE REVIEW

**Comment by Kierany9** [comment]
>map pr
>mapmerge
>screenshots
>logs

10/10 PR of the year

**Comment by LuisReyesX** [comment]
@Theomund , what about the special newscaster unit in HoS office that can censor news channels and put wanted reports/alerts.

**Comment by ghost** [comment]
@LuisReyesX I thought that the newscaster outside took care of that; I'll add that if need be. But, I'll need to think of a spot.

**Comment by ghost** [comment]
**Changelog:**
- rscadd: "Finally, a Security newscaster was also added in the Head of Security office."

**Screenshot:**

gentleman monitor eight 2016-09-05 215707

**Comment by ghost** [comment]
office zulu 2016-09-05 223458

**Comment by Pyko1** [comment]
Can you add a lightswitch next to door while on it.

**Comment by LuisReyesX** [comment]
my autism is finally happy

**Comment by Kokojos** [comment]
Yes + 1

**Comment by ghost** [comment]
Adding the light switch now.

**Comment by ghost** [comment]
fat delivery installation beta 2016-09-09 004328

**Comment by LilKek450** [comment]
add it you kikes

**Comment by SplergeBucket** [comment]
should be merged

**Comment by doobiedoo23** [comment]
+1/3

**Comment by ghost** [comment]
Yeah please +1

**Comment by Nebyab** [comment]
fuck me someone needs to merge this shit

**Comment by Gandalf2k15** [comment]
Please fix the conflicts. Then it can be merged,

**Comment by Pyko1** [comment]
aproved and fixes

**Comment by Pyko1** [comment]
but there is a conflict, please fix it

**Comment by Gandalf2k15** [comment]
Conflict. Fix.

**Comment by doobiedoo23** [comment]
Fix the conflict aaa

**Comment by SplergeBucket** [comment]
rip

**Comment by ghost** [comment]
Map conflicts are not easy to fix. Rip.

**Comment by ghost** [comment]
Their account is deleted, rip in pieces my dude.

**Pull request closed without merging**
