### PR TITLE
Zombie balance tweaks and bugfixes #2

### PR DESCRIPTION
**Pull request by Crystalwarrior**
- rscadd: "Adds antag hud for player zombies + lets zombies see infected people"
- tweak: "You will no longer transform into a Zombie if you're alive. Zombie virus now requires you to be dead for transformation to happen."
- tweak: "Zombies now fully take the armor into account. If you see a zombie with ablative armor chances are lasers won't do as much damage to it."
- tweak: "Made zombie bites warn the zombie whether or not the infection passed - this helps convey to zombies that biosuits/spacesuits have a chance to protect against bites."
- tweak: "You can now infect dead people as a zombie."
- bugfix: "Fixes some bugs with reposession of zombies"

### CODE REVIEW

**Comment by Crystalwarrior** [comment]
DNM, I'll include "Infected" and "Zombie" HUD icons for this

**Comment by Crystalwarrior** [comment]
Merge-ready now

**Comment by Crystalwarrior** [comment]
okay ACTUALLY merge ready.

**Comment by danhibiki** [comment]
ok

**Comment by Nebyab** [comment]
sounds good

**Pull request merged**
