### PR TITLE
Adds RD and CMO hardsuit to the map, removes 2 Space Suits from Command EVA

### PR DESCRIPTION
**Pull request by Chronitonity**
Adds the CMO and RD hardsuit to the map while removing the 2 space suits in Command EVA

Pictures of the hardsuits and the map

RD:
http://puu.sh/kIMKB/69d8aced85.png
CMO:
http://puu.sh/kIMMr/bf4ab574dd.png

Command EVA is now renamed Command Tool Storage, picture here:
http://puu.sh/kIMUH/5d5ceae844.png

Also changes the box storage room in maint to something not complete shit. Includes a nice social commentary about veterans being homeless or something. Heres a picture.
http://puu.sh/kIMQP/05f1c67243.png

### CODE REVIEW

**Comment by lcass** [comment]
Eh on command tool storage , put the rcd in there or something

**Comment by Chronitonity** [comment]
Rather not seeing how theres one literally right next door in EVA

**Comment by danhibiki** [comment]
Sure why not

**Comment by Foosili** [comment]
I'm personally unsure how I feel about sticking space suits IN medbay and research.

**Comment by Chronitonity** [comment]
RD and CMO already had access to space suits, but I don't think this is going to be a major change to anything balance wise. 

The main reason they're in their offices and not EVA is because they would be a decent amount easier to steal. If your worried about someone else getting the hardsuits, people can just lock the suit storage unit and not allow others to get in it without access iirc.

The main goal for this is to have the CMO be able to go get bodies that people left in space, seeing how he already gets a belt defib, this gives him a bit more use than being a doctor with all access

The RD hardsuit is basically a glorified bombsuit with as much fire protection, and it has a research scanner built in so he can tell tech levels.

I don't think this is gonna change anything for the worse, and if it does, a revert will just be removing two things from the map.

**Comment by Foosili** [comment]
Alright I'm down with seeing how this goes then.

**Pull request merged**
