### PR TITLE
AI Radio quickfix

### PR DESCRIPTION
**Pull request by AliiTea**
Shanks GunHog

### CODE REVIEW

**Comment by AliiTea** [comment]
https://github.com/HippieStationCode/HippieStation13/issues/175

Time to fix ^_^

**Comment by ghost** [comment]
@Memendia see commits. :^)

**Comment by Memendia** [comment]
What
WHAT did you do nigger

**Comment by ghost** [comment]
i sniped you. :100:

**Comment by AliiTea** [comment]
I hate you

**Pull request closed without merging**
