### PR TITLE
Remove tips about blobs, adds tips about pools.

### LINKED ISSUE #2525: outdated tips
notably the blob tips and other shit thats only on /tg/ and no longer here

### PR DESCRIPTION
**Pull request by Kokojos**
Sorta fixes #2525

### CODE REVIEW

**Comment by JohnGinnane** [comment]
Can I also ask that you add in a tip for the pool that people lying down (such as after falling in) are unable to breath and can quickly drown?

**Comment by Kokojos** [comment]
You get a 35% chance to get warned that you are drowning from the pool code each time you take damage, are you sure this would't be a bit redundant?

**Comment by JohnGinnane** [comment]
Perhaps. It's just to try let users know that if they throw/push people into the pool they could accidentally kill them

**Comment by Kokojos** [comment]
Updated.

**Comment by JohnGinnane** [comment]
Thank you! Does this need head approval?

**Comment by myontasm** [comment]
It does, but I doubt you'll be met with a 'no'

**Comment by ghost** [comment]
Yeah okay +1

**Comment by Carbonhell** [comment]
Needs nalar since this is technically a config update

**Comment by Carbonhell** [comment]
i repeat,  @nalarmg you are needed

**Comment by McHatters** [comment]
where in the world is nalar sandiego

**Pull request merged**
