### PR TITLE
Zombie apocalypse

### PR DESCRIPTION
**Pull request by Crystalwarrior**
Completely reworks zombie functionality:
- Zombies can now only infect LIVING humans with a Zombie disease.
- Zombies can now force open doors.
- Prevent Zombies from spawning in gold slime cores
- Zombies now have a consistently slow speed
- Zombies become adminspawn/derelict-only event right now. In the future I plan to make it a round conversion type of thing (when all antags die, etc.)

### CODE REVIEW

**Comment by danhibiki** [comment]
:+1: I think you should consider implementing this in the mulligan modes as soon as possible, barring negative input from heads or other person(s).

**Comment by Lawligagger** [comment]
I'm for this.

**Comment by Nebyab** [comment]
Yeah sure

**Comment by Crystalwarrior** [comment]
alright, as soon as I add the mulligan round support it'll be merge-ready.

**Comment by Chronitonity** [comment]
This is merge ready, just get a second head to sign off on the mulligan round zombies

**Pull request merged**
