### PR TITLE
Rebalances the laser rifle to be less ridiculously OP

### PR DESCRIPTION
**Pull request by calibraptor**
Laser rifle now does 30 damage as opposed to 45, and holds 12 shots as opposed to 8.

It doesn't make sense to me that the laser rifle deals a whopping 45 damage, while a laser cannon deals 40.

It's still a straight upgrade on the default laser gun. Dealing an additional 10 damage and having the same number of shots.

Reason for this change is I plan on outfitting red alert ERT with laser weaponry as opposed to pulse weaponry, and I'd prefer that the laser rifles not be massively overpowered as they are now.

### CODE REVIEW

**Comment by Hackole** [comment]
Reasonable rebalance. Not a bad idea.

**Comment by trifornt-tinfornt** [comment]
_I'm stupid and retracted this, but I'm still gonna leave this up_
Gandalf can't balance his PRs if his life depended on it (although at this rate the game is so deep into a hole of poor balancing that adding one or two particularly unbalanced items isn't going to be that large of a stir) though this balance change isn't a very good idea either. 8 shots of 45 damage is disgusting, but 12 shots of 30 damage is still upgrading its firepower and is kind of removing the point of the damage debuff as if you have anyone taking 30 damage they're gonna get slowed and you can just hammer them with more shots - especially if you have already stunned them.
3 shots to crit someone when your max clip is 8 means that if you land all of your shots you can only crit two people, and severely wound (and easily finish off) another. However, 4 shots to crit someone with 12 ammo means that you can crit 3 people successfully if you land all of your shots. It also gives you more room for error if you manage to miss some shots and as a result makes it slightly better.
The final shot in the foot being that normal laser guns have 10 ammo and this has 12. Yet it deals more damage.
Ultimately it seems to undo its self. Keep it at 8, please - or at maximum have it at 10. And I know that there are worse weapons out there (advanced energy gun which is the captain's laser but with a stun and disable function so god help us all) but it's not helpful if an item is already as powerful as 4 hit critting someone yet has a higher clip than the laser gun - which takes 5 hits to crit someone.

Also ERT is horrendously underpowered and useless, as they almost never achieve their goals of helping the station (oftentimes due to a lack of particularly helpful items) and attempt to do nothing but act like Deathsquad and charge their killers in an attempt to metagrudge them metagrudge just to get utterly stomped. They need to actually be able to help before they get a firepower nerf - like the Medical ERT member maybe having something that gives him more bruise packs and ointment, and the Engineering ERT members having higher-capacity RCDs.

**Comment by JohnGinnane** [comment]
Code looks good as is

**Comment by calibraptor** [comment]
@trifornt-tinfornt Do you play ERT very often? Medical and Engineering ERT receive plenty of supplies and tools to do their jobs effectively. Such as medi-guns and a bunch of spare compressed matter cartridges for the RCDs.

Also, laser guns have 12 shots, not 10.

The laser rifle and laser pistol are currently adminbus only so I don't see why making them ERT exclusive would cause any fuss, considering I'd be replacing 60 damage pulse weapons with lasers.

That said, ERT generally shouldn't be tearing up the station with pulses but should still be well armed. Which is why I want to outfit them with laser weaponry instead of pulses.

**Comment by trifornt-tinfornt** [comment]
They do? I frequently found them not having a lot of supplies for station repair - likely due to backpack restrictions.
Also if they do also have 12 shots and not 10, then the Captain's Laser has a lower cap.

Any way, if it's currently adminbus only then I retract what I've said.

**Comment by Voratius** [comment]
this is good balance comrade calibratov

**Comment by ghost** [comment]
This is reasonable tbh.
Although I've still not personally seen science traitor science use RnD recently.

**Comment by Badmex** [comment]
Sounds neat. Maybe the thing from Kierany should be considered.

**Comment by blobbernaut** [comment]
regular laser gun has 10 shots not 8

**Comment by ghost** [comment]
"This is reasonable tbh.
Although I've still not personally seen science traitor science use RnD recently."
That means a +1

**Comment by dreamcrab** [comment]
yea sure whatever +2621

**Comment by calibraptor** [comment]
About time, merge this so I can continue my work on the ERT regearing

**Comment by Gandalf2k15** [comment]
Merging as head input gained.

**Pull request merged**
