### PR TITLE
Removes anti stuns (and some other things)

### PR DESCRIPTION
**Pull request by ghost**
Chems REMOVED:
	crank
	methamphetamine
	bath_salts
	changelingAdrenaline
	stimulants

Chems MODIFIED:
	nicotine	 Removed stun resist 
	ephedrine	 Removed stun resist, increased stamina reduction 
	morphine	 Removed stun resist 
	unholywater	 Removed stun resist 
	synaptizine	 Removed chance for stun resist 
	
Theatre shield is now a toy roman shield

/obj/item/weapon/reagent_containers/hypospray/medipen/stimpack 
	Removed stimulants, increased omnizine

/obj/item/weapon/reagent_containers/syringe/stimulants
	Removed
	
/datum/design/implant_adrenalin
	Removed

/obj/item/weapon/reagent_containers/hypospray/medipen/stimpack/traitor
	Removed
	
/obj/item/organ/internal/chemgland
	Removed bath_salts, methamphetamine, crank from list
	
/obj/effect/proc_holder/changeling/adrenaline
	Removed

/obj/item/weapon/reagent_containers/food/snacks/burger/meatseek
	Removed crank as a reagent

/mob/living/carbon/human/proc/vampire_accelerated_recovery()
	Removed vampire ability to purge stuns

/obj/item/clothing/suit/armor/abductor/vest/proc/Adrenaline()
	Removed Abductor Agent ability to purge stuns

Uplink:
	Removed stimulant stimpack
	Removed Adrenal Implant

Wew, this is my current local changelog.
Anyway, antistuns ever since their introduction has shifted a lot of the powergaming towards chemistry and such. I've never been fond of stun combat in SS13 but antistuns are fundamentally flawed as they put the power in the hands of those who are willing to do this shit ad nauseam.

Stuns themselves could be reworked to be a bit more fair for everyone, but the stuns countered by antistuns fucks over most players while benefiting few. It's time for them to go.

### CODE REVIEW

**Comment by gumner** [comment]
dont remove meth,meth is fine

**Comment by ghost** [comment]
naw fuck off, they're all shite

**Comment by ghost** [comment]
yes cunt

**Comment by gumner** [comment]
fuck u meth is great

**Comment by KayeArray** [comment]
jesus christ now everything in the game is gonna die to one taser shot

**Comment by myontasm** [comment]
the war on drugs claim another

**Comment by gumner** [comment]
flashbang nukeops

**Comment by ghost** [comment]
Okay, I think I just need to remove the fake adnerals in space and such and another check to see if all anti stuns are gone.

**Comment by KittyKathy** [comment]
You forgot Synaptizine which has a chance to remove some stuns and Adminordrazine removes all stuns also this is stupid because it is buffing who can land a stun first.

**Comment by Pyko1** [comment]
Just nerf the combos allowing you to go  24/7 with anti stun chems.

Ie. healing chems only work at 100% when resting. And then remove tazers and let us be the disabler master serb.

**Comment by Iamgoofball** [comment]
>removing every single drug

# fuck you I worked hard on those

**Comment by KayeArray** [comment]
poor goofball

**Comment by ghost** [comment]
@KittyKathy thank ya, I'll keep in Adminordrazine though.

Reminder this is how the game USED to play and people had better chances to survive.

**Comment by ghost** [comment]
Holy fuck I invoked the goofball

**Comment by LufgtHuron** [comment]
is this a joke? 

if you're seriously going to remove all antistuns then just give some chem the speed boost. 

and on another note, this could possibly make the game unfun for anyone being a traitor. while yes, stim chems are overpowered removing stuff like adrenals (which have only three uses) will make waaaaay too many traitor rounds end waaaaaaay too quickly. 90% of people aren't robust as traitors anyway and die within minutes. they need adrenals to survive for at least a while.

**Comment by KittyKathy** [comment]
I was never around for per-rebase so i don't know about that. Just telling you in advance that when wizards summon events and it puts Adminordrazine in everyone it can be extracted and duplicated to fill your whole body with the chemical.

**Comment by ghost** [comment]
They should git gud because this is how it used to work and people did fine.
It ain't my job to coddle traitor tots. Get that adrenaline pumping knowing that any stun will be your last. Totally gets your heart racing.

**Comment by Pyko1** [comment]
also we need meth, but it needs to be something cooked at maint with explosions, welderfuel extremely timed chem heating with lighters and burnt dreams, paint thinner and tears of chaplain.

**Comment by Pyko1** [comment]
Anyways ultimately these things should be separated to different PR's really.

**Comment by trifornt-tinfornt** [comment]
naw fuck off they're all shit
adrenals implants are the only things that should stay because of the stun meta, which will be enhanced even more with this, they're only okay with the nerfs
but I wouldn't miss them if they got removed.

**Comment by ghost** [comment]
I think making e-shields more affordable will be enough to make nuke ops not totally get fucked over by it.
I miss e-shield e-sword nuke ops murdering everything that moved.

**Comment by Swagile** [comment]
making it so some faggot who spends 10 mins in chem using the same autismo act of mixing the same broken chems that allows him to dunk everyone was a bad meta

going back to the roots is a better idea, i support this change

and yeah, e-shield becoming lowered in price would be a big win for nuke ops if this goes through. eshields even block some ballistic projectiles so they aren't completely helpless and if they buy elite hardsuits they are almost unstoppable

**Comment by Iamgoofball** [comment]
>Reminder this is how the game USED to play and people had better chances to survive.
>going back to the roots is a better idea, i support this change

i see the "back in 2012 the game was good" crowd is swarming

don't listen to these autists

**Comment by Pyko1** [comment]
shit or not.
Should be split to different PR's.

IE.
Antistun Chem Removal
Theater Roman Shield Nerf
Uplink antistun removal

**Comment by Pyko1** [comment]
Also Even if the roman shield is a toy it should have some minimal brute block chance, because even a plastic shield is pretty decent against a knife or fist.

**Comment by ghost** [comment]
Roman shield thing was an oversight from crystal code that has been in for ages.

**Comment by ghost** [comment]
If you're not larping in inferior gear then you're doing it wrong.

**Comment by KittyKathy** [comment]
Why don't you just make the toy roman shield like block 1 melee hit or something then break like tray shields do?

**Comment by Pyko1** [comment]
0 protection against anything, from a vender that is behind limited access that has a stock of 1 and costing a coin, and it takes 1 hand to use, seems a bit excessive even if it does not have slowdown.

**Comment by ghost** [comment]
Yes, it's a costume thing?

**Comment by trifornt-tinfornt** [comment]
I agree with Pyko, this should be split up.
Removal of Chem Antistuns
Removal of Traitor Antistuns
Removal of Roman Shield (which is already up).
I'm down for all three.

**Comment by ghost** [comment]
I don't understand why everything in SS13 has to have practical purpose?
The chicken suit is just funny, it offers nothing besides that and it's fine.

**Comment by Pyko1** [comment]
yes but the roman shield is limited by access, amount and a coin. Making it a lot harder to get than yellow gloves for example.

**Comment by Pyko1** [comment]
it should be worse than riot shield, but it should at least have some use as non-sec shield.

**Comment by Swagile** [comment]
goof, please explain to us how the few who cooking anti stun chems for 10 mins in chem should be better than the people who know how to dodge, bait people, hide in lockers, use cover, and gather teammates?

or do you have no real argument to why anti stuns should be a thing

**Comment by KittyKathy** [comment]
For realism it should at least break when hit or used to attempt to block a hit, should not be hard right?

**Comment by ghost** [comment]
But then that makes it a non-functional costume piece if you're meant to use it as a thing?

Why can't you just use trayshields if you want something that works?

**Comment by ghost** [comment]
I mean it's just for costume purposes, it'd be pretty peeve-worthy to have some roman thing going on and then have it punched to pieces the moment you get out of the theater

**Comment by KittyKathy** [comment]
Oh yeah Dude is right I forgot people attacked you for no reason on this server.

**Comment by KittyKathy** [comment]
And here is the vampires anti-stun ability Accelerated Recovery.
https://github.com/HippieStationCode/HippieStation13/blob/master/code/game/gamemodes/vampire/vampire.dm#L355
And the part where it actually removes stuns.
https://github.com/HippieStationCode/HippieStation13/blob/master/code/modules/mob/living/carbon/human/life.dm#L405

**Comment by KittyKathy** [comment]
I have a question are you just removing anti-stuns or also things that boost speed above normal levels?

**Comment by ghost** [comment]
Speedboosts are okay since everyone used to run really fast.

**Comment by ghost** [comment]
Also hyperzine was easy as fuck to make and was pretty effective

**Comment by Hackole** [comment]
Thank jesus +1 begone foul demon

**Comment by blobbernaut** [comment]
Fucking no lmao

**Comment by blobbernaut** [comment]
Dnm

**Comment by Pyko1** [comment]
Anyways Hackole is +1 and baws cant vote since he made it, so *I wonder whom we are waiting for.

Even tho my opinion is still to split this to 3 PR's and have a proper discussion, instead of ramming multiple popular nerf things around the board in to 1 PR.

I do agree on nerfing all 3 tho, not just the scale and it would be better to separate em.

**Comment by TheOneAndOnlyCreeperJoe** [comment]
GMs or the newly appointed Headmin chosen by the two headmins in favor of this PR :mememan2:

**Comment by blobbernaut** [comment]
Removing adrenals is 0/10 fuck that noise

Remove tasers

**Comment by blobbernaut** [comment]
At least remove tasers

**Comment by gumner** [comment]
okay this looks good 
i support this
fuck antistuns 

-anderbergst

is this a joke or something

**Comment by Anderbergst** [comment]
just because i use it doesnt mean i like it lol

i just abuse whatever is good. If this happens, then find something else to abuse.

**Comment by gumner** [comment]
what,is this a massive joke? mcbaw wants to remove anti stuns and ander supports it? where's the camera?

**Comment by ghost** [comment]
https://www.youtube.com/watch?v=_V2sBURgUBI

**Comment by trifornt-tinfornt** [comment]
"At least remove tasers"
Stuns are actually way too engrained in SS13 to just be removed.
Antistuns are a very hard counter to something which has unfortunately been made 90% of the combat system thanks to /tg/'s god awful balance decisions (seriously who thought making bombs explode in a spiral was a good idea sure it gets rid of lag but come the fuck on people can outrun fucking gigantic bombs). That should be enough to say "they need removal."
Powergamers today don't even put up a fight any more because of them. They used to actually require being robust (besides the reactive teleport armor) to get you anywhere, but with antistuns they just say "oh well it doesn't matter as long as my antistuns are around!"
If you have the counter to them, syringe guns, then congratulations you just got fed a million weapons and all-access from some idiot who is trying to random search people in maint. However, if they're a traitor then ensuring that this never happens is as easy as buying a hardsuit or shutting off gravity. And if you don't have a syringe gun then good luck trying to take these guys down, because you need to stun someone who has all of this gear twice while they only need to stun you once.
Bullets and lethals would help at times but in tight corridors like in maint then you'd get stunned before you got a third shot in, and with armor it'd take a bit more than two shots even with a .357.

It's bad for combat as it's literally a hard counter to 90% of what combat is now.
It's bad for powergame/validhunting because it encourages this "safenet" mentality and if you know a way around the safenet then the powergamers feed traitors a bunch of weapons, and they will then go on a massive, and hilariously easy, murderous rampage that kills the entire crew.
It's bad for chems as they overshadow any other creative chemistry use that you could use to heal yourself, and bring out the stun chems even more.

They're just bad. Remove.

As a sidenote, this PR might actually make the ebow worth 12 TC again. I can guarantee that powergamers are gonna go back to shields as the big safenet, and the ebow penetrates shields. It'd sure be funny seeing what this does.

**Comment by myontasm** [comment]
god stop your bitching and go play chess

**Comment by trifornt-tinfornt** [comment]
you can't tell us what to do weeb
you have been dethroned of your power
we are taking over
remove antistuns

**Comment by KittyKathy** [comment]
Here is the new meta after this is merged voice activated smoke grenades that stun using the bar chemical neruotoxin you just need to wear internals or have a any purge chemical dental implant

When someone teases you to cuff you and isn't using internals just activate your grenade and dental if you don't have internals on then you win, good game no rematch.

**Comment by Swagile** [comment]
that takes a lot more preparation and can't be spammed as much as anti stuns can, considering you have to make grenades step by step, and anyone worth their salt always wears their internal mask 24/7

**Comment by trifornt-tinfornt** [comment]
plus this is already a way to counter antistun users right now.
That's not really a new meta.

**Comment by myontasm** [comment]
trifornt i dont thin kyou understand im for the removal of antistuns

**Comment by oprayx77** [comment]
im for this 100%

**Comment by KayeArray** [comment]
just overdose people on 200u of sugar.

where is your god now

**Comment by KittyKathy** [comment]
That is after we don't have anti stuns anymore how are you going to stop neurotoxin without purge chemicals or anti stuns also you can use chemicals that touch based like Synthflesh it does stamina damage based on the amount * 1.5.

**Comment by ghost** [comment]
Purge chemicals still exist?

**Comment by KittyKathy** [comment]
When i say purge chemicals i mean any chemical that removes other chemicals like Charcoal, Pentetic Acid and Calomel.

**Comment by ghost** [comment]
THEY STILL EXIST!

**Comment by KayeArray** [comment]
ok...

**Comment by Kierany9** [comment]
>removing bath salts

my baby did nothing wrong

**Comment by KittyKathy** [comment]
No one used bath salts at all except me that one time I got a organ that made it for me. Then I removed the organ because I don't like hallucinating.

**Comment by Kierany9** [comment]
it still did nothing wrong

**Comment by KayeArray** [comment]
i've been using bath salts recently, they're pretty memey but don't need any nerfs

**Comment by KittyKathy** [comment]
Oh guys there is still one thing that stops stuns HULK SMASH is the madman going to go there and remove that too?

**Comment by KayeArray** [comment]
pls no hulk is fine leave it alone

**Comment by KayeArray** [comment]
yeah i think hallucinations have a crash glitch

**Comment by gumner** [comment]
once a ling stung me with hallucination sting and i lagged to death,2fps and game crashed

**Comment by blobbernaut** [comment]
But your removing the fucking traitor anti stuns too which is not ok

**Comment by KittyKathy** [comment]
That means when you get caught as a traitor now during random searches you have to use something called a freedom implant or if they know you are a traitor and is killing you the next step in your master plan is to blow up and kill everyone around you.

**Comment by trifornt-tinfornt** [comment]
Yeah, Freedom Implants are still a thing.

**Comment by Kierany9** [comment]
Real talk, this is probably the best option. Shit's fucked and I doubt anybody can properly balance it without making everything a convoluted mess(or moreso than i left it when I last touched antistuns). +1 simply because everything else other than the nuclear option has been tried.

Bath Salts still did nothing wrong though.

**Comment by GuyonBroadway** [comment]
Remove freedom implants from R&D, or at least make them illegal tech 6

**Comment by KayeArray** [comment]
remove it and then begin work on a new meta

**Comment by Swagile** [comment]
fuck off with nerfing science, its already fucked because when you get to the good stuff, its already 20 mins into the round / everything is dead / your murderboned by some random jack off

at least 4 consistent gamemodes negate your will to research because it ends the round so fast / makes your RnD useless because people can use station tools to do what you can do with your toys (cult, rev, gang, nuke ops)

just stop

**Comment by KayeArray** [comment]
@Swagile agreed RnD is fine

**Comment by blobbernaut** [comment]
Traitors should *gasp* be harder to kill than normies!

**Comment by Anderbergst** [comment]
just cut one of your arm off

**Comment by KayeArray** [comment]
cuffs aren't really the problem since stun times are so long you can easily beat the victim to death

**Comment by Spacedong** [comment]
yeah sure

**Comment by ArcLumin** [comment]
I'm fine with removing anti-stuns if we remove all stuns and just do stamina damage

**Comment by Nebyab** [comment]
Anti-stuns are bad.
They've always been bad.

Stuns are good. Even if you don't like them, you need to accept that they're a fundamental part of the game. They're better if we don't have dumb shit like anti-stuns, regardless of your stance on stuns, you need to see that.

Its a rare day when me and trifornt agree totally on a stun balance issue.

**Comment by yobob591** [comment]
stuns should still be nerfed, stun should not have to equal death

**Comment by yobob591** [comment]
Not saying antistuns arent cancer, they are

**Comment by Spacedong** [comment]
>antistuns are literally the counter to 90% of combat
>powergamers can't rely on crutches anymore or just get stunned and get back up and brush everything off
>autist chemists can't be invincible to security anymore

do it, best update in years

**Comment by Swagile** [comment]
GM +1 from me

**Comment by SplergeBucket** [comment]
why removal the adrenaline implant
revert it to one get out of jail free card like it was before

**Comment by Swagile** [comment]
yeah that sounds like a better idea, loop

its 3  right now which is kinda shitty since its anti stun, 1-2 min speed boost, AND heals

so putting it down to 1 is good

**Comment by KayeArray** [comment]
just change the adrenals to how they used to be, multiple chances to instantly get up from a stun but no stimulants or other lasting effect bs.

**Comment by Sarcalogo** [comment]
Not much to say that hasn't been said, I guess I'll say it anyway, nobody will read it but I enjoy writing. I will try to make things as simple as possible.

In a universe where only stuns exist, anyone has the capacity to beat anyone. Stuns are readily available to the entire crew in various forms. Some jobs like security have access to more stuns and easier stuns, but everyone has access. In a universe where anti-stuns exist, only those who have anti stuns coupled with lethal weaponry can beat those using anti-stuns. The barrier of entry for obtaining an anti-stun is much higher than it is for obtaining a stun. Anti-stuns can be made using Chemistry (this requires specialized knowledge of ever changing game mechanics) or obtained as an antagonist. Anti-stuns are more time consuming to create and utilize than stuns, and as a result fewer people use them. This changes the dynamics of combat. Most people who use anti-stuns are unbeatable by the average crew member. Because the person cannot be stunned, they have to be damaged. It is much harder to kill someone than it is to stun them, especially because in most cases people using anti-stuns also use armor and high damage weapons. Most crew members don't have access to the types of weapons necessary to combat it. This creates the Super Security and uncreative killing spree traitor phenomena.

**Comment by ghost** [comment]
I'd prefer removing all anti stuns and then readding ones that people truly deem essential. It's the reason why I have commented out code rather than delete it.

**Comment by Kierany9** [comment]
>readding ones that people truly deem essential
>people truly deem essential
>readding
>essential

># bath salts

**Comment by KayeArray** [comment]
add baths to the game so you can use real bath salts to be squeaky clean

**Comment by blobbernaut** [comment]
One damn charge? For 8 tc?
You're already removing the lingering stimulant, it's just a 'remove the
current stun'. That's already a gigantic nerf. Adrenal implants aren't
actually overpowered anyway. They're essential, because "one click you're
dead" is, and always has been, shitty as hell.

What this really is, is somebody who thinks a fucking taser should kill
God. It makes no sense. You're removing a MASSIVE part of antag strength
without giving them anything back.

I think most of this PR will make the game worse.

**Comment by blobbernaut** [comment]
-1

**Comment by Kierany9** [comment]
@blobbernaut 

http://wiki.hippiestation.com/index.php?title=Syndicate_Items#Freedom_Implant

**Comment by blobbernaut** [comment]
That's never going to get used, what are you on? Who the fuck is going to cuff a guy with a gun or a nuke op?

**Comment by ghost** [comment]
Then buy an e-shield or dodge taser shots.

**Comment by trifornt-tinfornt** [comment]
E-Shields are godsends and completely shut down sec's ability to hurt you outside of flashbangs, and even those have a counter when playing as an op (go into travel mode you dip).
If you let sec get close to you when you're an op using an eshield then there's a bigger problem than the fact that you're about to get stunbaton'd and fucked.
or you can just git gud and shoot them before they can shoot you

**Comment by blobbernaut** [comment]
That's not a solution

Adrenals have existed for years and have never been a problem. Why remove them now?

**Comment by trifornt-tinfornt** [comment]
They have always been a problem, it's just they aren't exactly a very big problem. I don't entirely agree with adrenals being removed, but I'm still down for it if it means we're getting rid of the autistic chemistry antistuns as well.
Before Kierany stepped in and actually make adrenals a bit less ridiculous, using the adrenals implant guaranteed a win. Nobody would be able to stun you as you ran around at the speed of light and any attempts at stunning you, no matter what, just made you get up immediately. On top of super speed and lasting for 2 minutes.
Now they function a bit more rationally, they aren't a literal "lol I win" button. While you could always use lethals to take out adrenals users, have fun fighting against one that doesn't have a stun themselves.

Yes, traitors should be harder to kill than normal players. Freedom Implant, git gud. You get a ton of powerful gear. As an op you should not be having trouble considering you have enough firepower to kill 15 crewmembers in 15 seconds, and the eshield. If you're too concerned about getting stunned, bring a buddy with you and actually think out a plan instead of going full rush op.

**Comment by Anderbergst** [comment]
I abused anti stuns so much because I didn't want to lose to someone who also has anti stuns but now that all antistuns are removed, I don't have to worry about somebody having antistuns. 

This makes the game more fun and makes it more skill based. Merge this now!!!

**Comment by SpankMasterson** [comment]
I'll +1 this. The only one that should remain is maybe adrenal implants that cost TC.

**Comment by Swagile** [comment]
solve the conflicts and you get my gm + 1 mcbawger ;)

**Comment by ghost** [comment]
Aight, I still haven't added a changelog nor removed the fake adnreals from the gamma ship. I'll do that too.

**Comment by ghost** [comment]
12 travis errors over a changelog. God have mercy.
Anyway, changelog added finally after all that. As well as removing it from the gamma research vessel.

**Comment by GuyonBroadway** [comment]
Why the Gamma Derelict? What was wrong with the Derelict as whole that couldn't be fixed by removing a few items?

**Comment by ghost** [comment]
I removed the fake adrenals from the gamma derelict. That's all.

**Comment by GuyonBroadway** [comment]
Oh, I see, I misread it as _" As well as removing  the gamma research vessel."_

**Comment by Swagile** [comment]
yeah you get my GM + 1 then, mcbawger

conflicts are solved and all

**Comment by ghost** [comment]
I've tested to make sure things aren't in the uplink, the changeling power is gone,that abductors don't have the proc and that vampires don't have the verb.

**Comment by blobbernaut** [comment]
abductor power needs to stay and so do adrenals

**Comment by Swagile** [comment]
traitors maybe

but abductors can teleport out of any situation instantly if their scientist is any good and marks the ayy lmao before hand

so its a get out of jail free card

they don't need adrenalines on TOP of that

**Comment by KayeArray** [comment]
I HAVE IDEA:

When you get stunned you get asked a series of maths questions, the amount depending on the length of the stun. You can either ignore them and sit out the stun, answer them correctly which removes the stun or answer incorrectly which increases the length of the stun.

I'm a fucking genius right?

**Comment by yobob591** [comment]
merge my friendos

**Comment by Sarcalogo** [comment]
This Github is slow as shit and everyone who maintains it is a faggot.

**Comment by asskek** [comment]
FUCK THIS BRING BACK TREKCHEM

**Comment by Swagile** [comment]
trekchem was the shit

i wouldn't mind reverting to it

till then we have this

**Comment by Nebyab** [comment]
bring back trekchem

**Comment by ArcLumin** [comment]
i protest the removal of fake adrenals

**Comment by ghost** [comment]
It only just pushed my commits. Wew.

**Comment by ArcLumin** [comment]
"minorly" spacedong would have a conniption fit. But hey, code's good. Since this has head approval, merging.

**Pull request merged**
