### PR TITLE
Makes Prototype Honk Shoes Noslip

### PR DESCRIPTION
**Pull request by ArcLumin**
Makes Prototype Honk Shoes Noslip, but if they walk over the peels, it'll still delete them.

Some people just want to watch the world burn

Makes the slowdown shoes_slowdown

### CODE REVIEW

**Comment by ghost** [comment]
For what purpose. Slipping on your own peels is funny.

**Comment by ArcLumin** [comment]
To bring hell to the station

**Comment by LilKek450** [comment]
DELET DIS

**Comment by trifornt-tinfornt** [comment]
You mean the prototype honk shoes that spam bananas everywhere and are incomprehensibly annoying?
Hell no.

**Comment by ArcLumin** [comment]
I want them to be more annoying

**Comment by trifornt-tinfornt** [comment]
For what purpose? They're already extremely annoying as you can just walk around to spam banana peels everywhere around you. It's not like being able to slip on your own peels is a bad thing considering you can make the Starboard hallway take an hour to go through because you either keep slipping or constantly need to pick up bananas and throw them somewhere else.

**Comment by ArcLumin** [comment]
Because they need to be maximum annoying

also, they're fucked by magboots, or dragging pun pun over them before moving

**Comment by trifornt-tinfornt** [comment]
Why should the be maximum annoying? You haven't elaborated on that.
Also them being able to be fucked by a limited item or by dragging a monkey over the bananas isn't a bad thing.

**Comment by ArcLumin** [comment]
Well, that's the only thing they're around for, annoyance. It's the clown's ultimate tool, that rarely gets used because they'd rather use the bananium for making a honk mech. Plus, they tend to burn up lots of bananium

**Comment by trifornt-tinfornt** [comment]
If you want something that's no-slip and can spam bananas everywhere that don't vanish when people slip on them, then just build a H.O.N.K. instead of using the shoes. There's a reason as to why they'd prefer using the bananium for a honk mech when they want to be annoying.
They're fine as is, besides the honkerblast being ridiculous.

**Comment by ArcLumin** [comment]
Exactly, this is a small buff to the shoes to make them more viable

**Comment by trifornt-tinfornt** [comment]
But why, though?

**Comment by ArcLumin** [comment]
so that they're used more

**Comment by Kokojos** [comment]
No, the Honkmother wishes for everyone to slip.

**Comment by GenericGoose** [comment]
IT MUST BE DONE
SUBMIT TO THE HONK

**Comment by SplergeBucket** [comment]
if you slip on your own bananas you are gay and a scrub no for code, no nelly no

**Comment by ArcLumin** [comment]
Was 99% memecode anyways, didn't expect it to be merged

**Pull request closed without merging**
