### PR TITLE
Gravity Generator moved to engineering, Vault and Security Outpost moved back to below the AI Upload

### PR DESCRIPTION
**Pull request by Chronitonity**
Pictures in a second.

This also removes unneeded overhead from datum pooling because i forgot to add that a while ago.

### CODE REVIEW

**Comment by Chronitonity** [comment]
I am 90% sure travis is failing because no one updated him with Byond 509.

Anyway pictures.

Place holder area for where the vault was: http://puu.sh/kAvcQ/786f77c41d.png

Vault+Checkpoint: http://puu.sh/kAvl6/e124c254ab.png

Grav Generator room: http://puu.sh/kAvmC/e5059306f2.png 

Grav generator is under the Power Storage Unit in engineering.

**Comment by Chronitonity** [comment]
I also forgot to mention this puts Rwalls around chemistry

**Comment by TrashFiend** [comment]
Add more windows to the south side of the library or riot

The head mapper at /tg/ removed them from my original design because the library "should be a place where people can talk without the halls hearing." Considering that the back area can't be seen from the halls and they half-assed windows in there, there isn't much reason to not give it a full thing if windows.

I could make an issue or something if you need that

**Comment by Chronitonity** [comment]
@dragonrobot You mean making this wall all glass? http://puu.sh/kABAu/43d98d8e5e.png

**Comment by TrashFiend** [comment]
@chronitonity Yeah, making it look like the chapel.

**Comment by Chronitonity** [comment]
I'll save that for a different PR than this

**Comment by Chronitonity** [comment]
Fixes the vent in escape now

**Pull request merged**
