### PR TITLE
Adds another Gibbering Meme

### PR DESCRIPTION
**Pull request by AliiTea**
Adds the "khajiit has wares" thing from skyrim with ss13 twist

"Tajaran has warrrres, if you have coin"

### CODE REVIEW

**Comment by danhibiki** [comment]
No

**Comment by AliiTea** [comment]
no  <  memes
???

**Comment by Weisyl** [comment]
Fuck off Nex nobody likes you and to call you an official coder would make it the next SS13 meme.

:mememan:

**Comment by danhibiki** [comment]
its just not a funny gibber, its just something khajit say in skyrim

**Comment by AliiTea** [comment]
No need to go that far Derp, a simple fuck off would do..

**Comment by AliiTea** [comment]
No memes allowed :'(

**Comment by Weisyl** [comment]
Okay well fuck off

**Pull request closed without merging**
