### PR TITLE
/tg/ Ports: Massive NanoUI Rewrite + Holodeck Rework

### PR DESCRIPTION
**Pull request by Weisyl**
Ports some major NanoUI rework PRs from /tg/. So of course, all credit goes to /tg/.
PR's used:

Update NanoUI:
https://github.com/tgstation/-tg-station/pull/13195

Fix up NanoUI states; add snowflake for Drones:
https://github.com/tgstation/-tg-station/pull/13290

Fix Chemistry NanoUIs
https://github.com/tgstation/-tg-station/pull/13290

### CODE REVIEW

**Comment by Chronitonity** [comment]
Should be merged ASAP. I can't touch shit without causing conflicts here

**Comment by neersighted** [comment]
I don't know your codebase, but I'm working on the new NanoUI. If you need any help, I'm neersighted on Rizon.

**Comment by TDcoolguy300** [comment]
We've had issues with the holodeck during this port, for whatever reason it was multiplying anything in it everytime i changed, this was reverted until we can figure this out

**Comment by neersighted** [comment]
Holocode is magic to me. If you need help with NanoUI, let me know. I'm still working on it, big changes to the frontend are coming. In addition, I'm porting more UIs to NanoUI.

**Pull request merged**
