### PR TITLE
Ports RR's Sniper Rifles

### PR DESCRIPTION
**Pull request by Chronitonity**
Adds sniper rifles from TG to the Nuke Ops arsenal.

16 TC, With ammo being 4-5 TC depending on what you get

Screen shakes after a shot, and it takes 4 seconds fire another shot

Can zoom 7 tiles ahead (You can't see anything behind you)

Normal bullets do 70 damage and can break objects.

Soporific puts the target to sleep immediately

Haemorrhage drains 100 blood, does 15 damage 

Penetration shots do 60 damage but shoot through walls/mobs

You can silence/unsilence the gun.

Coders, especially @DerptheStewpidGoat and @Crystalwarrior you can now make guns zoomable 

As RR said:
Adds zooming ability to all guns, controlled by the zoomable var
Zooming can be added to a gun later on by calling build_zooming() on it

### CODE REVIEW

**Comment by danhibiki** [comment]
> Haemorrhage drains 100 blood, does 15 damage

This seems like a lot of blood along side the brute damage

**Comment by Weisyl** [comment]
@chronitonity I can grab you some specific mag load sounds for this and a new gunshot effect. And if you could make the desc. less memey I'd love you.
Also, does this fit on your back?

**Comment by Chronitonity** [comment]
Derp yeah on all fronts, send me the sounds and a description you want, and it can be carried on the back

**Comment by SplergeBucket** [comment]
sure

**Pull request merged**
