### PR TITLE
Noose People

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by TDcoolguy300** [comment]
Horrifying, but in the future i recommend making branches so you could make more than one PR at a time

**Comment by ghost** [comment]
I'll try that next time, as this is my first PR.

**Comment by Nokington** [comment]
No. :-1:

**Comment by ghost** [comment]
The code is already tested, by the way, and should run perfectly(in terms of getting things done) unless I screwed up something while dealing with github.

**Comment by TDcoolguy300** [comment]
In the terms of coding, it's fine. The Code-review stuff is just standard procedure

**Comment by ghost** [comment]
Alright, good to know.

**Comment by TrashFiend** [comment]
what

**Comment by Nebyab** [comment]
why

**Comment by ghost** [comment]
I think walking and talking nooses fit with the general lynching atmosphere of Hippie

Since they are clearly much more realistic than mothmen and skeletons, it would also add a new level of depth to the RP

**Comment by Nokington** [comment]
Again No.

**Comment by ghost** [comment]
Elaborate

**Comment by Nokington** [comment]
Probably the dumbest thing I have ever seen. We do not need these at all.

**Comment by ghost** [comment]
Well, you could say the same thing about mothmen.

**Comment by danhibiki** [comment]
Low effort, bad icon.. Nah.

**Comment by blobbernaut** [comment]
@Cherkir mothmen have a really well done icon 

this is ms paint 5 minutes icon

**Comment by blobbernaut** [comment]
you know what make this the model when cable coils get hit with a staff of animation

**Comment by ghost** [comment]
The icon could be improved if someone else did the sprites, but I'm not sure what you're looking for in a race of sentient nooses

It would look weird if they had a solid body like other races, unless it was a bunch of tangled up cable coils

Anyway, I think this would be a nice change from the plethora of snowflake races that currently inhabit Hippie, and would add a nice touch to the comedic environment

**Comment by danhibiki** [comment]
If the icon was better, I might consider it. But as for now, its clearly a PR meant to poke at moths. :-1:

**Comment by TDcoolguy300** [comment]
At this point it's been denied by two Headmins, sorry man

**Pull request closed without merging**
