### PR TITLE
Removes the ability to stack inflatables on top of eachother

### PR DESCRIPTION
**Pull request by varyy**

### CODE REVIEW

**Comment by KayeArray** [comment]
nah this is a meme

**Comment by Spacedong** [comment]
this is good, fuck off

**Comment by JohnGinnane** [comment]
Code looks good. Need head input though

**Comment by JohnGinnane** [comment]
Actually do we know if locate() also checks subtypes?

**Comment by TDcoolguy300** [comment]
It should check for subtypes, as it worked in my applications

**Comment by ghost** [comment]
Being able to put many turfs in 1 location is broken. This is a bugfix rather than a feature PR.

HOWEVER
You're making changes on your fucking master. Please do the whole make branches and making PRs from branches in the future please!

**Comment by ghost** [comment]
Wait they're not turfs but structures but yeah.
This is a bugfix and doesn't require headmin approval.

**Pull request merged**
