### PR TITLE
Adds tator pyrotechnic kit and foof

### PR DESCRIPTION
**Pull request by KayeArray**
Well shit looks like I used out of date(?) files somehow since it wants to merge old changes. I hope this won't be a problem, just ignore the cryogenic fluid and bartender shit since that already got merged.

Adds Dixoygen Difluoride (FOOF) as a chemist traitor exclusive. You should be able to get a more precise idea of what it does from the code but it essentially creates small very violent fires that melt the hull and walls of the station, on contact and if ingested it adds tons of firestacks and does a nasty amount of damage, it also decays over time unless in the presence of cryogenic fluid to stabilise.

Adds new 8tc syndicate pyrotechnic kit for tator chemists which contains FOOF and some other dangerous pyrotechnic stuff.

plz review code and stuff

### CODE REVIEW

**Comment by KayeArray** [comment]
uh oh git isn't happy

**Comment by KayeArray** [comment]
It's getting late so I'll fight git tomorrow, but feel free to comment on the more important stuff

**Comment by doobiedoo23** [comment]
Sounds like a shitty OP version of thermite to me

**Comment by ArcLumin** [comment]
So if I buy this pyro pack, the foof will quickly decay into oxygen and fluorine in the bottle, yeah?

**Comment by KayeArray** [comment]
No it comes with some cryogenic fluid in it.

**Comment by ArcLumin** [comment]
Why not put it in a cryostatis beaker then?

**Comment by TDcoolguy300** [comment]
I assume to not give them a Round-start Cyrobeaker to then put in other dangerous and explosive chemicals.

**Comment by KayeArray** [comment]
Pretty much that.

**Comment by KayeArray** [comment]
Going to open up a new pr without merge conflicts

**Pull request closed without merging**
