### PR TITLE
Adding new medicine chem - Antidote

### PR DESCRIPTION
**Pull request by Anderbergst**
This chem will only heal toxin damage.

(Since people were asking for a chem that only heals toxin damage without purging other chems in your body then here you go)

### CODE REVIEW

**Comment by ArcLumin** [comment]
Wow actually not memechem

Having said that, that toxin healing is really high. Maybe tone it down a tad?

Code's good though.

**Comment by Anderbergst** [comment]
ill tone it down no problem but can you tell me by how much?

**Comment by Anderbergst** [comment]
Im toning it down to -2.1 if that's good enough.

**Comment by ArcLumin** [comment]
Likely 1.5~2.0*REM, somewhere around there. For baselines, you shouldn't have a chem that heals your shit faster than cryoxadone, which heals at 3.0

**Comment by blobbernaut** [comment]
He wants this so that he can abuse methamphetamine and get around the toxin damage without having to use doctor's delight and nutriment. 

Close this. This is pure powergame.

**Comment by ArcLumin** [comment]
Protip; if you want to get around the nutriment drain on that, it's stupid simple. Just carry the rainbow crayon on you, which on use injects (past your helm, mask, everything) nutriment directly into your system. Or just play a doctor role, which invalidates the nutriment drain anyways.

**Comment by Anderbergst** [comment]
Im lowering the toxin healing to 1.7 then. Thanks for the feedback.

**Comment by ArcLumin** [comment]
Might as well do it 1.75, for a nice divisible number. But yeah, totally good with this. It's stronger than tricord for healing toxin but not as strong as charcoal, but gives the nice bonus of no chemdrain.

**Comment by Anderbergst** [comment]
Okay I will do that.

**Comment by KayeArray** [comment]
I already see many uses for sick chem powergame. I like this but I'm obviously biased.

**Comment by LufgtHuron** [comment]
I mean I asked for healing toxin damage without purging the chems but that was solely so it would be easier for me to abuse meth/other chems. 

I saw you abuse meth yesterday without a chem like this even and since that moment I can only say that I want to have this in game so I can abuse it but I don't want it in game because it will spawn more shit strats everyone already hates. 

Merging this in would make no fucking sense whatsoever especially since we already had the need to nerf stuff like ephedrine.

**Comment by trifornt-tinfornt** [comment]
Antitoxin and other toxins-healers purge chems for a reason. There are other chems that inflict toxin damage or have benefits that may result in some toxin damage. Antitoxin makes it so that you can't cheese your way out of it, flushing all of those chems out while still healing you. Even then the flushing out chems is actually helpful if you have, say, been shot by a death chem and need to heal yourself.
This just heals you. And it won't flush out the good chems as a compromise. As a result I already know where this will go if it's added. This is, in its entirety, a memechem. And I will guarantee it'd get used for powergaming and validhunting.
No.

**Comment by Spacedong** [comment]
no, kill yourself

**Comment by ghost** [comment]
Charcoal is fine. This is not needed.

**Comment by Iamgoofball** [comment]
remember when you guys had the first incarnation of goofchem meth and it never wore off?

**Comment by KittyKathy** [comment]
Nope to this PR, He just want to make a chemical that he can take with his meth or other drugs to combat the toxins damage from the drugs. 

There is a better way to do this simply make Anti-Toxin that the Med bots use able to be created using the chemical dispenser again. It was changed to make charcoal because here is the comment "There is literally no reason to make this it's just a shitter charcoal reeeeee". 
https://github.com/HippieStationCode/HippieStation13/blob/master/code/modules/reagents/Chemistry-Recipes/Medicine.dm#L256

Anti-Toxin removes all reagents that are considered toxins instead of all reagents like charcoal does and heals toxin damage.  It is useful if you don't want it to remove medicine in your body but want it to remove poisons but in a case where you overdose on a medicine like Tricordrazine it will not purge that chemical only heal the toxins damage which is why you need something like charcoal to remove the overdosed medicine.

**Comment by Anderbergst** [comment]
I guess there was already antitoxin that heals only toxin damage. I didn't notice that. I'll be closing this PR. Thanks for all the feedback.

**Pull request closed without merging**
