### PR TITLE
Disables random generation

### PR DESCRIPTION
**Pull request by TDcoolguy300**
Something appears to be holding up the template controller, i will need to investigate this further later. This is an urgent fix

### CODE REVIEW

**Comment by TDcoolguy300** [comment]
Turns out it's a naming issue, Pyko left spaces in his PR

**Comment by TDcoolguy300** [comment]
Or not, bloody hell.

**Comment by Pyko1** [comment]
Could it be related to these?

https://github.com/HippieStationCode/HippieStation13/issues/1812
https://github.com/HippieStationCode/HippieStation13/issues/1813

Since those things are broken on those pasted maps currently.

**Comment by TDcoolguy300** [comment]
IT needs to be worked on, but i dont have time for it.

**Comment by Nokington** [comment]
:+1:

**Pull request merged**
