### PR TITLE
Fixes heads

### PR DESCRIPTION
**Pull request by Gandalf2k15**
Heads are no longer retarded. They can be pulled and put in bags.
Seriously who thought this was a good idea?
fixes https://github.com/HippieStationCode/HippieStation13/issues/2543

### CODE REVIEW

**Comment by JohnGinnane** [comment]
Code looks fine, I wonder if anything relied on the heads being like this. Did you test messing around dismembered heads

**Comment by Gandalf2k15** [comment]
Yep

**Comment by JohnGinnane** [comment]
Do we require head input on this?

**Comment by Gandalf2k15** [comment]
Good question.

**Comment by ghost** [comment]
I'd rather have heads still be bulky and not to be able to remove their brain by hitting it.
That alone is really garbage.

**Comment by Gandalf2k15** [comment]
but it makes no sense

**Comment by ghost** [comment]
So?
Decapping people and hiding their heads pretty much is gibbing them. There should be at least some sort of difficulty associated with it. Decapping and cutting the brain out is easy as fuck and does the same thing. It bypasses an intended gameplay balance choice because memes. Making it so the bypass is the norm doesn't solve the problem of decapping being garbage for the victim.

**Comment by Gandalf2k15** [comment]
its easier to hide a body than it is a head cause you can drag them. At least make it dragable/throwable

**Comment by ghost** [comment]
You can't fit a corpse in a backpack is the problem as I see it, and debraining a corpse takes tools and/or time. Also heads are super easy to hide.

Personally I'd make them not retarded in how they move, but keep them too big for backpacks.

**Comment by ghost** [comment]
Unless you full strip then no due to SUIT SENSORS. Dragging bodies usually leaves a blood trail too. Killing someone, decapping them and taking their brain ensures they will never ever be cloned. Debraining from decapping takes no time at all.

**Comment by GenericGoose** [comment]
implying people follow blood trails
and chances are, if you are able to decap someone you won't be caring about someone trying to clone whoever you killed (because in my eksperience its just unstoppable murderbone from which there is no possible recovery)

**Comment by Nebyab** [comment]
make heads bulky

**Comment by Kokojos** [comment]
Bulky heads are stupid.
+1/3 to this

**Comment by Carbonhell** [comment]
Heads please discuss this
@McBawbaggings 
@Nebyab 
@teamstabwhateveryouare

**Comment by Spacedong** [comment]
@johnginnane

**Comment by JohnGinnane** [comment]
what

**Comment by McHatters** [comment]
Heads should be able to fit in bags if brains can.

**Comment by dreamcrab** [comment]
i like heads being something bulky, make it so you have to debrain them to be more stealthy

**Comment by Carbonhell** [comment]
needs news in 2 days or pr will be closed

**Comment by JohnGinnane** [comment]
Heads can you give your input please

**Comment by ghost** [comment]
To be fair, I'd rather have heads remain bulky and no longer have the mechanic of slicing a head open to extract brains.

Stealing heads is a sure fire way to make a body uncloneable and it's not that hard to do. Debraining takes a tad bit longer but the same applies.

**Comment by blobbernaut** [comment]
Tbh, I'd rather bodies be cloneable without the head especially since heads are small, hard to find, suffer occasional sprite issues making them invisible, and also really easy to remove, and can't have suit sensors.

It's almost as good as gibbing and I don't like it, cloning should first look for an attached head+brain, then look for a heart if there's no brain.

**Comment by blobbernaut** [comment]
Also I'd like heads be able to be put in MMI's.

**Comment by JohnGinnane** [comment]
I agree, you should be able to clone using decapitated body or head (or both), and then we could treat heads like we do brains

**Pull request closed without merging**
