### PR TITLE
Nexendias madness must end

### PR DESCRIPTION
**Pull request by lcass**
Reverts HippieStationCode/HippieStation13#270
FOR DILDOS EVERYWHERE AND FOR EMAGS!

### CODE REVIEW

**Comment by nalarmg** [comment]
:thumbsup:

**Comment by Weisyl** [comment]
Ok.

**Comment by Weisyl** [comment]
But you gotta revert dat changelog aswell.

**Comment by AliiTea** [comment]
This was already done..

**Comment by Memendia** [comment]
Already done

**Pull request closed without merging**
