### PR TITLE
Knight Armor

### PR DESCRIPTION
**Pull request by Chronitonity**
An updated version of #1295 for Doobie with updated sprites.

Closes #1295 

In addition adds a crate to Cargo allowing them to buy the Armor, costs a bit more than riot armor crate.

Also merges the riot armor crate with the helmets, whats the point of buying one and not the other.

Sprite credit to Ausops and Dorisdwarfs at TG
deus

### CODE REVIEW

**Comment by danhibiki** [comment]
god damn

**Comment by ghost** [comment]
booc

**Comment by Chronitonity** [comment]
Additionally here's the on mob sprite of all of them 

http://puu.sh/lAZum/0784feb714.png

**Comment by Crystalwarrior** [comment]
those sprites look amazing

**Comment by McHatters** [comment]
good stuff

**Comment by doobiedoo23** [comment]
heck yea

**Comment by danhibiki** [comment]
Fix merge conflicts, then we'll add it

**Comment by Lawligagger** [comment]
This looks pretty god, although the yellow on the helmet could use a little bit more shading.

**Comment by Chronitonity** [comment]
Waiting on the new helmet sprite

**Comment by Chronitonity** [comment]
New sprites are in, removed and added some names to the changelog header aswell

**Pull request merged**
