### PR TITLE
Welding Coffin Fix

### PR DESCRIPTION
**Pull request by AliiTea**
Removes the ability to weld a coffin shut.
Fixes https://github.com/HippieStationCode/HippieStation13/issues/1110

### CODE REVIEW

**Comment by Crystalwarrior** [comment]
no no no noNONONONO.
MEMENDIA JUST ADJUST THE OVERLAY.
Welding coffins shut is something I will NOT let be removed.

**Comment by AliiTea** [comment]
Pyko1 commented 2 days ago
coffins are wooden, maybe make em burn if you weld em as a lazy fix.

Reee fuck off

**Comment by Chronitonity** [comment]
:-1: Lazy fix, just fix coffin overlay

**Comment by AliiTea** [comment]
Coffins shouldn't be weldable they are WOODEN D:

**Comment by doobiedoo23** [comment]
you can weld wood you dumb fucker

**Comment by AliiTea** [comment]
It burns it.

**Comment by danhibiki** [comment]
:-1: I was welded into a coffin my first round. I don't want to see it leave.

**Comment by Nebyab** [comment]
what
literally what
Why would we ever remove something that is fundamentally a feature of this game? I love the fact that you can weld coffins. SS13 has never been a game based around strict realism, and to arbitrarily enforce it on a feature which does people no harm is silly.

**Comment by TDcoolguy300** [comment]
Two headmins have denied this, and therefore DNM can go on now

**Pull request closed without merging**
