### PR TITLE
Nerfs clown's pda slip time

### PR DESCRIPTION
**Pull request by rouge**
holy fuck, eight entire seconds of slip time?

inb4 saltlevelstoohighdrinkwateryouafricansaltminer

### CODE REVIEW

**Comment by rouge** [comment]
in less salty news: stun bolts should get changed to do just enough stamina damage to knock you down, so that when you get back up you can't run away at full speed.

**Comment by Carbonhell** [comment]
uh what
pda slip is just fine

**Comment by Kierany9** [comment]
Actually, that isn't eight seconds, it's eight ticks.

**Comment by blobbernaut** [comment]
8 ticks is 16-18 seconds

**Comment by blobbernaut** [comment]
for the uninitiated

**Comment by rouge** [comment]
It still stuns longer than a taser.

and on hippie 1 tick is two, because byond logic.

so @blobbernaut would be correct.

taser is 5 "ticks" and PDA is 8.

**Comment by ghost** [comment]
As a frequent mime who often steals the clown's PDA I can confirm it is a pretty fucking long stun.

**Comment by blobbernaut** [comment]
Make clown stun for rand(0,8) ticks.

**Comment by blobbernaut** [comment]
whatever number you put is wrong do my idea instead.

**Comment by Kierany9** [comment]
More like 13-14 seconds, a single tick is less than 2 seconds

**Comment by blobbernaut** [comment]
i don't care make it have random slip time, I think that'd fix it

**Comment by rouge** [comment]
@Kierany9 I don't care lmao, its just too long of a stun.

I can go count the seconds right now if you really want to argue about this dumb shit.

**Comment by blobbernaut** [comment]
also in the murderbone you were mad about the guy didn't even slip people with the pda I think it was syndie soap or a banana or something

**Comment by Kierany9** [comment]
but its still 13-14 seconds

**Comment by rouge** [comment]
@blobbernaut I personally got slipped by a PDA, im not mad tho as I was being a shitty person anyways.

**Comment by Carbonhell** [comment]
good ol' grudgecode

**Comment by Kierany9** [comment]
wait i just realized no logs denied please move to closed

**Comment by rouge** [comment]
wat

**Comment by Carbonhell** [comment]
the honkmother refuses this pr

**Comment by ghost** [comment]
Clowns cuff themselves so it can't reliably be used for valid hunting clowns? And clown PDAs are very much irreplaceable.

It's honestly fine.
-1.

**Comment by GenericGoose** [comment]
this is heresy
call hippie so he shuts this PR down

**Comment by ghost** [comment]
@McBawbaggings I agree, but the problem is antag clowns, or powergamers who grab the PDA (rare tbh).

**Comment by Nebyab** [comment]
no

**Comment by ghost** [comment]
2 HA disapproval.

**Comment by GenericGoose** [comment]
_HOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOONK_

**Comment by GeneralGoose** [comment]
also p sure 1 tick = 0.6s

**Comment by Kierany9** [comment]
Wrong way around mr goose, 0.6 ticks = 1s

**Comment by rouge** [comment]
gonna redo this PR, you can't stop me >:(

>tfw literally just watched a clown slip the captain and HoS and steal their shit and get away

**Comment by GenericGoose** [comment]
i tend to confuse things but i remember i calculated it
tfw ur too unrobust to not get slipped by a clown so you have to go on git and make a PR

**Comment by ArcLumin** [comment]
The only thing the clown has is slips.

**Comment by ArcLumin** [comment]
also Grudgecode is my heavy metal nerdcore deconstruction of the vaporwave genre and I'll thank you not to use my intellectual property as a tag

**Comment by GenericGoose** [comment]
git gud tag when

**Comment by myontasm** [comment]
the fact that this pr was even open at one point absolutely disgusts me

**Comment by Lawligagger** [comment]
gross pr

**Comment by GenericGoose** [comment]
i knew

**Pull request closed without merging**
