### PR TITLE
Fixes Heparin to actually scale with bleeding

### PR DESCRIPTION
**Pull request by ArcLumin**
Before, heparin would do a flat 1 damage per tick. However, how it was originally was supposed to work was for the brute damage to increase by how much the person bleeds. This should increase it. Lemme know if this amount is too low.

As far as I see it, this is a bugfix/oversight

### CODE REVIEW

**Comment by KayeArray** [comment]
Is this a buff or a nerf?

**Comment by ArcLumin** [comment]
I'd say it's a buff

**Comment by Hackole** [comment]
Was unaware of this being intended to scale with bleeding. Seems like just a bugfix to me in that case, but +1 either way

**Comment by ArcLumin** [comment]
Considering a head considers this a bugfix, as it likely is, this doesn't need head input. Good to merge once we get a code review

**Comment by ghost** [comment]
+1 okay

**Comment by ArcLumin** [comment]
Well now it doesn't even need to be considered a bugfix since it got full head input

Now we just need some fuck to code review it and it's good to merge

**Comment by blobbernaut** [comment]
var/blood_max = 0 //how much are we bleeding

**Comment by ArcLumin** [comment]
Yup

**Comment by blobbernaut** [comment]
so code is fine

**Comment by ArcLumin** [comment]
Aight, mergin

**Comment by blobbernaut** [comment]
l-lol

**Pull request merged**
