### PR TITLE
Maptweaks

### PR DESCRIPTION
**Pull request by Lawligagger**
Changes the following.

Adds Security Lounge: http://puu.sh/j4Ijb/485d9c8621.png

Tweaks to Medbay: http://puu.sh/j5zGD/ef683643c2.png

Pool tile change: http://puu.sh/j4IlW/f3e6d95670.png

RD Office change: http://puu.sh/j4Imx/26ea0b39d4.png

Bar tweak: http://puu.sh/j4Ina/0b6679bdd2.png

EVA and bridge change: http://puu.sh/j5zHy/76323c6f42.png http://puu.sh/j5zHy/76323c6f42.png

Also tweaks the mining asteroid textures: http://puu.sh/j4LUH/0f980e13b1.png

Engineering floor tile changes: http://puu.sh/j5zMj/db8f1cc4f1.png

### CODE REVIEW

**Comment by Nokington** [comment]
Let Kokojo take a look at it before merging.

**Comment by Lawligagger** [comment]
Sure thing.

**Comment by ghost** [comment]
Please run the `mapmerge` tool.

**Comment by Kokojos** [comment]
I left a long list of comments to hippie.

AS for the few changes : Medbay lobby should only use one light : Move it to the location of the light switch. (This maximise effiency)

Might want a window from the desk to the entrance so you can see if the door is lockdowned.

Move the entrance to the medbay storage down a bit and add first aid kits.
The AIR VENT in the medbay storage room is not a good air vent and is pumping terrible pressures.

Im really pushing for this but the CMO'S backroom is useless and compared to other heads, give him a unfair advantage. I really don't like it. Mostly because it has no use.

There's a light switch into the glass in front of the CMO, there's also a light tube, move it one step to the left

The light right under the entrance's desk, on the other side of the wall, left of the beds, can be removed. Mebay currently uses too much power
The lights right next to the entrance desk, to the right near the entrance, at least one of them must be removed.
[12:47:58 PM] Kokojo: You'll also have to edit the medbay APC to reach 5000 maxcharge.
[12:48:14 PM] Kokojo: and perhaps start at more than 10% max charge it's going down too quickly
[12:49:14 PM] Kokojo: Bar, EVA, asteroid and Pool looks okay.
[12:50:42 PM] Kokojo: Im questionning why sec needs another lounge next to the garage but w/e
[12:52:20 PM] Kokojo: That's about it, rest looks fine

Please tell me when this is fixed.

Also, you need to use the mapmerge tool correctly.

**Comment by ghost** [comment]
needs mapmerge.

**Comment by Kokojos** [comment]
Cannot accept in it's current state due to destroyed atmos:
http://postimg.org/image/i1mnmvnkb/

**Comment by Kokojos** [comment]
Closing due to nok making a better pull.

**Pull request closed without merging**
