### PR TITLE
APC Added to Russian Room Issue #2011

### PR DESCRIPTION
**Pull request by Zadeon**
Adds an APC to the Russian room in the derelict so that the vending machines work. For issue #2011

### CODE REVIEW

**Comment by Kokojos** [comment]
:+1: :100: ACTUALLY MAPMERGED CORRECTLY. PROMOTE HE

**Comment by Nebyab** [comment]
someone codecheck so this can be merged

**Comment by Pyko1** [comment]
Well it adds an apc all right, but the apc is on /area/derelict so it will be powering a lot more than just that room.

**Comment by Zadeon** [comment]
Ah I'll give it a new area then.

**Comment by Spacedong** [comment]
make the area named cheeki breeki

**Comment by Kokojos** [comment]
The code's good and all, but I seriously object to such an Area name.

**Comment by Spacedong** [comment]
>cheeki breeki isn't a good name for a russian area


idi nahui, blyad

**Comment by Zadeon** [comment]
I blame kokojo for this commit.

**Pull request merged**
