### PR TITLE
Medical mayhem

### PR DESCRIPTION
**Pull request by lcass**
I thought a new design for medbay might be nice. Take a look , tell me what you think. Enjoy.

P.S Specifically designed to stop crapsistants from breaking into medical , messing with cryo and having people stripped and stolen from. Also makes medical a little bit more fire proof.
Screenshots
http://i.gyazo.com/4cb3b72a1f7d93d751dd6fa72b9a55df.png - central area
http://i.gyazo.com/252d552c7e24a22fc9aa6c926c296a92.png - chemistry 
http://i.gyazo.com/a8d439c9d40d507e0d0b83f21cba868f.png - general storage
http://i.gyazo.com/5c59eac91bd1f81d0ee092b210302ad1.png - new genetics and cloning
http://i.gyazo.com/b4258a56b2896742a91b84ce5a9e272e.png - new smaller morgue , never really used
http://i.gyazo.com/32c0fae0f491a6ff8a2e8e18ceb07f9f.png - sleeper , main treatment and resting area
http://i.gyazo.com/02039ca0dfd292a8d345c77be8a1a8cd.png - surgery 
http://i.gyazo.com/63d9e7cb75287c99a480610cb1ec73b0.png - cryo , with more tubes
http://i.gyazo.com/009de8870255e20b295b3fd8b876a2e5.png - west hallway
http://i.gyazo.com/4d16781ad707142319380bbb40e2e290.png - CMO office

### CODE REVIEW

**Comment by ghost** [comment]
needs screenshots.

**Comment by lcass** [comment]
can do.

**Comment by SplergeBucket** [comment]
Needs a screenshot of the entire thing, will probably be controversial.

**Comment by lcass** [comment]
Axe this , never really worked that well , bit too cosy

**Comment by ghost** [comment]
axed it.

**Comment by lcass** [comment]
NOICE

**Pull request closed without merging**
