### PR TITLE
Alien balancing & spawn update

### PR DESCRIPTION
**Pull request by ghost**
Just fixed the merge conflict. To sum up what this update does:
- Makes aliens spawn within a 5 minute mid-round time period, but 6 times more often in that period. Assuming the average round is 50 minutes, this means they will spawn at an identical rate as in a 50 minute round.
- Makes 1 more starting ayylmao on average
- Makes eggs grow faster
- Nerfs tackling quite a bit and disarming slightly

### CODE REVIEW

**Comment by Nokington** [comment]
No thanks

**Comment by ghost** [comment]
@Nokington what do you have against an occasional ayylmao round that doesn't end within 5 minutes?

Far better gamemode than revs, at least.

**Comment by Nebyab** [comment]
I'd like to briefly point out the fact that changing their spawn rate has literally noting to do with balance. With that said, can you give me odds for how often we can expect to see them show up? I won't mind all that much if it still stays reasonably low.

**Comment by Pyko1** [comment]
13.3 Minutes in to the round sounds awfully early. And 15 as weight sounds awfully high, carps have 15 and that happens pretty much every other round.

**Comment by ghost** [comment]
@Pyko1 I wasn't aware carps were only 15. It seems like they happen far more often than aliens, not just 3x more often(which is apparently how weighting works)

Either way, I believe the spawn chance should be raised to compensate for the fact that aliens are worthless if they spawn after 30 minutes, they just don't have the time needed to build up. Perhaps I could make a variable for that, and make aliens more likely to spawn in early round but never in late round?

**Comment by Pyko1** [comment]
Or make the first alien spawn 1 step away from queen with full plasma, so it can get to nest making as soon as it finds a spot.

**Comment by ghost** [comment]
@Pyko1, yeah, maybe. But I think aliens spawning more often in early round would also be better. They're pointless if they spawn too late.

The average round lasts about 50 minutes, so they could have a 2x chance of spawning within 25 minutes(of roundstart) but no chance of spawning afterwards, as they're pretty much useless after that. Same spawn chances, but much more balanced.

**Comment by Nebyab** [comment]
Again, spawn time has nothing to do with balancing, but I also feel that something as potentially utterly round-altering as aliums is something that we shouldn't have a chance to spawn too early. Would it be possible to increase the odds of them spawning post-mulligan/ pre mulligan? With 30 minutes pre-mulligan and 15 post mulligan? Since that would liven up the round a bit, without running into the chance of them fucking up a round already in progress, since mulligan triggers on antag death.

**Comment by ghost** [comment]
Spawn time has a lot to do with balancing. Aliens are extremely uncommon right now, probably why people think they're a shit antag/they are a shit antag(just a bit). If they actually happened more often people would know what to fix.

I'm not aware of the mulligan variable but I'll check it out. Note that the default spawn time for them is already 20 minutes so I'm not sure if I'd like to raise it

@Pyko1 I'm going to make aliens spawn with more plasma and evolution points, yeah.

**Comment by Nebyab** [comment]
Ah, I thought you said 30 minutes was the default, my mistake. Aliums are a kind of shit antag, but they're also round-altering antags, which is why ideally I'd like to not throw them into rounds which could be in the swing of things.

**Comment by Nokington** [comment]
I am entirely against changing spawn times for aliens because they are boring and lazy fucking admins.

**Comment by ghost** [comment]
@Nokington Nice meme

But seriously aliens should be made playable so people can maybe make good changes to them after realizing that they are not _that_ shitty.

Going to update this PR in a bit, further suggestions are dank

**Comment by Spacedong** [comment]
hey how about we introduce aliens when the malf AI or only antag (wizard) dies within like 10 minutes of roundstart so people have a major antag to fight that isnt revealed immediately, but rather stay in shadows and are already reinforced with a base giving them stuff to fight, however powershitters will just call shuttle whenever possible because muh valids

**Comment by Spacedong** [comment]
also remove the aliens' instant push disarm tackle bullshit because that shits not gucci

**Comment by Pyko1** [comment]
Maybe change how the alien starts in to alien meteor.

Ie.
Have some meteor showers hit the station, and at the end spawn a meteor attached to station somewhere, that holds Alien queen and 2-4 aliens of other roles.

And yes the tackle is just crap.

**Comment by Nokington** [comment]
Once again I'm against changing anything with aliens spawning more. I don't care for the tackle though.

**Comment by AliiTea** [comment]
Just finished an Alien Random event round and holy shit was it ever fun...

Just make it slightly more likely too happen and it's golden.

**Comment by Pyko1** [comment]
Also apparently the tg merges buffed aliens already.
With praetorian aliens.

**Comment by ghost** [comment]
Thanks for the suggestions lads, I haven't been able to get around to doing this due to IRL stuff but I should have it PR'd by tomorrow.

**Comment by ghost** [comment]
Made some changes. Copypasta from the CL since I'm lazy:

Made aliens spawn in numbers of 2-3 instead of 1-2
Made aliens spawn only during the middle of the round but(much)more often during that time period
Made starting aliens spawn with maximum growth
Nerfs alien tackle and disarm chance
Made alien eggs grow a bit faster

This should make ayylmaos much more suitable for the 40-60 minute sort of rounds that Hippie seems to have, while making them a enough of a late-round antag to not fuck with other people's rounds.

**Comment by GunHog** [comment]
Do you hippies have the GIANT Alien and Praetorian from /tg/? I would encourage you trying it out!

**Comment by Carbonhell** [comment]
Yea i ported them a while ago

**Comment by AliiTea** [comment]
Prae is fucking awesome

**Comment by Nebyab** [comment]
I'm willing to give it a go. Worst case scenario its terrible and we've fucked over the codebase

**Comment by Nokington** [comment]
Still don't want this.

**Comment by ghost** [comment]
@Nokington you might as well remove aliens if you don't want to balance them

they're the mark of useless right now due to lazy fucking coders

**Comment by Nokington** [comment]
> Balance.

Yes lets make aliens spawn at full size and lets have there be more of them and lets make them happen more as well all in the name of balance.

**Comment by Nebyab** [comment]
Once again mate, altering the spawn rate ain't balance. And as much as I hate aliums, we might as well gives this a bit of a trial, who knows it may actually be fun. Worst case scenario, we do a revert the next day.

**Comment by ghost** [comment]
@Nokington @Nebyab the spawn rate is effectively unaltered, if you read my most recent post/the changelog. Tackle rate has been nerfed, hence balancing.

@Nokington Aliens were designed for much longer rounds that the ones on Hippie, and they take too much time to build up as it is, including evolving.

**Comment by Nokington** [comment]
Yeah because they were meant to end rounds that is why they were designed for longer rounds.

**Comment by ghost** [comment]
Code fixed, could the heads come to a consensus on whether or not this gets merged?

**Comment by carlarc** [comment]
playing alien is fun, playing against is probably fun too. queen scream is a little op though, i'd say nerf the stun duration

**Comment by Nokington** [comment]
This is at a stalemate as Neb is for it and I am against it.

**Comment by Lawligagger** [comment]
To break the stalemate, I'm not really feeling it.

**Comment by Carbonhell** [comment]
Stalemate broken and PR refused, closing.

**Pull request closed without merging**
