### PR TITLE
Vape rework

### PR DESCRIPTION
**Pull request by tortellinitony**
There have been a number of complaints about vaping that I hope to address with this.

ALL PENS
-New better sprites
-Reduced absorption rate of reagents

MEDIUM VOLTAGE PENS
-Added a 3% chance to explode, previously none
-Reduced cloud size from 1 to 0

EMAGGED PENS
-Increased rate to explode from 5% to 8%
-Reduced cloud size from 4 to 3

Examples of the old, big, ugly sprites: http://puu.sh/ruw0z/9e5f99ee15.png

The new sprites: http://puu.sh/ruwnP/59eccec26b.png

### CODE REVIEW

**Comment by doobiedoo23** [comment]
The sprites are way too big IMO.

I support the nerf, but I'd prefer them to be downsized.

**Comment by tortellinitony** [comment]
I'll try to make them smaller later and see if it looks retarded, but they still have to fit the overlay when you use a screwdriver on it.

**Comment by KayeArray** [comment]
While you're at it could you make their container code less snowflakey, at the moment you can only transfer 25u at a time regardless of transfer settings, left clicking empties it for some reason and you can literally suck the reagents out of solid objects like pills to fill the vape, its weird and doesn't fit with the other reagent stuffs.

**Comment by Kierany9** [comment]
>While you're at it could you make their container code less snowflakey, at the moment you can only transfer 25u at a time regardless of transfer settings, left clicking empties it for some reason and you can literally suck the reagents out of solid objects like pills to fill the vape, its weird and doesn't fit with the other reagent stuffs.

Is this what happens when Carbon isn't the one codechecking?

**Comment by tortellinitony** [comment]
> While you're at it could you make their container code less snowflakey, at the moment you can only transfer 25u at a time regardless of transfer settings, left clicking empties it for some reason and you can literally suck the reagents out of solid objects like pills to fill the vape, its weird and doesn't fit with the other reagent stuffs.

This is actually intentional, previously you could only take from glass containers, but I wanted to be able to vape food and stuff.

**Comment by tortellinitony** [comment]
Alright, here's some more changes I made:

New sprites! Smaller, I don't think I can go much smaller than this. http://puu.sh/ruMWG/780e766195.png

The e-Cigarette now has a lowercase e and an uppercase C!

It is also treated like a normal container and can take reagents normally! Woohoo!

**Comment by ghost** [comment]
Yeah sure +1

**Comment by Kierany9** [comment]
>This is actually intentional, previously you could only take from glass containers, but I wanted to be able to vape food and stuff.

what

how does that even work?

**Comment by Spacedong** [comment]
sprites are still fuckhuge and lack detail and don't really fit into the artstyle, make them slightly bigger than cigs, not fuckhuge 
https://vgy.me/ii1Qn2.png

also make them face horizontally, not vertically, it just makes them look weird as fuck

**Comment by tortellinitony** [comment]
New icons, they are styled after a different type of ecig! http://i.imgur.com/h0RWYSA.png

Also, when you wear the Vape Naysh shirt, you scream "Vape nation!"

**Comment by tortellinitony** [comment]
Did not mean to close that woops.

**Comment by TDcoolguy300** [comment]
Code looks fine.

**Comment by tortellinitony** [comment]
> So.. what is the point of medium voltage if cloud size is 0?

Cloud size 0 means that it only takes up the tile you stand on, rather than a cross-pattern surrounding your tile.

**Comment by Carbonhell** [comment]
+1ing the idea(didn't check the code since td did already)
after another gm okays it i'll merge it, hopefully it was correctly codechecked

**Comment by doobiedoo23** [comment]
+1 @Carbonhell

**Comment by Carbonhell** [comment]
> mfw you don't merge it
> you're useless

**Pull request merged**
