### PR TITLE
Derelict Remake with Changelog

### PR DESCRIPTION
**Pull request by Cafaling**
Travis if you let this build pass I'll add something to the code in honour of you.

Pictures will be added shortly.

### CODE REVIEW

**Comment by Cafaling** [comment]
Aaaand, album:
https://imgur.com/a/fxusW

**Comment by Cafaling** [comment]
Keep in mind that most/all secrets are hidden, so there is neat stuff to find, but you actually need to FIND it.

**Comment by Carbonhell** [comment]
How's stuff hidden if the code is opensource?Honk

**Comment by Cafaling** [comment]
I'll fuck you up Carbon

**Comment by AliiTea** [comment]
I know the secrets :^)

**Comment by Cafaling** [comment]
That's because you're a cheater Nex

**Comment by AliiTea** [comment]
Honk

**Comment by danhibiki** [comment]
Sure

**Comment by TDcoolguy300** [comment]
Anybody else wants approve this?

**Comment by lcass** [comment]
looks noice , better than shitty derelict we have now from 2009

**Comment by ghost** [comment]
add nw

**Comment by Cafaling** [comment]
Don't listen to Oprayx, he's just got a boner for this because I may or may not have put Metal gear stuff in there

**Pull request merged**
