### PR TITLE
Drones no longer need gravity to move

### PR DESCRIPTION
**Pull request by Chronitonity**
Lets be honest here for a minute.

Fuck whoever decided they needed gravity.

Drones need to fix the station/derelict, and its pretty hard to fix shit when gravity goes off, this just makes drones do their job a bit better.

### CODE REVIEW

**Comment by Nebyab** [comment]
Does this give them pre-nerf janicart mobility or the ability to move freely over non-space tiles regardless of gravity?

**Comment by Chronitonity** [comment]
Should be the ability to move without using gravity, think a jetpack.

**Comment by Shadowlight213** [comment]
This also makes them immune to spacewind.

**Comment by ghost** [comment]
yesssssssssssssssssssssssssssssss
fuck having to carry rods everywhere as a drone

**Comment by Cafaling** [comment]
:+1: 
This makes me want to play the physical form of autism more.

**Comment by danhibiki** [comment]
Sure

**Pull request merged**
