### PR TITLE
Soulstone fix

### PR DESCRIPTION
**Pull request by AliiTea**
Now librarians and Miners can use Soulstones!
Fixes https://github.com/HippieStationCode/HippieStation13/issues/1122

### CODE REVIEW

**Comment by AliiTea** [comment]
All I did was change 

/obj/item/device/soulstone to /obj/item/device/soulstone/anybody  :'D

**Comment by Chronitonity** [comment]
This is the laziest fix ive ever seen but sure okay

**Comment by AliiTea** [comment]
It's ready just removed fail changelog

**Comment by Nebyab** [comment]
yeah sure

**Pull request merged**
