### PR TITLE
Slight debuffing of the throwing knife

### PR DESCRIPTION
**Pull request by lcass**
Lowers the damage when thrown to be the same as that of a thrown null rod

### CODE REVIEW

**Comment by Nokington** [comment]
Make it 15 and its good to merge. Just tested 10 and its way too weak now

**Comment by Carbonhell** [comment]
Are you sure 15 is enough?I mean, syndicate cards cost one tc for an entire deck which should be 30-40 cards,each one does 10 brute damage when thrown and has an high chance of embedding,paying 6 tcs only for 5 more brute damage seems pointless.

**Comment by Nokington** [comment]
Who actually buys syndicate cards

**Comment by Carbonhell** [comment]
...Me,i once killed an entire crew with 2 decks

**Pull request merged**
