### PR TITLE
Removes Matterbins from Microwave Creation

### PR DESCRIPTION
**Pull request by ArcLumin**
What the literal fuck /tg/

fixes https://github.com/HippieStationCode/HippieStation13/issues/2895

### CODE REVIEW

**Comment by TDcoolguy300** [comment]
MUST. STORE. EVERYTHING

**Comment by TDcoolguy300** [comment]
codes fine, also.

**Comment by Kokojos** [comment]
Microwave lives matters bin +1

**Comment by ghost** [comment]
Yeah okay sure +1

**Pull request merged**
