### PR TITLE
JaniBackpack fix

### PR DESCRIPTION
**Pull request by AliiTea**
Fixes the Janitors backpack sprayer only holding 500 when it should have held 700

_I made a whoops_

### CODE REVIEW

**Comment by Carbonhell** [comment]
Where is it said that it had to held 700 instead of 500?

**Comment by AliiTea** [comment]
https://github.com/HippieStationCode/HippieStation13/pull/2030
@Carbonhell 
Right here.

**Comment by AliiTea** [comment]
No one going to look at this??

**Comment by myontasm** [comment]
I think 500 units sounds fine to me.

**Comment by Carbonhell** [comment]
^ so uh, if another headmin refuses the pr's gonna be closed

**Comment by AliiTea** [comment]
I already raised it to 700... this is just to make it actually have 700..

 /obj/item/weapon/watertank/janitor/New()
    ..()
    reagents.add_reagent("cleaner", 700)      <---------

**Comment by Carbonhell** [comment]
Oh,just noticed. Well,you shoudl've said that in your other pr, the title only defines the janicart,not the backpack too

**Comment by Carbonhell** [comment]
Well,i prefer waiting for headmins to vouch in before merging this anyway,they may have not noticed aswell.

**Comment by myontasm** [comment]
Alright, if it already were supposed to be at 700 then why not.

**Comment by Carbonhell** [comment]
@nebyab @nokington

**Comment by Nokington** [comment]
ok

**Comment by AliiTea** [comment]
Two heads have said yes plz merge

**Pull request merged**
