### PR TITLE
Fixes changeling not being de-husked when regenerating

### PR DESCRIPTION
**Pull request by Kokojos**
Fix to #1852

### CODE REVIEW

**Comment by Nokington** [comment]
:+1:

**Comment by Nebyab** [comment]
why not

**Comment by FuryMcFlurry** [comment]
not sure but, shouldn't changelings NOT be able to regenerate when husked by another changeling? After all the absorbing changeling gets all the victims DNA points.

**Comment by FuryMcFlurry** [comment]
image

**Comment by Kokojos** [comment]
Lings  can regenerate while dead, so.... close this if you want me to code that.

**Comment by Nokington** [comment]
Yeah lings should not be able to regen if eaten by another ling

**Pull request closed without merging**
