### PR TITLE
Removes cats as a playable race

### PR DESCRIPTION
**Pull request by doobiedoo23**
Title

### CODE REVIEW

**Comment by TDcoolguy300** [comment]
> 0 files changed

**Comment by doobiedoo23** [comment]
fixed

**Comment by Crystalwarrior** [comment]
wow code looks terrible, fix it

_yes codecheck is ok ok_

**Comment by myontasm** [comment]
Yes.

**Comment by Nokington** [comment]
So this removes cats from spawning at round start?

**Comment by doobiedoo23** [comment]
No, you just can't pick cats as a race. Catbans still work fine.

**Comment by Nokington** [comment]
Ok

**Comment by Crystalwarrior** [comment]
b-but... why can't I join as a cat and be a hermit?
I want my hardmode outside of catbans.

**Comment by Crystalwarrior** [comment]
Can we discuss this?

**Comment by Spacedong** [comment]
keep it but remove cats being able to be antag, problem solved

**Comment by myontasm** [comment]
There's nothing to discuss, cats were never meant to be chosen anyways.

**Comment by Crystalwarrior** [comment]
That's quite a bold thing to say seeing as cats were playable for almost an entire year now.

**Comment by myontasm** [comment]
Before the rebase in October you couldn't. That's not a "whole year" my friend.

**Comment by myontasm** [comment]
They could if you had been given the snowflake thingie by admins.

**Comment by Crystalwarrior** [comment]
Exactly, and quite a few people had catbeast as an option without having to be completely catbanned. Myself included.

**Comment by Crystalwarrior** [comment]
Like I said instead of instantly removing something that has quite a few opportunities for interesting gameplay we should at least talk about the GOOD and the BAD of it. Don't rush this shit ffs

**Comment by lcass** [comment]
I strongly disagree with this update , lots of players have fun through joining and trying to survive as a cat east and this update removes that. What is actually gained by doing this? It just removed a feature that has been around for ages with little reason.

**Comment by Crystalwarrior** [comment]
Not to mention Cluwnes are already being worked on, having to be stuck with TWO punishment races is just going to be silly.

**Comment by Nokington** [comment]
I'm neutral on this either way.

**Comment by carlarc** [comment]
This is dumb. Add cluwnes AND keep cats.

**Comment by danhibiki** [comment]
Cats weren't selectable as a race because of a poor execution of a rebase, with no negativity meant towards those who performed it. Trying to use it as an excuse is pretty weak, because the majority head opinion at the time still wanted cats to be playable, its just none of the coders wanted to. Just my two cents.

**Comment by AliiTea** [comment]
This is stupid.
:-1:

**Comment by ghost** [comment]
Sick burns coming straight out from nex.
Catbeasts are a-okay, they get the urge to random lynch out your system. If anything I think they should be exempt from most if not all antagging. I've never really liked the idea of cult/rev cats.

**Comment by Crystalwarrior** [comment]
Yup, remake this PR into no-catbeast-antags and we're going to be just dandy.

**Comment by Pyko1** [comment]
I love catbeast hunting, as well as occasionally playing as a cat just to see how long i can survive.
Would be sad to see catbeasts limited only to catbanned people.

Them being restricted from roundstart and all sort of mulligan/event antags would be fine tho.

**Comment by carlarc** [comment]
This would just make people ask for catbans

**Comment by McHatters** [comment]
wait, so no roundstart catbeast antags? Or no roundstart catbeasts?

**Comment by TDcoolguy300** [comment]
This is a no-roundstart catbeast PR

**Comment by calibraptor** [comment]
If cats are going to be removed as a roundstart race, then we might as well add a shitload of disabilities to them too. Amplify the punishment.

**Comment by lcass** [comment]
If you are going to do this then just readd the snowflake feature entirely .

**Comment by Crystalwarrior** [comment]
Cluwnes are in now, this PR is unnecessary.

**Comment by Nokington** [comment]
Yeah I dont really think we need this

**Comment by Lawligagger** [comment]
should I go ahead and deny this

**Comment by Crystalwarrior** [comment]
@lawligagger yup

**Comment by Crystalwarrior** [comment]
I guess I'll go ahead and close this then.

**Pull request closed without merging**
