### PR TITLE
Re-adds the prototype station, removes old comms sattelite.

### PR DESCRIPTION
**Pull request by Kokojos**
As it was before the rebase. Yeah, it's been that long.

Fully repairable although it's easy to repair it in the most part.

Notable Loot is : 
1: Full centcom outfit and desert eagle (Hidden in safe, no stetoscope on station)
2: Two blue space tomato and a moonflower
3 : One taser gun and one retro laser gun
4 : STORY BOOK WITH ACTUAL LORE! ON HIPPIE? HERESYYYYYY

proto

### CODE REVIEW

**Comment by dreamcrab** [comment]
do we have to kill the old comms sat for this? can we have both?

**Comment by calibraptor** [comment]
Why remove the comms sat?

**Comment by Kokojos** [comment]
The original though behind this was to avoid space clutter. It is entirely possible for me to re-add the satellite, however it will make finding things very easy in space on this peculiar Z-level*.

**Comment by Gandalf2k15** [comment]
aaaaaaaaaaa dont remove comms sat! and a desert eagle???!!!!!

**Comment by Kokojos** [comment]
@Gandalf2k15 The gun is hidden behind a safe, and you need a stetoscope to open it. It's really, really not easy to open, and it is time consuming even if you know how.

**Comment by Pyko1** [comment]
Should add this as a template instead, and generally move all the static shit to templates besides station/mining and centcomm.

**Comment by trifornt-tinfornt** [comment]
Nah, I'd prefer it being a Z-Level thing instead of a random template.

**Comment by Kierany9** [comment]
>One taser gun and one retro laser gun

Eeeeeh.

>removes old comms sattelite

No. Why?

>desert eagle

[internal screaming]

This is literally just a smaller derelict that's easier to repair and has better loot, and replaces the WGW spam station. -1

**Comment by Crystalwarrior** [comment]
+1
I really want this map to be back. It's an easier-to-repair "refuge station" that can serve as a sort of escape from the main station, and I always found Derelict to be way too hard to repair if you just wanted somewhere in space to chillax.
The guns don't seem too much of a big deal, and desert eagle being hidden behind a safe is much better than it just casually laying around.

Why the hell would you remove existing space junk though?? Make it a template or something :(

**Comment by Kokojos** [comment]
Guess il have to redo this with the comms sat.

**Comment by Rodocks** [comment]
when is this going to be commited?

**Comment by AliiTea** [comment]
This was in before and there was absolutely no problem with the deagle or guns it was mostly ignored.

**Comment by Nebyab** [comment]
Next to nobody ever was able to retrieve the deagle way back when, I doubt we're going to see that problem come up again.

**Comment by danhibiki** [comment]
No, people were able to loot the station for its valuables fairly easy, but that was a problem with the teleporter in science and is a non-issue now. Having guns or traitor equipment off station is nothing new, shouldn't be a problem unless we are looking to curb its inclusion. Having one or two more isn't going to be a huge weight though

**Comment by Nebyab** [comment]
To clarify I was referring to manually. People did abuse telescience which is why its pretty much been excised and thus we don't have to worry about this loot ending up in the round on a regular basis.

**Comment by Kokojos** [comment]
Made a better PR

**Pull request closed without merging**
