### PR TITLE
waffle.io Badge

### PR DESCRIPTION
**Pull request by waffle-iron**
Merge this to receive a badge indicating the number of issues in the ready column on your waffle.io board at https://waffle.io/HippieStationCode/HippieStation13

This was requested by a real person (user Crystalwarrior) on waffle.io, we're not trying to spam you.

### CODE REVIEW

**Comment by Crystalwarrior** [comment]
@nalarmg this bot scares me

**Comment by Nokington** [comment]
A real person. Amazing

**Comment by Carbonhell** [comment]
who are you
fite me 1vs1
fgt
(it's a bot right?)

**Comment by Carbonhell** [comment]
i'll leave this shit to @nalar

**Pull request merged**
