### PR TITLE
Adds baneposting

### PR DESCRIPTION
**Pull request by doobiedoo23**
Hacking the security gas mask/SWAT mask will now allow you to spout quotes from the infamous plane scene, complete with low quality sound files.

image
image

### CODE REVIEW

**Comment by doobiedoo23** [comment]
oh fuck i forgot 'dr pavel, i'm cia' one sec

**Comment by myontasm** [comment]
IF I CLOSE THIS PULL WILL YOU DIE?

**Comment by doobiedoo23** [comment]
IT WOULD BE EXTREMELY PAINFUL

**Comment by Weisyl** [comment]
This is why we need the FUCK label again.

**Comment by myontasm** [comment]
YOU'RE A BIG CONTRIBUTOR

**Comment by doobiedoo23** [comment]
FOR YOU

**Comment by myontasm** [comment]
WAS GETTING PULLED PART OF YOUR PLAN?

**Comment by danhibiki** [comment]
yes plz

**Comment by Spacedong** [comment]
ITS MASKETTA MAN, NOT MASKED MAN, DO YOU EVEN KNOW THE L O R E HOTHEAD?

**Comment by Spacedong** [comment]
THE FIRE RISES

**Comment by Nokington** [comment]
sure

**Comment by doobiedoo23** [comment]
Update: Emagging the security gas mask will cause it to be stuck on you permanently (because if you pull it off, you'll die). Despite this, there are benefits. It will give you protection from flashbangs but also make you bald.

**Comment by Lawligagger** [comment]
yes please

**Comment by Nokington** [comment]
still sure

**Comment by nalarmg** [comment]
2 heads approved, merged.

**Comment by Lawligagger** [comment]
you fucking piece of shit ninja

**Comment by TalkingCactus** [comment]
Fuck, you beat me to this.

**Pull request merged**
