### PR TITLE
Nuke Ops tweaks 

### PR DESCRIPTION
**Pull request by Chronitonity**
Thanks to Kor from TG for the big two parts of these
- rscadd: "You can now buy reinforcement syndicates from your uplink at 25 TC a pop. These syndicates get no hardsuit or TC to spend."
- rscdel: "Syndicates can no longer buy a teleporter board and teleport to the station. Instead they can buy:"
- rscadd: "An Assault Pod Targetting Device for 25 TC, which will let them sync up to the new assault pod in their hanger and choose a location to send it."
- rscadd: "This pod is a one way trip! So make sure to take everything you need including the Nuke, or leave an operative or two behind to take the shuttle."
- rscdel: "Bulldog shotguns no longer spawn in the shuttle locker. You now need to buy your weapons from the uplink again."
- tweak: "Syndicate weapons have been slightly lowered in price. This is subject to change again with community feedback, either for cheaper or more expensive weapons."

http://puu.sh/m0MJu/6e2e8f727b.png 

http://puu.sh/m0GUz/61bb8b1396.png

Ignore the turrets, i ended up stripping those because im too lazy to properly update our turret code right now.

Lowered a lot of the gun costs by a tc or a few (Or in the Saws case 15 because once someone disarms that from you its over for the team) to make up for the stripping of roundstart deathguns

Hopefully this will make it easier for the dream of ASS Ops to happen

### CODE REVIEW

**Comment by Chronitonity** [comment]
wow every pr today has tweaks in the title how weird

**Comment by Foosili** [comment]
birds that bob their head back and forth and peep really fast when they fly away 👌👀👌👀👌👀👌👀👌👀 good shit go౦ԁ sHit👌 thats ✔ some good👌👌shit right👌👌th 👌 ere👌👌👌 right✔there ✔✔if i do ƽaү so my selｆ 💯  i say so 💯  thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ💯 👌👌 👌НO0ОଠＯOOＯOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ👌 👌👌 👌 💯 👌 👀 👀 👀 👌👌Good shit

**Comment by Foosili** [comment]
> fails check

do NOT sign me the FUCK up 👎👀👎👀👎👀👎👀👎👀 bad shit ba̷̶ ԁ sHit 👎 thats ❌ some bad 👎👎shit right 👎👎 th 👎 ere 👎👎👎 right ❌ there ❌ ❌ if i do ƽaү so my selｆ🚫 i say so 🚫 thats not what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ 🚫 👎 👎👎НO0ОଠＯOOＯOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ 👎 👎👎 👎 🚫 👎 👀 👀 👀 👎👎Bad shit

**Comment by Foosili** [comment]
> passes check 
> birds that bob their head back and forth and peep really fast when they fly away 👌👀👌👀👌👀👌👀👌👀 good shit go౦ԁ sHit👌 thats ✔ some good👌👌shit right👌👌th 👌 ere👌👌👌 right✔there ✔✔if i do ƽaү so my selｆ 💯 i say so 💯 thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ💯 👌👌 👌НO0ОଠＯOOＯOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ👌 👌👌 👌 💯 👌 👀 👀 👀 👌👌Good shit

**Comment by Foosili** [comment]
> gets merged

birds that bob their head back and forth and peep really fast when they fly away 👌👀👌👀👌👀👌👀👌👀 good shit go౦ԁ sHit👌 thats ✔ some good👌👌shit right👌👌th 👌 ere👌👌👌 right✔there ✔✔if i do ƽaү so my selｆ 💯 i say so 💯 thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ💯 👌👌 👌НO0ОଠＯOOＯOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ👌 👌👌 👌 💯 👌 👀 👀 👀 👌👌Good shit

**Pull request merged**
