### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by XeonFaux**
Should fix some bugs.

### CODE REVIEW

**Comment by Nokington** [comment]
What bugs does it fix?

**Comment by XeonFaux** [comment]
It fixes three runtimes, a spelling error, and a performance fix.

**Comment by XeonFaux** [comment]
Fixed another runtime, and another performance update.

**Comment by Nokington** [comment]
After someone checks the code ill :+1:

**Comment by danhibiki** [comment]
Looks good

**Pull request merged**
