### PR TITLE
Significant mining buffs

### PR DESCRIPTION
**Pull request by calibraptor**
Purpose of this PR is to make it worthwhile to actually play as a shaft miner during our often infamously short rounds.

Changes:
- <s>Shaft miners actually spawn ON the asteroid now.</s> Reverted due to the possibility that it would fuck with certain gamemodes.
- Significantly increased how much ore will generate all over the asteroid. The west side of the asteroid still generates a lot more valuable ore than the east side however.
- Added three mining drills to the mining outpost. (Seriously, who thought it was a good idea to remove round start mining drills? I'm looking at you tgstation.)
- Terrible manual mining scanners have been replaced with advanced scanners in all mining secure lockers.
- Science outpost has been removed, which was decided by popular vote in the June 4th admin meeting. Scientists can still take the shuttle to the northern mining outpost and use the barebones gear there to mine however.

hiiiii

(The little golden squares are where it has a chance to generate uncommon ore)

East side example:

east

West side example:

west

Go gently into that good night sweet prince:

nooooooooooooo

### CODE REVIEW

**Comment by trifornt-tinfornt** [comment]
But the roundstart drills were actually the Sonic Jackhammers, right?
Please let my precious Sonic Jackhammer back.

**Comment by ghost** [comment]
:+1:

**Comment by ghost** [comment]
Shaft miners should spawn on station. For the sake of revs.
Drills being available to shaft miners is fine.
I personally thought ore deposits were okay though.
I'd like for advanced scanners to be available too, there's no fun in constantly smashing z on a scanner.

**Comment by calibraptor** [comment]
@McBawbaggings Advanced scanners can be gotten with the mining voucher you start with.

EDIT: Also the shaft miners spawn on-station again.

**Comment by ghost** [comment]
No more potentially insta ending rev rounds.
Make mining great again. +1

**Comment by Gandalf2k15** [comment]
This will have zero effect.

**Comment by Voratius** [comment]
I'd be great if mining mobs were just removed, they don't really serve much purpose as-is.

**Comment by Kokojos** [comment]
yeah sure why not

**Comment by Sarcalogo** [comment]
If you want to REALLY buff mining, you'll remove the advanced scanner nonsense. Basically, before scanners and mining scanners, wearing mesons would allow you to see all ore, forever. 

If you can remove that, that will be a REAL improvement.

**Comment by trifornt-tinfornt** [comment]
Yeah, scanners have no reason to exist and just make mining's life harder. On a server with 20 minute rounds, that's not exactly helpful. Especially now that we have mining mobs back.

**Comment by calibraptor** [comment]
@trifornt-tinfornt Replaced sucky scanners with less sucky ones.

**Comment by Nebyab** [comment]
let's just have good mesons and this pr and everything will be neat and wonderful and forever happy

**Comment by Spacedong** [comment]
I thought mininig is better after rebase honestly, why do we need to buff it so much? you can already haul so much ore if you're good, christ, stop handholding, mining mobs need to be buffed, its so easy to kite them as it is

**Comment by calibraptor** [comment]
@Spacedong If you have the ripley maybe. Mining with just a pick means the round is practically over by the time you deliver the ore. I experienced it several times after the rebase, which is why I don't play mining anymore.

**Comment by calibraptor** [comment]
@Nebyab Tried my darndest but couldn't get the ore to be visible with mesons without it fucking up. Advanced scanners work fine enough anyway, toggle them on and forget about them.

**Comment by dreamcrab** [comment]
ive never used the ripley and have been able to get assloads of minerals every time i play miner

but whatever, if it gets people to play miner then im for it

**Comment by Carbonhell** [comment]
remove the scanner bullshit and i'll kiss you pls
code's ok as for now,unsure if the map is too,would need a mapper to check

**Comment by calibraptor** [comment]
@Dreamcrab Issue isn't that mining is hard much less that it's a long, boring grind that is quickly invalidated by shuttle call before you get to do anything fun with your gathered minerals.

But yeah, that's two +1's and a conditional +1 that I apparently don't have the skill and experience to fulfill without crap breaking. Miners all get the advanced turn-on-and-forget scanner now anyways.

This is ready to merge.

**Pull request merged**
