### PR TITLE
Canvas'

### PR DESCRIPTION
**Pull request by AliiTea**
Wew here we go!

### CODE REVIEW

**Comment by SplergeBucket** [comment]
conflicts
i dunno what does

**Comment by lcass** [comment]
think this may be merge conflicting with justins and vice versa. Although I can't be sure.

**Comment by Chronitonity** [comment]
Nah, thats not how git works. Its probably the changelog

**Comment by lcass** [comment]
facking , changelag

**Comment by AliiTea** [comment]
fak

**Pull request closed without merging**
