### PR TITLE
Adds Craftable Tiki Masks

### PR DESCRIPTION
**Pull request by Chronitonity**
Made from 2 Wood Planks, these masks will allow you to look like a real jerk. Clicking on a mask will allow you to change from 4 different types of masks.

http://i.imgur.com/U7obiXr.png

http://i.imgur.com/cUSMRim.png

Sprites are by the lovely @Nienhaus.

### CODE REVIEW

**Comment by Chronitonity** [comment]
Also adds a normal eyepatch to the theater vendor, all the other pirate gear was there.

**Comment by Nebyab** [comment]
Yeah sure

**Comment by danhibiki** [comment]
Sure

**Comment by ghost** [comment]
Woot.

**Pull request merged**
