### PR TITLE
Fixed butt's stored value not being update

### LINKED ISSUE #1714: Your butt is full!
If you put food in your butt it seems to get consumed, but your butt is still full.

Bix Nood stuffs the donut into his own butt.
Bix Nood stuffs the donut into his own butt.
You start inspecting your ass!
There's nothing in here!
Your butt is full!

### PR DESCRIPTION
**Pull request by JohnGinnane**
Added some code after the (sleep filled) for loop which will attempt to remove the object from butt.contents and update butt.stored correctly.

Fixes #1714

### CODE REVIEW

**Comment by Gandalf2k15** [comment]
For what it means, the code looks good in my eyes anyway.

**Comment by JohnGinnane** [comment]
I wasn't aware Byond accepted { and } for scope stuff. I compiled, and tested on my PC with them and only after I put up the PR and did another little review I noticed something was off..

**Comment by Gandalf2k15** [comment]
I think in byond they stand for something different.

**Comment by ghost** [comment]
> He puts the { on the same line of the condition

ATTEST FOR YOUR SINS

**Comment by JohnGinnane** [comment]
Depends on the project. If you want it on new line I'll do new line. It's just a habit..

**Comment by Kokojos** [comment]
Seems legit.

**Pull request merged**
