### PR TITLE
Off-station Permabrig BOOYEAH

### PR DESCRIPTION
**Pull request by calibraptor**
A whole new permabrig has been constructed on the asteroid z-level in place of where the labor camp used to be. It includes recreational facilities for well behaved prisoners, including some mining facilities.

Meanwhile the on-station permabrig has been converted into a training room for security officers, equipped with a firing range and training bombs. <s>Isolation and the prisoner transfer center has been left untouched.</s> Isolation has been removed by popular demand and replaced by a handy little medbay, complete with it's own mini morgue.

Some more maintenance has been constructed between the <s>isolation maintenance</s> brig west wing maintenance and the speakeasy to allow easier access by authorized engineers. 

Claims that these changes will make the brig less secure against unauthorized intruders are simply ridiculous and likely subversive syndicate propaganda.

Screenshots will be uploaded soon-ish

upper

lower

main

### CODE REVIEW

**Comment by Kierany9** [comment]
>Moves permabrig off station, nice.
>Doesn't remove isolation which is basically a shittier permabrig that everybody hates.

FUCK

**Comment by calibraptor** [comment]
@Kierany9 Unfortunately I must satisfy the whims and needs of fun hating powergamers as well.

**Comment by Kierany9** [comment]
As it stands, permabrig and isolation are interchangeable. The only reason why you'd use isolation is if you're a really fucking shit person and enjoy watching people quit the game immediately because they have nothing to do for 40 minutes or are so paranoid of "muh escapees".

Also goddamnit why'd you have to add two more isolation cells on the new permabrig _as well as keep the old one_?

**Comment by calibraptor** [comment]
@Kierany9 The normal cells function the exact same way if the officer putting you there decides not to open the recreation shutters. It's honestly up to the officer in question how pleasant or shitty your permabrig experience will be.

The High Risk Isolation cells are, by design, for dangerous prisoners who would pose a threat to their fellow inmates, such as changelings, traitors, and other dangerous peeps. 

Maybe scream at the headmins to finally come up with an official spesslaw to differentiate normal perma cells and high risk isolation.

**Comment by Pyko1** [comment]
Cant say that I'm a big fan that extra armory door.

Maybe replace it with desk and shutters instead?

**Comment by calibraptor** [comment]
@Pyko1 Sure!

**Comment by Gandalf2k15** [comment]
Can we uh, get rid of the isolation cells?

**Comment by Kierany9** [comment]
>The normal cells function the exact same way if the officer putting you there decides not to open the recreation shutters.

I've never had the recreation shutters closed actually. Five bucks says it's because they don't know that they exist and start open by default.

>The High Risk Isolation cells are, by design, for dangerous prisoners who would pose a threat to their fellow inmates, such as changelings, traitors, and other dangerous peeps.

In theory, yes. In practise those guys are executed on sight and instead you get chucked in solitary for greytiding.

Anyway, I'll shut up now and let some other people give feedback. New perma is fine. Firing range is nice but I feel as if that wing of the brig is taking up too much space for so little now that permabrig is gone.

**Comment by calibraptor** [comment]
Ehhhh I'll see about removing the solitary cell from the main station and one of the ones from the off-station perma

**Comment by Sarcalogo** [comment]
Do you think somebody could somehow make it so the Warden can actually see the brig cells so he's incentivized to actually stay in the brig and not just be a renamed officer.

**Comment by ghost** [comment]
> Extra painting stand

Isn't there a hardcap on how many there can be before everything dies?

> 2 Isolation chambers

That's no fun imo.

> Random airlock above left isolation chamber

Can you change the execution chamber to have a manual valve for the vent in the room below it? You could have it run across the pipes and go up right?

**Comment by calibraptor** [comment]
@McBawbaggings 

Extra Painting Stand: You've significantly spooked me, I'll remove it.

Isolation Chambers: Removing the left-most one and the on-station one, so it's a decent walk to actually get to the one existing isolation cell, and to make it clear that any officer that sticks a greytider in there instead of the much-closer-to-the-shuttle-dock perma cells is being an absolute asshole.

Random airlock: I actually noticed that a short while after posting the screenshot and removed it. As for the manual valve request I'll see what I can do.

**Comment by carlarc** [comment]
sounds great, but the firing range should have weak versions of pretty much every single energy weapon (including xray, pulse, disabler)

**Comment by calibraptor** [comment]
@carlarc I'll give you practice lasers, nothing more.

**Comment by carlarc** [comment]
i mean practice versions not the real thing, so bored assistants can break into the firing range and scare the heads with a fake pulse

**Comment by ghost** [comment]
They all fire the same though, there's no point in making practice pulse cannons.

**Comment by carlarc** [comment]
blergh, whatever.
other than that this is a almost superb pr +1

**Comment by Zadeon** [comment]
Good stuff +1

**Comment by trifornt-tinfornt** [comment]
Yeah, I love the idea! A nice, large area where prisoners can still do things. My only problem is that it's off Z-Level. Why not just have it be an off-station satellite so when you're permabrigged you can still escape?
Regardless, it's a very nice idea that I think I'll love.

> Isolation is still here

Yeah nevermind.

**Comment by Gandalf2k15** [comment]
Remove all isolation pls

**Comment by Sarcalogo** [comment]
What the hell are you supposed to do prisoners who break out of perma, attempt to break out of perma, attack others in perma? What do you do if perma is damaged and inhospitable?

You are forcing an execution on them. Isolation is necessary. If you don't like it, just ghost, because that's your only alternative anyway.

**Comment by calibraptor** [comment]
I've removed isolation from the main station and one of the isolation cells from the off-station perma. Hopefully that will satisfy the frothing masses. Now gimme a minute to update the screenshots.

**Comment by JohnGinnane** [comment]
The biggest issue I have with isolation is it basically means you can't play the game at all, unless someone knows you're there and breaks you out. 

At least if you ghost you could play as a golem or something. You can ghost while you're alive but doesn't this stop you from playing the rest of the round at all?

Having the one is okay, especially if it's off-station because sec are less likely to transport one guy there and might just put them in a normal brig cell.

The new perma looks fantastic and I'd happily go there just for the peace and quiet!

**Comment by trifornt-tinfornt** [comment]
> What the hell are you supposed to do prisoners who break out of perma, attempt to break out of perma, attack others in perma? What do you do if perma is damaged and inhospitable?
> You are forcing an execution on them. Isolation is necessary. If you don't like it, just ghost, because that's your only alternative anyway.

Hah, of course Sarcalogo would be the one to come and defend the terrible, inescapable garbage that is Isolation.

Isolation is widely hated for a reason. It literally cannot be escaped, there's nothing to do, and it's practically just an execution. If it gets to that point, why not just shoot lasers at their face until they die? Permabrig still lets people do things there, which is why people tend to prefer it.

**Comment by calibraptor** [comment]
Screenshots have been updated. There's only a single High Risk Isolation in existence now, and it requires that you walk down a long hallway a decent distance away from the normal perma cells in order to put someone in it.

Needless to say, anyone that goes through that much trouble to throw you in there is being a dong.

**Comment by blobbernaut** [comment]
isolation is literally for "executing" people without getting bwoinked. There is no other reason to use it.

**Comment by ghost** [comment]
> That chem machine in maint

It gives me a feeling so complicated 

> The Permabrig area having space inside in the room, seperated by rwindows slits

That's a pain to repair and generally speaking unrequired. There was already issues of people smashing the windows to space and that is even more so dangerous.

I think everything else is gucci.

**Comment by calibraptor** [comment]
@McBawbaggings

> That chem machine in maint

It's a portable chem machine, it has a very restricted selection of chemicals and only has a chemical capacity of 5. This is nothing compared to the full chem machine located in the abandoned lab.

> The Permabrig area having space inside in the room, seperated by rwindows slits

That's actually intentional. A 100% safe and secure permabrig would be boring in my honest opinion.

**Comment by ghost** [comment]
I'll revoke the windows thing, since it was foreseen structural weakness and intended.

**Comment by calibraptor** [comment]
@McBawbaggings 

Removed the portable chem dispenser and added thin firelocks to the r-windows you were talking about. I'll be passing out right after the checks pass so any other possible changes will have to wait until I wake up.

Otherwise this PR now fulfills the requirements of your conditional 'yes'. Need one more head to chime in before we can get mergin'

**Comment by doobiedoo23** [comment]
Chem machine would be fun

**Comment by ghost** [comment]
The Yes is now here, +1

**Comment by dreamcrab** [comment]
yea this is pretty rad but if it were solely up to me id keep the two isolation cells

**Comment by carlarc** [comment]
nnoooo

**Comment by Gandalf2k15** [comment]
Delete all of em

**Comment by calibraptor** [comment]
Aight, just confirmed with dreamcrab. I've got a yes from two heads here, this is ready to merge.

**Comment by calibraptor** [comment]
Do not merge yet, just discovered some issues that need to be resolved.

**Comment by calibraptor** [comment]
Good now.

**Pull request merged**
