### PR TITLE
Lets drones pick things up through the right click menu.

### LINKED ISSUE #1462: drones can't right click to pick up items
it says (mob can't use this verb type) or something like that, makes it a pain in the ass getting stuff out of stacks but alt-click works fine.

### PR DESCRIPTION
**Pull request by TrashFiend**
Fixes #1462 

Drones not being able to pick stuff up through the right-click menu is wonky. Alt-click works fine but some people use the right-click menu I guess.

Mainly doing this to see if I did the whole git thing right. Maybe I fucked up setting up git, dunno! Tested on a private server and it works fine.

### CODE REVIEW

**Comment by TDcoolguy300** [comment]
Seems good.

**Comment by danhibiki** [comment]
I'd like to hear from nalar too, but hearing this from TD is a huge endorsement

**Comment by nalarmg** [comment]
Code's fine.

**Comment by SplergeBucket** [comment]
This is a bugfix, merging.

**Pull request merged**
