### PR TITLE
ASS UPDATE

### PR DESCRIPTION
**Pull request by Carbonhell**
Atoms.dm:adds a check in examine verb to see if an item is poo stained or blood stained
Blood.dm: colors the blood overlay with a brownish color, if the item gets put in someone's ass its overlay blood color will stay brown, includes hands too
Items.dm:adds two new vars, with comments saying what they do:
var/assthrown = 0 //set to 1 to make the item 100% embed into an user when superfarted.
var/wasinass = 0 //if 1 the overlay will be poo one, i know it's crap but our current overlay code doesn't allow more than this
cig_lighters.dm:moves the overlay adding to its own proc so you can properly call it and it doesn't become invisible in poo overlays
snacks.dm:can now eat food through ass, once reagents end the trash(aka a plate or something like that)gets placed correctly inside the ass
staples.dm:you can now reattach your butt with a staple gun,aim groin. It'll be loose through,aka no superfart functions
emote.dm:adds farting objects out or superfarting them. farting ejects them normally(without the needing of removing the jumpsuit!), superfart throws them behind the user with a range of 6 tiles and 100% embedding, plus adds special effects when you fart with a special item inside.
examine.dm:adds checks for poostaining. if the item is poo stained it'll show "poo-stained" item when examining. this is mostly used for stuff like glasses,gloves,but i added it to all items just to be sure.
human.dm:adds a location to the butt so explosions work properly.
human_defense.dm:woop woop ass inspection,grab intent + aim groin,remove jumpsuit beforehand. you do it, wait around 2 seconds, and if there's an item it'll fall out, your hands will get stained with poo through.  woop woop get an ass inspection
human/life.dm:adds bleeding if your butt has an object with bleedchance higher or equal than 20. i used 20 since it's the value of shards, the best item i could think of.
species.dm:add items to your butt!Only 1 item,must remove jumpsuit. items accepted are only small/tiny, grab intent + aim groin.
pill.dm:now pills synthetize slowly through butt too, the reagents are slowly transfered(1 unit per second to avoid cigarette bug) from pill to human src
buttes_and_bots.dm:adds loose var so stapled butts aren't op and surgery still has a meaning
I hope it's all,phew,i worked on it for an entire week. changelog will soon come

### CODE REVIEW

**Comment by Carbonhell** [comment]
still need to make a changelog

**Comment by Spacedong** [comment]
IN MY ASS I JUST KNOW THAT THERES NO WAY TO LIGHT UP THE ASS IN HIS EYES WHOAH
HOAHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH

**Comment by Carbonhell** [comment]
Sorta completed except a small bug with ass inspection: when you ass inspect someone, THEIR hands will get poo-stained. No fucking clue why, user refers to the right mob, so no idea...If anyone's willing to check go on

**Comment by ghost** [comment]
gross

**Comment by SplergeBucket** [comment]
Atoms.dm:adds a check in examine verb to see if an item is poo stained or blood stained
Blood.dm: colors the blood overlay with a brownish color, if the item gets put in someone's ass its overlay blood color will stay brown, includes hands too
Items.dm:adds two new vars, with comments saying what they do:
var/wasinass = 0 //if 1 the overlay will be poo one, i know it's crap but our current overlay code doesn't allow more than this
cig_lighters.dm:moves the overlay adding to its own proc so you can properly call it and it doesn't become invisible in poo overlays
examine.dm:adds checks for poostaining. if the item is poo stained it'll show "poo-stained" item when examining. this is mostly used for stuff like glasses,gloves,but i added it to all items just to be sure.
human_defense.dm:woop woop ass inspection,grab intent + aim groin,remove jumpsuit beforehand. you do it, wait around 2 seconds, and if there's an item it'll fall out, your hands will get stained with poo through. woop woop get an ass inspection

No.
Not what I signed up for, fam.
A simple ass pocket treated much like a piece of equipment storage in which you could fart or superfart out stuff. No poo, no spanking, none of that wierd shit.

**Comment by Delimusca** [comment]
standing dangerously close to the "bring back poo" cliff. :hankey:

**Comment by Nebyab** [comment]
As someone who's been always iffy on the ass-update as a whole, adding shit is something I'm against. Just inherently against. I'd be okay with the actual ability to hide shit in your ass, but all this other stuff is a serious "What the fuck" sorta proposal for me.

**Comment by Carbonhello** [comment]
Poo overlays removed.
Spanking and slapping asses removed.

**Comment by SplergeBucket** [comment]
may want to consider merging this while we rebase to see how our playerbase handles it

**Pull request closed without merging**
