### PR TITLE
Updates to Gamma Derelict

### PR DESCRIPTION
**Pull request by TDcoolguy300**
fixed the plating error, removed some pointless extinguishers, added some more loot, and removed a pointless nanomed.

### CODE REVIEW

**Comment by TDcoolguy300** [comment]
I forgot to mention that Gandalf2k15 made this, i am just the middleman

**Comment by Gandalf2k15** [comment]
Does this really need two head's input?

**Comment by doobiedoo23** [comment]
What loot was added?

**Comment by Gandalf2k15** [comment]
Some heavy armor, a shitty mossin and a 357

**Comment by doobiedoo23** [comment]
Not too crazy on the armour and .357, to be honest.

**Comment by Gandalf2k15** [comment]
Its got worse loot than the ruski station and only has a 10% chance to spawn, the loot is pretty even. And its incredibly hard for people to find it. So its a nice little reward providing they don't die to the ruskies which they likely will.

**Comment by doobiedoo23** [comment]
Eh whatever, +1

**Comment by Nokington** [comment]
K

**Comment by Gandalf2k15** [comment]
Awaiting merge

**Pull request merged**
