### PR TITLE
Fixes a lot of shitty bugs,get fucked buggotron

### LINKED ISSUE #1040: Chaplains Thralls
They don't seem to properly show up at antag panel.
The players traitor panel shows them like any other player except with the time of death.

### LINKED ISSUE #1099: Shadowlings can delay the shuttle infinitely
As the title says. A single shadowling used the ability which delays the shuttle from arriving for another 15 minutes. They were able to use this ability 3 times (meaning the round was delayed from ending by 45 minutes) just so they could murderbone. From what I could tell, they simply sacrificed a thrall to delay the shuttle, then revived them so they could do it again. Even then, shadowlings as a whole should only be able to do it once. PERIOD.

### LINKED ISSUE #1147: On transforming as a monkey to human, it'll put any intercom on your same tile in your belt slot,again
https://github.com/HippieStationCode/HippieStation13/pull/376/files
Just need to re-do this fix here, tg didn't add it yet for some raisins

### LINKED ISSUE #1153: can't change transfer rate on backpack water tank
as the title says, you could change it like right after we rebased but now you can't, fix this ASAP botany is fucking ruined because I can't evenly distribute now

### LINKED ISSUE #1173: Metal baseball bats can be table crafted to make wooden spiked bats.
Probably because metal bat is a child of wooden bat, I assume. Just looks a bit silly.

### LINKED ISSUE #1203: Atmoslathe has a CRITICAL MISSPELLING
http://puu.sh/lkUT6/d32f9b4352.png

ed oxygen tank instead of red

@Carbonhello

### LINKED ISSUE #1206: Fire extinguishers make floor wet with their water
/title, this makes fire extinguishers ridiculously fucking powerful and haviing any other water-based sliptools is pretty much redundant.

@Carbonhell THIS IS ALL YOUR FAULT AAAAAAAAAAAAAAAAA

### PR DESCRIPTION
**Pull request by Carbonhell**
Fixes #1099 
Fixes #1040 along with a bug where all the organs would duplicate on both the floor and the skelethrall
Fixes #1173 
Fixes #1206 
Fixes #1147 
Fixes #1203 
Don't merge yet,nearly fixed #1153 
Also removed PATCH define and replaced wherever it was used with TOUCH, for consistency, so if you splash styptic powder it actually heals you a la goon style

### CODE REVIEW

**Comment by Carbonhell** [comment]
DON'T MERGE YET eh

**Comment by Chronitonity** [comment]
Im eh on removing patch myself, dont think you really need to

**Comment by Carbonhell** [comment]
It makes no sense. It's literally a special thing used only for stuff like styptic powder,silver sulfazine and synthflesh, and i wasn't even able to understand why. Now you can actually heal people by splashing the chem too like it should be,so.

**Comment by Chronitonity** [comment]
Id rather it be in a different PR than bug fixes. It sounds more like a balance thing so i cant insta heal with more thN 50u of something

**Comment by Carbonhell** [comment]
Patch removal reverted, still need to do some fixing to watertanks

**Comment by Carbonhell** [comment]
can't manage to fix watertanks yet, will fix them tomorrow.

**Comment by danhibiki** [comment]
On hold until its finished

**Comment by Carbonhell** [comment]
Fixes #1153  pr completed

**Pull request merged**
