### PR TITLE
Botany Buffs: First Strike

### PR DESCRIPTION
**Pull request by danhibiki**
# Plants

Double the chance of gaining regeants from your current cig and increased the amount of reagents gained to 5.
Decreased the amount of nicotine per cig by 10, to 5.

Swished around a ton of different chemicals to plants

Doubled the total speed of plant growth.
Modified harvest formula to regulate plantgrowth

Ambrosia Vulgaris now has diminishing impedrezene and oculine, and has everything but spacedrugs removed
Ambrosia deus is now space drug, omnizine, and perfluorodecalin. This will make it that so are certain potencies, if you continue to smoke you will not be able to speak at the same time (too high to talk)
Glowberries now contain teslium
Amanita's now contain mushroom hallucinogen and rotatium. They are no longer inheritly poisonous.
Grapes lost vitamins, gained salglu solution. This is so there is still a reliable source of salglu elsewhere besides drugs.
Increased the amount of O- blood from blood tomatos
Took morphine away from Reishi and gave it Krokodil
Replaced lexorin in death berries with Sulfanol
Gave potassium to chantrelle.
Gave sulfur to cabbage.
Gave ash to Novaflowers.
Gave salt petre to snapcorn.
Plump helmets now give mannitol.
Walking mushrooms now give tricordrazine.
Destroying angel now contains amatoxin, heparin, lexorin, and teslium. Extremely lethal upon consumption

 See the effects here
Liberty caps contain space drugs and at higher potency very trace amounts of calomel.
Poppys contain morphine.
Replica pods can now harvest more than 2 seed packets from a blank replicapod, increased by yield. Cloning someone thru replicapod will provide bonus potatos based on yield.
Probably more that I missed for plants
# Wud

Added wooded walls.
Check it out
Uses a proprietary smoothing system,not up to date on TGs smooth wall yet but should be a future goal with aspiring icon artist.
Created by using hatchet on a barricade, which then produces a window frame. Frame can be filled with wood or glass.
200 health, can be destroyed by beating it. Barricades and wooden walls can catch on fire and burn.
Check out burning down wood walls(Warning: 4MB gif)

Added tooth hatchet, which is a little weaker than a normal hatchet, and breaks in 40 hits.

To do:
- [x] Make windows for wooden walls work properly
- [x] Tweak drug values so higher potency is lethal/helpful while still retaining unique elements at lower potencies
- [x] Add tooth hatchet

Credits to Derpthestewpidgoat for the wall code, some unknown contributor to the Russian Polar Station team for the wall sprite, and Fury for the tooth hatchet sprite. Credits to Hippie for the touch up on the fire sprite.

### CODE REVIEW

**Comment by TrashFiend** [comment]
🌿🌿🌿🌿🌿🌿🌿🌿🌿🌿dank shit dank sHit🌿thats ✔ some dank🌿🌿shit right🌿🌿th 🌿ere🌿🌿🌿right✔there ✔✔if i do ƽaү so my selｆ 🚬i say so 🚬thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ🚬🌿🌿🌿НO0ОଠＯOOＯOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ🌿🌿🌿🌿 🚬 🌿👀 👀 👀 🌿🌿Dank shit

**Comment by Weisyl** [comment]
Credits too please

**Comment by danhibiki** [comment]
of course, i've got a couple people to credit. I don't even have the changelog uploaded, and I have a couple other changes I haven't listed yet

**Comment by danhibiki** [comment]
This is ready for review

**Comment by Nokington** [comment]
Is this gonna update the botany layout too?

**Comment by danhibiki** [comment]
No, that is not part of this PR

**Comment by Nokington** [comment]
Alright well still +1

**Comment by Weisyl** [comment]
The spriter wasn't part of our team but was an unknown dude from the Russian Polar Station, which is closed-source for the most part.

**Comment by Nebyab** [comment]
yeahs ure

**Pull request merged**
