### PR TITLE
Anti-CID spoofing.

### PR DESCRIPTION
**Pull request by TDcoolguy300**
This PR introduces a Two-step system in order to determine whether a player is using a CID spoofer. On the first join the CID will be logged to a list with their respective Ckey. Upon rejoining from the BYOND client or hubpage, it checks whether the CID has changed, and if it has, it kills the connection for the client for atleast a round. This does not care for ranks, so Admins and players alike will need to ditch their spoofers should they use them.

AGAIN: This is a Two step system as basic as this: Join, Get booted,  Rejoin and you can play or not play.

### CODE REVIEW

**Comment by TDcoolguy300** [comment]
Also, i forgot to mention, this will also allow players to log into other machines should they need to.

**Comment by TDcoolguy300** [comment]
Modified so the server stores the first Ckey, so Authorization only needs to occur once now.

**Comment by TDcoolguy300** [comment]
Per round, that is.

**Comment by ghost** [comment]
Yeah okay +1

**Comment by Carbonhell** [comment]
code's k

**Comment by GenericGoose** [comment]
do we have  to rejoin  every round now?

**Comment by TDcoolguy300** [comment]
Only at the start, join once to authorize, join again to play.

**Comment by TrashFiend** [comment]
Wouldn't this fuck over anyone who tries to play on different computers (e.g. desktop & laptop)

**Comment by TDcoolguy300** [comment]
It only maintains itself throughout the round. Should the round restart you need to Reauth yourself.

**Comment by TDcoolguy300** [comment]
But if a client were to switch to a Laptop from their Desktop, they will be locked out of their current character.

**Comment by TrashFiend** [comment]
Let me make sure I got this right:

You join and get kicked once the first time you connect and then you're good to rejoin and play forever on that computer. You can't play on another computer until another round happens where you do the process again, basically de-authorizing the first computer. If you want to play on the first again it's the same thing.

Right?

**Comment by TDcoolguy300** [comment]
Correct. Once the round has ended, every client needs to go through the checks again, however to compensate i will talk into having the round-start timer increased.

**Comment by GenericGoose** [comment]
ssoo rrejooin affter restart.....
tthats poo
unless gammee doeess  it onn ittss ownn 
annd itts still gay

**Comment by TrashFiend** [comment]
Ok that sounds horrifically annoying. 

Instead of coasting into the next round you now have to go back to the hub and potentially sit through an ad/BYOND fuckery to get back in the game each and every round. I assumed this was a thing that carried over into future rounds.

**Comment by TDcoolguy300** [comment]
I can't possibly carry it over to other rounds without some sort of Database management, but that also means Ckeys can't time out the one computer's authorization. At best i'll be able to provide 2-3 computers per account, with a possible timeout period of 2-3 months. I'll need Nalar to do the actual tables though.

**Comment by Spacedong** [comment]
this sounds fucktardedly annoying jesus

**Comment by GenericGoose** [comment]
DNM  pppl thinkk its annoying

**Comment by ghost** [comment]
I was under the impression that the spoofer needed a one time check.
Please make it a one time check as this will be annoying to use.

**Comment by ghost** [comment]
Never mind, one time check makes it impossible to use another computer.

**Comment by KayeArray** [comment]
sounds really irritating

**Comment by Earthykiller127** [comment]
haha nigga, ppl wouldn't even need to grief anymore, your system would literally piss ppl more than they get pissed off from griefers hahaha

**Comment by GenericGoose** [comment]
maybe this PR is the ultimate griff

**Pull request closed without merging**
