### PR TITLE
Refurnishes the Wizard's Den

### PR DESCRIPTION
**Pull request by TheOneAndOnlyCreeperJoe**
http://i.imgur.com/eqMXivT.png

Makes the Wizard's Den look less of a flying scrapyard and more like a ship that is used by the Wizard Federation. Tried to stay true as possible to the previous design.

Ship spans 19 in width and 30 in height.

Features:
- Removed all the holes, pods and forcewalls and replaced them with actual parts of the ship.
- Moved the Dresser beneath the Magic Mirror
- Added more stuff to the tease room (still un-accessible trough any means)
- Added 2 guest chambers for whatever purpose (possible future wizard captive objective)
- Added a D&D Table, Poker Table, a Cola + Cigarette vendor and 2 arcades in the bridge.
- Added 2 displays which contains every toy mech available, as well as littering a few more toys around the place.
- Added a few more jokes here and there (the Wizard not having a driver's license)

### CODE REVIEW

**Comment by Carbonhell** [comment]
seems good

**Comment by Nokington** [comment]
K

**Comment by Lawligagger** [comment]
I kinda liked it better when it had the purple void outside and everything was made of wood

**Comment by carlarc** [comment]
i say we just get a new wizard map
also give it thrusters

**Comment by TheOneAndOnlyCreeperJoe** [comment]
thrusters are there but just outside of the picture.

**Comment by Kokojos** [comment]
This is so much better than what we have now. Yes.

**Comment by Nebyab** [comment]
The dumb lore justification reason for it being all fucked up was dumb, this is better

**Comment by AliiTea** [comment]
I liked the fucked up one...

**Comment by TheOneAndOnlyCreeperJoe** [comment]
double head approval

**Pull request merged**
