### PR TITLE
Fixes bolt of change turning people into drones without restrictions.

### PR DESCRIPTION
**Pull request by ghost**
They could fire guns and attack people and shit.
Also adds a comment to warn people not to use /mob/living/simple_animal/drone

### CODE REVIEW

**Comment by danhibiki** [comment]
This is a relatively urgent fix

**Comment by Spacedong** [comment]
but the real question is why does /mob/living/simple_animal/drone even exist at this point

**Comment by blobbernaut** [comment]
:-1: I think it should be a lawless drone from the staff of change to be honest, but maybe it should have a different sprite

**Comment by myontasm** [comment]
Blob, we already have the chance to score a syndieborg from the staff of change. That's enough in my opinion.

**Comment by ghost** [comment]
The reason /mob/living/simple_animal/drone exists is so I wouldn't have to override onclick code for syndrones and safedrones.

**Comment by ghost** [comment]
Staff of change should be filled with lots of bad choices and few good choices. It should be almost always bad. Lawless drones is bad.

**Comment by SplergeBucket** [comment]
this is a fix
should be merged

**Comment by ArcLumin** [comment]
I think it's fine as is

Bigger issue is staff of changing drones into other mobs

**Comment by myontasm** [comment]
Why isn't this merged yet aaaa

**Comment by TDcoolguy300** [comment]
¯_(ツ)_/¯

**Pull request merged**
