### PR TITLE
Change name from "cryptographic sequencer" to "electromagnetic sequencer"

### PR DESCRIPTION
**Pull request by ghost**
Everybody calls it an emag anyway and this adds consistency, helping new traitors find their shit without poking around the menu.

### CODE REVIEW

**Comment by Spacedong** [comment]
>all those commits

advanced OCD shitposting, holy shit

**Comment by ghost** [comment]
image
ok but why tho

**Comment by ghost** [comment]
@Spacedong i'm using the web editor while my repo syncs

@Mithrandalf it seems your issue is that it's not necessary. perhaps, though I believe this is more intuitive for new players instead of mixing up the terminology (seeing as emag has no spelling connection to cryprographic sequencer)

**Comment by Nebyab** [comment]
no

**Comment by calibraptor** [comment]
Muda

**Comment by ghost** [comment]
image

**Comment by ghost** [comment]
Before you all shitpost in my pull request, can you give reasons why this _isn't_ an improvement? Come on, you're better than this.

**Comment by Carbonhell** [comment]
ayy lmao

**Comment by Nebyab** [comment]
I''d rather not see something changed that doesn't need to be.

**Comment by Nebyab** [comment]
also "electromagnetic sequencer" is garbage technobabble.

**Comment by ghost** [comment]
@Nebyab The status quo is the enemy of progress, you know. (also please forgive me i don't know what terms goes good together)

**Comment by myontasm** [comment]
what the fuck NO

**Comment by Nebyab** [comment]
okay, but needless change is also the enemy of progress

**Comment by ghost** [comment]
@Nebyab That doesn't make any sense. That's like saying that having a safety on a gun isn't necessary because somebody could just point the gun away from somebody he didn't want to kill. Do you have any examples of this?

**Comment by Nebyab** [comment]
what

**Comment by ghost** [comment]
image

**Comment by ghost** [comment]
I understand grammar changes to make things read better but this is just change for the sake of change? No thank you -1.

**Comment by TDcoolguy300** [comment]
But it's Technobabble, it's intended.

**Comment by Kokojos** [comment]
Un-needed PR. :-1:

**Comment by ghost** [comment]
Closing due to 2 HA disapproval.

**Comment by KayeArray** [comment]
Should change it to electromagneticgraphic cryptoquasisequencing device.

**Pull request closed without merging**
