### PR TITLE
Adds new Hockey themed traitor set! Fuck spacedong, Merge fast cus it was pre approved.

### PR DESCRIPTION
**Pull request by GuyonBroadway**
Adds a potent hockey themed bundle of items for traitors, that includes a potent set of armour with helmet, a two-handed weapon mounted on a backpack that is the bastard child of a powerfist and baseball bat, some fancy pants looking roller-skates, A belt that can deploy a special thrown item that deals damage, stamina damage and stuns a target upon hitting them, this has a cooldown of about ten seconds and has slots to store up to two of them, and a hockey skull mask for badass points.
This set is purchasable from the traitor uplink for 20tc.
The whole set is NODROP, once you put this shit on you go all in, the idea is it's like a chainsaw level rampage item on steroids.
The armour is syringe proof, fireproof and spaceworthy if worn with the helmet and mask and they all have some decent energy resistance. However the potent hockey stick weapon can only be deployed from it's back mounted holder which cannot be removed, so in order to fully use it's power you need to sacrifice some versatility. Also if you get stunbaton'd you are down for 10 like anyone else.
The belt deploys little holopucks to your hand that deal about 10 brute and 20 stamina damage when thrown, this is amplified by the baseball bat effect from the hockey stick. They can be caught and thrown back at you so be careful.
The stick deals 18 damage and has a powerfist like knockback effect. Due to how the throw code works if they hit a wall they take 10 extra damage that pierces armour and stuns them for a little while. Leaving them helpless as you slap them into the wall over and over. It must be used with both hands to make use of it's damage but you need a free hand to throw (and bat back) objects.
Sprites are made by Fury McFlurry (except the puck sprite, that's just the middle of the E-sheild)
Possible changes that may or may not be necessary.
-Buff/Nerf the damage of the pucks and/or the stick itself.
-Buff/nerf the protective values of the armour, including its resistances to space/fire/syringes
-Possibly make an item that strips you down and equips the set directly on you so people can't cherry pick the gear.(This is a snowflakey solution)
 
The reason the right foot looks a little stretched is because the hockey stick is held down like a real hockey stick when you onehand it so it lines up with the skates.
hockeyset

### CODE REVIEW

**Comment by GuyonBroadway** [comment]
ALSO I ACCIDENTALLY TO MY FUCKING MASTER PLEASE MERGE FAST AND END MY PAIN!!

**Comment by blobbernaut** [comment]
That looks fucking incredible tbh

**Comment by GuyonBroadway** [comment]
YOU HAVE NO IDEA HOW MUCH BLOOD AND ALCOHOL WENT INTO MAKING THIS! I HAVE DRUNK SEVERAL PINTS OF BEER IN THIS DAY ALONE AND WHILE I SPILLED NO BLOOD I CANNOT RULE OUT FURY SPILLING SOME!

THIS WAS JUST A JIMMYING TO FIX CONFLICTS CAUSED BY SPACEDUNGS SAXOPHONE, IT WAS ALLREADY APPROVED AND CHECKED BY JOHN MERGE ASAP.


I'll calm down now...

**Comment by ArcLumin** [comment]
Merging because it was head approved in the previous PR as well as code reviewed. Code seems the same. Previous PR had to be closed because lolgithub. Merging

**Pull request merged**
