### PR TITLE
Fixes mint toxin

### PR DESCRIPTION
**Pull request by tortellinitony**
Hell yeah, it works!

### CODE REVIEW

**Comment by ArcLumin** [comment]
Don't forget your changelog lad.

Code's good.

**Comment by tortellinitony** [comment]
changelog added

**Comment by Pyko1** [comment]
With this cant you just load a syringe gun with 14 nutriment and 1 mint toxin for instant gib?

**Comment by Pyko1** [comment]
I recall it used to be much harder to became fat, that just reach the nutrition_level_fat.
So even tho this is a fix, its also a big buff to mint toxin as 15 or so nutriment is more than enough to reach nutrition_level_fat unless you are starving.

**Comment by ArcLumin** [comment]
You only get 1u mint toxin from the mint in the kitchen, and nutriment makes you fat REALLY slowly.

**Comment by ArcLumin** [comment]
To properly kill someone with this, you'd need to shoot them with 15u nutriment, wait a few minutes, and then shoot them with mint toxin. Good luck doing that, they already know you like to shoot people. And you only have one mint, with 1u toxin. You only got one shot do not miss your chance to blow.

**Comment by Pyko1** [comment]
fill a burger with nutriment, or wait for someone to munch multiple food items, also cant you just drop the mint toxin in a water tank and gib people with 1 mint/999 water mix?

**Comment by ArcLumin** [comment]
It needs to be enough of a reagent to actually allow it to process. In my tests, the lowest you can water down a chem is 1/10th

**Comment by ArcLumin** [comment]
Mind you, that doesn't stop some fuck with an oddy making infinite mint toxin

**Comment by Pyko1** [comment]
But anyways, this fix is also a humongous buff to mint toxin.

If I recall correct you had to be above nutriment_level_fat for like 10 minutes before to actually get fat disability. With this change the mint toxin will gib you as soon as your nutriment is over 600, which can be easily achievent by eating a box of donuts or a couple burgers, or even just 1 food item with some extra nutriment/sugar stuffed in it.

Not that I say its entirely bad thing, but it is a balance change that needs head input.
But Id take some serious consideration how much you want to buff a poison that can instantly gib people with just 0.1 units.

The nutriment_level_fat is the chubby level, which is pretty common thing to happen.
In my opinion it would had been better to re-add getting the fat disability instead, even if it would just mean a flavour text on examine.

**Comment by tortellinitony** [comment]
Well duh it's a huge buff, mint toxin doesn't even work!

**Comment by Pyko1** [comment]
Huge buff to what it used to be when it worked.

**Comment by KayeArray** [comment]
A smart lad would use a cryo cell or pool to dupe the mint toxin. 

Though I want to see this fixed because I like my mints.

**Comment by ArcLumin** [comment]
You need 100u to pop it in the pool

So you still need an oddy's infinite chem making shit

In which case you already have a chem duper.

**Comment by KayeArray** [comment]
You can still easily dupe with cryo

**Comment by Gandalf2k15** [comment]
Headmins pls.

**Comment by doobiedoo23** [comment]
S u r e

**Comment by ArcLumin** [comment]
approval from me, whatever that's worth.

**Comment by ghost** [comment]
I swear to fuck, I thought I commented on this PR _twice._
Yeah sure +1 very nice good shit.

**Comment by SplergeBucket** [comment]
yes

**Pull request merged**
