### PR TITLE
Updated README.md

### LINKED ISSUE #2811: Readme is still using /tg/station terminology
Is this intentional or should we update it to Hippie?

### PR DESCRIPTION
**Pull request by JohnGinnane**
Will contain information and links to our content rather than /tg/

Fixes #2811

### CODE REVIEW

**Comment by JohnGinnane** [comment]
Not sure a changelog is required as it's only a change to the GitHub Read Me. At the top I have mentioned we are a fork of /tg/station. Just need suggestions on what else to add/remove

**Comment by JohnGinnane** [comment]
**Note to self:** This created a branch on the HippieStation13 git, as I just edited it from the website. Be sure to delete if this PR is merged or not

**Comment by ghost** [comment]
Seems sufficient.

**Comment by ghost** [comment]
nice cool i like it

**Comment by JohnGinnane** [comment]
One thing I have in mind is where people can go if they're having issues setting up Git? Slack is invite-only and we don't have a public IRC (that I'm aware of) so that leaves forums. I could add that if you wish

**Comment by ghost** [comment]
If they have questions, they'd be best to ask on the server for slack invites. If they want to help, they should be invited.

**Comment by JohnGinnane** [comment]
Accidentally created branch on main repo. Going to recreate later today on branch of my fork

**Pull request closed without merging**
