### PR TITLE
Butts now deal toxin damage

### PR DESCRIPTION
**Pull request by ArcLumin**
Whoop whoop get an ass inspection

### CODE REVIEW

**Comment by yobob591** [comment]
yes please butt launchers are trash right now we need a butt buff

**Comment by gumner** [comment]
Best pr since hippie was created tbh

**Comment by ArcLumin** [comment]
Seems only projectiles have that damage_type proc, so I'll have to make it do shit myself

**Comment by KayeArray** [comment]
Make xeno and bluespace butts even more robust pls.

whoop whoop

**Comment by ArcLumin** [comment]
Closing this for a bit till I find a better way to do it. Was just some quickly done code

**Pull request closed without merging**
