### PR TITLE
Readds crystal's flame proof windows. (CURRENTLY UNUSED)

### PR DESCRIPTION
**Pull request by ghost**
Currently exists for adminbus purposes or for mapping purposes.

### CODE REVIEW

**Comment by calibraptor** [comment]
+1 you're a real pal.

**Comment by calibraptor** [comment]
FUCK

**Comment by myontasm** [comment]
Would be great as something for the execution room in brig aswell

**Comment by calibraptor** [comment]
Yeah the brig could definitely use these

**Comment by ghost** [comment]
Yeah I tested it on my own serb to be certain. Shit works yo.

**Comment by dreamcrab** [comment]
if it works then lets goooo!!! plus one all over this shit

**Comment by Spacedong** [comment]
are these those special purple windows used for gas chambers and stuff? if so +1 all the way I love fireproof windows, it'd make gassing jews easier

**Comment by calibraptor** [comment]
@Spacedong Aye they are, I need them terribly for a mapping project but the execution chamber could use em' too.

**Comment by Lawligagger** [comment]
+1

**Pull request merged**
