### PR TITLE
New Chem - Autisticium (Part Two)

### PR DESCRIPTION
**Pull request by Anderbergst**
In this PR, I introduce to you a new chem called Autisticium. 

This is meant to be a secret chem.

The chemical will require 100 reagents to make.
It will also require a temperature of 1000K to mix it.

List of the reagents required.
1. pentetic Acid
2. silver sulfadiazine
3. rezadone
4. spaceacillin
5. inacusiate
6. synaptizine
7. saline-glucose solution
8. miner's salve
9. synthflesh
10. styptic powder
11. calomel
12. perfluorodecalin
13. atropine
14. mannitol
15. mutadone
16. bicaridine
17. kelotane
18. bromelain
19. Dermaline
20. tricordrazine
21. sterilizine
22. space lube
23. cryptobiolin
24. virusfood
25. plantbgone
26. acetone
27. Formaldehyde
28. cyanide
29. Fluorosulfuric Acid
30. sulfonal
31. lipolicide
32. unstable mutagen
33. lexorin
34. chloral hydrate
35. mute toxin
36. mindbreaker toxin
37. teslium
38. Heparin
39. Rotatium
40. Bleach
41. space drugs
42. crank
43. krokodil
44. methamphetamine
45. heroin
46. bath salts
47. aranesp
48. goldschlager
49. patron
50. icetea
51. nuke cola
52. gin fizz
53. Manhattan Project
54. gin and tonic
55. Cuba Libre
56. Classic Martini
57. white russian
58. Screwdriver cocktail
59. Bloody Mary
60. Pan-Galactic Gargle Blaster
61. Brave Bull
62. tequila Sunrise
63. toxins special
64. beepksy smash
65. doctors delight
66. irishcream
67. manlydorf
68. hooch
69. irish coffee
70. atomic bomb
71. margarita
72. three mile island ice tea
73. whiskey soda
74. black russian
75. Bahama mama
76. singulo
77. Allies Cocktail
78. Demons blood
79. booger
80. Anti-Freeze
81. barefoot
82. sbiten
83. red mead
84. amasec
85. changeling sting
86. andalusia
87. Neurotoxin
88. irish car bomb
89. syndicate bomb
90. devils kiss
91. banana honk
92. thirteen loko
93. Canned laughter
94. grape soda
95. triple citrus
96. nutriment
97. vitamin
98. stable plasma
99. napalm
100. thermite

Once the chem is made and used on a person then that person will be instantly gibbed.

Only the most autistic of autistics will be able to make this chem and harness its powers.

### CODE REVIEW

**Comment by gumner** [comment]
seeing how impossible it is to make i guess its ok?

**Comment by Anderbergst** [comment]
I can make this in an hour and 30 minutes without anybody messing with me and having all materials.

**Comment by Anderbergst** [comment]
But that's only when im fast.

**Comment by gumner** [comment]
you require almost every chem on the game so i guess... ok? not worse than a ling

**Comment by gumner** [comment]
make that people brain come out when they're gibbed so they arent out of the round forever

**Comment by Anderbergst** [comment]
I mean it's not like this chem will impact anyone in the round since it will take forever to make it...

**Comment by Anderbergst** [comment]
And i guess I have to make a changelog too? ahh fuck i forgot rip

**Comment by gumner** [comment]
code seems fine so far

**Comment by Anderbergst** [comment]
gumner after this im gonna try to code your vampire shit thats my next project lol

**Comment by Anderbergst** [comment]
it will probably take me weeks but ill work hard on it lul

**Comment by Anderbergst** [comment]
Actually I lied, i need to do more simpler codes before i tackle harder codes like vampires... sorry

**Comment by KayeArray** [comment]
very creative

**Comment by Anderbergst** [comment]
I can already see someone spending two hours making the chem just to make an autisticium smoke grenade lolololol

**Comment by KayeArray** [comment]
inb4 someone uses this with an odysseus
inb4 someone sticks this in the pool

**Comment by ghost** [comment]
What the fuck are these file extensions.

**Comment by Pyko1** [comment]
Needs correct extensions, and/or to be placed in correct places/files.

Currently this does nothing.

**Comment by gumner** [comment]
yeah you dont need to create a entire new file for 1 chem or for gibbing

**Comment by JohnGinnane** [comment]
Alright, some issues with this:

* The code for **Autisticium Chemical Reaction** `should be in /code/modules/reagents/Chemistry-Recipes/Others.dm`
* The code for **Autisticium Regeant** should be in `/code/modules/reagents/Chemistry-Reagents/Other-Reagents.dm`
* The **changelog** should be in /html/changelogs and have a file extension of `.yml`
* The code for **Autisticium gib** should be in `/code/modules/reagents/Chemistry-Reagents/Other-Reagents.dm` probably right beneath your definition of the reagent.

Take a look at the files I mentioned, they should be in Documents\GitHub\HippieStation13\... if you set it up following the guide

**Comment by ghost** [comment]
This PR is more autistic than the chem itself

**Comment by KayeArray** [comment]
well it is from you know who

**Comment by ArcLumin** [comment]
Wouldn't be too hard or too slow to make this in a round as you just gotta plan out a route.

**Comment by Anderbergst** [comment]
well fuck i think i messed up

**Comment by Anderbergst** [comment]
im gonna work fixing on this

**Comment by KayeArray** [comment]
easy fix just stick the code in the proper files rather than making entirely new snowflake ones.

**Comment by ghost** [comment]
oh yeah this is a bad idea too since an instant deathchem that can be made by having no fun and being super autistic is bad design

**Comment by KayeArray** [comment]
make the afflicted actually develop autism and develop permanent max brain damage, jittering, and dizziness instead

**Comment by gumner** [comment]
if you do what ban said,then make it easier to make,cause im not getting every chem just for giving people autism,people already have autism.

**Comment by JohnGinnane** [comment]
I'd say leave the gib in, but maybe make it difficult to trigger, like maybe on people who are crit or something. This won't be easy to acquire right away (that we know of), so nerfing it before it's in the game seems a little harsh

**Comment by gumner** [comment]
the code is good,you just gotta copy pasta it and put it in the right places.

**Comment by Anderbergst** [comment]
So i pretty much just go find that file then edit then copy and paste my file to the right file?

**Comment by gumner** [comment]
the code in it,yes

**Comment by ArcLumin** [comment]
yup

**Comment by Anderbergst** [comment]
okay im doing it right now

**Comment by Anderbergst** [comment]
okay i want someone to confirm is this right now?

**Comment by ghost** [comment]
Still don't have the reaction nor the changelog and you're adding useless files. This is still a bad idea anyway.

**Comment by Anderbergst** [comment]
i know im adding them right now wait up

**Comment by Anderbergst** [comment]
Yea i give up on this. RIP.

**Comment by Anderbergst** [comment]
ill do a part three when i get everything right and clean.

**Comment by KayeArray** [comment]
just take a breather and look at how the other reagents are coded, it's not too hard to figure out

**Pull request closed without merging**
