### PR TITLE
Disables the gateway

### PR DESCRIPTION
**Pull request by Gandalf2k15**
Disables the gateway until further notice. Its lagging for some unknown reason.

### CODE REVIEW

**Comment by blobbernaut** [comment]
RIP :(

**Comment by blobbernaut** [comment]
are you sure it's not the zombies

**Comment by Gandalf2k15** [comment]
I'm sure
If it was it would be diseases.

**Comment by blobbernaut** [comment]
what was lagging specifically

**Comment by Crystalwarrior** [comment]
mob controller, I still suspect it's zombies.

**Comment by Gandalf2k15** [comment]
Mobs was at 5.

**Comment by Crystalwarrior** [comment]
Hm, actually I dunno. It might be gateway just as it might be zombies.

**Comment by blobbernaut** [comment]
yeah there were no more living mobs on the gateway.

**Comment by Gandalf2k15** [comment]
Disable it just to be sure I guess.

**Comment by JohnGinnane** [comment]
Merging to confirm whether it's still zombies or potentially gateway.

**Comment by calibraptor** [comment]
Gateway will be brought back later right? I still want to make maps for it. :(

**Comment by JohnGinnane** [comment]
I believe that is the intention. Disabled temporarily while we look into
what's causing the lag as it's unbearable and can crash the server

**Comment by blobbernaut** [comment]
blease revert

**Pull request merged**
