### PR TITLE
New Strider 40mm MGL and elite hardsuit for Nuke Ops, awaymission resize for consistency

### PR DESCRIPTION
**Pull request by Weisyl**
- rscadd: "Added the new Strider 40mm Multi-Grenade-Launcher for nuke ops. Can hold six 40mm grenades and costs 25 TC. Can also appear from summon guns. Credits to Dr. / Sgt. Fragg for the sprite."
- rscadd: "Added the new Elite Syndicate Hardsuit for nuke ops. Has moderately better armory in every category against damage and is immune to fire and highly effective in protection against explosions. Costs 12 TC. Credits to /tg/ for this port."
- bugfix: "The pulse rifle now has proper on-back icons once again, along with using pre-rebase fire sounds."
- bugfix: "Fixed laser cannon on-back sprites."
- bugfix: "The AKS-740U is now on the wild west map for real this time and can now appear from summon guns."

Also resized blackmarketpackers to be 255x255 for consistency and possibly fix some away-mission related issues?

Pictures:
New Elite Hardsuit + MGL 40mm:
http://puu.sh/lICgO/7248cf0479.png

Damage from a single 40mm grenade: 
http://puu.sh/lIClj/af73c308dd.png

### CODE REVIEW

**Comment by danhibiki** [comment]
Sure

**Comment by ghost** [comment]
Please credit the original spriter of the elite syndicate hardsuit instead of just randomly porting shit you didn't draw

**Comment by Weisyl** [comment]
I wasn't aware of who the original spriter was, so the least I could do was credit the server I ported it from.

**Comment by ghost** [comment]
Jesus christ, /tg/ didn't credit the original artist either when they ported it, nevermind

**Comment by Nebyab** [comment]
sure

**Comment by Foosili** [comment]
Alright, sure.

**Pull request merged**
