### PR TITLE
A fistful of mapping fixes

### PR DESCRIPTION
**Pull request by calibraptor**
- Fixed the permabrig mining vendor so it actually works.
- Fixed a couple rogue vents
- Made the pipes in the execution chamber visible
- Fixed unconnected pipes on multiple z-levels
- Fixed duplicate pipes on multiple z-levels
- Fixed active turfs at round start on multiple z-levels

### CODE REVIEW

**Comment by ghost** [comment]
Technically feature PR because of the vending change. (Adding atmos firesuits)
I did the maths and some playing.
You'd need to mine 235 sand tiles alone to buy the entire kit of the helmet, suit, coffee, burn patch, stimpack.

And then it's up to you to navigate the east side asteroid on a strict time limit. It's much more engaging to make prison breaks since it's long, grueling but achievable.

+1

**Comment by Sarcalogo** [comment]
Victor Rennem says there is a toolbox in the permabrig? Really...? Seems really stupid dude.

**Comment by ghost** [comment]
There is but it's in the maint which has rwalls and locked doors.
If you can get into there, you can break out anyway.

**Comment by Kokojos** [comment]
Yes +1

**Comment by dreamcrab** [comment]
yea looks coooooooooool +5

**Comment by calibraptor** [comment]
Got a yes from 2 Head nerds, merge & !update por favor.

**Pull request merged**
