### PR TITLE
Vampire PR

### PR DESCRIPTION
**Pull request by Chronitonity**
This will contain all the shit that gets added to Vampire. DNM for now.
Credit to TG for this shit.

Right now this allows Vampires to drink the "blood reagent" from syringes or beakers to get Dirty Blood

It also allows them to drink from bloodpacks if they want to.

### CODE REVIEW

**Comment by Carbonhello** [comment]
Can't this be merged already,it has some neat stuff

**Comment by Chronitonity** [comment]
Nope

**Comment by Foosili** [comment]
Neat. :+1:

**Comment by danhibiki** [comment]
Once its done, sure.

**Comment by ghost** [comment]
https://github.com/tgstation/-tg-station/pull/11951 Xhuis did some really great work here. Imitation is the sincerest form of flattery, right?

**Comment by Chronitonity** [comment]
I'm busy fucking with baseball bats, this is fine to merge, i'll work on the whole night vision biz later

**Pull request merged**
