### PR TITLE
Chaplain Holy Armor

### PR DESCRIPTION
**Pull request by Chronitonity**
Ports TG's fixing of glowshrooms and allowing items in hand to slowdown people

Also adds the tesla armor but reworks it to be a chaplain specific item. 50% of the time it blocks attacks to the chest and shocks people within 3 tiles. If you don't want to get shocked, aim somewhere else. As a trade off it has no armor stats at all compared to the normal templar armor (40 brute defense.)

It costs 14 TC.

### CODE REVIEW

**Comment by danhibiki** [comment]
failed chekz.

But yes

**Comment by Weisyl** [comment]
TBH I think the chance is too high. Maybe 25% to 30% chance to shock people instead?

**Comment by SplergeBucket** [comment]
Sounds good to me.

**Comment by Crystalwarrior** [comment]
@DerptheStewpidGoat then it'd be completely useless and you'd be better off just stealing reactive teleport armor
Something like that for 14 TC is good imo.

**Comment by FuryMcFlurry** [comment]
Maybe give some other sprites?

**Comment by McHatters** [comment]
What sprite would this use anyways?

**Comment by FuryMcFlurry** [comment]
the shitty gimmick armor he gotten. so same sprites

**Comment by McHatters** [comment]
so indistinguishable from the armor that spawns in the chaplain's closet?

**Comment by FuryMcFlurry** [comment]
Never played chaplain, but the files indicate for the templar armor.

**Comment by Chronitonity** [comment]
they're the same on purpose.

**Pull request merged**
