### PR TITLE
Changes Centcom so that admin created ERT teams can't automatically just go and get lethal weapons

### PR DESCRIPTION
**Pull request by Chronitonity**
When they arent supposed to

Changes the layout around from this 

http://puu.sh/lpWmz/2feb138260.png

to this

http://puu.sh/lpWTy/f9590f898a.png

### CODE REVIEW

**Comment by AliiTea** [comment]
:-1: removing all the fun stuff while I can't play

**Comment by ghost** [comment]
makes sense

**Comment by doobiedoo23** [comment]
:+1:, nex go away and watch some of your weird gook cartoons you fuck

**Comment by AliiTea** [comment]
I don't want to

**Comment by Carbonhell** [comment]
wait,ert is being used?wot, but anyway yeah,this is a bugfix so

**Comment by danhibiki** [comment]
Not a bug fix really, but its a welcome change.

**Comment by calibraptor** [comment]
+1

ERT went straight for the AKs and Rocket pistols last time they were used.

**Comment by Foosili** [comment]
Good. Fuck off nex

**Comment by Nebyab** [comment]
Yeah sure

**Pull request merged**
