### PR TITLE
map tweaks

### PR DESCRIPTION
**Pull request by Lawligagger**
Tweaks to the map

RD Office: http://puu.sh/j2Vlu/cb1d466786.png

CMO Office: http://puu.sh/j2VdH/99b8f31aa0.png

Medbay Lobby: http://puu.sh/j2VbQ/6907630578.png

Medbay Waiting Room: http://puu.sh/j2VbG/cd169fcac5.png

Bar: http://puu.sh/j2Vb6/15fc552518.png

Bridge: http://puu.sh/j2VaR/f1913c08c3.png

EVA: http://puu.sh/j2Vaq/8787f6fc5f.png

Medbay Storage and surgery: http://puu.sh/j2rZX/8d65868e89.png

### CODE REVIEW

**Comment by ghost** [comment]
Please run the `mapmerge` tool @Lawligagger if you require help ask @Kokojos

**Comment by AliiTea** [comment]
http://puu.sh/j2rZX/8d65868e89.png
YOU CAN'T ENTER D:

**Comment by Nokington** [comment]
@Memendia He knows, we pointed everything wrong out to him in coder.

**Comment by AliiTea** [comment]
@Nokington oh..

**Pull request closed without merging**
