### PR TITLE
Adds logs for my pool update

### PR DESCRIPTION
**Pull request by Kokojos**
Self-explanatory

### CODE REVIEW

**Comment by AliiTea** [comment]
> no code changes

**Comment by ghost** [comment]
best update of 2016, :+1: holy SHIT where do you come up with this stuff Kokojo

**Comment by nalarmg** [comment]
Needs actual code changes before we merge this.

**Comment by Kokojos** [comment]
@nalar My poolupdate already passed. It's #1947

**Comment by Nebyab** [comment]
i'm not sure what this is, unless its the changelog in which case i dunno why it hasn't been merged, then again i don't know much about anything

**Comment by nalarmg** [comment]
Because there was confusion as to what this was. It wasn't immediately clear that this was just a changelog for a different PR. @Kokojos Please specify these things in the description in future! It makes things a lot easier.

**Pull request merged**
