### PR TITLE
Server to IRC/Slack updates.

### PR DESCRIPTION
**Pull request by nalarmg**
Allows for admin PM exchanges to be sent to Slack/IRC for monitoring.

### CODE REVIEW

**Comment by myontasm** [comment]
Big Brother sees me yellin' vulgarities at the griefers

**Comment by AliiTea** [comment]
Great now everyone on slack will see my autism whenever I have to ahelp >_>

:+1:

**Comment by Nokington** [comment]
Sounds good

**Comment by danhibiki** [comment]
Yes

**Comment by Lawligagger** [comment]
Yes please.

**Pull request merged**
