### PR TITLE
Replaces Msay text with Runescape Text.

### PR DESCRIPTION
**Pull request by AliiTea**
Mentors are now memes!

### CODE REVIEW

**Comment by Spacedong** [comment]
uhh

**Comment by AliiTea** [comment]
REEE this only changes the msay text

**Comment by TDcoolguy300** [comment]
Still needs to be reviewed, not everybody wants to see godawful Runescape text.

**Comment by nalarmg** [comment]
No thank you. This is just being silly for the sake of being silly.

**Comment by Foosili** [comment]
What? No. :-1:

**Pull request closed without merging**
