### PR TITLE
Fixed being able to equip items to belt on your naked body

### PR DESCRIPTION
**Pull request by JohnGinnane**
Is now consistent with ID slot, pockets, etc.

### CODE REVIEW

**Comment by Crystalwarrior** [comment]
This is intended though...
It was confirmed as a feature all the way back to pre-rebase, where even after rebase it was ported back.
Fix stripping belt items not working instead.

**Comment by JohnGinnane** [comment]
Hm, but how can you put an item on your naked belt slot? For example a crowbar

**Comment by JohnGinnane** [comment]
I can change the show_inv() to show the belt if it's not obscured (similar to uniform for example), instead of being a child of the uniform slot

**Comment by Carbonhell** [comment]
https://github.com/HippieStationCode/HippieStation13/pull/2172
I already did it

**Comment by JohnGinnane** [comment]
Ah okay, whoops

**Pull request closed without merging**
