### PR TITLE
Fixes up that cryo bug

### PR DESCRIPTION
**Pull request by lcass**
If cryo is unpowered you can't put bitches inside it.

### CODE REVIEW

**Comment by nalarmg** [comment]
And what happens if someone is inside one when power is lost?

**Comment by lcass** [comment]
Then they are cucked , like if a beaker is inside a chem machine when there is no power. The cryo cell is lucked and they are cucked.

**Comment by Chronitonity** [comment]
:+1:

**Comment by nalarmg** [comment]
If it's unpowered they should probably be popped out/be able to pop themselves out.

**Comment by lcass** [comment]
Nah man. If you are stuck inside a machine you should suffer for your crimes.

**Pull request merged**
