### PR TITLE
Removes the singular zombie from the derelict 

### LINKED ISSUE #1224: Remove the zombie from the derelict
Players can possess it and eventually reach the main station to infect people. Suggest it be made admin only or a random event to prevent every round being a zombie round.

### PR DESCRIPTION
**Pull request by Chronitonity**
Players could control it and force Zombie rounds apparently 

Fixes #1224

### CODE REVIEW

**Comment by Carbonhello** [comment]
Are you sure you just deleted the zombie and not the floor and the area under it too

**Comment by Chronitonity** [comment]
Yes.

**Comment by danhibiki** [comment]
Yes

**Comment by Nebyab** [comment]
why was this ever even a thing?

**Pull request merged**
