### PR TITLE
Dio brando clothing edits

### PR DESCRIPTION
**Pull request by gumner**
wryyyyyyyyyyy

### CODE REVIEW

**Comment by gumner** [comment]
these uh delete jotaro.dmi shit are the ones that i made myself and uploaded to my own master cause im retarded,not related to scinex jotaro sprites

**Comment by MethMedic** [comment]
Add screams tbh

**Comment by gumner** [comment]
it does

**Comment by gumner** [comment]
this needs head inpput @spank @McBawbaggings @dudeinyourbackyard

**Comment by ghost** [comment]
Fucking hell, it's been 24 minutes. Don't ping right off the bat.

**Comment by gumner** [comment]
give input

**Comment by gumner** [comment]
pls

**Comment by ghost** [comment]
+1 but fuck off with that shit

**Comment by gumner** [comment]
hug me

**Comment by Anderbergst** [comment]
you probably need a better sound effect quality just sayin

**Comment by gumner** [comment]
the sound sounds fine 2 me,dont think you can upload anything that isnt ogg to spessmen

**Comment by gumner** [comment]
heads give input pls

**Comment by gumner** [comment]
wait dont merge this yet i will add more screams

**Comment by SpankMasterson** [comment]
sure im sick of jojo code but sure +1

**Comment by ghost** [comment]
Infact -1, the SFX are low quality as fuck.

**Comment by ArcLumin** [comment]
Boost the quality of the sound and McBaw will +1

**Comment by gumner** [comment]
working on bigger shit nao,gonna close

**Pull request closed without merging**
