### PR TITLE
Tweaks

### PR DESCRIPTION
**Pull request by Kilmannan**
Fixed Cell door being all access, put conveyors at arrivals to off start-state due to that 'start state on' bug.

### CODE REVIEW

**Comment by TDcoolguy300** [comment]
This good to go?

**Comment by Kilmannan** [comment]
Yes? If you're asking me?

**Comment by TDcoolguy300** [comment]
I need to know from you to be sure that it's good to merge, i dont know what could be going on in your mind.

**Comment by Kilmannan** [comment]
Yeah, sorry, it's all good to go. Just some quick fixes. My mind is a wonderful place, highly rated on Trip Advisor and well worth a visit.

**Pull request merged**
