### PR TITLE
New mining area + safety pickaxe

### PR DESCRIPTION
**Pull request by Gandalf2k15**
Adds a new abandoned mining area! LORE: Ship was hijacked and crashed into the old docking area. Wew.
Pictures(In byond crap editor):
image

Also gives new safety pickaxe a new sprite
image

BTW this does not change permabrigs pickaxes only puts it in the code for later use.

### CODE REVIEW

**Comment by calibraptor** [comment]
It's neat looking and all but I don't really see how it adds to the asteroid, also why is it directly connected to the mining outpost?

**Comment by ghost** [comment]
You've modified the example changelog instead of making your own.

**Comment by Gandalf2k15** [comment]
cock

**Comment by Gandalf2k15** [comment]
Its connected as it used to be the main dock LORE wise. And NT done a knock off job of cleaning it up.

**Comment by trifornt-tinfornt** [comment]
Free syndicat toolbox + C4.
...

**Comment by calibraptor** [comment]
Something like this could easily take up much less space, /not/ be connected to the outpost, and probably even be a space template. The asteroid is honestly the wrong place for something like this.

**Comment by Gandalf2k15** [comment]
I'm gonna remove the connecting outpost it looks retarded

**Comment by Gandalf2k15** [comment]
Honestly there aint enough shit to explore there.

**Comment by Sarcalogo** [comment]
Maybe the mining outpost should actually be a mining outpost? That is, basic things necessary to live and function instead of a few vending machines? Perhaps a botany area or something?

**Comment by Gandalf2k15** [comment]
I agree with you there.

**Comment by Gandalf2k15** [comment]
Updated to make more sense.

**Comment by calibraptor** [comment]
<s>Eh yeah sure.</s>

**Comment by Gandalf2k15** [comment]
whoops fucked up abit ill fix it

**Comment by Gandalf2k15** [comment]
I fucking love gitclient fixing all the conflicts for you. Anyway that fucked shit up fucking...

**Comment by Gandalf2k15** [comment]
This also fixes the pickaxes not being safety ones in perma

**Comment by calibraptor** [comment]
Well now -1 since the real pickaxes are intended for mining mobs. Also I've kinda reconsidered and this is a permanent map addition that literally nobody asked for.

Talk to TD about making it a template or something.

**Comment by Gandalf2k15** [comment]
Reverted safetypickaxe.

**Comment by blobbernaut** [comment]
+1 because new shit in space

>Honestly there aint enough shit to explore there.

**Comment by dreamcrab** [comment]
cool why not +1

**Comment by ghost** [comment]
> That little c4 by itself

Somewhat concerning.

**Comment by Kokojos** [comment]
Heh im sorry it's just kinda bland. 

-1/3 from me.

**Comment by ghost** [comment]
I'd rather the safety pickaxe was a dull pink like the safety rolling pin rather than the bluespace looking pick you have it as.

The mass amount of body bags seems strange for a freak accident.
The C4 is not a good idea.

**Comment by Gandalf2k15** [comment]
I'll tend to this later

**Comment by Gandalf2k15** [comment]
I give up on this. Its not really worth it.

**Pull request closed without merging**
