### PR TITLE
Fixed vodka not making floor slippy when used to clean

### LINKED ISSUE #3072: vodka cleans floors without making them wet
you dont even need a recipe, just mass stockpile vodka from the abandoned bar and you have instant 1000u space cleaner, what a joke update do you people even codecheck anymore

### PR DESCRIPTION
**Pull request by JohnGinnane**
Just like water and holy water. RIP power janitor, we hardly knew ye.

Fixes #3072

### CODE REVIEW

**Comment by Spacedong** [comment]
thanks

**Comment by blobbernaut** [comment]
-1, cannot set the vodka-floors on fire

**Comment by Kokojos** [comment]
@blobbernaut This is why we need to code in liquids.

**Comment by ArcLumin** [comment]
I can't agree with this, as alcohol has an extremely quick evaporation period, so by the time you finish mopping it will have already finished drying. And if you do want it to be slippery, it needs to dry faster than water

**Comment by Spacedong** [comment]
this was a shit update from the start what did u want

**Comment by ArcLumin** [comment]
M U H I M M E R S H U N

**Comment by JohnGinnane** [comment]
Will look into making the floors flammable

**Comment by JohnGinnane** [comment]
And make it dry faster than water

**Comment by ghost** [comment]
Why not just leave it as is then? Technically space cleaner isn't dry on application, and would just evaporate quicker than water, but it's not a feature for convenience sake.

Honestly, water is the easiest material to get for the janitor, so it's not like you'll run out of shit to slip people with. Washing the floors with vodka is a hassle, so it needs to have a decent reason to be used over water.

**Comment by ghost** [comment]
You see Ivan, when is clean floor with vodka, crew is not staying mad for vodka taste when slip.)))

**Comment by Pyko1** [comment]
code looks fine, and is a bug fix really, merging

**Pull request merged**
