### PR TITLE
Allows different tools to deconstruct/construct things faster

### PR DESCRIPTION
**Pull request by Chronitonity**
Ports TG's toolspeed var.

Currently this only effects bigger crowbars, the syndicate screwdriver, and experimental welding tools

Ups force of wrench and crowbar to 7.

### CODE REVIEW

**Comment by Crystalwarrior** [comment]
Ooo, this sounds coolio

**Comment by danhibiki** [comment]
sure

**Comment by danhibiki** [comment]
Only thing I'm concerned about actually is we are porting TG values, which means its going to be drastically slower.

**Comment by Nebyab** [comment]
see,ms good

**Pull request merged**
