### PR TITLE
Medical Nutriment Update

### PR DESCRIPTION
**Pull request by ghost**
makes ass-blasting less detrimental when the chef won't cook

### CODE REVIEW

**Comment by Spacedong** [comment]
so basically just run the chef out of town and make there be no downsides to assblasting? uhhh

**Comment by ghost** [comment]
> implying the Chef isn't a useless moron who never cooks because new tg cooking sucks

**Comment by Spacedong** [comment]
who is to blame here, chef or /tg/ rebase?

**Comment by ghost** [comment]
Both. /tg/ coders are morons, chefs never cook anyway

**Comment by Spacedong** [comment]
i cook as chef

**Comment by ghost** [comment]
you are a good person then

**Comment by Pyko1** [comment]
Nutriment is piss easy to get as it is now, and chef is barely needed anyways. I see no reason to add it free to sleepers, and make ridiculously simple recipe for it to chemistry. Currently it at least take slightly more than 2 seconds to make enough nutriment to feed the station for hours.

**Comment by ghost** [comment]
How is nutriment easy to get, especially if there aren't any chemists doing their job(Which happens all the time)

Sleepers heal everything else, and hunger is the biggest crutch on Hippie. No reason why sleepers shouldn't give nutriment as well as other chems.

**Comment by Pyko1** [comment]
Hunger has never ever been an issue to me, there is so much food outside to kitchen so that it should not be an issue until 1+ hour to the round and no one has cooked anything, and the botanist havent grown anything either. Unless of course you keep farting 24/7 and sewing that butt back on. This just makes chef even more useless than he already is.

**Comment by Pyko1** [comment]
Not to mention you can pretty much shove anything in to deepfryer and it will have nutriment.

**Comment by Pyko1** [comment]
Also the effort  and materials to make a burger which has 6 nutriment is no where compared to the effort in this PR, where you need 2 clicks at chemistry to make 50 nutriment, or actually inject it for practically free on sleepers.

**Comment by ghost** [comment]
Deepfried nutriment is ass. New cooking is too much effort for chefs to bother, and they constantly close their shutters, so no assistants going in and making food.

I'm willing to make the chemistry recipe more complex, but I think nutriment in sleepers would be useful as hell.

**Comment by Pyko1** [comment]
Takes practically no effort to cook, and there is snack vendors that should keep any normal person who does anything besides farting operational.

**Comment by TrashFiend** [comment]
I think I've been in all of 1 rounds in the past month where I had food go beyond yellow.

There are a ton of vending machines around the station to get your fix, I don't think its ever been a problem to be honest.

**Comment by ghost** [comment]
It's a constant problem for some of us. Ass blasting fucks up your hunger for a while, even snacks don't fix it. And did you read my comment about cooking @Pyko1 ? It doesn't happen, chef leaves the kitchen and locks it down.

**Comment by Pyko1** [comment]
Maybe stop assblasting if you are starving?

As far as I know the nutrition is actually meant to limit the assblasting you can do.

**Comment by Pyko1** [comment]
Erm, it seems i closed this on accident while replying.

**Comment by ghost** [comment]
Oh, wew lad. I was going to make the new update from another branch, but apparently I'm still shit with using the github command line so that didn't work.

Evidently sugar does give you nutriment after testing which makes the chem update pretty pointless, so I might just reintroduce the sleeper/ass grinding as a separate PR.

**Comment by ghost** [comment]
Yeah, apparently sugar gives 2/3rds the nutriment of nutriment, not sure why I never realized that.

I'll open a new PR later anyway, so no problem

**Pull request closed without merging**
