### PR TITLE
Secbot can no longer be pulled when enabled

### PR DESCRIPTION
**Pull request by Crystalwarrior**
/title, prevents secbots from being your personal ez-arrest tools unless you actually enable them to do the job.

### CODE REVIEW

**Comment by Kierany9** [comment]
no

you do not understand the fun of being a clown with sechuds

**Comment by Crystalwarrior** [comment]
thing is it's incredibly broken and can be used to gain access to places you're not supposed to have access to, + securitrons are a royal pain in the ass when someone's chasing you with one on their back.
The only way to kill a securitron when an HoS is dragging one around with him, sometimes even does it all the time, is to ranged-attack the securitron, and even then you have to worry about the HoS himself as well.

**Comment by trifornt-tinfornt** [comment]
Not to mention, detain mode.

**Comment by myontasm** [comment]
I'm not sure about this, I'll think it through.

**Comment by Lawligagger** [comment]
on the fence with this right now, thinking about it

**Comment by carlarc** [comment]
please remove detain mode

**Comment by Nokington** [comment]
nah

**Comment by Lawligagger** [comment]
nah on removing detain mode or nah as a whole nok

**Comment by myontasm** [comment]
You know what,
yeah sure
as long as detain mode is kept then ok :ok_hand:

**Comment by Spacedong** [comment]
no

**Comment by blobbernaut** [comment]
Securitrons should be able to use the vents to travel super fast

**Comment by carlarc** [comment]
if you're gonna keep detain mode give it a timer so it isn't a permanent stunlock

**Comment by ghost** [comment]
Can you turn them on while stunned? If so, this doesn't really change much and is kinda pointless.
If you can't then I'll give it my thumbs up. It gives a bit more to actually using securitrons smartly instead of antag cucker. (Securitrons really should be used for patrolling the station IMO rather than back up police.)

**Comment by trifornt-tinfornt** [comment]
You can't really turn them on while stunned, but what you can do is examine someone and set them to arrest - even when stunned.
The Beepsky will start attacking them.

**Comment by ghost** [comment]
But provided the assailant gets the drop on them first, the sec lads can't just meme turn them on yeah?

**Comment by trifornt-tinfornt** [comment]
No, they can't. But it's completely possible to drag a securitron behind you, find a guy and set him to arrest the second he stuns you causing Beepsky to perma-meme them with Detain mode.

**Comment by ghost** [comment]
You mean in the current state? I was moreso asking if this PR was merged, would you be able to activate the beepsky after you being stunned.

**Comment by trifornt-tinfornt** [comment]
No, you wouldn't.

**Comment by ghost** [comment]
I think this is totally legit change then, it means if you're beepsky isn't on as you see something fishy then you're in shit. +1

**Comment by EMT321** [comment]
I don't believe you can set people to arrest while slipped or stunned.

**Comment by Crystalwarrior** [comment]
Yeah, otherwise it'd be a bug since most of the UI have checks for that.

**Comment by dreamcrab** [comment]
lets see how it goes. +1

**Comment by ghost** [comment]
This has 2 headmin approval atm.

**Comment by Crystalwarrior** [comment]
Suppose this is merge ready then?

**Comment by Nebyab** [comment]
nah

**Comment by Crystalwarrior** [comment]
why.

**Comment by Crystalwarrior** [comment]
Closing this in favor of https://github.com/HippieStationCode/HippieStation13/pull/2284 which is frankly a better idea

**Pull request closed without merging**
