### PR TITLE
Adds info to syndicate key

### PR DESCRIPTION
**Pull request by ArcLumin**
Title, because I get so many mentor messages about "HOW DO I TALK ON SYNDIECHAT REEEE"

### CODE REVIEW

**Comment by Carbonhell** [comment]
what the fuck
:t exists?
i always used :h

**Comment by ArcLumin** [comment]
And :y for centcom chat

**Comment by ghost** [comment]
Yeah okay +1

**Comment by Badmex** [comment]
Sure +1/3

**Comment by SplergeBucket** [comment]
yeah

**Comment by JohnGinnane** [comment]
Code looks good. Do we need a changelog for such a small change?

**Comment by Lawligagger** [comment]
oh yeah mr krabs

**Pull request merged**
