### PR TITLE
Ports TG's effect system optimizations

### PR DESCRIPTION
**Pull request by danhibiki**
Credits: https://github.com/tgstation/-tg-station/commit/d3ee9102118ae3b1dec6433f82249ab1abda46d5

### CODE REVIEW

**Comment by danhibiki** [comment]
After review, this will be ready, I have tested and confirmed it works. There are minor updates I need to catch up on, but this is the large framework for it.

**Comment by TDcoolguy300** [comment]
Looks good to me

**Comment by nalarmg** [comment]
Should add any updates to it before merging. Codes fine.

**Comment by danhibiki** [comment]
Theres a couple stray updates, i'll round them up and post them in here so I can a good guideline

**Comment by danhibiki** [comment]
I checked TG and see no relevant fixes beyond what I've ported. https://github.com/tgstation/-tg-station/commits/master/code/game/objects/effects/effect_system

**Pull request merged**
