### PR TITLE
Added more checks for APC control screen

### LINKED ISSUE #404: Control APCs without an ID card
You can toggle the cover lock and the Main breaker if you were to walk away, wait for it to disconnect, run back to the APC and click either the ON button for the main breaker or the ENGAGE button before the Interface updates, it will toggle the APCs state for the button you had pressed.

### PR DESCRIPTION
**Pull request by Jaygriff**
fixes #404

### CODE REVIEW

**Comment by Jaygriff** [comment]
@Nokington @Lawligagger @SplergeBucket 
This shit needs to go in ASAP

**Comment by Nokington** [comment]
@danhibiki @JustinBNewton Did travis even pass?

**Comment by Jaygriff** [comment]
@Nokington Its not a compile able script. Its referenced in the nano so it wouldn't run through travis/compile.

**Comment by Jaygriff** [comment]
@Nokington No way to break internal game components but its quite clear what the code changes were and that they weren't harmful/doing bad shit.

**Comment by Nokington** [comment]
@JustinBNewton Alright, its always better to be safe.

**Comment by Jaygriff** [comment]
@Nokington I tested it, dont worry. But travis wont run it through no matter what.

**Pull request merged**
