### PR TITLE
Map Changes

### PR DESCRIPTION
**Pull request by ghost**
nerf arena in maint woo
https://i.gyazo.com/2fa1e60625e80749af2f94f1a53fd739.png
correctly used mapmerge and some subtle shit i didn't do correct the first time

### CODE REVIEW

**Comment by Chronitonity** [comment]
You didnt properly use mapmerge lad

**Comment by nalarmg** [comment]
Also needs a changelog.

**Comment by Chronitonity** [comment]
Unless it gets map merged it can't be merged, Pyko is reworking the armory and i'd rather not have this screw him up

**Comment by ghost** [comment]
after trivial autism i have fixed it

**Pull request merged**
