### PR TITLE
Fixes revenants being able to be eaten by sing

### PR DESCRIPTION
**Pull request by Scinexx**
Revenant was previously able to be eaten by the singularity, Also I think it was intentional before?

anyways, this is my first pull request, so let me know if I fucked something up in the process.

### CODE REVIEW

**Comment by ArcLumin** [comment]
Yee, finally

**Comment by KayeArray** [comment]
Normally I would say that not even ghosts are safe from a moving physics raping hole of death but the SS13 singularity is a pussy bitch wannabe and I support this.

**Comment by Swagile** [comment]
Is the name of your changelog .yml literally Create Scinex - . . . ?

You don't need the "Create" part in there.

**Comment by ArcLumin** [comment]
No, it's Scinex - RevenantSingFix.yml 

Not like it matters

**Comment by Swagile** [comment]
Ah, alright.

Im just used to changelogs only having the title and name of branch.

**Comment by Scinexx** [comment]
Yeah, I'm a bit new to this so I'm probably prone to doing funky shit like that.

**Comment by ArcLumin** [comment]
Changelog filename doesn't matter, so don't worry about it.

**Comment by ghost** [comment]
Code makes it appear to be intentional design. Bad design nonetheless. +1.

**Comment by Hackole** [comment]
yeah +1. Didn't realize that sings could eat a revenant, woof.

**Comment by ArcLumin** [comment]
https://github.com/HippieStationCode/HippieStation13/issues/2984 fixes this, weee

**Comment by GuyonBroadway** [comment]
It's kinda silly that a thing with total freedom of movement and invulnerability outside situations it can mostly control could blunder into the sing containment zone and "just die". I support this change.

**Comment by SplergeBucket** [comment]
the singularity is a beast of many powers and one of that powers is killing the shit outta things
-1 tbqhgh

**Comment by ghost** [comment]
What if it only kills provided you've manifested? Being non-existent and dying to singulo is bad.

**Comment by ghost** [comment]
You're pushing your jojo PR onto your rev PR.

**Comment by Swagile** [comment]
Yeah, make a new branch, add, commit, then push in that new branch.

**Comment by GuyonBroadway** [comment]
Ye forgot the tgstation.dme file ye cretin. But either way if you wanna add Joseph Johnson's rather otherworldly escapades uniforms make another PR.

**Comment by GuyonBroadway** [comment]
use git checkout (new branch name here) to change to your other branch ya ding dong.

**Comment by ghost** [comment]
this is a strictly no bully zone
please don't hurt each others feelings

**Comment by GuyonBroadway** [comment]
In the UK we have a system where the more you insult and bully a person the more you like them. You picece of ***^*&^&( *$£&^)@ ~£~£*&(*£$2 #£2**

**Comment by ArcLumin** [comment]
https://youtu.be/_m4VvpRQCeM

**Comment by ArcLumin** [comment]
Stop pissing off travis

**Comment by Scinexx** [comment]
Haha fuck, I'll delete this and restart

**Pull request closed without merging**
