### PR TITLE
Updates simple mob summons + fixes egg conflict bug

### PR DESCRIPTION
**Pull request by ArcLumin**
Adds sharks, hivelords, goliaths, scrakes, basilisks, fugus, and bats to hostile mob summons. Removes a unnecessary line in the spawning file.

Adds goldgrubs to passive mob summons.

Also fixes headslugs being able to plant eggs in xeno hosted bodies, causing issues.

Fixes headslug eggs conflicting when two eggs are implanted, causing the 2nd planted egg to gain the body.

### CODE REVIEW

**Comment by KayeArray** [comment]
Wait headslug got removed from xeno spawn list? fucking shadow nerfs

**Comment by ghost** [comment]
Headslug was taken out intentionally. It shouldn't be added back in.

**Comment by ArcLumin** [comment]
It was a stealth add in via a "bugfix". I see no issue with popping it back in.

**Comment by KayeArray** [comment]
Headslug was fun though......

**Comment by ghost** [comment]
It was admin policy to delete headslug spawns until someone removed them from spawning. Making non antag changelings is powergaymey as fuck in a bad way.

**Comment by KayeArray** [comment]
Yeah I can see why but tbh it wasn't really that op considering how fucking long it takes to get compared to the rest of science which gets bombs, laser cannons and adrenals,

**Comment by ArcLumin** [comment]
I figured it'd be perfectly fine as is. I don't see any issue with this, other servers still have it on as a feature, including the rebase.

**Comment by GuyonBroadway** [comment]
Considering how hard it is to actually get rainbow slimes coupled with how you are valid salad but not an Antag I think it could be Ok with a couple server policy tweaks. For example eating a body without checking it's cloneable should be banworthy. And use of a mind transference potion AT ALL should generate an admin message. so an eye can be kept on the guy using it.

Not to mention it's only usable for hostile mob spawns, meaning you have to deal with at least 4 other aggressive oogly booglies which could easily kill you before transferring your mind. 

And lastly because the spawn list is now larger you have a smaller chance to get a headslug. This RNG upon RNG upon RNG, while a bad form of balance, would probably provide a good enough barrier to prevent this shit happening round in round out.

**Comment by LufgtHuron** [comment]
Wait, what the fuck does a rainbow slime do?

**Comment by TDcoolguy300** [comment]
I do not approve of removing the Anti-headslug code, as Dan added it initially, Koko commented it out, and then Carbon reactivated it, and there WAS a changlog about this months ago, it's just that Koko Disabled it without notifying ANYONE.

**Comment by TDcoolguy300** [comment]
Also, the Rainbow slime creates a Mind transference potion, puts your mind into the mob you use it on, only works on simple mobs as far as i know.

**Comment by KayeArray** [comment]
Actually the easiest way to make yourself a ling is to spawn random hostile mobs until you get one and let it kill you, it's risky and dangerous but doesn't need no rainbow slimes.

**Comment by ArcLumin** [comment]
Personally, I'd love it if headslugs would be spawnable, hard to do, could take a while, but possible to self ling. But if I see too many people against it, I'll set them to 0 on the spawn.

**Comment by ArcLumin** [comment]
Removes headslugs from gold core spawning, due to feedback. Adds Scrakes.

**Comment by ArcLumin** [comment]
Oh wait this is PR #3005, hol up, we childish gambino

**Comment by ArcLumin** [comment]
Removing unneeded tags as code has been reviewed and the controversial content has been altered/removed. I would like current thoughts on this PR.

**Comment by ghost** [comment]
This is still a good buff to gold slimes considering scrakes have 300 HP and can do (upto) 40 damage a hit.

**Comment by blobbernaut** [comment]
I want the headslugs in tho

also what are scrakes

**Comment by ghost** [comment]
Self linging is bad and should not be enabled.
Scrakes are big chainsaw guys that have 300HP and deal anywhere from 15 to 40 damage a hit.

**Comment by ArcLumin** [comment]
They're also INCREDIBLY slow, slower than even mechs.

By comparison we have the statue, which can blind people, get the drop on them stupid fast and instakill them. That is kind of a horror mob, this is kind of another kind. Not nearly as strong as, say, a buffed up slime or a statue, or even stuff like ayys.

**Comment by ghost** [comment]
Statues are horribly OP and shouldn't be the standard but sure.
We can give this a shot then. +1 for trialling.

**Comment by doobiedoo23** [comment]
why the hek not

**Comment by SplergeBucket** [comment]
if the headslugs were remoeved +1

**Pull request merged**
