### PR TITLE
Revert "Catwalks are now Objects, Get_apc() no longer lags like hell"

### PR DESCRIPTION
**Pull request by Jaygriff**
Reverts HippieStationCode/HippieStation13#483

Broken wires on catwalks as well as bad setup. Objects =/= stuff you walk on

### CODE REVIEW

**Comment by Chronitonity** [comment]
Should remove the apc fixes here, they do fix a major issue.

**Comment by Jaygriff** [comment]
I agree.

**Comment by WhiteFox08** [comment]
Working on a fix for catwalks, no need to revert

**Comment by WhiteFox08** [comment]
Fixed at #488

**Pull request closed without merging**
