### PR TITLE
Added "We Are Number One" sound to the sax

### PR DESCRIPTION
**Pull request by Anderbergst**
Added the sound to the sax.

### CODE REVIEW

**Comment by yobob591** [comment]
you fucked it

**Comment by Anderbergst** [comment]
Can someone tell me why travis build failed? FUCK

**Comment by Anderbergst** [comment]
Alright it works now

**Comment by ghost** [comment]
This is quality +1

**Comment by Spacedong** [comment]
no

**Comment by Spacedong** [comment]
we already have a suit that makes the sound, and if yyou combined it with the saxophone you can play the tunes while doing it, why would you add this to it anyway? it makes no sense

**Comment by ghost** [comment]
The suit doesn't make any sound effects. You just shout out lines. I asked him to remove the SFX screams and he did.

**Comment by Spacedong** [comment]
for what purpose?

**Comment by Spacedong** [comment]
waiit it does mak sounds what r u talking about

**Comment by yobob591** [comment]
he means the suit says the lines and the sax plays the music

**Comment by Anderbergst** [comment]
what yobob said

**Comment by SpankMasterson** [comment]
sure why not +1

**Comment by ghost** [comment]
Hey, while you're modifying the file, mind adding an '!' to the end of the saxophone desc?

**Comment by Anderbergst** [comment]
okay

**Comment by ghost** [comment]
neat
+1

**Comment by Swagile** [comment]
GM + 1 if code checks out

**Comment by GuyonBroadway** [comment]
Why is this not a thing yet?

**Comment by Anderbergst** [comment]
this is ready

**Comment by zenek123321** [comment]
Merge now

**Comment by lcass** [comment]
You have two headmin decisions +1 , i'll give it a check and mergerinio if it is all good.

**Pull request merged**
