### PR TITLE
Fixes Bomb suits --CREDITS: GeneralGoose

### PR DESCRIPTION
**Pull request by Gandalf2k15**
SEE: https://github.com/HippieStationCode/HippieStation13/pull/2522/commits/0e6fe1fcc90b89c02632acfa0bba67e6059f497e for more info
fixes https://github.com/HippieStationCode/HippieStation13/issues/2530

### CODE REVIEW

**Comment by JohnGinnane** [comment]
Hold up. His PR also has this fix, isn't this redundant if his is getting merged?

**Comment by Gandalf2k15** [comment]
the reasoning is because of the code freeze, and having fixes and features is disallowed. This speeds things up.

**Comment by JohnGinnane** [comment]
Okay, so his PR will just be the CQC Gloves Disguise feature?

**Comment by Gandalf2k15** [comment]
Yep

**Comment by JohnGinnane** [comment]
Merging as it's a bugfix

**Pull request merged**
