### PR TITLE
Fixing bullshit

### PR DESCRIPTION
**Pull request by TkashiDaBeast**

### CODE REVIEW

**Comment by trifornt-tinfornt** [comment]
The greatest shit PR ever.

**Comment by dreamcrab** [comment]
wat

**Comment by TkashiDaBeast** [comment]
Wrong repository. Sorry 'bout that. 
New to using GIT.

**Comment by trifornt-tinfornt** [comment]
Oh, okay.

**Comment by myontasm** [comment]
shit happens

**Pull request closed without merging**
