### PR TITLE
🍆🍆🍆 Lcass likes to mess stuff up (JK It was me)

### PR DESCRIPTION
**Pull request by Jaygriff**
Fixes bullshit in science with disposals and a reinforced false wall on
top of a regular wall.

### CODE REVIEW

**Comment by ghost** [comment]
http://i.imgur.com/FpdwLQE.png

**Comment by Jaygriff** [comment]
@Nienhaus what you dont like utilizing new features in git such as EMOJIS FOREVER

**Comment by Jaygriff** [comment]
IM NOT DONE JUST YET LADIES AND GENTLEMEN

**Comment by Jaygriff** [comment]
ok its ready to roll

**Comment by lcass** [comment]
Does this fix the disposal pipe aswell?

**Comment by Jaygriff** [comment]
yes

**Comment by Jaygriff** [comment]
both of them

**Comment by lcass** [comment]
alright. This is involved with the chem update so i'll merge it.

**Pull request merged**
