### PR TITLE
More Flammable Shit

### PR DESCRIPTION
**Pull request by Cafaling**
If I could make everything flammable I probably would.

### CODE REVIEW

**Comment by Cafaling** [comment]
I am not a pyromaniac, despite what Carbon may say or assume.

**Comment by danhibiki** [comment]
Sounds good to me

**Comment by Cafaling** [comment]
The commit I just did for body pillows should handle the conflicts. Just matches the changes Carbon did to them with the burn_state.

**Comment by Cafaling** [comment]
Fack

**Pull request closed without merging**
