### PR TITLE
Updates experimentor bounding box

### PR DESCRIPTION
**Pull request by lcass**
Walking through a dense mofo shouldn't be alright.

### CODE REVIEW

**Comment by Chronitonity** [comment]
http://puu.sh/kOO31/6ffc53e3d0.png 

You're supposed to be able to walk over that part, its practically on the ground

**Comment by Chronitonity** [comment]
Also why did you make an entirely new branch on the git for one line of text

**Comment by lcass** [comment]
Because I can't be arsed to modify my fork , once it's merged it's gone. Walking over that is a bit silly it's the heavy autolathe sprite and it's a conveyor not really the best place to be walking.

**Comment by Chronitonity** [comment]
Pretty sure Nalar specifically said not to do with with branches but whatever. As for that its good if people need to crowd around it, so still :-1:

**Comment by lcass** [comment]
That just sounds like a lazy reason to not add it , barely anyone goes in there plus it makes it seem more polished instead of just being able to walk over the sprite.

**Comment by Chronitonity** [comment]
Its something that doesn't need an addition and it sure doesn't make it seem "more polished", its not a full tile and should let people walk over it. Its not even a big deal either way because honestly who cares.

**Comment by Foosili** [comment]
This doesn't really need to be in. None of the other machines work like this regardless of "height". For consistencies alone I'd rather us not do this :-1: .

**Comment by lcass** [comment]
Other machines? If I recall there are no other machines on the map that take up 2 tiles apart from multi tile constructions such as the particle accelerator which acts like this.

**Comment by nalarmg** [comment]
For the record - Do not create or push branches to the main repo (reverts are an exception) as when you do, everyone who forks is forced to have a copy of what you may be working on. Keep everything you work on contained to your own fork/local repo where at all possible. - from the Trello.

"I can't be bothered" is a terrible excuse.

Waiting for further head input, since this is sort of inconsistent and not particularly needed/necessary.

**Comment by danhibiki** [comment]
While its odd consistency wise to have a machine we can walk over, I don't think making it impassable will help anything.

**Comment by nalarmg** [comment]
Most heads seem against this, so closing.

**Pull request closed without merging**
