### PR TITLE
Bible refactor + Relics

### PR DESCRIPTION
**Pull request by Carbonhell**
Refactors bible code and removes its vars from ticker(what the fuck even)
Ports facepunch relics by using NanoUI code
Relics currently in:
Immunity: cures diseases
Purge: heals 5 toxin damage
Divine sight: heals 5 eye damage
Clear headed: removes mindbreaker/spacedrug and their effects
Reverb: 5% chance to fully heal deafness,otherwise heals 5 point of ear damage
Mending: heals 5 brute
Greed: spawns random coins/spacecash, needs 2 people to chant the chosen prayer
Gluttony: Spawns random food like a silver extract, needs 2 people to chant the chosen prayer

Healing relics heal 5 damage by default but there's an high chance that this effect lowers,depending on how many times the relic got used( times_used*20)
All relics have a chance for their range to lower, default range is 5 except for immunity which is lower. Minimum is 1.(times_used \* 10)
All relics have a chance to break(times_used \* 5)
Only one relic can exist at a time, if it breaks a new one can be chosen. You can set the prayer/chant from the bible by using it in hand.

### CODE REVIEW

**Comment by Carbonhell** [comment]
Also clown bible and banana bible have been merged into one bible which WON'T give you the clown disability anymore(this is just retarded), and gives back the old 2 peels like it did pre rebase

**Comment by Nokington** [comment]
Yesssssss. Finally a reason to play chaplain again

**Comment by Crystalwarrior** [comment]
~~Reverb should heal 5 ear damage instead of eye damage imo~~

Otherwise code looks good :+1:

**Comment by Carbonhell** [comment]
http://imgur.com/y6nrCZX

**Pull request merged**
