### PR TITLE
Fixes being able to clickspam electrified airlocks to spam sparks

### LINKED ISSUE #1232: Walking into an electrified door with insulated gloves on will endlessly spam sparks.
/title, this can potentially cause fuckloads of lag and is generally terrible.

### PR DESCRIPTION
**Pull request by Carbonhell**
Fixes #1232

### CODE REVIEW

**Comment by Carbonhell** [comment]
hello darkness my old friend

**Comment by Pyko1** [comment]
code seems fine

**Comment by Nebyab** [comment]
ok

**Comment by Crystalwarrior** [comment]
Gonna merge then, this is a bugfix

**Pull request merged**
