### PR TITLE
Made blob round notifications to infected players more noticeable + Quick Fix for issue #189 + Butt Pies

### PR DESCRIPTION
**Pull request by Jaygriff**
### Made blob round notifications to infected players more noticeable

simple font changes will allow people who are infected to notice when
they are infected.
### Quick Fix for issue #189

Did some research and for some reason the the protected_jobs list is not
getting transfered over to the restricted_jobs list at round start as it
should. So i just put the protected jobs list into the restricted jobs
list for the time being... Would like to find out why the setting is not
being correctly transferred eventually.

Research steps included: Setting limits to 1 (as my server would only
have 1 person)
Forcing round to always traitor.
Enrolling as cyborg only (The only role on the restricted_jobs list)
Then restarting the round 10 times.
Test concluded that I was not set to antag a single time, therefore the
restricted_jobs list was working properly, and the protected_jobs list
was not.
### Added buttpie

First experiment with DMI and icons.. Turned out well, might as well contribute it.
from: http://www.hippie-station-13.com/forums/viewtopic.php?f=21&t=753
Thanks to noscopetoolbox for contribution.

### CODE REVIEW

**Comment by ghost** [comment]
We're currently in an feature freeze, not going to pull this in the current state, give us a few days :)

**Comment by Jaygriff** [comment]
Sure thing, just did this stuff to familiarize with the code before i put in a coder application. Is there a way to make multiple pull requests so all my changes for a day arent in one, big pull request?

**Comment by ghost** [comment]
@JustinBNewton Yes, create one branch per PR.

**Comment by AliiTea** [comment]
Last time ButtPies were added we had the "Some Rights Reserved" happen D:

**Comment by Jaygriff** [comment]
Ive done it right! Tested and all!

**Comment by Jaygriff** [comment]
Do not merge, working on some deep issues with one of the changes I made.

**Comment by Nokington** [comment]
Wait, are you making it so heads can't be traitors anymore? HoS, HoP and the Captain are the only heads that shouldn't be able to be traitors.

**Comment by Jaygriff** [comment]
That whole fix has a issue right now.. gonna resolve it when I'm done separating them in to branches

**Pull request closed without merging**
