### PR TITLE
Added temporary debugging messages for the server

### PR DESCRIPTION
**Pull request by JohnGinnane**
Just added some simple debugging. Perhaps another coder in another time zone could check this out?

### CODE REVIEW

**Comment by nalarmg** [comment]
It would be better to change these to the message admins proc or something else not visible by players.

**Comment by JohnGinnane** [comment]
Good point, hold on and I'll make that change and test it..

**Comment by JohnGinnane** [comment]
Done! I'm heading to bed in the next hour though so if someone does merge and server is updated, would someone mind checking the output of this and logging under #2364

**Comment by Carbonhell** [comment]
not needed anymore i assume?closing

**Pull request merged**
