### PR TITLE
Fixes a couple typos

### PR DESCRIPTION
**Pull request by ArcLumin**
Fixes a couple typos in abandoned crates preventing items from spawning. I'll work on my lootcrate update later

### CODE REVIEW

**Comment by Badmex** [comment]
>powerfist 

AAAAAAAAAAAAAA

Still they should have already been included so yeah it's okay

**Comment by KayeArray** [comment]
Considering the fact you can find a katana at mining and take a trip to the derelict to get a revolver I see no problem with a small chance to get a power fist.

**Comment by Lawligagger** [comment]
ok

**Comment by Gandalf2k15** [comment]
Needs a changelog

**Comment by ghost** [comment]
@ArcLumin it should be dead easy to make a changelog so it's one step away from getting merged

**Comment by ArcLumin** [comment]
Is a cl really necessary for a typo fix?

**Comment by Gandalf2k15** [comment]
Good to go. Merging

**Pull request merged**
