### PR TITLE
Kilms map PR

### PR DESCRIPTION
**Pull request by danhibiki**
Don't have a preview image, but Kilm should chime in soon.

### CODE REVIEW

**Comment by Kilmannan** [comment]
image

**Comment by SplergeBucket** [comment]
uh
that preview image doesnt really provide me with a wide map showing how it looks in reference to everything else
im not sure where thats even located
is it above EVA's maintenance???

**Comment by Kilmannan** [comment]
Sorry, that spacial change is already live on the map. It's purely an internal space change hence why a localised image. Will get one on when I finish work later.

**Comment by Kilmannan** [comment]
image

**Comment by Nebyab** [comment]
seems neat

**Pull request merged**
