### PR TITLE
Alters Sniper Scope

### PR DESCRIPTION
**Pull request by ArcLumin**
Alters sniper scope from the buggy offset shit it was previously, now it increases client view range rather than offsetting it. It also now anchors you down while it's zoomed in. Now maybe the sniper rifle will be useful?

This framework also will work for adding scopes to normal guns.

Zooming in makes you move slower.

### CODE REVIEW

**Comment by SpankMasterson** [comment]
Neat, +1

**Comment by SpankMasterson** [comment]
so the way you changed it will zoom 7 tiles in w/e direction they face? what if youre facing a wall?

**Comment by ArcLumin** [comment]
Nah, it literally zooms out your client an extra 7 tiles. So it changes your view range from 7 to 14

**Comment by ArcLumin** [comment]
>getting label sniped

**Comment by JohnGinnane** [comment]
:¬)

**Comment by Hackole** [comment]
I don't know about the scope just giving you extra view range in any direction. Why wouldn't people just toggle it on and leave it on, then?

**Comment by Spacedong** [comment]
@hackole
the way the zoom works is that its disorienting if you play the entire game with it on

**Comment by ArcLumin** [comment]
You need to have the sniper with you to do it.

**Comment by ArcLumin** [comment]
Okay, longer post since I'm not on a dying phone

Not only do you need the expensive as hell sniper rifle the check the zoom, but the previous way of zooming was super buggy as shit. You literally could not aim properly with that because of the difference between the way you shoot and the way you see. This is the most viable way to boost the zoom function without it being broken.

**Comment by lcass** [comment]
as long as it resets when you move or lose the sniper rifle I think it's fine.

**Comment by ArcLumin** [comment]
That it does. Well, it resets when you lose the sniper rifle, that is

**Comment by ArcLumin** [comment]
Now it anchors you down while it's zoomed in

**Comment by Hackole** [comment]
yeh ok if it's stopping you from speeding around while you're scoped in. +1/3

**Comment by ghost** [comment]
What happens if you zoom in and someone disarms you and steals the gun? Will you auto unanchor?

**Comment by ArcLumin** [comment]
Yes, it cancels the zoom like normal

**Comment by ghost** [comment]
hopefully shit doesnt explode because of it
+1

**Comment by ArcLumin** [comment]
Just needs a code review and we're gucci to merge

**Comment by ArcLumin** [comment]
Apparently can't use the anchor proc, so now while you can move, it automatically cancels the zoom if you do.

**Comment by ArcLumin** [comment]
Gotta think of a better way to check for movement or anchor it, hmm

**Comment by ArcLumin** [comment]
I'm literally fucking retarded it was a capital M this entire time

**Comment by Pyko1** [comment]
What if being zoomed in caused you minor stamina damage to ensure you cant just camp a hallway 24/7

**Comment by ArcLumin** [comment]
It works now. It properly checks for movement. My only issue was I didn't capitalize the M in move

**Comment by Carbonhell** [comment]
What the fuck, why is if(user.Move) compiling, Move isn't even a var

**Comment by ArcLumin** [comment]
DNM till I can find the best way to do this

**Comment by lcass** [comment]
look at the handcuff code for the solution.

**Comment by Pyko1** [comment]
approved but code needs work

**Comment by Carbonhell** [comment]
Pwrsonally i love how the sniper scope works currently, Especially the offset part... I guess i am the only one, but anyway -1 from me

**Comment by ArcLumin** [comment]
You do realize that the aniper scope doesn't work currently? Because its a camera offset the trajectory of the bullets are the same as non-scoped, so they'll miss the target if its anything but a straight line

**Comment by JohnMcLaime** [comment]
Sniper scope has been bugged for so fucking long, i think it was after we got new pixel shooting. It is a useless item since you cant use the scope for firing at the moment. No need for anchor bullshit, just make it  so if you move it cancels the scopeview.

**Comment by ArcLumin** [comment]
Biggest issue is for me to check if they're moving or not without it being a hacky way. I haven't looked into it too far though

**Comment by ArcLumin** [comment]
This has been fixed, just needs code review

**Comment by ArcLumin** [comment]
fuck, canmove resets upon the next tick

**Comment by ArcLumin** [comment]
Alright, fuck setting it to cancel on move, thought of a better way. You just move slow as fuck when zoomed in

**Comment by ArcLumin** [comment]
Needs code review and it's good to go

**Comment by TheOneAndOnlyCreeperJoe** [comment]
code is fine.

**Comment by ArcLumin** [comment]
mergan

**Pull request merged**
