### PR TITLE
Changes the skeleton scream to 'RATTLE ME BONES'

### PR DESCRIPTION
**Pull request by doobiedoo23**
Changes the skeleton scream to 'RATTLE ME BONES'. rattle rattle

### CODE REVIEW

**Comment by lcass** [comment]
Where is the music from my skele ribs?!?! WHERE?

**Comment by ghost** [comment]
please ADD

**Comment by Foosili** [comment]
Depends on how loud and obnoxious this scream is.

**Comment by danhibiki** [comment]
Sounds like it would get irritating on repeat hearing

**Comment by doobiedoo23** [comment]
The sound is randomly pitched and sped, to be honest it's pretty hilarious and to be fair, we've got much more annoying stuff like the infinite borg screaming and pinging.

**Comment by Nebyab** [comment]
I'd be alright with it to test it out. If it ever becomes a problem or too irritating, we can always revert it.

In summation: Yeah sure

**Pull request merged**
