### PR TITLE
Removes the eye adjust verb that is no longer in use

### PR DESCRIPTION
**Pull request by WhiteFox08**
Yew

### CODE REVIEW

**Comment by Weisyl** [comment]
Does this get rid of it refreshing lighting for everyone constantly?

**Comment by Weisyl** [comment]
nice

**Comment by Jaygriff** [comment]
Wow, dint think the travis actually worked. Neat.

**Comment by WhiteFox08** [comment]
coding inside github # yolo

**Comment by Weisyl** [comment]
good 2 merge :+1:

**Comment by Jaygriff** [comment]
If only travis was instant...

**Comment by WhiteFox08** [comment]
This may reduce some delays we have, who knows.

**Comment by Weisyl** [comment]
Hey, if it gets rid of shitty unused code which lags the hell outta the server, it's fine by me

**Pull request merged**
