### PR TITLE
Adds Plasmamen as a roundstart species

### PR DESCRIPTION
**Pull request by TheOneAndOnlyCreeperJoe**
Adds a 'challenge' roundstart species which uses mostly old assets in the code with a few things here and there stolen from /tg/. Has only negative attributes and (almost) zero redeeming ones.

http://i.imgur.com/h7EjfLH.png

Positive Attributes (bare minimum compensation so that they're at least remotely playable):
-Starts with a spaceworthy helmet and a fashionable jumpsuit to go alongside it.
-Can breathe Pure Plasma.
-Starts with a large air tank filled with plasma to breathe from.
-DNA can't be used for transfer sting.

Negative Attributes:
-Suffers from instant combustion when not either wearing a special plasaman jumpsuit/hardsuit and helmet.
-Cannot breathe Oxygen
-Can't play as Security, Heads of Staff or Mime/Clown
-Unable to acquire jumpsuit/helmet from anywhere besides other plasmamen.
-Cannot be cloned due to instant combustion.
-Isn't Human (duh).

Shit that was removed from old Plasmamen:
-Can no longer auto-extinguish using suits.
-Helmet no longer protects from bio, no longer hides any inv slots and is no longer thick material (aka syringes can pass trough)
-Now has blood and is no longer immune to Radiation
-No longer heals from Plasma

### CODE REVIEW

**Comment by Spacedong** [comment]
we went over this and we said that we'd never have this a long time ago, -1 you realize they'll just take their suits off and fucking light everyone on fire

**Comment by TheOneAndOnlyCreeperJoe** [comment]
and they'll burn themselves too. We already have species that give disadvantages (cats), so why not add more?

**Comment by Spacedong** [comment]
also we already have plasma men where have you been, they're only adminspawnable

**Comment by TheOneAndOnlyCreeperJoe** [comment]
you think I wouldn't notice that when adding the code? Title's a little lackluster but it adds them as a roundstart species.

**Comment by Nebyab** [comment]
no. I complete forgot the point spacedong brought up, simply more reason to not have them.

**Comment by trifornt-tinfornt** [comment]
@Spacedong @Nebyab The second they take off their suit they're going to start dying from heat, and usually they'll start dying from oxyloss (plasma-loss?) as well.

Also, as I said before, you need to do some fixes. Plasmamen can spawn as Nuke Ops/ERT/Deathsquid where they will promptly die of heat and fire, so you need to give them either a special syndihardsuit that lets them survive as soon as they spawn, or straight-up ban the race from Ops. Same goes for Shadowlings as they will need to shed their clothes.
The sprite for their suit also looks god-awful, and I suggest replacing it with the new /tg/ sprite.

I honestly think that this PR should be given a chance, but it should start off only being given to players who would be able to handle themselves before being finally merged, else as Spacedong said, there will be the inevitable shitter trying to imitate a Chaos Holoparasite.

A couple of PRs from /tg/ you might want to port:
https://github.com/tgstation/tgstation/pull/17292
https://github.com/tgstation/tgstation/pull/12427
https://github.com/tgstation/tgstation/pull/9380

**Comment by TheOneAndOnlyCreeperJoe** [comment]
Alright, you can't use their DNA for transfer sting anymore.

**Comment by Nebyab** [comment]
s n o w f l a k e r a c e

**Comment by TheOneAndOnlyCreeperJoe** [comment]
Nebyab can't handle this PR's because it's categorized as a species.
Nebyab is xenophobic. Equal rights for Plasmahuffers!

On a serious note, what point is there to denying players that are genuinely interested in a challenge from it? It changes the gameplay dynamic for the player playing it and barely for those around them. If you want to play the game the hardway then we should let you.

And to be honest, judging it purely because it's a species is a little trash don't you think? If I had brought out this system as a traits menu where you can select disabilities if you want to you would've probably said yes.

**Comment by trifornt-tinfornt** [comment]
I think it's solely because of the fact that some people might run around setting people on fire, which means medical will have to use two whopping burn patches and will ultimately end in some shitter just getting catbanned.

**Comment by Nebyab** [comment]
Nah mate. Creeper and I discussed this.

I didn't even consider that till this PR. Creeper is just meming about me.

**Comment by calibraptor** [comment]
No.

People will just join in, take off their suits, and set other people on fire.

**Comment by doobiedoo23** [comment]
ban them then????

**Comment by TheOneAndOnlyCreeperJoe** [comment]
People can already set themselves on fire, the process here is easier but it's still the same result that being you're also shooting yourself in the foot by doing it (especially since I removed the horrible auto-extinguish and forced them to stop drop and roll to extinguish).

Besides we can just ban shitlers for doing it.

**Comment by dreamcrab** [comment]
we have been pretty set on only havin cosmetic races be roundstart races, as much as i wanna laugh about the plasmamen I CANNOT ALLOW THIS TO HAPPEN IN GOOD FAITH

**Comment by McHatters** [comment]
people won't care if they set themselves on fire as long as they can set other people on fire with them. We're a pretty spiteful bunch.
-1

**Comment by Nebyab** [comment]
holy shit @dreamcrab I'm not alone

**Comment by TDcoolguy300** [comment]
Although i never normally give input, this has to be a -1 from me. Plasma men are just too destructive to be a round-start race, not to mention they can literally set the station on fire just by taking off their clothing. For administration, dealing with Round-start plasmamen will be hell.

**Comment by Kokojos** [comment]
Not okay with this.

**Comment by danhibiki** [comment]
> takes off suit to breathe in a plasma filled area
> starts massive fire

So many issues can pop up.

**Comment by danhibiki** [comment]
If anything, I'd say just remove the insta-combustion, but I suppose thats part of the feature that is attractive to those who want plasmamen

**Comment by dreamcrab** [comment]
the only races i want at roundstart are things that dont have special perks.

plasmamen should be some incredible hulk supermatter accident kinda thing, where if you get caught in the blast theres like.. a tiny chance for you to not be deaded instantly

**Comment by dreamcrab** [comment]
then you live on as a horrible mutated fire creature and never get a suit and must be put down

**Comment by danhibiki** [comment]
What if plasmamen were just a genetic disability akin to hulk just like dreamcrab suggest? Then it would be like the counterweight to it.

**Comment by trifornt-tinfornt** [comment]
Considering the virologist can unleash a virus that fucks with people's genetic abilities/disabilities that will give him a random, even better "spontaneous combustion" disease.

If all else fails, give the plasmaman a special kind of fire that doesn't ignite plasma and doesn't set others on fire unless he's actually set on fire naturally.

**Comment by trifornt-tinfornt** [comment]
That works too.

**Comment by SplergeBucket** [comment]
yeah only cosmetic unless you're puttin them as some brand of admin-only bus race but ??? anyway

**Comment by TheOneAndOnlyCreeperJoe** [comment]
Got shot down faster than... Well I don't know.

**Pull request closed without merging**
