### PR TITLE
Removes the Space Cube, replaces this with TG's Torus Space Map

### PR DESCRIPTION
**Pull request by Chronitonity**
https://github.com/tgstation/-tg-station/pull/11643

All of the info is there if you're interested in reading. Note that this requires a file in the config be made and according to @whitefox08 only @nalarmg @danhibiki @SplergeBucket or @Nebyab can do that, so add the config file before you merge this.

tl;dr of the above pull, this gets rid of the weird cube looping space map we have, and creates more randomized maps in space. All in all less shit space. Hooray.

All credit goes to Razharas and the TG boys.

### CODE REVIEW

**Comment by danhibiki** [comment]
Sure

**Comment by Pyko1** [comment]
Does this mean we can easily add more Z-levels?

**Comment by Chronitonity** [comment]
Yes

**Comment by WhiteFox08** [comment]
DNM until Nalar or Dan adds configs

**Comment by SplergeBucket** [comment]
yeah im fine with this

**Comment by Kokojos** [comment]
Pretty sure Jaygriff tested it and had problems porting it. If there is now problem I want this

**Pull request merged**
