### PR TITLE
Changes cloning access so that all medical professions can access it, adds surgery shutters

### PR DESCRIPTION
**Pull request by Chronitonity**
You can now access the cloning room (not the DNA scanners) as any medical profession job. 

Surgery now has some shutters to give privacy, because lets be honest, it needed them.

http://puu.sh/lrQnA/c3c98f73b0.png

### CODE REVIEW

**Comment by danhibiki** [comment]
:+1:

**Comment by Chronitonity** [comment]
This also adds newscasters to security, and fixes a CRITICAL bug where the AI couldn't open the shutters when security went into lockdown mode, even though it was able to close them

**Comment by Pyko1** [comment]
Might want to add lamps to the surgery observatory as all the light it gets comes from surgery.

**Comment by Chronitonity** [comment]
Lights go through the door right behind it, or atleast should.

**Comment by Pyko1** [comment]
I recall it was pretty poorly illuminated to begin with.

**Comment by Chronitonity** [comment]
If it becomes an issue later I'll address it quickly, but as for now I think its fine, and it looked fine in testing.

**Comment by Foosili** [comment]
sure ting

**Comment by Nebyab** [comment]
Yeah sure

**Pull request merged**
