### PR TITLE
Guardian+Z level change

### PR DESCRIPTION
**Pull request by Chronitonity**
Adds logging to guardian chat so we can see what people say in that through logs now.

Nerfs chaos guardian thanks to Dudeinyourbackyard for bumping into everyone and kiling them, it shouldnt give as much fire stacks which means less rolling.

Removes some of the different Z level guns, replaces them with gimmick items such as an owl hardsuit, alien surgery tools and a few guardian injectors. These items weren't strictly antag so this should be better.

### CODE REVIEW

**Comment by Nebyab** [comment]
Chron, would you be able to give me an idea of what was replaced where?

**Comment by Chronitonity** [comment]
The glocks and syndie pistols on the seperate z levels were removed due to them being antag onlyweapons that allowed scientists to fuck people up with.

**Comment by SplergeBucket** [comment]
Yes, fuck those shitty weapons people dump there.

**Comment by SplergeBucket** [comment]
http://puu.sh/kpxzo/6c5f79f36f.png
alright merging then

**Pull request merged**
