### PR TITLE
Plasma rifles again! again again!

### PR DESCRIPTION
**Pull request by KayeArray**
Finally I think I got it fixed!

Adds a Plasma Rifle for ERT and Deathsquad Commanders (fancy blue and berets).
Also includes bad sprites made by me because I suck at drawing.
I would put more here but it's all in the changelog and code.

Now includes a currently admin spawn only combi revolver which can fire .357 printed rounds and singular plasmoids. Suggest ways to implement into game pls

### CODE REVIEW

**Comment by Pyko1** [comment]
pics or didn't happen!

**Comment by KayeArray** [comment]
why does travis want my soul?
ok it's one missing " in the changelog wew

**Comment by KayeArray** [comment]
i'll make you a god damned vidya soon

**Comment by KayeArray** [comment]
https://www.youtube.com/watch?v=L4nO4755B5I&feature=youtu.be

**Comment by Spacedong** [comment]
i liked the vid

**Comment by gumner** [comment]
does it need sprites?

**Comment by SpankMasterson** [comment]
Seems a lil OP maybe but it's for DS so who cares

**Comment by KayeArray** [comment]
I designed it to be a pulse rifle equivalent hence the power. While the overall dps is obviously higher don't forget the downsides such as limited range and only 80 shots as opposed to 200 (pretty yuge imo). Think of it as a sidegrade.

**Comment by KayeArray** [comment]
@gumner This has sprites as you can see in the video, idk if they are good or not

**Comment by gumner** [comment]
yeah they look great,i thought you used some other gun sprite

**Comment by Swagile** [comment]
GM + 1, who cares if its OP its for ERT and DS considering they are going into a station that is probably being cucked by scrubs

**Comment by ghost** [comment]
Ehhh +1 I guess??

**Comment by KayeArray** [comment]
Still open to suggestions on how to implement the new combi revolver I sneakily commited. One idea is to have it replace the mateba although whether this is a nerf or a buff is up to debate.

**Comment by KayeArray** [comment]
I've tweaked the ERT and DS loadouts, read the changelog to see details.

Please comment on what you think of this in regards to balancing since this does kinda buff ERT Commanders.

**Comment by Spacedong** [comment]
chex failed

**Comment by KayeArray** [comment]
wtf travis

**Comment by Spacedong** [comment]
nigger look

https://vgy.me/MLEKYg.png

wrong indentation

**Comment by KayeArray** [comment]
ok it does not look like that in notepad ++ let me fix it

**Comment by Spacedong** [comment]
👌

**Comment by KayeArray** [comment]
there we  go

**Comment by ArcLumin** [comment]
Code's good

**Comment by KayeArray** [comment]
Any updates on this?

**Comment by Swagile** [comment]
we have one HA's +1 and a maybe from spank, who is also HA

spank needs to confirm if he +1'd or not and then we go from there

**Comment by SpankMasterson** [comment]
sure why not, +1. i also support giving ert and death squad microbomb implants so people cant loot them tho

**Comment by KayeArray** [comment]
Headmin approval and codechecked, this should be ready to merge?

**Comment by lcass** [comment]
Here we go again , lift the jug and fill my mouth with that thick sweet git.

**Pull request merged**
