### PR TITLE
removes the shitty changelogs

### PR DESCRIPTION
**Pull request by TheOneAndOnlyCreeperJoe**
it didn't work anyway

### CODE REVIEW

**Comment by yobob591** [comment]
what

**Comment by yobob591** [comment]
oh uh sure??

**Comment by TheOneAndOnlyCreeperJoe** [comment]
ye the changelog never showed up

**Comment by KittyKathy** [comment]
Probably too many things or something just do what McBawbaggings did and put a link to the PR where it lists all the changes and a small general description.

**Comment by Spacedong** [comment]
what did he mean by this?

**Comment by TheOneAndOnlyCreeperJoe** [comment]
the changelogs didn't work because they were 2big

**Comment by nalarmg** [comment]
Fixed in https://github.com/HippieStationCode/HippieStation13/pull/3291

**Pull request closed without merging**
