### PR TITLE
Makes inflatable walls less strong and abusable.

### LINKED ISSUE #2710: inflatable walls are horrendously OP and take like 5-6 hits to deflate
really nigga its so easy to fuck someone over with these suckers, make them die in 1-2 hits, not fucking 6

### PR DESCRIPTION
**Pull request by Kokojos**
Fixes #2710

Reduces Inflatable HP from 50 to 20. (Still 3 crowbar hit)
Makes them have a (very small) deploy phase, (I tested and space-pull dosen't stop you), so you can't deploy them while running.

### CODE REVIEW

**Comment by Spacedong** [comment]
>still deflates instantly when alt-clicked

remove that ^

**Comment by dreamcrab** [comment]
i like it

**Comment by dreamcrab** [comment]
dont listen to spacedong

**Comment by ghost** [comment]
Yeah okay +1

**Comment by JohnGinnane** [comment]
Code looks good

**Comment by Kokojos** [comment]
2 heads okayed

**Pull request merged**
