### PR TITLE
Makes exchange objective be more common

### PR DESCRIPTION
**Pull request by Carbonhell**
as the title says, through objective code looks like shit,i don't even. Would benefit from a refactor which uses typesof so adding objectives means only creating it and not adding it to all procs

### CODE REVIEW

**Comment by Nebyab** [comment]
ok

**Comment by Crystalwarrior** [comment]
Yes please.

**Comment by Nokington** [comment]
K

**Comment by Crystalwarrior** [comment]
Alright, merging this shit.
More sub rosa in muh spessmen.

**Comment by Nokington** [comment]
> says he is gonna merge it
> doesnt merge it
> wew lad

**Comment by Carbonhell** [comment]
> says that a maintainer forgot to merge it
> doesn't merge it,as an headmin
> meanwhile i can't merge it because i'm the PR maker
> 
> > > still waiting

**Comment by myontasm** [comment]
WEW

**Pull request merged**
