### PR TITLE
Reverts PA sprite.

### PR DESCRIPTION
**Pull request by Gandalf2k15**
It now looks like this:
image
Instead of this:
image

### CODE REVIEW

**Comment by ghost** [comment]
Yes please

**Comment by calibraptor** [comment]
Yeah +1 I preferred the old sprite anyways

**Comment by blobbernaut** [comment]
I like the current sprite a bit better myself

**Comment by ghost** [comment]
I like them both.

The suggested reversion one fits the artstyle more tho.

**Comment by dreamcrab** [comment]
yes i like it very nice +7

**Comment by GenericGoose** [comment]
Original fits better, new one looks cool but doesn't fit. Also the screen hitboks was a fucking pain in the ass to click, only thing i hate about it.

**Comment by Nebyab** [comment]
thank christ

**Comment by Gandalf2k15** [comment]
wew 3 hedmin votes

**Comment by Spacedong** [comment]
thank god ive been waiting forever :+1:

**Comment by JohnGinnane** [comment]
Merging as approved by 3 head admins.

**Pull request merged**
