### PR TITLE
Complete Martial Arts rework!

### PR DESCRIPTION
**Pull request by Crystalwarrior**
Changelog:
- rscdel: "Pinning people down is no longer possible unless you have an appropriate martial art."
- experiment: "Security Officers, including the Detective, now spawn with a Krav Maga Martial Art! Krav Maga martial art functions differently from it's /tg/ counterpart. Hippie Station's version lets you pin people down, as well as perform robust disarms that instantly put the weapon in your hands."
- rscadd: "- You can now perform a pindown if you attack your opponent with grab item, with disarm intent, in AGGRESSIVE grab stage."
- rscadd: "Ported Atlas Station wrestling with a bunch of tweaks! There are too many possible moves that you can perform to list their executions here, but, here's what you can do:"
- rscadd: "- Clinch (50% Aggro Grab chance), Backhand Chop, Chop Drop, Choke Slam, Back Breaker, Moonsault, Corkscrew Elbow Drop, Suplex, Tombstone Piledriver, Cutter/RKO and finally, the Powerbomb!"
- rscadd: "Completely rewritten the CQC martial art to be more faithful to the Metal Gear franchise, as well as making it very viable in 1v1 surprise attacks."
- rscadd: "Current CQC moves:"
- rscadd: "- Clinch (50% Aggro Grab chance)"
- rscadd: "- Roundhouse Kick (5-hit combo, KO)"
- rscadd: "- Face Slam (Neck Grab + Harm Intent + attack w/ grab, KO, small brute)"
- rscadd: "- Robust Disarm (Same as Krav Maga - instantly puts weapon in-hand, sacrifices push down chance)"
- rscadd: "- Karate Chop (Neck Grab + Disarm Intent + attack w/ grab, +20 Staminaloss, makes victim confused)"
- rscadd: "- Half-wing choke (Replaces choking, twice as fast to perform, adds +20 staminaloss on attempt)"
- rscadd: "Plasma Fist Martial Art was completely rewritten to make your punches MUCH faster, but some combos are harder to execute!"
- rscadd: "Current Plasma Fist moves (H = Harm, D = Disarm, G = Grab):"
- rscadd: "- TORNADO COMBO! Throws all opponents in-range away from you (HHD)"
- rscadd: "- THROWBACK PUNCH! Throws your opponent backwards and lights them on fire (DHD)"
- rscadd: "- KNOCKOUT KICK! Weakens opponent, deals hefty damage (GGH)"
- rscadd: "- THE ULTIMATE PLASMA FIST TECHNIQUE! Gibs opponent similarly to Ei Nath. Leaves brain. (GHDGHDH)"
- experiment: "Plasma Fist has been added as a buyable scroll for Wizard. It costs 8 skill points due to it's sheer, powerful potential and due to the fact that you're basically buying a spell bundle. The cost is subject to change based on player feedback."
- tweak: "Reduced all grab resist cooldowns from 10 seconds to 5 seconds."
- tweak: "Added a sound effect and visible_message to being slammed into walls by throws"
- tweak: "Now resisting out of pindowns will always let victim get up faster than assailant"
- tweak: "Being tablepushed onto a glass table now gives you 5 brute and has a chance to embed the shard into you."
- bugfix: "Fixed teleporting issue with grabs"

### CODE REVIEW

**Comment by Chronitonity** [comment]
:+1:

**Comment by Weisyl** [comment]
> experiment: "Security Officers, including the Detective, now spawn with a Krav Maga Martial Art! Krav Maga martial art functions differently from it's /tg/ counterpart. Hippie Station's version lets you pin people down, as well as perform robust disarms that instantly put the weapon in your hands."

no no no no please god NO

**Comment by Chronitonity** [comment]
@DerptheStewpidGoat : I've yet to see you bring an actual argument to this aside the fact that theres a few players you don't like who play security and that you wouldn't want them to have it

**Comment by ghost** [comment]
this is good
just add a way to learn a martial art rather than just choosing sec or something
z level reward maybe?? ( for krav maga )

**Comment by Weisyl** [comment]
Uh let's see, snowflake arts for security, a get-fucked-forever pindown, and a disarm that also PUTS the weapon in your hand which makes it arguably better than pushing them down and would also be a better strategy in robusting someone than using most melee weapons besides maybe the stun baton or telescopic baton, especially if you got a riot shield in your other hand.

**Comment by Chronitonity** [comment]
Literally nothing snowflake about it but okay. Pinning down got a decent nerf, where if you resist out of it then it stuns the guy pinning you, and you can resist every 5 seconds rather than every 10. 
The weapon being put in your hand is intentionally better, that is the point of it. You sacrifice the ability to push PEOPLE over though. 

Security shouldn't be using other weapons that don't stun though, so I don't see your point in this being /better/ for them than other melee weapons when they shouldn't be toolboxing someone in the head, and the fact that it doesnt do anymore damage or anything, just gives them an edge in taking down people hand to hand, which, if you're fighting security that way, you should be worried.

**Comment by Weisyl** [comment]
The snowflake bit I was referring to was how it was only available to security, and while it'd be arguably worse if everybody had this, I'd rather this be a thing for nobody by default except maybe antags if they purchase a scroll or whatever to learn it. Also if you're fighting security in melee and they've already lost all their stunning gear, then you shouldn't also have to worry about them also being able to go jackie chan on your ass. And yes my feeling is in fact that this'll attract power gamers even more so to security. As I've also argued before, while the whole thing about the combat system being "robust" was more of an ironic joke, I liked the melee combat system better when it was fairly simple, except now we're constantly introducing these new martial arts which completely detract from the simplicity. It's not really something you can ignore either since a fair amount of players (primarily hotkey users I believe) use it. The non-hotkey players are also in trouble because of this as it's a whole lot more difficult to switch intents on the fly, while hotkey users have an E-Z time doing so.

**Comment by Chronitonity** [comment]
Non hotkey users have always been at a disadvantage and not adding things because "its more difficult for them" is terrible.

Half of the goal is so that it attracts more security players, we have no one who plays security during rounds, giving them a slight incentive in the form of 2 abilities isnt anything major. It shouldn't matter if it attracts more "powergamers" because powergaming isn't something we harshly discourage.

**Comment by Weisyl** [comment]
I get your point but the main reason why so few people play security likely has something to do with how our community as a whole acts towards them. I'd feel it'd be better if we just gave all officers by default a bit more gear or slightly buffed gear like tasers to have slightly more charge, or flashes to be less likely to burn out. An unrelated issue with flashes is that the flashers tend to burn out terribly often if you place them in the brig which happens to be where they're most useful.

**Comment by Chronitonity** [comment]
Giving them more gear is exactly what don't want because any chucklefuck can stunprod+cuff and take the gear. This way its something that can't be stolen just to be a dick. + It makes sense for ~highly trained security enforcers~ to be trained to be slightly better at combat than everyone else on the station.

**Comment by Weisyl** [comment]
"Highly trained security enforcers"
Last I checked it was generally agreed that security officers were just a bunch of glorified mall cops, maybe with the exception of the warden or HoS or detective.

**Comment by Chronitonity** [comment]
I'm half joking but it still makes sense for them to be better trained.

I'm not gonna spend half the day arguing on this, It's clear your position, but I think I've refuted most of your statements, so we can leave this for the heads to decide if its good to test live.

**Comment by ghost** [comment]
it doesnt make sense that sec fights the same way an assistant does
this is good, i would just like a book or some shit on krav maga that is on some z level

**Comment by danhibiki** [comment]
Krav maga isn't an art strictly for assassinations, historically its been used by the IDF for years, and its been used by the US military.

:+1:

**Comment by Weisyl** [comment]
It doesn't make sense that assistants can also set up a black hole in an advanced containment field and use these machines which collect radiation from it and turn it into loads of energy.

**Comment by ghost** [comment]
this probablly wont affect gameplay alot anyway so :+1:

**Comment by Crystalwarrior** [comment]
@oprayx73 goddamnit yes it will oprayx lol
I feel that Krav Maga will change the way Security players have to think about unarmed combat.
Not having pushing down chance is a big deal, where instead of praying on RNG for doing all the work to you you have to do some work yourself while having rather consistent execution rate.

**Comment by trifornt-tinfornt** [comment]
The "steal item out of your hands" thing is unbelievably cruel to melee traitors and for every officer to have that just makes it unfair.
I have a very strong love for the melee traitor weapons so when I constantly see them get nerfed because people cried about how they don't know how to run away/shoot from the guy who is clearly powerfisting everyone on the station it gets extremely annoying. But this will just annihilate all of them but the CQC Gloves and Knife Boxing Gloves.

You know that Double Esword? The item that is much weaker than the Chainsaw, costs 16 TC despite only really making every fight a melee fight that's usually in Sec's favor and has a damage buff of 2 which somehow justifies that insane price? Now I can just steal it out of your hands, the thing hardly blocks melee at all. Now you're screwed because you wasted 16 TC on this thing and you most likely couldn't afford anything other than a pen which I can also swipe out of your hands. That's not balancing against the weapon when the weapon relies entirely on melee as well. You can stun me in one hit or just spam flash because usually traitors don't have sunglasses until later and I still need multiple hits to take you down. The Chainsaw was better balanced because it stuns on hit as well, and it also blocks against melee making fights against sec still very tense but in the end winnable for both sides depending on the robustness. No, I'm not trying to say that this update can't happen because it'll destroy a weapon that already sucks even more, but it's just an example.

What about the Powerfist? The item that has been nerfed to oblivion but knocks people back on hit? Use that recharge time to swipe it away and then powerfist THEM to death. To be fair, this thing that costs 10 TC has a better chance against Sec than the Double Esword as the knockback is unbelievably useful and it also gives you enough TC to buy other things like adrenals or EMP.

Regardless, it seems extremely unfair and cruel to melee traitors who already have it pretty hard given that sec usually can just spam disablers down the hall to stop them in their tracks, or y'know, just shoot at them and yet you need to give Sec an item that allows them to steal their attempt at combat in one move, but unlike Disarm Intent which will allow you to pick the item back up if yer robust, just puts it immediately in the officer's hand and allows them to go to down. The Double Esword's attempt at fixing the disabler bit just makes Sec smack you with a baton and now they can just swipe it away from you so it's even more moot. Hell, even Engineering/Science/etc. can just make a stunprod as soon as the round starts as well as giving Science some free flashes which means that those departments get extra weaponry against traitors (I'm looking at you, Calibraptor).

Gonna derail this a bit, please buff the poor double esword. The standard Esword in most combat situations can get kills just as well as that thing can (aside from the taser bit) and costs only 8. Deflecting taser shots, as cool as it sounds, is not effective when it costs 16 out of 20 TC and forces you to hold it in both hands and remain melee - no matter how robust or deadly it is when combined with stuff like lube (which got a recent nerf) because the thing can actively work AGAINST the traitor as well because of the No-Slips nerf.

I wouldn't be complaining this hard if Sec wasn't already so geared up, had counters to these things already, and most importantly had a ton of powergamers running around playing as sec randomly tasing everyone on sight and are usually so geared that Traitors will normally lose to those guys unless they actively wasted TC to fight them.

/rant

Aside from THAT ability, is gud add it.

**Comment by calibraptor** [comment]
-1

Security doesn't need to be all powerful martial artists. Honestly a map change to the brig to make it more secure to break-ins would do wonders to solve the problem of greytide breaking all the windows and making it completely non-functional.

**Comment by Chronitonity** [comment]
That solves literally none of the problems brought up

**Comment by danhibiki** [comment]
I think this will incentify people to play security more, which is an under utilized role, as well as giving them a slight defensive edge in an otherwise outnumber situation. Besides dealing with traitors, security has to deal with any random gaggle of greytiders that take it upon themselves to disrupt the round.

**Comment by Nebyab** [comment]
We no longer live in the days where if something didn't work, we were stuck with it forever. I'm 100% for seeing how this ends up working out. If it turns out this this completely breaks the intended playing field between sec and the crew/antags, then we can figure out the problem and fix it. I'm very optimistic that this change might bring about a more stable number of sec players.

**Comment by Foosili** [comment]
I'm interested in seeing how this works out, if its shit we can revert, kickflip, ollie outtie, pop-shovit, mctwist, etc.

**Pull request merged**
