### PR TITLE
Removes Multiverse Sword

### PR DESCRIPTION
**Pull request by AliiTea**
https://trello.com/c/1HpEhm9V/682-remove-multiverse-sword-from-being-obtained-by-the-wizard

Removes the Multiverse Sword from the wizards spellbook

### CODE REVIEW

**Comment by Weisyl** [comment]
It'd probably be better if you just commented it out instead.

**Comment by AliiTea** [comment]
Commented out
@DerptheStewpidGoat

**Comment by Nokington** [comment]
yes

**Comment by Lawligagger** [comment]
oh boy

**Pull request merged**
