### PR TITLE
This puts the pool back on the map, fully working, with all it's features besides the chemdump.

### PR DESCRIPTION
**Pull request by Kokojos**
Borgs can get out of the pool, as can most things now.
The pool filter will have no Emag use until I re-import sharks! 

The base code for chemdump is already there, just hidden.

 image

### CODE REVIEW

**Comment by TDcoolguy300** [comment]
Pictures mate

**Comment by Kokojos** [comment]
There is now an image

**Comment by SplergeBucket** [comment]
http://puu.sh/mcbRP/a71a491b71.png
wot about these lockers?

**Comment by trifornt-tinfornt** [comment]
Simple, bring back the old wrestling area and push the chapel back up. Now the johncena ambience sound can be used again.

**Comment by danhibiki** [comment]
First the pool. Then, the people's engine

**Comment by Kokojos** [comment]
@SplergeBucket 
they have been moved in the Dorm, and the shorts were left in the pool area.

**Comment by SplergeBucket** [comment]
i give me seel of aproval

**Comment by Nebyab** [comment]
seems good

**Comment by Lawligagger** [comment]
Looks good to me, Also, I miss the old chapel.

**Pull request merged**
