### PR TITLE
Hardsuit&Rechargers

### PR DESCRIPTION
**Pull request by AliiTea**
Ports GunHog's

Constructable Rechargers & Hardsuit messages for things like Bombs/Rad/EMP
## CopyPaste of PR

Rechargers can now be constructed/deconstructed as a machine. Requires the board and a capacitor.
Rechargers can now be upgraded with superior capacitors to increase recharge rates!

~

All hardsuits

Hardsuits now provide a warning message for radiation and EMP events.
Radiation messages provide the intensity of the radiation pulse.
EMP messages indicate if the pulse is light or strong.
Prototype hardsuit

Displays the size of nearby explosions. It is a simpler message than what the full doppler array provides, limited to 21 tile range instead of 100.
All messages are visual, and display on the suit's electronic visor. They show a neat little icon when you are wearing the helmet to signify that the helmet is the source of the message.
image

### CODE REVIEW

**Comment by lcass** [comment]
yes++++++ finally useful for blobs.

**Comment by danhibiki** [comment]
Give me more information

**Comment by AliiTea** [comment]
@danhibiki more info provided

**Comment by Nebyab** [comment]
This seems solid. How available are the recharger boards exactly? Does this fiddle with any of the ones already existing on station. As long as there aren't an obscene number of boards, I have no objection to this.

**Comment by Nebyab** [comment]
Fears have been assuaged: yeah sure

**Comment by nalarmg** [comment]
Code's fine, waiting for further headmin review.

**Pull request merged**
