### PR TITLE
Chapel upgrade, fight ring implementation, woodshop fix

### PR DESCRIPTION
**Pull request by TheMocheeze**
WWE SLAM THIS SUNDAY NIGHT JHNNNNNN CENAAAAA

### CODE REVIEW

**Comment by Iamgoofball** [comment]
You guys need to use mapmerge

**Comment by j-mie** [comment]
When I was HeadCoder that was the rule... It's just lazy not too.

**Comment by TheMocheeze** [comment]
What the fuck is mapmerge, why do I need to use it?

**Comment by AliiTea** [comment]
Time to start using that rule now

Never touch map without using mapmerge

**Comment by WhiteFox08** [comment]
Retard zone

**Pull request merged**
