### PR TITLE
Fixes

### LINKED ISSUE #1565: Brig Office Shutters overlap the sliding glass door.
balls

aaaaaaaaa you cant click this

### LINKED ISSUE #1572: Random disposal pipe in new arrivals
http://vgy.me/xGJJWD.png

### PR DESCRIPTION
**Pull request by XeonFaux**
Fixes #1572
Fixes #1565

### CODE REVIEW

**Comment by TDcoolguy300** [comment]
Gotta solve the merge conflicts

**Comment by Kokojos** [comment]
Not mapmerged. Please mapmerge it properly using the tool in Your ss13 folder/tools.

**Comment by XeonFaux** [comment]
Why the "Do Not Merge"? I fixed it by map merging.

**Comment by ghost** [comment]
holy shit squash your commits

**Pull request closed without merging**
