### PR TITLE
capitalised typo

### PR DESCRIPTION
**Pull request by ghost**
first commit no bully please

### CODE REVIEW

**Comment by ghost** [comment]
Who's this nerd

he doesnt even have a profile picture

everyone laugh at the nerd without a profile picture

**Comment by ghost** [comment]
hahah i'm going to get a picture and this comment will look so stupid hahahahahahhahaha

**Comment by Kierany9** [comment]
Oi get off our turf nerd, this is pro coder land only, we'll beat you up otherwise.

(jk welcome to the hell that is github)

**Comment by KayeArray** [comment]
Profile pictures are for the weak, don't listen to this filthy Mithrandalf he lacks one himself and is merely trying to deceive you.

**Comment by ghost** [comment]
I dont want to change mine, it looks like Bane.

**Comment by TheOneAndOnlyCreeperJoe** [comment]
If I pull that default avatar off will you die?

**Comment by GenericGoose** [comment]
um, you don't get to bring profile pics

**Comment by ghost** [comment]
fresh out of hecks i see

**Comment by GenericGoose** [comment]
you're a new guy

**Comment by danhibiki** [comment]
for you

**Comment by GenericGoose** [comment]
it doesn't matter who this nerd is
what matters is his plan

**Comment by ghost** [comment]
Merging this commit, with no survivors.

**Comment by GenericGoose** [comment]
baneposting 4lyfe

**Pull request merged**
