### PR TITLE
Map Changes

### PR DESCRIPTION
**Pull request by XeonFaux**
Detectives Office, EVA, Lawyer's office, a secret room.

Cargonia overhaul coming soon.

### CODE REVIEW

**Comment by XeonFaux** [comment]
preview one
preview two
preview three
preview four

**Comment by Nokington** [comment]
Couple of things, that oxygen jetpack in EVA should be a CO2 jetpack. From the looks of it EVA is doubled walled to the north not good. And missing doors for that maintenance access? After those couple of things are addressed, ill +1.

**Comment by XeonFaux** [comment]
Eva not double walled, just was like that when picture was taken, maitenance door was fixed after picture, oxygen was for command staff. Also oxygen jetpack was put onto a rack instead of table, after picture.

**Comment by danhibiki** [comment]
Re-adds maintenance tunnel that is much needed, moves law office to logical position.
:+1:

**Comment by Nokington** [comment]
Alright. +1

**Pull request merged**
