### PR TITLE
Fixes farts

### PR DESCRIPTION
**Pull request by tortellinitony**

### CODE REVIEW

**Comment by gumner** [comment]
make so that scrubbers can succ it and it will be balanced

**Comment by tortellinitony** [comment]
they already can

**Comment by gumner** [comment]
ooh

**Comment by ArcLumin** [comment]
Protip; farts spawn at a fairly colder temperature than normal so people tend to take minor temperature damage

**Comment by PopNotes** [comment]
copypasting my idea from the shitty spacedong post that sucked

Rework, rework, rework.
Rework instead of fucking removing everything like a shitler.
Make fart gas dissipate really quickly and decay much faster, problem solved and you can still choke someone with your ass blasts so long as you stay on the same tile.

**Comment by PopNotes** [comment]
I view the only real (aside from bugs/lack of visibility on analyzers) issue to be the fact that assgas stays in the air for fucking centuries when it should spread out super quick and decay pretty fast too, think the way a real poot would

**Pull request merged**
