### PR TITLE
Fixing runtimes for nooses and holowrassling belts

### PR DESCRIPTION
**Pull request by Crystalwarrior**
solves runtime issues with holodeck wrestling belt and nooses/by extention add_logs proc

### CODE REVIEW

**Comment by TDcoolguy300** [comment]
REEEEEEEEEEEEEEEE

**Comment by Crystalwarrior** [comment]
oh, fiddlesticks, what now

**Comment by TDcoolguy300** [comment]
This good to go?

**Comment by Crystalwarrior** [comment]
yuppers

**Comment by TDcoolguy300** [comment]
REEEEEEEEEEEEEEEEEEEEE

**Pull request merged**
