### PR TITLE
Fixes Vampires and Holy Water

### PR DESCRIPTION
**Pull request by ArcLumin**
Previously, holy water would not instantly affect vampires, it'd take 30 ticks or so, Now it's instant, as was intended

### CODE REVIEW

**Comment by yobob591** [comment]
good, vampres are strong af plas mergg

**Comment by blobbernaut** [comment]
Looks like it was working exactly as intended and this is grudgecode.

**Comment by ArcLumin** [comment]
comments on it says it kills vampires fast, but it actually kills them quite slowly.

**Comment by ghost** [comment]
Might be an idea to cross reference from /vg/ code

**Comment by blobbernaut** [comment]
Nerf the damage them, 8 per tick is absurd

**Comment by KittyKathy** [comment]
You know what's really absurd? that they can turn into a bat and wait out the holy water taking no damage at all because god mode bat.

**Comment by SpankMasterson** [comment]
+1

**Comment by ArcLumin** [comment]
Considering this is how the code was originally intended, this is a bug fix. Needs code review then it's good to merge.

**Comment by Pyko1** [comment]
The original code is vague what was intended

I kinda think it was meant to kill vamps fast as soon as the chem started to effect
now its just an another antag tester for vamps.

imho it needs head input, code is fine tho.

**Comment by ghost** [comment]
go ahead

**Comment by ArcLumin** [comment]
mergan

**Pull request merged**
